shaka-project/shaka-player

AUTHORS, CONTRIBUTORS, third_party/closure/goog/uri/uri.js
This fixes handling of URIs with special characters. Without this patch, segment URIs such as e.g. http://example.com/0.webm?param=%26 are translated to http://example.com/0.webm?param=&.
=> Fix query parameter encoding

CONTRIBUTORS, lib/dash/mpd_parser.js
For live streams, minimumUpdatePeriod can be set to 0. It means that
we shouldn't refresh the manifest until there's an explicit signal
from within the stream. As of now, there's no way to get that signal
from MSE. So as a workaround, if we see a minimumUpdatePeriod of 0,
we set it to 10 seconds. This is similar to how Exoplayer [1] and Dash.js [2]
handle this case.
[1] https://github.com/Dash-Industry-Forum/dash.js/blob/fe14ee023c0e3aa073284ce034758942e8f3c7bf/build/test/js/utils/MPDHelper.js#L12
[2] https://github.com/google/ExoPlayer/blob/953e1118a58a269ded8b0246874bd827d900fcf0/library/src/main/java/com/google/android/exoplayer/dash/DashChunkSource.java#L270
=> mpd parser: Handle minimumUpdatePeriod being set to 0.

AUTHORS, CONTRIBUTORS, lib/player/stream_video_source.js
Tested in FF (Nightly), Opera (Beta), and Safari
=> defer assigning to video.currentTime Fixes #101

AUTHORS, CONTRIBUTORS, lib/debug/asserts.js, lib/debug/log.js, lib/debug/timer.js, lib/player/player.js, support.js
This ports our fixes back into the Shaka source.
@ustudio/dev Can somebody review this, before I open a PR back to the upstream source?
=> Load without errors in IE 9

AUTHORS, CONTRIBUTORS, lib/media/i_stream.js, lib/media/simple_abr_manager.js, lib/media/source_buffer_manager.js, lib/media/stream.js, lib/media/text_stream.js, lib/player/http_video_source.js, lib/player/i_video_source.js, lib/player/stream_video_source.js
Mainly for use in a custom ABR manager, where calling StreamVideoSource.selectVideoTrack could pass an optional offset param, which is the number of seconds in front of video.currentTime that the buffer should be cleared from. 
Useful when configuring the player with a large buffer that should be truncated when upgrading from a lower bitrate to a higher one (so that the user sees the newer bitrate without having to player through the size of the buffer)
Addresses issue #95
=> Optional offset param to IVideoSource.selectVideoTrack for partial buffer clear

lib/player/player.js
I realize getAdaptationEnabled is deprecated but it was returning undefined. Until it gets taken out I assume it should be returning the correct value.
=> Correct typo in getAdaptationEnabled causing it to return undefined

AUTHORS, CONTRIBUTORS, build/wrapper.template.js
To prevent crashing with other module loaders that support `define`, but are not full AMD module loaders, check for `define.amd` as well before defining the AMD module.
=> Check for define.amd along with typeof(define)

lib/media/simple_abr_manager.js
Add a configurationchanged event that fires when videoSource.configure()
is called. This is useful for components that need to know when certain
configurations have changed such as when bandwidth restrictions have
been changed. In this case, the simple_abr_manager can force a video track
update when restrictions have been changed instead of waiting for a
bandwidth update.
This is the kind of thing I have in mind for #160 as an alternative solution.
=> Introduce configurationchanged event.

AUTHORS, CONTRIBUTORS, lib/dash/mpd_parser.js, lib/dash/mpd_request.js, lib/util/failover_uri.js, spec/mpd_parser_base_url_spec.js, spec/mpd_spec.js
Add support for responseURL where supported.
XMLHttpRequest spec 4.6.1 adds the responseUrl attribute:
https://xhr.spec.whatwg.org/#the-responseurl-attribute
**Browser Support**
Chromium: https://code.google.com/p/chromium/issues/detail?id=377583
Webkit: https://bugs.webkit.org/show_bug.cgi?id=136938
Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=998076
A current use case is when the DASH manifest is located at a URL that is redirected via 302 to another location. Currently, the mpdParser will then pull the chunks from the original URI rather than the URl from which the manifest was ultimately downloaded.
**Example - Current Flow**
http://some.host.org/path/manifest.mpd returns 302 to http://other.host.org/path/manifest.mpd.
Subsequent requests for mp4 chunks will be: …
=> Add support for 302 redirect

app.js, lib/player/http_video_source.js
Passing an empty config object is no longer acceptable because the
keySystem property is mandatory on drmConfig objects.
Also modified HttpVideoSource constructor comment so that the drmConfig
comments are the single source of truth regarding well-formed drmConfig
objects.
=> Correct instantiation of HttpVideoSource with no content protection.

AUTHORS, CONTRIBUTORS, build/lib.sh
Leaning just on `find` for order, two different checkouts will produce different file list orders for different people building it, at the moment, on some OS:es / file systems. Sorting the input file list prior to compiling makes sure that built output will produce the same result no matter who builds it where, which is all sorts of helpful when the built file is also under version control.
=> Always build the same input files to a stable output

lib/dash/mpd_utils.js, lib/media/segment_index.js, test/segment_index_unit.js
Hi,
I have a multi period live stream and, at some time shaka was stopping with an INVALID_SEGMENT_INDEX error.
I discovered that the issue was caused by the fact that when segment references are merged at the manifest change, some of the segments are skipped, considered to be duplicates of the previous received segments. This is true in general, but when the period changes, last segment is expanded to end of the period (in MpdUtils.fitSegmentReferences). This updated segment was not merged into the final segment list which was causing a gap.
I added a unit test that reproduce the issue and I also made a fix for it.
=> Update end time of last segment in a period when new periods are added

AUTHORS, CONTRIBUTORS, externs/errors.js
Make it possible to access the response when requests fails.
I tried to change to `['xhr'] = ` but then the tests failed because of type error
Hope it's correct to target v1.6.x branch.
=> Extern xhr error property

lib/dash/content_protection.js, lib/dash/dash_parser.js, lib/dash/segment_list.js, lib/dash/segment_template.js, lib/media/drm_engine.js, lib/media/manifest_parser.js, lib/media/media_source_engine.js, lib/media/playhead.js, lib/media/presentation_timeline.js, lib/media/streaming_engine.js, lib/net/data_uri_plugin.js, lib/offline/db_engine.js, lib/offline/download_manager.js, lib/offline/storage.js, lib/player.js, lib/polyfill/patchedmediakeys_20140218.js, lib/util/config_utils.js, lib/util/stream_utils.js, lib/util/string_utils.js
This change adds missing dependencies to shaka-player with the exception of adding 'shaka.offline.Storage' to 'shaka.offline.DownloadManager'. Doing so creates a circular dependency.
```
Checking the tests for type errors...
ERROR - Circular dependency detected: shaka.offline.Storage -> shaka.offline.DownloadManager -> shaka.offline.Storage
1 error(s), 0 warning(s)
```
I will look into resolving that circular dep in a dedicated change.
=> Add missing goog.require() dependencies

lib/media/segment_index.js, lib/media/stream.js
As per issue #330, manifests are only required to be approx.
correct with respect to their description of the media segments.
In order to avoid stalling when seeking through content like this,
fetch the chunk prior to the one that supposedly contains the
current time.
This is an attempt to apply a similar fix to Ia7bb74d0120.
=> Attempt to fetch one chunk prior on seeking

lib/dash/dash_parser.js, lib/dash/mpd_utils.js, lib/dash/segment_base.js, lib/dash/segment_list.js, lib/dash/segment_template.js
If we rely on duration != null in-progress recordings get their last segment stretched to the end.
Fix for #423
=> fitSegmentReferences: Check isLive() using presentationTimeline

lib/media/playhead.js, test/media/playhead_unit.js
If there is a duration set the start of the window will not move.
We've been including a `timeShiftBufferDepth` equal to the duration for in-progress recordings. Otherwise the `presentationTimeline.isLive()` check fails.
=> playhead reposition: treat anything with a duration as vod

lib/media/text_engine.js, test/media/text_engine_unit.js
Empty WebVTT cues are valid, and should still be considered buffered. 
By using a cues object with 0 length as a proxy to the init segment, we lose valid empty WebVTT segments. Instead, use existence of start/end as a proxy to init segments.
This regression was introduced in ab64c76ee90eafe6f8813c400a54eedfdf22bf81
=> Consider empty text cues buffered

lib/dash/segment_list.js, lib/dash/segment_template.js, test/dash/dash_parser_live_unit.js, test/test/util/dash_parser_util.js
`presentationTimeline.getSegmentAvailabilityStart()` yields a start time relative to the AST, but all of the reference start/end times are relative to their PTOs. We need to normalize the start time to the period before we evict any segments.
=> Do not prematurely evict segments from multi-period manifests

AUTHORS, CONTRIBUTORS, lib/media/vtt_text_parser.js, test/media/vtt_text_parser_unit.js
Fixes https://github.com/google/shaka-player/issues/521
=> Fix vtt with one digit hour

AUTHORS, CONTRIBUTORS, demo/assets.js, externs/shaka/manifest.js, lib/dash/content_protection.js, lib/media/drm_engine.js, test/media/drm_engine_unit.js, test/test/util/manifest_generator.js
=> Some DRM providers require default KID in wrapped license requests

AUTHORS, CONTRIBUTORS, externs/shaka/manifest.js, externs/shaka/offline.js, externs/shaka/player.js, lib/dash/dash_parser.js, lib/offline/offline_utils.js, lib/offline/storage.js, lib/util/stream_utils.js, lib/util/xml_utils.js, test/dash/dash_parser_manifest_unit.js, test/offline/storage_unit.js, test/player_unit.js, test/test/util/manifest_generator.js
=> Provide framerate and codecs information on video tracks

AUTHORS, CONTRIBUTORS, docs/tutorials/license-server-auth.md, externs/shaka/net.js
- Add tutorial tag to shakaExtern.RetryParameters
- Add more description to Lisence Server Auth Sample Code
=> Small Refinements on Documentation

AUTHORS, CONTRIBUTORS, lib/net/data_uri_plugin.js, test/net/data_uri_plugin_unit.js
When using Data URIs for the manifest an `UNABLE_TO_GUESS_MANIFEST_TYPE` is thrown. The mimeType is used to look up the manifesst parser but mimeType is `undefined ` because `shaka.net.DataUriPlugin` does not return the correct 'content-type' in the header.
With this change `shaka.media.ManifestParser` (lib/media/manifest_parser.js, line167) can select the manifest parser correctly.
Data URIs used:
> data:application/dash+xml,[encoded xml]
and
> data:application/dash+xml;base64,[base64 encoded xml]
=> Fix when using Data URIs for the manifest

externs/shaka/player.js, lib/media/media_source_engine.js, lib/media/mp4_ttml_parser.js, lib/media/mp4_vtt_parser.js, lib/media/streaming_engine.js, lib/media/text_engine.js, lib/media/ttml_text_parser.js, lib/media/vtt_text_parser.js, lib/player.js, test/cast/cast_utils_unit.js, test/media/cue_integration.js, test/media/drm_engine_integration.js, test/media/mp4_ttml_parser_unit.js, test/media/mp4_vtt_parser_unit.js, test/media/streaming_engine_integration.js, test/media/streaming_engine_unit.js, test/media/text_engine_unit.js, test/media/ttml_text_parser_unit.js, test/media/vtt_text_parser_unit.js
Fix for #480
This should be reviewed closely. Specifically I'm not thrilled that I had to modify all the other text parsers to receiver an argument that none of them are going to use. That seems confusing to me but I wasn't sure how to avoid that.
=> Add config option for using segment relative timestamps for VTT

lib/media/ttml_text_parser.js, test/media/ttml_text_parser_unit.js
We currently have TTML subtitles that contains `<br>` elements inside a paragraph for linebreaking. This pull request replaces the `<br>` elements with a newline character. Having `<br>` inside a paragraph is valid in TTML as far as I have understood by looking at the examples in https://www.w3.org/TR/ttaf1-dfxp/
=> TTML subtitles: Support for <br> inside a paragraph

lib/media/ttml_text_parser.js, test/media/ttml_text_parser_unit.js
This pull request solves the problem with TTML text alignment. We have TTML subtitles that has tts:textAlign=left and the subtitle was placed on the left side of the player but the text was centered. If I am reading the VTTCue specification correctly [1] the cue.align also needs to be set. This was not done and is solved by this PR.
[1] https://w3c.github.io/webvtt/#dom-vttcue-align
=> Fix for TTML text alignment

externs/texttrack.js, lib/media/ttml_text_parser.js, test/media/ttml_text_parser_unit.js
It was discovered that TTML alignments that is not centered (e.g. left) was shown incorrectly in Firefox. The reason I discovered was that the cue.positionAlign was not set and defaulted to "center". This caused the subtitles to be positioned on the left (when tts:textAlign=left) but with the text center aligned.
Note that for Firefox v48 or lower the implementation of cue.positionAlign did not fully follow the spec and was corrected in v49 and above.
=> Fix for TTML alignment (non-centered) in Firefox

lib/abr/ewma.js, test/abr/simple_abr_manager_unit.js
=> Avoid ewma sampling from failing on 0 duration segments.

externs/texttrack.js, lib/media/ttml_text_parser.js
This PR contains a fix with incorrect TTML positioning. When converting tts:origin for example "10% 10%" we need to set the VTTCue.snapToLines to false as according to spec:
> A boolean indicating whether the line is an integer number of lines (using the line dimensions of the first line of the cue), or whether it is a percentage of the dimension of the video. The flag is set to true when lines are counted, and false otherwise.
This PR also contains the required Externs for VTTCue / TextTrackCue properties that otherwise was not included in the compiled version and default values was used instead.
_(This PR replaces the git mess I made in #591, sorry about that)_
=> Incorrect TTML positioning

AUTHORS, CONTRIBUTORS, lib/util/xml_utils.js
This occurrs when hyphen is contained inside manifest Location/BaseUri element and new MutationObserver(...).observe(...) called before #608
=> Fix MSIE 11 fails to play video

lib/media/ttml_text_parser.js, test/media/ttml_text_parser_unit.js
This modifies the fix from #572. We have streams that also have `<br>` tags nested in `<span>` tags that were getting missed by #572
=> Add new lines in TTML cues with nested <br> tags

AUTHORS, CONTRIBUTORS, lib/media/ttml_text_parser.js, test/media/ttml_text_parser_unit.js
Fix for issue #646.
A div element with no timing and only whitespace should be considered empty.
Added a test that checks this.
=> Fix of TTML bug for white-space div with no content

lib/player.js
If no content has been loaded and therefore there is no streamingEngine
then these two functions will fail. Add a guard to check and return an
empty array if there is no streamingEngine.
Close #677
=> Add guard to stop getAudioLanguages and getTextLanguages from failing

lib/dash/dash_parser.js, test/dash/dash_parser_manifest_unit.js
=> Don't ignore InbandEventStreams at the Representation level

CONTRIBUTORS, lib/dash/mpd_utils.js, lib/dash/segment_template.js
This PR solves #690 (and replaces PR #702)
With the following SegmentTimeline snippet
<SegmentTemplate timescale="10000000"  media="$Time$.mp4">
<SegmentTimeline>
<S t="5369174623790086" d="40000000/>
<S d="40000000" />
</SegmentTimeline>
the second segment erroneously gets the wrong timestamp 5369174663790087 due to rounding errors.
This is because the calculation is done using values scaled to seconds as follows:
(5369174623790086 / 10000000 + 40000000 / 10000000) * 10000000 = 5369174663790087
The problem with this rounding error is that the timestamp is used in the $Time$.mp4 URL template, and results in an HTTP 404 error when requesting the segment from the server.
Somewhat higher precision (roughly 1 more bit) can be achieved by avoiding the scaling and just do an integer addition …
=> Improvement of segment timeline $Time$ accuracy

lib/player.js
In some cases it may be necessary to get access to the HTML Media Element (the one that is passed in during initialization of a player) from a player instance when you no longer have a reference to what it was initialized with. In this case it would be helpful to have a method to do so (and not have to access player.video_ directly, which could change at any point not reflected by semver as it's not an official API).
=> Add official method for accessing HTML media element

AUTHORS, CONTRIBUTORS, demo/assets.js
I have added a response filter for VDMS manifest responses, as well as a license request filter for VDMS license requests.  I then add a couple of test assets that utilize these filters and point to the VDMS widevine and clearkey license proxies.
=> Pull request for issue #780 - Support for VDMS Streams in demo app

CONTRIBUTORS, lib/media/drm_engine.js
=> Check if PlayReady license message is wrapped in XML.

CONTRIBUTORS, externs/shaka/player.js, lib/util/stream_utils.js, test/offline/storage_unit.js, test/player_unit.js
=> Add video and audio stream IDs for getStats().switchHistory

AUTHORS, docs/tutorials/config.md, externs/shaka/player.js, lib/media/streaming_engine.js, lib/player.js, test/media/playhead_observer_unit.js, test/media/playhead_unit.js, test/media/streaming_engine_integration.js, test/media/streaming_engine_unit.js, test/test/util/streaming_engine_util.js
Do not infinitely retry on top of the retry-policy already defined by
RetryParameters, especially for VOD. For live video the previous retry
logic is still useful to be robust against clock-sync or asset
availability issues. This commit adds a boolean configuration parameter,
infiniteRetriesForLiveStreams, to allow the user to turn this behavior
off even for live video.
Fixes #830 and #762
=> Stop infinitely retrying on network errors for VOD

lib/offline/offline_manifest_parser.js, lib/offline/storage.js, test/offline/offline_integration.js, test/offline/storage_unit.js
Carrying on from the discussion in Issue #873 
Currently only ChromeOS truly supports offline storage and playback.
This change allows other browsers to support offline storage of media only. A remote/temporary license request will be made during playback, so the user must still be online.
This will help users to pre-download content before traveling to a location with a patchy/expensive internet connection.
=> Support for offline data with an online license request

CONTRIBUTORS, demo/common/assets.js
Replacement of deprecated Playready test license server in Shaka Demo App.
closes #945
=> Update Playready test LAURL

demo/index.html, demo/offline_section.js
Using `title` on `storeDelete` button in the demo is not helpful on a mobile device. This CL improves it by moving it in a separate `<span>` element.
=> Improve store/delete button UX on mobile

demo/offline_section.js
=> Demo: auto-select offline copy of asset after storing

demo/asset_section.js, demo/configuration_section.js, demo/index.html
This PR adds suggestions for audio and video robustness fields which may be obscure to newcomers especially if they didn't read https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html yet.
=> Add robustness suggestions for Widevine

lib/media/drm_engine.js, lib/offline/storage.js, lib/player.js, test/media/drm_engine_integration.js, test/media/drm_engine_unit.js, test/offline/offline_integration.js
=> Publish an event from DrmEngine if the CDM accepts the license.

demo/common/assets.js
A couple of VDMS multi drm (widevine + playready) samples to add to the demo app.  This merge request addresses issue #1140
=> Add 2 VDMS assets to the demo player that support playready and widevine

lib/media/drm_engine.js
This is a workaround for Chrome bug https://crbug.com/690583.
Resolves #1093
=> Don't wait for sessions to close on DrmEngine#destroy

externs/shaka/player.js, lib/player.js
Those externs are referenced in other parts of documentation
=> Added missing @exportDoc annotations

AUTHORS, CONTRIBUTORS, externs/shaka/player.js, lib/dash/dash_parser.js, lib/player.js, test/dash/dash_parser_content_protection_unit.js, test/dash/dash_parser_live_unit.js, test/hls/hls_live_unit.js, test/hls/hls_parser_unit.js, test/test/util/dash_parser_util.js
The DEFAULT_SUGGESTED_PRESENTATION_DELAY_ in DashParser is useful to have configurable
when the stream provider isn't able to add `suggestedPresentationDelay` in the manifest.
Fixes #1234
=> Change so that default presentation delay for DASH is configurable #1234

AUTHORS, CONTRIBUTORS, lib/player.js
A very small change, I acknowledge, but while writing type definitions for using shaka-player with our TypeScript codebase, I came accross this one.
TimelineRegionAdded, TimelineRegionEnter and TimelineRegionExit are the only events to miss the "Event" suffix.
As this is indeed a very small change I do not think this justifies opening an issue next to this pull request.
=> Rename Timeline related events to include the "Event" suffix used throughout the rest of the project

externs/shaka/manifest_parser.js, lib/util/mp4_parser.js
The comment for the definition of `shakaExtern.ManifestParser.PlayerInterface` misses a word, adding it here.
Also fixes a typo in another comment.
=> Add a missing word in ManifestParser comments

lib/net/http_fetch_plugin.js
The motivation for this change is to allow the client app to
share Shaka's support detection.
This should enable #1075.
=> Move Fetch API support detection into public method.

lib/dash/dash_parser.js
Warn if parsing the date from the UTC timing element fails, instead of silently failing to do time synchronization.
=> Issue #1317 - Warn if we don't get a valid date from UTCTiming server.

lib/net/http_xhr_plugin.js, test/net/http_plugin_unit.js
Also wrap mock XHR event handlers in try-catch blocks in
http_plugin_unit to avoid regression.
Resolves #1302
=> Catch BAD_HTTP_STATUS error thrown by makeResponse in xhr.onload

demo/common/assets.js
As of 04-02-2018 VDMS manifest servers are no longer passing
data via cookies.  As such the servers are no longer setting 
'Access-Control-Allow-Credentials' header in the response.  
The demo player is currently configured to set include credentials
for the VDMS assets and without the Allow Credentials error we get
a CORS error when attempting playback:
The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'https://shaka-player-demo.appspot.com' is therefore not allowed access
This change updates the VDMS asset callback to ensure that the credential
mode is no longer 'include'.
=> Fix playback of VDMS assets in demo app

AUTHORS, CONTRIBUTORS, build/wrapper.template.js
I came across the following  issue while using Shaka as a dependency of another pre-bundled library that was delivered to my company as a single UMD-wrapped package with no resolvable dependencies. While I can see that this is an abuse of the node module system, I anticipate many other video libraries may deliver Shaka to customers like this to avoid complexity for their customers. I will be following up with the author of the library as well, but I can't see any downside of adding the suggested changes and making Shaka more robust in the process.
Thanks!
Shaka assumes that `this` within the top-level IIFE will be bound to `window` in a browser environment.
```js
(function() {
console.log(this); // window
})()
```
This works correctly as long as Shaka is a top-level dependency …
=> Explicitly bind wrapping IIFE to window for ES5 strict mode compatibility

AUTHORS, CONTRIBUTORS, demo/common/assets.js
For details about content see https://github.com/Axinom/dash-test-vectors#live-clear
The HLS variant is currently experiencing excessive caching on the CDN, so it is likely to fail to play. I am working on sorting that out.
=> Added Axinom Live test video

AUTHORS, CONTRIBUTORS, build/wrapper.template.js
To support require in nodejs of shaka-player to fix this issue
https://github.com/google/shaka-player/issues/1445
I have added a check for window
=> Added check for window

AUTHORS, CONTRIBUTORS, lib/dash/dash_parser.js, lib/net/networking_engine.js, test/dash/dash_parser_live_unit.js
Adds shaka.net.NetworkingEngine.RequestType.TIMING for identification of clock sync requests in networking filters. Fixes #1488.
=> Add new request type TIMING for clock sync requests

AUTHORS, CONTRIBUTORS, externs/shaka/abr_manager.js, lib/media/streaming_engine.js, lib/player.js, test/media/streaming_engine_unit.js
The goal of this PR is to introduce an optional parameter that allows the buffer to be cleared but not entirely.
The idea is to keep a safe margin that avoids rebuffering events but allows for fast switches. The value of this parameter should be computed and provided by a custom ABR manager. Nothing changes if the value is not provided of course (e.g. SimpleAbrManager).
Since the buffer could be busy, another parameter had to be introduced to save the value of the safe margin when the call to clear the buffer is deferred to a later update.
Something similar was present in Shaka v1, but it was removed with the redesign.
=> Add safe margin parameter to avoid rebuffering interruptions when clearing the buffer

lib/net/http_fetch_plugin.js
Previously, HttpFetchPlugin would treat any non-Shaka error as
HTTP_ERROR when there were potentially other circumstances which
could have produced a non-Shaka error.
This change catches errors from fetch sooner, so that there is no
need to do a fuzzy check for error.severity. It also clears the
request timeout regardless of whether fetch throws or not.
Closes #1519
=> Refactor HttpFetchPlugin to clarify error outcomes

AUTHORS, CONTRIBUTORS, externs/shaka/player.js, lib/dash/dash_parser.js, lib/util/player_configuration.js, test/dash/dash_parser_content_protection_unit.js, test/dash/dash_parser_live_unit.js, test/dash/dash_parser_manifest_unit.js, test/hls/hls_live_unit.js, test/hls/hls_parser_unit.js, test/test/util/dash_parser_util.js
EDIT: pull request updated to add manifest.dash.ignoreMinBufferTime
~~i'm not really satisfied of adding a defaultRebufferingGoal to config but at least changes in code are very light~~
see #1547
=> specific rebufferingGoal override manifest one #1547 

AUTHORS, CONTRIBUTORS, docs/tutorials/offline.md
=> Bugfix/offline tutorial sample #1608

demo/offline_section.js, externs/shaka/offline.js, lib/media/drm_engine.js, lib/offline/session_deleter.js, lib/offline/storage.js
**Library**: Call setServerCertificate before store and delete operations, when serverCertificate exists:
In case of store(), it can be configured by the application.
In case of delete(), it is retrieved from the stored manifest.
**Demo application**: before store(), request and configure the certificate, when a certificateUri is given in asset.
Fixes #1623.
=> Set server certificate before Store and Delete

ui/controls.js
Hey @joeyparrish and @ismena,
As recommended in https://developers.google.com/web/updates/2018/10/watch-video-using-picture-in-picture#listen-pip-events, it is better to listen to Picture-in-Picture events instead of waiting for PiP related promises to resolve as PiP window can close and open not only from your media player UI.
For instance, closing PiP window from the close PiP window button didn't update shaka controls.
This PR adds support for this. 
Here's another example where we use PiP events: https://googlechrome.github.io/samples/picture-in-picture/
Note that I had to create a `localVideo_` variable as the `video_` proxy one didn't allow me to add PiP event listeners properly. Moveover, PiP events don't make sense for remoting.
Issue #1682
=> Update controls when external PiP events occur.

lib/dash/content_protection.js, lib/dash/dash_parser.js, lib/dash/mpd_utils.js, lib/util/xml_utils.js, test/dash/dash_parser_content_protection_unit.js
This PR is based off https://github.com/google/shaka-player/pull/1010.  It closes #484 and parses license urls from `<ms:laurl>` and `<mspr:pro>` in the DASH manifest.  I believe I have addressed all the suggestions made in the original PR.
/cc @forbesjo
=> Add license url parsing

demo/common/assets.js
Changed livesim assets to new host URLs https://livesim.dashif.org.
Added SegmentTimeline with $Number$ in addition to SegmentTimeline with $Time$.
Addes startOver URLS: interval [-20s, 20s] compared to wall-clock. These turn into static at interval end.
Corrected some information.
=> Updated DASH-IF livesim asset URLs and added new ones

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
This patch removes the requirement that a URI component must exist on any EXT-X-MEDIA other than SUBTITLES.  In additiona, the tests have been updated to capture the SUBTITLE requirement, while allowing AUDIO and VIDEO to be optional.
=> Address optional URI component mentioned in issue 1086 and issue 1730

ui/less/containers.less
The background is white on Safari in full screen mode. For example:
1. Open the test page in Safari
1. Load the Angel stream
1. Enter full screen mode
The background under the content is black.
=> Set black background in fullscreen mode

CONTRIBUTORS, lib/hls/hls_classes.js, lib/hls/manifest_text_parser.js, test/hls/manifest_text_parser_unit.js
Fixes the problem reported in #1808 
HLS parser wrongly assumes that a tag may have either a value or attributes, not both.
The RFC doesn't describe a general tag format or even give a name to what's called tag value in the Shaka Player codebase, but it clearly gives the format of EXTINF tag:
`#EXTINF:<duration>,[<title>]`
This PR makes the following changes:
* Removes either value or attributes validation from `shaka.hls.Tag`
* Simplifies branching and adds a check for value in the list of attributes in `shaka.hls.ManifestTextParser.parseTag()`
* Removes misuse of `let` in `shaka.hls.ManifestTextParser.parseTag()`, most local variables are never reassigned and can be `const`
* Adds a test case to guard against regression
=> Add support for HLS tags with both value and attributes

AUTHORS, CONTRIBUTORS, lib/media/stall_detector.js, lib/util/platform.js
Fix for https://github.com/google/shaka-player/issues/1704
=> Fix stalls on WebOS

lib/polyfill/mediasource.js
The Bitly link to Dolby's Dolby Vision Profiles and levels PDF points to a document version that no longer exists. 
Replace it with a Bitly link to https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-profiles-levels.pdf
=> Dolby Vision fixes for Chromecast

lib/media/media_source_engine.js, test/media/media_source_engine_unit.js
React Native introduces its own polyfill for window.URL.createObjectURL which is not compatible with Shaka. Encapsulating a reference to the original function inside of the MediaSourceEngine circumvents this issue.
Issue #1842
=> Fix React Native createObjectURL polyfill incompatibility

lib/dash/dash_parser.js, test/dash/dash_parser_live_unit.js
Resolves https://github.com/google/shaka-player/issues/1367
=> Make manifest redirections sticky for updates

lib/cast/cast_utils.js, lib/player.js
Add a new function called getLoadMode that returns the current load mode. The possibel response is:
DESTROYED, NOT_LOADED, MEDIA_SOURCE and SRC_EQUALS
This function is necessary for https://github.com/google/shaka-player/issues/1003 because AirPlay only works with SRC mode.
=> Add getLoadMode function

build/types/polyfill, externs/pictureinpicture.js, lib/polyfill/pip.js, shaka-player.uncompiled.js
Add PiP pollyfill for Safari
Based in https://github.com/gbentaieb/pip-polyfill
=> Add PiP pollyfill

CONTRIBUTORS, lib/media/drm_engine.js, lib/util/uint8array_utils.js
This PR will fix an issue where the license request will fail in case that there are url unsafe characters in license request post body. It will make the post request parameters have spc=base64 structure instead spc:base64.
=> Fix to FairPlay request license

externs/shaka/net.js, lib/net/data_uri_plugin.js, lib/net/http_plugin_utils.js, lib/offline/offline_scheme.js, test/test/util/fake_networking_engine.js, test/test/util/test_scheme.js
This property tracks the original request uri, which would be
useful to know in the event of a redirect.
Issue #1971
=> Add requestUri as a property on shaka.extern.Response

AUTHORS, CONTRIBUTORS, lib/text/ttml_text_parser.js
This PR fixes the issue #2028. It trims the textContent containing the base64 code of the subtitles.
=> Trim base64 subtitles in smpte:backgroundImage

AUTHORS, CONTRIBUTORS, externs/shaka/text.js, lib/text/cue.js, lib/text/ttml_text_parser.js, test/text/ttml_text_parser_unit.js, ui/less/containers.less, ui/text_displayer.js
This PR adds:
- a notion of nested cue, that renders inside the parent cue
- a first support of spans inside paragraphs
How to test:
- Live MPD w/ TTML subtitles https://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestARD.mpd
- VoD w/ French subtitles https://e213.cdn.m6web.fr/videos/test_pixel/usp/mb_hd2/subtitle/NCIS-TEARS2_chromecast_unp_sd_dash_v1.ism/Manifest.mpd (the subtitles are not in sync w/ the video, this was only made for debugging purpose)
TODO
=> improve TTML rendering

lib/text/ttml_text_parser.js, test/text/ttml_text_parser_unit.js
Since #1962, any nodes with begin or end attributes with empty content would not be interpreted as cues (`<p begin="xx" end="xxx" smpte:backgroundImage="yyy" />` for example)
This PR fixes this. 
To test: Live sim TTML Image Subtitles embedded (VoD)
=> fix ttml background image support

AUTHORS, CONTRIBUTORS, ui/range_element.js
Fixes #1918.
You're able to seek on iOS, but I'm not fully confident yet. Might be a good idea to extend the touchable surface in height in `shaka.ui.RangeElement`.
=> UI: Seek bar doesn't work on iOS

ui/text_displayer.js
=> Add background transparent if not set in SMPTE-TT subtitles

lib/dash/segment_template.js, test/dash/dash_parser_segment_template_unit.js
When trying to play some of our manifest Shaka was creating wrong URIs for each representation due to reference issue. This PR fixes that and replicates how it's done inside `createInitSegment_`
=> fix: Reference issue with SegmentReference createUris

lib/offline/download_manager.js, lib/offline/storage.js, lib/polyfill/patchedmediakeys_ms.js, lib/util/pssh.js, test/offline/storage_integration.js
Reverts google/shaka-player#2042
The PR as it landed broke some test cases and functionality for storing persistent licenses, and it doesn't seem to work even for its intended use case.
=> Revert "feature: Offline PSSH support for manifest that are missing inline init data"

lib/text/ttml_text_parser.js, test/text/ttml_text_parser_unit.js
when using DOMParser parseFromString with an empty string it returns an errored XML document
the next part of the code is then executed and throw an unnecessary error
=> fix case where TTML data is an empty string

lib/offline/download_manager.js, lib/offline/storage.js, lib/util/error.js, lib/util/pssh.js, test/offline/storage_integration.js
This is a PR for the same thing as #2042 for solving issue #1531 . I took the comments from #2042 and created a solution based on that with the issues resolved.
I test different type of contents and all works. However I know that the bot doesn't test on machine with persistent support, please review it manually also.
=> feature: Offline PSSH support for manifest that are missing inline init data

lib/polyfill/indexed_db.js
When using Shaka player inside an cross domain iframe in Firefox with 3rd party cookies blocked, `probeSupport` method throws a SecurityError.
The error is thrown in lib/offline/indexeddb/storage_mechanism.js:340, when accessing `window.indexedDB`.
The proposed solution removes `window.indexedDB` with a polyfill, using the same approach implemented for Chromecast.
=> Disable indexedDB support if a SecurityError is thrown

lib/dash/dash_parser.js, lib/util/manifest_parser_utils.js, test/dash/dash_parser_manifest_unit.js
Filter image DASH adaptation sets until https://github.com/google/shaka-player/issues/559 is resolved
Sample stream https://dash.akamaized.net/akamai/bbb_30fps/bbb_with_tiled_thumbnails_2.mpd
Now the error DASH_NO_SEGMENT_INFO is returned
=> Filter image adaptation sets

externs/shaka/abr_manager.js, externs/shaka/player.js, lib/abr/simple_abr_manager.js, lib/media/play_rate_controller.js, lib/player.js, lib/util/stats.js, test/player_unit.js, test/test/util/simple_fakes.js
Resolves https://github.com/google/shaka-player/issues/812
=> Take into account the playbackRate in bandwidth calculations

AUTHORS, CONTRIBUTORS, lib/media/drm_engine.js, lib/util/platform.js
For Video Futur platform, like for Tizen, key IDs should not be
transformed to big-endian UUIDs, it causes `4012
RESTRICTIONS_CANNOT_BE_MET` error.
Issue #2189
=> Fix error `4012 RESTRICTIONS_CANNOT_BE_MET` for Video Futur platform

lib/player.js
Resolves https://github.com/google/shaka-player/issues/2246
=> Disable video when the media element is AUDIO

lib/text/mp4_ttml_parser.js, test/hls/hls_parser_unit.js
Fixes #2378
- register TTML handler for `stpp.ttml.im1t` codec
- adjusted HLS test case to comply with rfc8216bis section 4.4.5.2
This change keeps the legacy support for codec string `stpp.TTML.im1t`. Note that while unit tests pass without this, there is good reason to assume that there is still plenty content out there using the legacy content string.
To test:
- HLS: https://demo.unified-streaming.com/video/tears-of-steel/master_hls_fmp4_clear.m3u8
- DASH: https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-ttml.ism/.mpd
=> Add lower case codec string for IMSC1 Text profile

lib/offline/storage.js, lib/util/player_configuration.js
Resolves https://github.com/google/shaka-player/issues/2383
=> Make trackSelectionCallback async

lib/offline/download_manager.js, lib/offline/storage.js, lib/util/pssh.js
The commit https://github.com/google/shaka-player/commit/c56fe7db1932f236989934bb095e161a48f82f61 introduce a regression in manifest with Playready and Widevine.
The commit doesn't filter initData that are not part of the current DRM selected for download.
=> Fix download contents with Widevine and Playready in the manifest.

AUTHORS, CONTRIBUTORS, lib/media/presentation_timeline.js, test/dash/dash_parser_live_unit.js
This is the fix for this issue.
https://github.com/google/shaka-player/issues/2411
`shaka.dash.DashParser.processManifest` is using the `presentationTimeline.usingPresentationStartTime()` to determine if it parses UTCTiming or not.
The `usingPresentationStartTime` always returns the false when maxSegmentEndTime_ is not null.
When the manifest has `SegmentTimeline`, it seems always setting a value to `maxSegmentEndTime_`.
I added the code not to set `maxSegmentEndTime_` when `autoCorrectDrift` is false.
=> Fix the bug that UTCTiming is ignored even when autoCorrectDrift is off

lib/player.js
Add a new event in the player that indicate that the load is complete.
This is necessary for SS ADS because it does the `player.load` process.
=> Add loaded event to the player

AUTHORS, CONTRIBUTORS, externs/shaka/text.js, lib/text/cue.js, lib/text/ttml_text_parser.js, test/text/ttml_text_parser_unit.js, test/ui/text_displayer_unit.js, ui/text_displayer.js
Scope of PR:
- parse ttp:cellResolution and provide it to shaka.text.Cue, so text displayers can  use it in next calculations
- add support of fontSize in '%' and 'c' to ttml_text_parser
- add support of font size in cell resolution units to shaka.ui.TextDisplayer
- add unit tests
Note:
- add partial support of font size in percentages to shaka.ui.TextDisplayer
**From w3c spec:*
*Percentages:  if not region element, then relative to the parent element's computed font size; otherwise, relative to the Computed Cell Size.*
Currently will be calculated relative to the Computed Cell Size.
Spec:
tts:fontSize - https://www.w3.org/TR/ttml1/#style-attribute-fontSize
ttp:cellResolution - https://www.w3.org/TR/ttml1/#parameter-attribute-cellResolution
<length> - …
=> Add support of fontSize in percentages and cell resolution unit for TTML captions

AUTHORS, CONTRIBUTORS, lib/media/drm_engine.js, lib/util/platform.js
Solves #2448 and #2447
I've tested it manually on device and it works fine, not sure if this could cause any other issues though?
The check is for both Tizen 2.3 and 2.4, but I have not been able to connect a debugger to Tizen 2.3 yet. I suspect the issue is there aswell and I hope that this will fix it. As mentioned by @avelad in #2448 , this is probably the same as #813. 
`webkitneedkey` is fired with the same `event.initData` for the video and audio tracks, which is flagged by `newInitData` as a faulty state.
I am not sure how to write tests for this, I'd be happy to take any pointers..
=> Tizen2.4 bugfixes

lib/dash/content_protection.js, test/dash/dash_parser_content_protection_unit.js
Resolves https://github.com/google/shaka-player/issues/2440
=> Add non-standard DASH PlayReady UUID

CONTRIBUTORS, lib/text/ttml_text_parser.js
This is regarding the issue  #2477 
percentValues_ regex works fine for "100%", but not for "100.00%"
I have modified the regex to support 100.00%.
I have sent mpd URL to shaka-player-issues@google.com to validate the issue.
=> Bitmap Subtitle is displaying middle of the screen

externs/shaka/ads.js, lib/ads/ad_manager.js, lib/ads/server_side_ad_manager.js, lib/player.js, test/test/util/fake_ad_manager.js
This change include:
- Remove bad pause for SS ads
- Fix cuechange trigger event. Safari doesn't fire cuechange if the track mode is not hidden or showing. We force the change in several times to ensure that the change is done.
Note: This change include some changes of https://github.com/google/shaka-player/pull/2476 but this PR doesn't expose any new event. Also simplify the logic to introduce metadata events from mux.js in a future
=> Fix metadata tracks for SS

lib/hls/hls_parser.js, lib/util/error.js, test/hls/hls_parser_unit.js
Resolves https://github.com/google/shaka-player/issues/1561
=> Add variable substitution support to HLS parser

lib/player.js
Resolves https://github.com/google/shaka-player/issues/2518
=> Filter metadata textracks in player APIs for src mode

lib/media/drm_engine.js
For webOS TV 2020 platform, like for Tizen, key IDs should not be
transformed to big-endian UUIDs, it causes `4012
RESTRICTIONS_CANNOT_BE_MET` error.
Issue #2512
=> Fix error `4012 RESTRICTIONS_CANNOT_BE_MET` for webOS TV platform

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
Resolves https://github.com/google/shaka-player/issues/1598
=> Parse HLS CHARACTERISTICS attribute

lib/polyfill/mediasource.js, lib/util/platform.js
OPUS was disabled in Tizen at https://github.com/google/shaka-player/issues/1751 but, in new versions of Tizen, OPUS is working
=> Allow OPUS on Tizen 5 or higher.

lib/util/buffer_utils.js, lib/util/fairplay_utils.js
@exportInterface is used by the extern generator, but ignored by the
compiler. @export should be used for shaka.util.FairPlayUtils and
shaka.util.BufferUtils.
Closes #2626 and #2627
=> export shaka.util.FairPlayUtils and shaka.util.BufferUtils

build/types/ui, docs/tutorials/ui-customization.md, externs/airplay.js, shaka-player.uncompiled.js, ui/airplay_button.js, ui/enums.js, ui/locales/en.json, ui/locales/source.json, ui/ui.js
Resolves https://github.com/google/shaka-player/issues/1003
=> Add AirPlay button to overflow menu

lib/text/simple_text_displayer.js, test/text/simple_text_displayer_unit.js
=> Render bold/italics/underline on SimpleTextDisplayer

AUTHORS, CONTRIBUTORS, lib/media/drm_engine.js, test/media/drm_engine_unit.js
This fixes the case sensitivity in the `DrmEngine` `willSupport` method. This comparison should be case insensitive, particularly for codec profiles described in hex which may be either lower or upper case. The change normalizes both the stored content types and the method arguments.
edit: Will likely target this for 2.5 as this release is the one directly affecting me. 
Closes #2799
=> fix: Fix case sensitivity for drm content type

README.md
Related to: https://github.com/google/shaka-player/issues/2783
Note: to resolve the complete issue it would be necessary to add CEA-708 to the list of supported when the support is added.
=> Add note about CEA-608/708

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
=> Check KEYID format in lowercase

lib/util/platform.js
Edge Chromium UA example: `User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Safari/537.36 Edg/79.0.309.43`
Since https://github.com/google/shaka-player/pull/2801, trying to play PlayReady content with Shaka on Edge Chromium would result in a MANIFEST_RESTRICTIONS_CANNOT_BE_MET error since it wasn't selected to do the endianness black magic.
Edge Chromium should be detected as Edge to correctly correct the key endianness.
This affects the `v3.0.4` and `v2.5.16` releases.
=> fix: correctly detect Edge Chromium as Edge

build/conformance.textproto, lib/media/playhead.js
Hi!
This request forces shaka-player to use `Date.now()` for time calculations.
First point here is that this is faster than `new Date().getTime()`.
Second point is that it allows monkey-patching `Date.now()` in runtime.
We are having issues with using `Date.now()` for time calculations (`Date.now` is not monotonic because it's affected by system time changes).
We are are going to monkey-patch `Date.now()` by using offset returned by `performance.now()` so it becomes monotonic and this patch makes this change consistent in our code and shaka-player.
=> ban new Date.getTime()

lib/media/playhead.js
There is a race condition: it could happen that `onPollWindow_` checks falling outside the availability window before `videoElement` returns the `currentTime` correctly (it returns 0 instead) so the following calculation leads to incorrect jump forward. Now it will use `this.videoWrapper_.getTime()` which returns `startTime` in that case instead.
=> onPollWindow_: use startTime when currentTime is not ready yet (fixes #2848)

lib/text/ttml_text_parser.js
Related to https://github.com/google/shaka-player/issues/2756
=> Remove hard-coded tts:extent namespace in TTML parser

ui/seek_bar.js
Previously, when seeking we do a **pause** then **continue play** after seeking. That will lead to a subtle bug.
For example: user pause a video, then seeking.
The end result user want: video is seeked but continued to be pause, that is not the current behavior (video will play when done seeking).
Is there any benefit of our current approach ?
=> seeking while video paused no longer continue playing

docs/tutorials/plugins.md
When user read about these anotation `+@complete -@polyfill`, they wonder where it came from.
It is not immediately obvious where to see it without reading the next section.
I know this because I've dig into `build.py` file to realize this line: `Build files are the files found in build/types...`
And when I comeback to read - it is in the next section, it is worth to duplicating in this case I think.
=> docs: add link to complete list of categories

AUTHORS, CONTRIBUTORS, externs/ima.js, lib/ads/client_side_ad_manager.js
Currently, shaka throw an error if adTagUrl is not set in imaRequest.
This add the possibility to use a VAST document directly using adsResponse property instead of making a request with an ad tag url.
Resolves #2892
=> feat(ads): allow adsResponse for making ad request

build/apps.py, build/build.py, build/check.py
fix #2973 
Only 3 py commands need `mkdir`, the rest are self-contained already
=> build: add mkdir to make .py command self-contained

lib/util/periods.js
The compareClosestPreferMinimalAbsDiff_ was missing a * in the
jsdoc comment; closure compiler was complaining with
> WARNING - Parse error. Non-JSDoc comment has annotations.
> Did you mean to start it with '/**'?
=> periods(fix) jsdoc comment in function

AUTHORS, CONTRIBUTORS, lib/dash/segment_template.js
Issue : https://github.com/google/shaka-player/issues/3038
We found the issue within our app with the latest Chromecast CAF receiver update (November 22, 2020) that use Shaka 3.0.x. With our live stream containing 90 minutes of buffer, we notice high level of buffering issue with our customer.
| Before | After |
| ------ | ----- |
| ![shaka-demo-app-leak-before](https://user-images.githubusercontent.com/475632/101791560-ac67ed00-3ad1-11eb-806b-017f22cf6a6c.png) | ❌  |
|  ![Screen Shot 2020-12-09 at 2 46 14 PM](https://user-images.githubusercontent.com/475632/101791653-c86b8e80-3ad1-11eb-8e8e-8dd4f848258b.png) | ![Screen Shot 2020-12-09 at 2 45 34 PM](https://user-images.githubusercontent.com/475632/101791683-d02b3300-3ad1-11eb-803d-de1053f46459.png) |
I builded a custom version of Shaka …
=> Fix memory leak when creating segment references from a timeline

lib/media/streaming_engine.js
Closes: https://github.com/google/shaka-player/issues/2982
=> Fix source buffer remove interval is too small

README.md, package.json
This new version supports CEA-708
=> chore: Update mux.js

externs/shaka/net.js, lib/net/backoff.js
Closes: https://github.com/google/shaka-player/issues/1578
We are having problems with Chromecast-CAF and since it uses ShakaPlayer it is necessary to change this here by default.
=> Change default timeout network requests

lib/text/ttml_text_parser.js
Width should be used for calculation x, and height for calculation y.
=> fix(ttml): Wrong calc of viewport anchors for cue region

README.md, build/types/text, lib/player.js, lib/text/lrc_text_parser.js, shaka-player.uncompiled.js, test/text/lrc_text_parser_unit.js
Add LyRiCs (LRC) support
Format info: https://en.wikipedia.org/wiki/LRC_(file_format)
=> Add LyRiCs (LRC) support

AUTHORS, CONTRIBUTORS, lib/dash/dash_parser.js
There's probably some closure config somewhere that would fix this but I don't know closure what so ever, this does however align more with how the rest of the code references imports.
=> fix(#3085): compiled lib not finding MimeUtils

CONTRIBUTORS, lib/ads/client_side_ad_manager.js
Listen to the `google.ima.AdErrorEvent.Type.AD_ERROR` event from the
IMA SDK AdsLoader instead of the `google.ima.AdEvent.Type.AD_ERROR` in
order to properly catch some ad errors that are currently being missed.
Resolves #3095
=> fix(ads): Use the correct AdsLoader AD_ERROR event

lib/media/drm_engine.js, lib/polyfill/patchedmediakeys_apple.js
Closes: https://github.com/google/shaka-player/issues/2999
=> Prefer unprefixed EME for Safari

lib/player.js
Closes: https://github.com/google/shaka-player/issues/1782
=> Clear error code needed for bad MIME type in addTextTrack

lib/media/segment_index.js
tested with Webpack mode=production which caused the issue. 
Solve #3092
=> fix: memory leak after bundling 3.0.x branch and latest version with Webpack

externs/ima.js
Sets the type of the google.ima.settings object extern to
`google.ima.ImaSdkSettings` to avoid duplicating the defined methods.
Also adds the setVpaidMode method and VpaidMode enum to the
google.ima.ImaSdkSettings class extern.
Resolves #3134
=> feat(ads): Add setVpaidMode to the ima externs

AUTHORS, CONTRIBUTORS, lib/media/streaming_engine.js, test/media/streaming_engine_unit.js
Adds support to parse version 1 of 'emsg' boxes.
The structure of 'emsg' box is described in the DASH-IF spec at
https://dashif-documents.azurewebsites.net/Events/master/event.html#emsg-format
Added unit test to ensure the box is correctly parsed.
=> Support for DASHEventMessageBox Version 1

lib/text/ui_text_displayer.js
This PR solves issue #3151.
We've seen some SmartTVs show one subtitle without removing the previous one.
I think this is happening because two different subtitles may meet the condition of "greater or equal than" and "lower or equal than" at the same time. After changing the greater than or equal with a greater than subtitles were fixed.
=> (fix) Subtitles are shown stacked

lib/util/multi_map.js, lib/util/stream_utils.js, test/util/stream_utils_unit.js
avc1: 240, 360, 480, 720, 1080
vp9: 240, 360, 480, 720, 1080, 1440, 2160 (average bandwidth is higher, more variants)
Before:
Best codecs: avc1 (incorrect)
After:
Best codecs: vp9 (correct)
Details: #3056
Remove variants where the height is not found in all codec groups.
=> Fixed choice of codecs for 4K and higher

build/generateLocalizations.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Module named io is imported and io.open() is used instead of open() for fixing encoding error which occurs in python2 .
added encoding type as utf-8 in line 251 for fixing UnicodeDecodeError
Fixes # (issue)
#3208
#3204
=> fixed error #3208 #3204

build/check.py, build/compiler.py, build/generateLocalizations.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
issue #2985 occurs in windows . replacing '\\' with '/' fixes the error for windows but impling the changes to all platforms may result in errors so an if condition is added to replace slashes only in windows . 
there was a ';' inside check.py which i believe was a syntax error so removed it .
Fixes # (issue)
#2985
=> fixed issue #2985

ui/enums.js, ui/small_play_button.js
Addition of replay icon after ending of video
Fixes #3247
=> Addition of replay icon

docs/tutorials/ui-customization.md, ui/airplay_button.js, ui/cast_button.js, ui/enums.js, ui/less/containers.less, ui/loop_button.js, ui/pip_button.js
The present pull request provides a partial solution to #2676 (Add overflowMenuButtons to the UI bar) by making the Picture-in-picture, Loop, Cast and AirPlay buttons available in the UI control panel.
The final result is achieved using the [CSS display none approach](https://github.com/google/shaka-player/issues/2676#issuecomment-801642557) suggested by @joeyparrish, and looks as follows:
<p align=center>
</p>
=> feat(ui): Add Loop, PIP, Cast, AirPlay buttons to control panel

README.md, build/test.py, karma.conf.js, package.json
With this change it is possible to run the tests in Edge Chromium by default.
Karma needs to be updated to allow wildcard scoped packages to be used by default, see: https://github.com/karma-runner/karma/pull/3659
Test results on macOS:
```
./build/test.py
[WARNING] Using default browsers: ['Chrome', 'Edge', 'Firefox', 'Safari']
[INFO] Generating Closure dependencies...
[INFO] Compiling the library (ui, release)...
[INFO] Running test (1 / 1, 0 failed so far)...
Chrome 89.0.4389.90 (Mac OS 10.15.7): Executed 2058 of 2096 (skipped 38) SUCCESS (7 mins 14.056 secs / 7 mins 4.732 secs)
Edge 89.0.774.54 (Mac OS 10.15.7): Executed 2011 of 2096 (skipped 85) SUCCESS (7 mins 12.33 secs / 7 mins 4.255 secs)
Firefox 86.0 (Mac OS 10.15): Executed 2011 of 2096 (skipped 85) SUCCESS (7 mins 18.377 secs …
```
=> Allow test Edge Chromium with Karma

docs/tutorials/drm-config.md, externs/shaka/player.js, lib/dash/content_protection.js, lib/dash/dash_parser.js, lib/media/drm_engine.js, lib/offline/storage.js, lib/util/player_configuration.js, test/demo/demo_unit.js, test/media/drm_engine_unit.js
Turns out the solution I developed for PlayReady recommendation (#1495 & #2750) is way too complicated and brings too many different use cases to handle over multiple files to be considered fit to be merged, without being scared for regressions (in my own opinion). Alongside that issue, some errors due to recommendation use could be raised outside the silent try catch, making it quite difficult to debug them for developers
In that PR, I make the DASH keySystems configurable so that any developer could chose to opt-in for recommendation based on DASH DRM UUID. 
```js
player.configure({
dash: {
keySystemsByURI: {
'urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95': 'com.microsoft.playready.recommendation',
'urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95': …
```
=> feat: make dash keySystems configurable

lib/hls/hls_parser.js, lib/util/error.js, test/hls/hls_parser_unit.js
=> fixes(hls): adds fallback to MP4 in case the Mime type is not identified by parser

ui/less/ad_controls.less
controls were covering the SkipAd button.
this commit lifts up the shaka-client-side-ad-container.
also the shaka-server-side-ad-container was overflowing outside shaka-controls-container, now its shrinkable.
refer to #3284 
=> fix(ads): height property was not taking effect on client side ads #3284

docs/tutorials/offline.md
When configuring offline storage in initStorage in initialising storage, an OfflineConfig was used instead of a player config, which worked in v2.5 but not in ~v3.5~ v3.0. Because of this when the final code was run the progress bar wouldn't work properly as progressCallback was not set.
=> Update offline tutorial to use a player config for offline storage

demo/demo.less
=> hover effect on setting icon and some padding

demo/common/asset.js, demo/common/assets.js, demo/main.js, externs/shaka/manifest.js, externs/shaka/player.js, lib/media/drm_engine.js, lib/net/networking_engine.js, lib/util/error.js, lib/util/manifest_parser_utils.js, lib/util/player_configuration.js, test/media/drm_engine_unit.js, test/offline/manifest_convert_unit.js, test/offline/storage_integration.js, test/test/util/manifest_generator.js
Fixes #1906
Works when running alone but doesn't when running with all the other tests (same thing on master)
> Chrome 89.0.4389.128 (Mac OS 10.15.7) Offline stores, plays, and deletes protected content with a persistent license FAILED
=> feat: add serverCertificateUri in DRM advanced config

lib/offline/storage.js
There are currently two errors: STORAGE_LIMIT_REACHED and DOWNLOAD_SIZE_CALLBACK_ERROR.
The first error was never thrown because the catch threw the second error. This PR fixes that error.
=> Fix missing error STORAGE_LIMIT_REACHED when the downloadSizeCallback is false

externs/shaka/net.js, lib/media/streaming_engine.js, lib/net/http_fetch_plugin.js, lib/net/networking_engine.js, lib/util/networking.js
=> Append segment chunk strictly in order

lib/util/mp4_parser.js
=> Fix index out of bound issue when parsing mp4 segment

lib/text/web_vtt_generator.js, test/text/web_vtt_generator_unit.js
This PR adds align and vertical settings to WebVttGenerator
=> Add align and vertical settings to WebVttGenerator

lib/text/ui_text_displayer.js
There are measurements that use absolute values in pixels after a conversion. By making this change we force to update the subtitles that are being shown to have the correct dimensions.
=> React to fullscreenchange event in UITextDisplayer

lib/util/stream_utils.js, test/util/stream_utils_unit.js
Currently a full chain comparison is done, but in video codecs, you may want H.265/VP9 with no profile preference, with this change it is possible to do this.
Examples:
'hvc1' instead of 'hvc1.1.2.L123.80' and 'hvc1.1.2.L153.80'
'vp09' instead of 'vp09.00.40.08.00.02.02.02.00'
Issue: #2179
=> Improve preferredVideoCodecs & preferredAudioCodecs

lib/text/ui_text_displayer.js
There are measurements that use absolute values in pixels after a conversion. By making this change we force to update the subtitles that are being shown to have the correct dimensions.
Related to: https://github.com/google/shaka-player/pull/3414
=> Force update captions with resizes

lib/text/ui_text_displayer.js
Notice when debug non relevent issue.
If we always force update captions, then the logic inside updateCaptions_ does not make sense (as we keep delete/insert cue at lightning speed with every tick update)
=> fix: not force update caption by default

lib/media/content_workarounds.js
The fake encryption solution implemented for Xbox seems to be failing for streams that have EC-3 tracks so I've added an encryption box for that as well
=> fix: Add encrypted box on EC-3

docs/tutorials/faq.md
FAQ docs on how to disable Range header requests at start of HLS playback. Which speeds up start of playback when your server has problems with Range header requests
- [] My code follows the style guidelines of this project
=> docs: how to disable Range header requests at start of HLS playback

AUTHORS, CONTRIBUTORS, lib/media/streaming_engine.js, test/media/streaming_engine_unit.js
Fixes #3384 
streaming_engine maintains a reference to ongoing fetch operations for
video, audio and text segments. Using these references, the fetch
operations may be cancelled (e.g. due to a seek).
Immediately following a seek, fetch operations were started for init
segments and media segments. Upon completion of the init segment
operation the reference to the media segment operation was overwritten
with null, so could not be cancelled.
This was particularly evident on platforms where the seek bar is
dragged, as this produces multiple seeks. When dragging backwards it
was possible for the buffer to contain segments beyond the play head.
The solution is to await completion of the init segment fetch before
starting the media segment fetch.
- [X ] Bug fix (non-breaking change which fixes …
=> Fix #3384 Multiple Seek Backwards (e.g. Drag)

lib/media/streaming_engine.js, lib/player.js
Close: https://github.com/google/shaka-player/issues/3450
=> Fix: selectVariantTrack doesn't clear buffer if already selected

externs/shaka/player.js, lib/dash/dash_parser.js, lib/util/player_configuration.js, test/dash/dash_parser_manifest_unit.js
Implements #3339
Added support for efficient preprocessing of DASH manifest after they have been parsed into an XMLDocument
This is configure with the new manifest.dash.manifestPreprocessor  setting.
This is need to efficiently repair manifests that are not compatible with Shaka player.
Documentation for DashManifestConfiguration changes
=> Add support for efficient preprocessing of DASH manifests after parsing into an XMLDocument

AUTHORS, CONTRIBUTORS, lib/player.js
When sending a video to an AirPlay target, such as an Apple TV or a TV
with AirPlay built in, it can become impossible to change from one
audio language, to a second audio language, then return to the first
audio language.
When enabling a new audio track, it is assumed that
all other tracks will be disabled. However, while sending media to the
AirPlay target, no tracks are automatically disabled. As a result, it
would become impossible to reselect certain audio tracks as the player
would keep playing an enabled track, even if it isn't the most recently
enabled track.
Issue #3125
=> Fix audio language switching while using AirPlay

externs/aria.js, ui/airplay_button.js, ui/audio_language_selection.js, ui/cast_button.js, ui/constants.js, ui/fast_forward_button.js, ui/fullscreen_button.js, ui/language_utils.js, ui/loop_button.js, ui/mute_button.js, ui/overflow_menu.js, ui/pip_button.js, ui/play_button.js, ui/playback_rate_selection.js, ui/presentation_time.js, ui/resolution_selection.js, ui/rewind_button.js, ui/seek_bar.js, ui/spacer.js, ui/text_selection.js, ui/ui_utils.js, ui/volume_bar.js
Related to: https://github.com/google/shaka-player/issues/3378
=> Stop using setAttribute for ARIA

ui/big_play_button.js, ui/locales/en.json, ui/locales/source.json, ui/play_button.js, ui/small_play_button.js
Close: https://github.com/google/shaka-player/issues/3512
=> Fix: Replay button does not have correct aria-label

AUTHORS, CONTRIBUTORS, lib/player.js, test/player_unit.js
Fix Y position calculation for the `getThumbnails` funtion.
Fixes #3511 
=> Thumbnail position calculation

lib/player.js
fix https://github.com/google/shaka-player/issues/3448
in 2.5.1, we can pick variant track from manifest alone.
this functionality is broken from v3.
this patch allowed user to pick variant track from streaming event.
=> fix: user can pick variant track/texttrack from streaming event

ui/play_button.js
Close: https://github.com/google/shaka-player/issues/3495
=> Fix: Incorrect icon Play after video ends and rewind

lib/cast/cast_utils.js, lib/player.js
Add goToLive method to the Player. This new method is very useful in live streams.
=> Add goToLive method

lib/polyfill/media_capabilities.js
Maybe related to: https://github.com/google/shaka-player/issues/3530
=> Add support to file type in MediaCapabilities polyfill

lib/media/drm_engine.js, lib/player.js, lib/util/stream_utils.js, test/util/stream_utils_unit.js
=> Add basic support to file type in mediaCapabilities implementation

lib/polyfill/media_capabilities.js
Maybe related to: #3530
Note: In iOS, since there is no support for MediaSource, if the type is 'media-source' it always returns false, but if the type is 'file' it is checked whether it is supported or not.
MediaCapabilities support: https://caniuse.com/mdn-api_mediacapabilities
=> Add Support to iOS 12 in MediaCapabilities polyfill

lib/polyfill/media_capabilities.js
Related to: #3530
Errors found in Apple browsers about MediaCapabilities 
- HLS is not supported using file type.
- TS is not supporting using media-source type.
=> Always polyfill MediaCapabilities for Apple browsers

docs/tutorials/ui-customization.md, ui/externs/ui.js, ui/fast_forward_button.js, ui/playback_rate_selection.js, ui/rewind_button.js, ui/ui.js
The present pull request aims to provide a solution to #3443 (How to Customise PlayBackRate or Fast_Forward rate) by adding optional custom rates for playback, fast forward and rewind.
Fixes: #3443
<p align=center>
</p>
Initialize the client with a `config` that contains `playback_rate`, `fast_forward` and `rewind` in the `controlPanelElements` and select a list of rates for `playbackRates`, `fastForwardRates` and `rewindRates`.
```js
const config = {
'controlPanelElements': ['playback_rate', 'fast_forward', 'rewind'],
'playbackRates': [0.5, 1, 1.5, 2, 4.321],
'fastForwardRates': [2, 4, 8, 1],
'rewindRates': [-1, -2, -4, -8],
}
ui.configure(config);
```
<details>
<summary><code>docs/tutorials/ui-customization.md</code></summary>
Adds a brief description and example for the …
=> feat(ui): Add configurable rates

docs/tutorials/ui-customization.md, ui/airplay_button.js, ui/audio_language_selection.js, ui/cast_button.js, ui/controls.js, ui/controls.less, ui/externs/ui.js, ui/fast_forward_button.js, ui/fullscreen_button.js, ui/less/tooltip.less, ui/loop_button.js, ui/mute_button.js, ui/overflow_menu.js, ui/pip_button.js, ui/playback_rate_selection.js, ui/resolution_selection.js, ui/rewind_button.js, ui/small_play_button.js, ui/text_selection.js, ui/ui.js
The present pull request aims to provide a solution to #3269 (Add hover tooltips to control panel buttons) by adding configurable tooltips to control panel buttons.
Fixes: #3269
<p align=center>
</p>
Initialize the client with a `config` that sets the `enableTooltips` option to `true`.
```js
const config = {
'enableTooltips': true
};
ui.configure(config);
``` 
<details>
<summary><code>docs/tutorials/ui-customization.md</code></summary>
Adds a brief description and example for the `enableTooltips` configuration.
</details>
<details>
<summary><code>ui/airplay_button.js</code>, <code>ui/fullscreen_button.js</code>, 
<code>ui/cast_button.js</code>, <code>ui/loop_button.js</code>, 
<code>ui/mute_button.js</code>, <code>ui/overflow_menu.js</code>, 
<code>ui/small_play_button.js</code></summary> …
=> feat(ui): Add tooltips to control panel buttons

lib/cea/sei_processor.js, lib/util/mp4_box_parsers.js, test/cea/mp4_cea_parser_unit.js, test/util/mp4_box_parsers_unit.js
This PR fixes two issues:
1. CEA-608 subtitles not showing up
2. Decoder error (Code 3016) occasionally thrown by Chromium VDA
For issue 1, the root cause is incorrect MP4 TKHD unboxing. Track ID should be 4 bytes instead of 8. That causes a mismatch in track ID and timescale mappings. Timescale value will then fallback to default (90,000) and parse to MDAT unboxing. All CC packets will use the wrong timescale for calculating the timestamp.
For issue 2, it's caused by the method of removing emulation prevention bytes from MP4 H.264 SEI NALU packets. Removing the byte by shifting all elements will cause Chromium VDA to complain about conformance (likely it has a lower tolerance than other browsers). Note that Safari and Firefox seem to allow such modification.
This is solved by creating a …
=> Fix: Issues related to CC & MP4 H.264

lib/media/content_workarounds.js
`content_workarounds.js` was introduced for Tizen and Xbox platforms.  We found that that meant a regression where certain streams were unable to be played.
This PR adds avc3 into the content workarounds in the same was as avc1 to ensure these streams can be played once more.
Fixes #3589 
=> avc3 added to content workarounds

lib/media/content_workarounds.js
`content_workarounds.js` was introduced for Tizen and Xbox platforms. We found that that meant a regression where certain streams were unable to be played.
This PR adds ac-3 into the content workarounds in the same was as ec-3 to ensure these streams can be played once more.
Related to https://github.com/google/shaka-player/pull/3625
=> ac-3 added to content workarounds

lib/ads/ad_manager.js, lib/ads/server_side_ad_manager.js
This change causes the safe SS-DAI settings to be reset when a stream is unloaded.
=> Fix Server Side Ad manager stop

externs/shaka/ads.js, lib/ads/ad_manager.js, lib/ads/client_side_ad_manager.js, lib/ads/server_side_ad_manager.js, lib/player.js, lib/text/web_vtt_generator.js, test/test/util/fake_ad_manager.js, test/text/web_vtt_generator_unit.js, ui/seek_bar.js
When an external subtitle track is added and you are using DAI, the external track does not take into account the ads that the video has, so this PR makes this internally take into account when generating the external track.
=> Take into account the ad cue points (server side only) in external text tracks

AUTHORS, CONTRIBUTORS, externs/shaka/net.js, lib/net/http_plugin_utils.js
This pull request fixes the issue: #3640 
Basically I just added response status to response filter, it can be useful for someone who needs to check response status and based on that do some actions.
=> Add response HTTP status to Networking engine responses

lib/ads/client_side_ad_manager.js
Close: https://github.com/google/shaka-player/issues/3638
=> Fix: dimensions of CS Ad are wrong after the first pre roll.

lib/polyfill/aria.js, lib/polyfill/encryption_scheme.js, lib/polyfill/fullscreen.js, lib/polyfill/mathround.js, lib/polyfill/media_capabilities.js, lib/polyfill/mediasource.js, lib/polyfill/orientation.js, lib/polyfill/patchedmediakeys_apple.js, lib/polyfill/patchedmediakeys_ms.js, lib/polyfill/patchedmediakeys_nop.js, lib/polyfill/patchedmediakeys_webkit.js, lib/polyfill/pip_webkit.js, lib/polyfill/storage_estimate.js, lib/polyfill/video_play_promise.js, lib/polyfill/videoplaybackquality.js, lib/polyfill/vttcue.js
This change allows polyfills to be installed individually e.g. `shaka.polyfill.MediaCapabilities.install()` instead of `shaka.polyfill.installAll()`
Related to #2625
=> chore: Add @export annotations to polyfill install methods

ui/less/containers.less
The present pull request aims to provide a solution to a minor visual bug present in the control panel displaying unaligned "sub-menu" buttons (i.e: `quality`, `language`, `playback_rate`). 
In the following example, the green and orange rectangles are exactly the same size and dimensions for both images. Note how the alignment of both rectangles and the size of the red areas change between the before (top) and after (bottom) images.
<p align=center>
</p>
Initialize the client with a config that contains sub-menu buttons (i.e: `quality`, `language`, `playback_rate`) and control panel buttons (i.e: `fast_forward`, `fullscreen`, `overflow_menu`) in the `controlPanelElements`.
```js
const config = {
'controlPanelElements': ['quality', 'loop', 'fast_forward', 'language', 
'playback_rate', …
```
=> fix(ui): Control panel alignment

lib/player.js
Fix: https://github.com/google/shaka-player/commit/7b2a17276b495c7961fac1fdcbf944b613c542d1
The previous commit, when using the `detach` function, `this.adManager_` is destroyed and there is nowhere where it will be recreated. But this is not necessary, only with the call to `release` the dependencies of the video are eliminated, and the object is reusable.
=> Fix dispose of ad manager on detach

build/types/polyfill, externs/webcrypto.js, lib/polyfill/random_uuid.js
Related to: https://github.com/google/shaka-player/pull/3662
=> Add randomUUID polyfill

AUTHORS, CONTRIBUTORS, lib/util/stream_utils.js, test/util/stream_utils_unit.js
Fixes #3729
If the video variant stream contains information about `hdr`, then we now use that to provide a value for `transferFunction`, when constructing the [`VideoConfiguration`](https://w3c.github.io/media-capabilities/#videoconfiguration) object used to get decoding info from media capabilities API.
The following applies:
```js
switch (video.hdr) {
case 'SDR':
mediaDecodingConfig.video.transferFunction = 'srgb';
break;
case 'PQ':
mediaDecodingConfig.video.transferFunction = 'pq';
break;
case 'HLG':
mediaDecodingConfig.video.transferFunction = 'hlg';
break;
}
```
=> Pass HDR information when getting decoding info from media capabilities

AUTHORS, CONTRIBUTORS, lib/dash/dash_parser.js, test/dash/dash_parser_manifest_unit.js
This is for fixing a case in geo-redundant streams failover:
1. ShakaPlayer identifies DASH period based on period id
1. Period ids generated by two synchronized packager could be inconsistent temporarily in some negative scenarios
1. After the scenario the packagers resync at the live edge, but the inconsistency is preserved in the manifest for the length of the DVR window
1. When ShakaPlayer receives a new mpd with inconsistent period ids (i.e. jumping between mpds from two packagers), it might result in
- Wrong presentation time
- Wrong buffer ahead estimation
- Old segment references added into segment index
1. Consequently, playback gets stalled and requires end-user to refresh the player (i.e. VPF)
N/A
=> Geo failover robustness

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
Correctly obtain value of DEFAULT tag so variants can be tagged as primary, to avoid arbitrary audio language selection in multi-variant playlists.
Fixes #3769
=> fix parsing of HLS 'DEFAULT' attribute

lib/text/text_engine.js, lib/util/periods.js
Fixes #3783
Embedded CEA-608 captions don't work on multi period live DASH DAI streams after new periods appear in the manifest because commas are appended the streams originalId string, which disrupts some stream matching code in text_engine.js
The problem has been resolved by preventing makeTextStreamsForClosedCaptions() from altering the PeriodCombiner.textStreams_ array.
NA
- [NA] I have made corresponding changes to the documentation
- [No] I have added tests that prove my fix is effective or that my feature works
=> Fix #3783 captions not working after a period transition on live DASH streams

AUTHORS, CONTRIBUTORS, lib/dash/dash_parser.js, test/dash/dash_parser_manifest_unit.js
Fixes #3726
Now we parse value of descriptor for `urn:mpeg:mpegB:cicp:TransferCharacteristics` in `AdaptationSet` to indicate `hdr` property on `shaka.extern.Stream` which seems equivalent to HLS definition given in `VIDEO-RANGE` attribute within [`EXT-X-STREAM-INF`](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-09#section-4.4.6.2).
This is done by reading the supplemental / essential property in the parsing of `AdaptationSet`, then mutating the `hdr` property on `shaka.extern.Stream` if no `hdr` exists after `parseRepresentation_`.
The alternative considered was to parse all essential / supplemental properties on any `shaka.dash.DashParser.InheritanceFrame` and then carrying that through to the `parseRepresentaiton_` function; this can be seen …
=> Dash hdr signalling via essential or supplemental property

lib/text/ui_text_displayer.js
Fixes: https://github.com/google/shaka-player/issues/3745
=> Fix captions use the entire screen

.github/workflows/build_and_test.yaml, test/media/streaming_engine_integration.js
Allows Github Action tests to run integration tests on macOS.
=> Github Actions macOS Integration Tests

test/media/streaming_engine_integration.js
The test StreamingEngine "can handle seeks behind availability window" was
frequently failing on macOS Chrome. This makes the test a bit more
permissive.
=> fix(tests): Fix failing test on GitHub Actions.

demo/main.js, lib/ads/client_side_ad.js, lib/ads/client_side_ad_manager.js, ui/controls.js, ui/fullscreen_button.js
Fixes: https://github.com/google/shaka-player/issues/3832
=> Add video fullscreen support for iOS

lib/util/stream_utils.js
Fixes: https://github.com/google/shaka-player/issues/3845
=> Allow WebP and AVIF image streams

externs/shaka/player.js, lib/player.js, lib/util/stream_utils.js, test/player_unit.js
The commit https://github.com/google/shaka-player/commit/264c84249684ee809f53fd4117f9aab4e0a599ac introduce 2 issues:
- `stream.segmentIndex` is not always constructed (eg: DASH)
- In Image track the size of the thumbnail itself is returned and not the size of the complete image, so it is necessary to return the size of the complete image in `getThumbnails` so that later the UI can correctly place the image if the layout is different to 1x1.
=> Fix thumbnails issues

lib/media/streaming_engine.js, test/media/streaming_engine_unit.js
Ensure buffer is cleared on an unbuffered seek, for media states that are mid-update even if they have no buffer yet. This prevents the update operation from appending buffer for the old time and potentially getting one media state stuck buffering to catch up to the target seek position.
Fixes #3299
=> clear buffer on unbuffered seek for updating media states

.github/workflows/build_and_test.yaml, build/test.py, karma.conf.js
This adds a new test configuration flag, `--spec-hide-passed`, which (if the test reporter is `spec`) causes passing tests to not produce any logs. This configuration flag is set on GitHub actions runs, so that the logs from them aren't so overwhelmingly long.
=> test: Hide passing tests in GitHub actions runs.

.github/workflows/README.md, .github/workflows/build_and_test.yaml, .github/workflows/tools/update-issues/issues.js, .github/workflows/tools/update-issues/main.js, .github/workflows/tools/update-issues/package-lock.json, .github/workflows/tools/update-issues/package.json, .github/workflows/update_issues.yaml
This replaces an internal tool that we have been running on a private
Jenkins server.
=> ci: New workflow to update issues

.github/workflows/README.md, .github/workflows/test_update_issues.yaml, .github/workflows/tools/update-issues/main.js, .github/workflows/tools/update-issues/mocks.js, .github/workflows/tools/update-issues/package-lock.json, .github/workflows/tools/update-issues/package.json, .github/workflows/tools/update-issues/reporter.js, .github/workflows/tools/update-issues/tests.js
This ports over internal tests suggested in #3889.
=> ci: Add tests for new update-issues tool

test/ui/text_displayer_layout_unit.js
This fixes some missing cues in screenshot tests for native rendering in Safari.
Changes to tests only.
=> test: Fix flake in screenshot tests around native captions

karma.conf.js, package.json, test/test/util/util.js, test/ui/text_displayer_layout_unit.js
Instead of pixel-wise comparison with a change threshold, we now use a
structural similarity (ssim) module to decide how much a screenshot
has changed.  This better tolerates small rendering differences due to
differences in GPUs across machines.
Changes to tests only.
=> test: Make screenshot comparisons more tolerant

roadmap.md
This updates the roadmap for v3.2 and v3.3 (out) and v3.4 (upcoming).
This also trims down our current priorities to what the team at Google
will be addressing in the near term.
=> chore: Update roadmap

demo/main.js, lib/hls/hls_parser.js, lib/media/media_source_engine.js
Issue #2337
Change-Id: I909a1c09cac270cd4127a2ddd2ce5506d6ef0f35
We were not probing MediaSource for containerless format support before.
This meant that, among other things, the demo did not register the new raw AAC asset as playable.
=> fix: Probe for containerless format support.

lib/media/streaming_engine.js
Add null check for emsgSchemeIdUris when EMSG boxes are parsed, as this value is null for HLS streams
Fixes #3886
=> add null check for emsgSchemeIdUris in streaming engine parseEMSG_

lib/offline/storage.js
Fix download of https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8
The filterManifestByMediaCapabilities method is async, but the code doesn't wait for it to finish before continuing the download process. This PR fix it.
=> Fix download of some HLS assets

.github/workflows/validate_pr_title.yaml
This will allow automated generation of changelogs and releases based
on PR titles.
=> ci: Require PRs in conventional commits syntax

test/player_integration.js
Instead of waiting for the playhead to reach a specific time that we
know to be the end, then expecting ended to be true, we can use the
purpose-built waiter that waits for the ended event.
We also need to set the timeout explicitly, so that we have enough
time to play through to the end.
=> test: Fix flaky player integration test

lib/hls/manifest_text_parser.js, test/hls/hls_parser_unit.js
Example manifest:
`#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=1000000, RESOLUTION=1920x1080`
=> fix(HLS): skip whitespace in attributes

.github/workflows/build_and_test.yaml
CI for Firefox on Linux is failing because of (I suspect) an outdated
package index in Ubuntu.  This addresses it by updating the package
list before installing ffmpeg.
=> ci: Fix ffmpeg install failure for Linux+Firefox

lib/ads/ad_manager.js, lib/cast/cast_proxy.js, lib/cast/cast_receiver.js, lib/net/networking_engine.js, lib/player.js, lib/util/fake_event_target.js, ui/controls.js, ui/localization.js
Before, we would count on all event listeners for FakeEventTargets to
be cleaned up by the object that listens.  Now, FakeEventTarget
implements IReleasable, so that all listeners are removed when owners
call release().
For objects extending FakeEventTarget and also implementing
IDestroyable, the destroy() methods will call out to super.release()
to clean up listeners then.  The owner should use destroy() in those
cases.
Issue #3949 (memory leak in DASH live streams with inband EventStream)
=> fix: Add explicit release() for FakeEventTarget

lib/media/quality_observer.js, lib/media/region_observer.js, lib/media/region_timeline.js, lib/player.js, test/media/quality_observer_unit.js, test/media/region_observer_unit.js, test/media/region_timeline_unit.js
Three classes (RegionTimeline, RegionObserver, and QualityObserver)
were all designed with callbacks instead of events.  A single callback
is inflexible compared to events, which allow multiple listeners.  We
already have a long-standing and robust event system, so why not use
it?
Issue #3949 (memory leak in DASH live streams with inband EventStream)
=> refactor: Replace callbacks with events

externs/shaka/text.js, lib/media/media_source_engine.js, lib/media/streaming_engine.js, lib/text/lrc_text_parser.js, lib/text/mp4_ttml_parser.js, lib/text/mp4_vtt_parser.js, lib/text/sbv_text_parser.js, lib/text/srt_text_parser.js, lib/text/ssa_text_parser.js, lib/text/text_engine.js, lib/text/ttml_text_parser.js, lib/text/vtt_text_parser.js, test/media/media_source_engine_unit.js, test/text/text_engine_unit.js
When running in sequence mode, we ignore the normal timestamps
of video and audio segments. This lead to problems in some Apple-
encoded webvtt content, which used the X-TIMESTAMP-MAP tag to account
for the timestamp offsets in their video. Thus, those subtitles would
end up 10 seconds offset.
This changes the webvtt parser to ignore the X-TIMESTAMP-MAP when in
sequence mode.
Issue #2337
=> fix(text): Fix webvtt offset in sequence mode

lib/dash/dash_parser.js, lib/media/region_observer.js, lib/media/region_timeline.js, test/dash/dash_parser_live_unit.js, test/dash/dash_parser_manifest_unit.js, test/media/region_observer_unit.js, test/media/region_timeline_unit.js
EventStreams in DASH generate TimelineRegionInfo objects, which are
then stored in the RegionTimeline and RegionObserver classes.  But
DashParser would add all regions to RegionTimeline, even if they would
be quickly removed again, and RegionObserver would cache some regions
from the timeline without ever removing them.
This fixes the issue from both of those directions.  DashParser will
now ignore regions that are outside the DVR window (and therefore
would soon be removed from RegionTimeline), and RegionObserver listens
to an event on RegionTimeline to clean up its own storage when regions
fall outside the DVR window during playback.
Closes #3949 (memory leak in DASH live streams with inband EventStream)
=> fix: Fix memory leak in DASH live streams with inband EventStream

build/checkversion.py
We double-check the version in the changelog to make sure it matches
the npm and player versions.  But with our new release automation, we
have a new changelog format.  This updates the parsing so that release
checks can succeed.
=> build: Update version parsing to match new release automation

README.md, lib/hls/hls_parser.js, lib/util/platform.js
In Tizen 2/3 and WebOS 3.x there is no support for SourceBuffer.mode=sequence so as a result of change https://github.com/google/shaka-player/issues/2337, it necessary disable support for the HLS parser so that the user can at least use the native one with src= .
=> feat!(hls): HLS disabled in old browsers/platforms due to incompatibilities

AUTHORS, CONTRIBUTORS, build/test.py
Fixes #3079
When running custom asset tests with the custom license server parameter, it is easy to make mistakes on the argument value. The `--test-custom-license-server` option expects the user to pass in a key-value pair of `KEYSYSTEM_ID=LICENSE_SERVER_URL`. This change checks if the provided value has `KEYSYSTEM_ID` as its key through a custom argparse type.
=> test: Validate custom license server option in test.py

build/compiler.py, package-lock.json, package.json, ui/less/ad_controls.less, ui/less/buttons.less, ui/less/containers.less, ui/less/range_elements.less, ui/less/tooltip.less
Downgrade less to v3.  v4 is failing on macOS for some reason.  See
less/less.js#3693
This also makes some less/CSS changes that are useful for future
upgrades:
- wrap all calculations in calc(), which is required in less v4
- remove unneeded @transparent variable
Finally, this fixes an erroneous error message that said "extern
generation failed" instead of "CSS compilation failed".
Closes #3981
=> build: Downgrade less

.github/pull_request_template.md
The old template is bulky and does not reflect the new workflows we
have on GitHub.  All that is really critical is that users start using
Conventional Commits syntax and tag issue numbers.
=> ci: Simplify PR template

.github/workflows/release.yaml
1. When release-please creates release PRs, it removes the -uncompiled
tag in the version number in lib/player.js.  This adds a step to the
workflow to maintain the player.js version manually.
2. This also adds a new job that tags the master branch after a
release PR is merged.  We maintain the -master tags on the master
branch corresponding to each release so that it is easier to manage
the range of commits for cherry-picks.
3. The "npm ci" step was failing because our package-lock.json was not
compatible with v12 of NodeJS.  This updates our workflow to use v16.
The npm release workflow has now been tested in a fork up until the
publish step.
4. The tagging and GitHub release publication parts of the workflow
were previously failing due to an issue with release-please parsing
the branch …
=> ci: Fix several release workflow bugs

lib/hls/hls_parser.js, lib/media/media_source_engine.js, lib/media/streaming_engine.js, test/media/media_source_engine_integration.js, test/media/media_source_engine_unit.js, test/media/streaming_engine_unit.js, test/test/util/fake_media_source_engine.js
HLS now appends segments in sequence mode. In order to handle seeks,
we set the timestampOffset property on SourceBuffer to the startTime of
the segment. This is done after every seek, or on startup.
For non-sequence-mode content (DASH), we normally set timestampOffset
based on the Period structure.  This should be suppressed in sequence
mode, though, where only the reference startTime matters.
The buffering issue was caused by two things in combination:
1. The HLS parser set meaningless timestampOffset values that would
change when a playlist was updated
2. We would use those timestampOffset values in setStreamProperties,
even though this should be skipped in sequence mode
These two things in combination would lead MediaSourceEngine to start
inserting segments near the start of the …
=> fix(hls): Fixed buffering issue with live HLS

package-lock.json, package.json
In #3991, I changed the syntax of our colors to a modern rgba syntax.
For example, rgba(255, 255, 255, 0.85) would become rgba(255 255 255 /
85%). However, less v3 seems not to understand that properly, and
performs division on the last two parts, resulting in output of
rgba(255 255 3%), which is indeed invalid.
This fixes the issue by upgrading to less v4, which understands the
new rgba syntax and leaves it alone. The output for that will now
match the input.
To work around an issue with less v4, this uses a prerelease version
with a fix for https://github.com/less/less.js/issues/3693 . See also
https://github.com/tomas/needle/issues/391
This doesn't affect any release branches, since #3991 hasn't been
cherry-picked.
Closes #4027
=> chore(deps): Upgrade less to v4 (prerelease)

lib/util/fairplay_utils.js
This adds 3 new methods to FairPlayUtils:
- isFairPlaySupported --> Closes PR #3562
- spcFairPlayRequest --> This method adds basic spc FairPlay request filter
- commonFairPlayResponse --> This method adds a basic FairPlay response filter that supports a lot of DRM providers.
=> feat: add new methods to FairPlayUtils

karma.conf.js
This was originally supposed to help resolve "too many open file"
errors in the test runner, but we could not prove that this made any
difference.  Still, it doesn't seem to hurt.  Tests start up ~6%
faster (several seconds difference on my workstation).
=> test: Minimize file globs served by test runner

package-lock.json
This was causing issues with older versions of npm.
=> chore: Remove SSH URLs from package-lock.json

externs/shaka/net.js, lib/media/drm_engine.js, lib/net/networking_engine.js, test/util/cmcd_manager_unit.js
Adds initData and initDataType field to all LICENSE-type requests.
Based on comments here: https://github.com/shaka-project/shaka-player/issues/4001#issuecomment-1050655197
=> feat(DRM): add initData and initDataType to license requests

build/docker/Dockerfile, build/docker/docker-compose.yml, docs/tutorials/welcome.md
add docker-compose.yml and Dockerfile to compile shaka inside container; reference it on docs;
Many devs using Shaka and wishing to compile the library are required to install all prerequisites on their machine. For docker devs, this is extremely bad as it requires installing Java and Python on OS.
This commit adds a basic configuration for quick compilation via Docker, without requiring any other prerequisites. Improvements can be made in order to allow all Shaka workflow inside Docker.
Suggested in #181
=> docs: Add Dockerfile and docker build instructions

package-lock.json
Minimist is vulnerable to prototype pollution, and is no longer
receiving updates.  Details of the vulnerability can be found here:
https://github.com/advisories/GHSA-xvch-5gv4-984h
This updates our indirect dep on json5 to remove its minimist dep.
Jimp, Karma, and WD all rely on v0 of mkdirp, which uses minimist.
This forces them to use v1 of mkdirp, a rewrite which doesn't use
minimist.
=> test: Drop indirect dep on vulnerable minimist module

.github/workflows/release-please.yaml
I had set these backwards (name as email and vice-versa).  Oops!
=> ci: Fix release PR name and email

.github/workflows/release-please.yaml
The "if" fields do not need to use expression syntax (`${{ }}`), and
some conditionals will be easier to read if we omit that.
=> ci: Use simplified expression syntax

.github/workflows/build-and-test.yaml, build/docker/Dockerfile
This adds CI tests for Docker builds, to make sure they keep working.
This also simplifies the Docker build by removing things related to "pip", which we do not use.
=> ci: Test Docker build

.github/workflows/release-please.yaml
This option will get us a full history upfront, so there is no need
for git fetch.
=> ci: Use fetch-depth option to actions/checkout

.release-please-config.json
This release-please config file is a temporary measure until our first
automated feature release from main.  So we have to explicitly state
the version number for this first release, and keep it up-to-date.
After the release, we should be able to remove this file and let the
workflow decide on version numbers automatically based on commit
messages.
=> ci: Next release from main will be v4.0.0

.github/workflows/release-please.yaml
A couple of steps were in the wrong order.  We must compute tags and
subdomains before the "prep" step, which wipes out .git.
=> ci: Fix appspot deployment failure

AUTHORS, CONTRIBUTORS, lib/util/periods.js, test/util/periods_unit.js
Fixes #3724
Fix dedup stream logic adding `bandwidth` in the `filterOutTextStreamDuplicates` condition.
Another possible solution could be add the `originalId` in the all the filter conditions: #3725  
=> fix(dash): Account for bandwidth before filtering text stream

ui/less/range_elements.less
Since range elements are special input elements, they must reflect user interaction, so when the user hovers over the range element, the cursor must be a pointer.
Related https://github.com/shaka-project/shaka-player/pull/3220
=> fix(UI): Add cursor pointer to range elements

lib/dash/dash_parser.js, lib/dash/mpd_utils.js, lib/dash/segment_template.js, lib/util/string_utils.js, lib/util/uint8array_utils.js, lib/util/xml_utils.js
See: https://github.com/shaka-project/shaka-player/issues/4062#issuecomment-1077826210
=> fix(dash): Fix performance regression

lib/media/presentation_timeline.js, test/player_integration.js, test/player_unit.js, test/test/util/manifest_generator.js
For content where the manifest parser uses the notifySegments API
(DASH SegmentBase/SegmentList/SegmentTimeline, or HLS, but not DASH
SegmentTemplate+duration), the Player seekRangeEnd configuration was
not being honored correctly.
This fixes the issue in PresentationTimeline and adds a regression
test to our playRangeStart/playRangeEnds tests.
Fixed #4026
=> fix: Fix playRangeEnd for certain content

build/types/polyfill, lib/polyfill/symbol.js, shaka-player.uncompiled.js
Close https://github.com/shaka-project/shaka-player/issues/4072
=> fix(cmcd): Fix Symbol usage in CMCD on Xbox One

package-lock.json, package.json
This fixes broken deps file generation on Window by upgrading to a
pre-release version of the deps tool.  The upstream issue was filed in
https://github.com/google/closure-library/issues/1159 and fixed in
https://github.com/google/closure-library/pull/1160.
This issue has never affected a release version of Shaka Player, and
was introduced when we switched deps tools in 6f274cbc.
Closes #4085
=> fix: Fix broken deps file generation on Windows

lib/player.js
Some events and timers were used to process track changes with src=
playback on Safari, but they did not properly clean up when the player
was unloaded or destroyed.  In the case that this happened quickly
after starting playback, exceptions would be thrown or tracks could
manipulated after new content began.
This fixes the cleanup of these timers and events to be aware of
Player unloads or destruction.
Closes #4087
=> fix: Fix exceptions when quickly shutting down src= on Safari

.github/workflows/build-and-test.yaml, .github/workflows/safari-homedir-launcher.sh
In the GitHub Actions environment, it is now possible to install and
run tests on Safari 14.  Though not completely straightforward, it
doesn't add much code to the workflow and shouldn't be too difficult
to maintain.
Closes #3899
=> ci: Test on Safari 14

lib/polyfill/mediasource.js
It appears that the problems we previously had with TS content
on Safari have been fixed. We no longer need the workaround where
we transmuxed TS on that platform.
=> feat(HLS): Re-add TS support to Safari

build/gendeps.py
Since transitioning from the deprecated depswriter.py to the new
closure-make-deps tool in 6f274cbc, the build system has been ignoring
any failures in the generation of deps.js.  This is because the new
tool doesn't return a proper non-zero exit code when it fails.  (See
https://github.com/google/closure-library/issues/1162)
This changes the build scripts to check for empty output instead,
which seems to be reliable for the moment.
=> build: Don't ignore failures to generate deps

test/test/util/util.js
Jasmine 4 deprecated some part of its custom matcher API.
This puts us in compliance with the new API (by omitting a parameter
we didn't really need), and silences the deprecation warnings (which
only showed up when enabling logging in the tests).
=> test: Fix Jasmine 4 deprecation warnings

demo/demo_uncompiled.js
Rather than require everything, require only the top-level classes for
the demo, and let them require their dependencies.  This is consistent
with how this works in the library itself.
Related to issue #4094
=> build(demo): Minimize goog.require in demo_uncompiled.js

app-engine/demo-version-index/main.py
The script for deploying the demo version index page has a function
that chooses which versions to display. This script has a special
mode meant for testing that shows a default list of demo versions.
This mode was only supposed to trigger when run locally, but the
check did not work properly, so the demo version index was deploying
with a very out-of-date list of versions.
This fixes that check.
Closes #4074
=> fix(demo): Fix default demo index versions

shaka-player.uncompiled.js
Related https://github.com/shaka-project/shaka-player/pull/4114
=> chore: remove goog.require('shaka.polyfill.MathRound') in uncompiled

.github/workflows/demo-version-index.yaml
The demo index generation is now based on the git tags.  So when
checking out the repo to generate the index, the entire history is
needed.
Closes #4074
=> ci: Fix generation of demo index by fetching all history

.github/workflows/build-and-test.yaml
If another instance of the build-and-test workflow is started for the
same PR, cancel the old one.  If a PR is updated and a new test run is
started, the old test run will be cancelled automatically to conserve
resources.
=> ci: Cancel old test runs when a PR is updated

lib/hls/hls_parser.js, lib/media/segment_reference.js, test/hls/hls_parser_unit.js
Parse EXT-X-GAP HLS tag and add a status enum to shaka.media.SegmentReference.
shaka.media.SegmentReference.Status.AVAILABLE --> Normal behaviour
shaka.media.SegmentReference.Status. UNAVAILABLE --> Related to https://github.com/shaka-project/shaka-player/issues/2541
shaka.media.SegmentReference.Status. MISSING --> EXT-X-GAP in HLS
Note: only the parsing is added, but the functionality is not yet implemented.
Issue https://github.com/shaka-project/shaka-player/issues/1308
=> feat(hls): parse EXT-X-GAP

test/media/drm_engine_integration.js, test/media/streaming_engine_integration.js, test/offline/offline_integration.js, test/player_external.js, test/player_integration.js, test/test/util/waiter.js
This should help debug flakiness and failures in StreamingEngine tests
on Safari and Firefox.
=> test: Add debug info to failure messages in test waiter

test/media/streaming_engine_integration.js, test/test/util/waiter.js
There was an exception to waitForEnd in StreamingEngine tests that
could have been handled generically inside the waiter for all tests.
It was also necessary to poll for ended state since the Firefox 99 update.
This fixes some recent test failures on Firefox 99.
=> test: Deflake StreamingEngine tests on Firefox

test/text/ui_text_displayer_unit.js
This seems to reduce flakiness in the TextDisplayer tests.  The
theory is that Safari throttles timers when the system is very busy,
which it often is during full test runs across multiple browsers.  By
not relying on timers and triggering an explicit update in the
TextDisplayer, the tests seem to become more reliable.
=> test: Improve TextDisplayer test reliability and timing

test/media/streaming_engine_integration.js
This seems to improve some intermittent test failures on Safari.
=> test: Tweak StreamingEngine test timeouts

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
Closes https://github.com/shaka-project/shaka-player/issues/4135 
Closes https://github.com/shaka-project/shaka-player/issues/1959
=> feat(hls): make a head request if hls subtitles have no extension

test/ui/ui_integration.js, test/ui/ui_unit.js, ui/locales/en.json, ui/locales/source.json, ui/resolution_selection.js
The present pull request aims to provide a solution to #2071 (Quality selection UI for audio-only content) by replacing the resolution selection menu with a quality selection menu in audio-only content.
Fixes: #2071
Initialize the client with a config that contains `quality` in the `controlPanelElements` and load the player with an audio-only manifest.
```js
const config = {
'controlPanelElements': ['quality'],
}
ui.configure(config);
await player.load('https://storage.googleapis.com/shaka-demo-assets/dig-the-uke-clear/dash.mpd');
```
<details>
<summary><code>test/ui/ui_integration.js</code></summary>
Removes the integration test that checks for a hidden resolution button in audio-only content.
</details>
<details>
<summary><code>test/ui/ui_unit.js</code></summary>
Expects the correct …
=> feat(ui): Add quality selection for audio-only content

.github/workflows/release-please.yaml
We should replace all dots with dashes, not just the first one.
=> ci: Fix appspot subdomain computation

.github/workflows/release-please.yaml
These tags should be attached to the head of the main branch, so that
is what we should check out during the tagging job.
In v3.1.7, v3.2.5, and v3.3.3, we accidentally tagged the heads of the
release branches.  The `-main` tags for those releases had to be
corrected manually.
=> ci: Fix -main tags on release

ui/less/ad_controls.less
This bug has always been there, as far as I can tell, since the ads UI
was added.  This issue was caught by an internal compilation tool and
another project that consumes our UI.
=> fix(css): Fix missing % in calculation

ui/seek_bar.js
On 29th of April, git.io will stop redirecting
Ref: https://github.blog/changelog/2022-04-25-git-io-deprecation/
So let's update this comment to keep the original reference there
=> docs: update git.io link to original destination

build/generateTsDefs.py
=> fix: Export d ts as a module

lib/media/media_source_engine.js, test/cast/cast_utils_unit.js, test/media/media_source_engine_integration.js, test/media/media_source_engine_unit.js, test/media/streaming_engine_integration.js
Fixes an issue where non-encrypted content were unable to playback due to encryption detection done with `this.video.mediaKeys`. It seems we could set MediaKeys even though the content is not encrypted, therefore trying & failing to add information in the init segment and resulting into a `CONTENT_TRANSFORMATION_FAILED`.
I am still unsure why this is happening exactly but I think it could be a side-effect of #3776 . I'll keep looking for the real cause of the issue, but I think this is a reasonable fix to rely on stream info
I'll test different versions of Tizens we have because I think this workaround isn't needed on all of the versions
=> fix: Fix encryption detection to work around broken platforms

build/generateTsDefs.py
Reverts shaka-project/shaka-player#4163
Closes #4167
=> fix: Revert "Add missing module export in generated typescript defs"

lib/dash/dash_parser.js, test/dash/dash_parser_manifest_unit.js
According to https://developerkb.dolby.com/support/solutions/articles/16000067758-what-is-dolby-digital-plus-joc-joint-object-coding- Dolby Atmos (JOC):
> Joint Object Coding describes the process by which Dolby Digital Plus with Atmos decoders, receiving a legacy 5.1 mix and sideband metadata, are able to reconstruct the original Atmos mix.
So there is no need to deal with a separate mimetype, it can be decoded with Dolby Digital+ (better for retrocompatibility).
Closes https://github.com/shaka-project/shaka-player/issues/4171
=> fix(dash): Fix playback of Dolby Atmos

.github/workflows/build-and-test.yaml, .github/workflows/selenium-lab-tests.yaml, build/README.md, build/test.py
This changes the default behavior of the test runner.  Now tests that
require access to license servers will run by default.  To disable DRM
tests (for example, if there is no connection to the outside
internet), use --no-drm.
=> test: Run DRM tests by default

lib/offline/storage.js
If a storage operation is aborted (via API, not via closing the page),
this will now be cleaned up from the database.  More work is needed to
find and remove orphaned segments in the database.
Related to #4166 and follow-up to PR #4176.
=> fix(offline): Clean up orphaned segments on abort

.github/workflows/release-please.yaml
Having both v4.0.0 and v4.0.0-main tags refer to the same commit
confuses some of our build scripts because git describe can produce
either tag.  So we should only create -main tags when the release is
from a branch.
=> ci: Do not create a -main tag if the release is from main

lib/player.js
We want to avoid reporting MANIFEST RESTRICTIONS_CANNOT_BE_MET error twice.
This is because when error detected from `onKeyStatus_` calls `updateAbrManagerVariants_` which calls `checkRestrictedVariants_` and error is catched and propagated from `onError_` **but source code execution continues** 
and `chooseVariantAndSwitch_` triggers same error again:
```javascript
onKeyStatus_() {
....
if (tracksChanged) {
this.updateAbrManagerVariants_(); 
//   -> checkRestrictedVariants_ 
//     -> RESTRICTIONS_CANNOT_BE_MET
}
...
if (currentVariant && !currentVariant.allowedByKeySystem) {
...
this.chooseVariantAndSwitch_(); 
//  -> chooseVariant_
//    -> updateAbrManagerVariants_ 
//      -> checkRestrictedVariants_ 
//        -> RESTRICTIONS_CANNOT_BE_MET
}
``` …
=> fix: Do not report MANIFEST RESTRICTIONS_CANNOT_BE_MET error twice

lib/util/manifest_parser_utils.js, test/hls/manifest_text_parser_unit.js
Also verified that DASH av1 playback already works.
=> fix(hls): Fix av1 codec selection in HLS.

test/player_unit.js
Adding tests for https://github.com/shaka-project/shaka-player/pull/4194 in order to ensure that, when `onKeyStatus({ kid: 'output-restricted'})` error is thrown **ONLY** one `RESTRICTIONS_CANNOT_BE_MET` error is triggered/thrown.
=> test: Trigger RESTRICTIONS_CANNOT_BE_MET once from onKeyStatus error

lib/hls/hls_parser.js, lib/media/streaming_engine.js, lib/player.js, lib/util/error.js
Related to https://github.com/shaka-project/shaka-player/commit/42eecc84f992ca6a680c3a5fd46d1c300fe92a72
Closes https://github.com/shaka-project/shaka-player/issues/1308
=> feat(hls): Add support for EXT-X-GAP

docs/tutorials/upgrade.md
This was removed in the release, but we failed to note this in the
upgrade guide.
Closes #4210
=> docs: Add note to upgrade guide about manifest.hls.useFullSegmentsForStartTime

karma.conf.js, test/player_external.js
Custom asset and external tests (not run by default) were failing to run due to
missing dependencies.  This fixes that issue.
This also improves logging of debug info when a custom asset test times out.
Related to investigation of #4161
=> test: Fix custom asset and external tests

lib/player.js, test/player_unit.js, test/test/util/simple_fakes.js
v4.0.0 introduced a regression.  When SegmentIterator's seek() method
was removed, one reference to it was missed in Player.  This was only
used when streaming.startAtSegmentBoundary is true, and there were no
tests to exercise that code path.
This adds new tests and fixes the regression.
Closes #4188
=> fix: Fix exception with streaming.startAtSegmentBoundary

lib/media/media_source_engine.js, lib/media/streaming_engine.js, lib/text/vtt_text_parser.js, test/text/vtt_text_parser_unit.js
Since the transition to sequence mode for HLS in v4.0.0, VTT cue
timings were broken.  This is mainly because VTT cue timing in HLS is
meant to be based on an offset from the media timestamps, and we
generally don't know those now that we use sequence mode.
To fix it, this change uses MediaSource segment mode for the very
first video segment as a way to extract the timestamp, then clears the
buffer, switches to sequence mode, and appends it again.  This lets us
get the timing data we need, while avoiding major drawbacks of the
previous HLS implementation:
- We don't need to fetch segments upfront (which is high latency)
- We don't need to fetch segments twice (once for timestamps, and
once again to buffer)
- We don't need to maintain parsers (which were complex and limited
the formats we …
=> fix: Fix VTT cue timing in HLS

package-lock.json, package.json
Let's make it explicit a Node.js version required for development, to make contributions easy.
=> chore: require node 14 or above

lib/player.js, lib/util/error.js, test/player_integration.js, test/player_src_equals_integration.js, test/test/util/simple_fakes.js
addChaptersTrack() was already an async method, but it did not wait
for the chapter data to be loaded by the browser.  The solution is to
wait for the `load` event on the `<track>` element we create.
To accomplish this, some cleanup and refactoring was done in how
tracks are managed.  Summary of changes:
- The `addtrack` event, which triggered management of tracks in src=
playback, is now used for all types of playback.  In src= mode, it
manages all tracks, and in MSE mode, it only manages chapters
tracks (which are added to the video element as in src= mode).
- `processChaptersTrack_()` has been renamed to
`activateChaptersTrack_()`, since its only job is to set the
track's mode field to make the browser load it.
- `activateChaptersTrack_()` is now only ever called via the
`addtrack` …
=> fix: Wait for chapters track to be loaded

lib/dash/dash_parser.js, lib/player.js, lib/util/mime_utils.js, lib/util/periods.js, lib/util/stream_utils.js, test/util/mime_utils_unit.js, test/util/periods_unit.js
=> fix: PERIOD_FLATTENING_FAILED error when periods have different base sample types.

lib/offline/indexeddb/storage_mechanism.js, test/offline/indexeddb_storage_unit.js, test/offline/storage_compatibility_unit.js, test/test/boot.js, test/test/externs/filters.js
Xbox One tests have been failing often for some time now, so it went
unnoticed that offline was not working.  It seems that IndexedDB is
not working properly on Xbox, and the platform throws `UnknownError`.
This restricts offline so that it is not triggered on Xbox One, and
this also fixes the filtering of our offline tests to respect the
offline storage muxer's support method.
=> test: Disable offline for Xbox One

lib/util/config_utils.js, lib/util/player_configuration.js
Many times in our default configuration, we need to create an empty
default implementation of a callback.  The compiler wants to strip
out unused parameters from these functions, but this breaks our
runtime-type-checking for functions in configure().  We need a way to
keep the full function signature in default config callbacks in
compiled mode.
This adds a new utility: ConfigUtils.referenceParametersAndReturn().
It references the input parameters so the compiler doesn't remove them
from the calling function, and returns whatever value is specified.
The utility function is marked with `@noinline`, so the compiler won't
tamper with it.
Default config callbacks that use this utility will still bear the
complete function signature even in compiled mode.
The caller should look something like …
=> refactor: Add utility to keep unused parameters

docs/tutorials/upgrade.md, externs/shaka/player.js, lib/media/drm_engine.js, lib/util/player_configuration.js
Some FairPlay providers still need this part, so we should never have removed it.
The default is to do no transformation.
=> fix: Re-add initDataTransform config

.github/workflows/release-please.yaml
The v3.2.7 and v3.3.5 releases went out without updating the version
number in lib/player.js.  This fixes the workflow to match the
release-please branch name, and changes the workflow to fail if the
branch name changes again in the future.
=> ci: Fix player version update on release

ui/controls.js, ui/externs/ui.js, ui/ui.js
This new configuration value allows users to determine how far
the video seeks when you press the arrow keys on the video
element.
Closes #4245
=> feat(UI): Added keyboardSeekDistance config to UI

lib/media/drm_engine.js
There is an async call, waiting for sessions to update, right before
the StreamingEngine fires off an drmsessionupdate event.
This could potentially cause an error, as the StreamingEngine's
player interface could potentially be set to null during destruction.
This adds a check to see if the StreamingEngine has been destroyed,
to catch that case.
Based on a test failure of #4241
=> fix: Don't send drmsessionupdate after unload

lib/util/mime_utils.js
This should fix the fMP4 playback issue in https://github.com/shaka-project/shaka-player/issues/3691
In multiplexed HLS stream, the audio mime type is incorrectly set to `video/*` but `MediaCapabilities.decodingInfo()` is expecting `audio/*`.
```
{
"type":"media-source",
"audio":{
"contentType":"video/mp4; codecs=\"mp4a.40.2\"",
"channels":2,
"bitrate":8000000,
"samplerate":1,
"spatialRendering":false
},
"video":{
"contentType":"video/mp4; codecs=\"avc1.640033\"",
"width":1920,
"height":1080,
"bitrate":8000000,
"framerate":59.94,
"transferFunction":"srgb"
}
}
```
```
...
Guessing multiplexed audio+video.
...
TypeError: Failed to execute 'decodingInfo' on 'MediaCapabilities': The audio configuration dictionary is not valid.
```
HLS manifest:
```
#EXTM3U …
```
=> fix: Fix audio mime type in multiplexed HLS stream

README.md, package-lock.json, package.json
This new version closes https://github.com/shaka-project/shaka-player/issues/3761
=> chore: Update mux.js to 6.1.0

lib/hls/hls_parser.js, test/hls/hls_live_unit.js
Because zero-duration references cause such chaos, ensure that the HLS
parser never produces these.  Preload-hinted segments should use the
target duration for partial segments, and if that required attribute
is missing from the playlist, then preload-hinted segments should be
skipped.
Closes #4223
=> fix(HLS): Fix duplicate hinted segments

CONTRIBUTORS, externs/shaka/player.js, lib/cast/cast_proxy.js, lib/cast/cast_receiver.js, lib/media/gap_jumping_controller.js, lib/media/playhead.js, lib/media/stall_detector.js, lib/media/streaming_engine.js, lib/player.js, lib/util/fake_event.js, lib/util/stats.js, test/media/playhead_unit.js, test/media/stall_detector_unit.js, test/media/streaming_engine_integration.js, test/player_integration.js, test/test/util/simple_fakes.js, test/ui/ui_unit.js, ui/statistics_button.js
An event `stalldetected` can be dispatched when Shaka Player detects a stall based on the value of stallThreshold through [StreamingConfiguration](https://shaka-player-demo.appspot.com/docs/api/externs_shaka_player.js.html#line920).
A second event `gapjumped` could also be dispatched when Shaka performs a jump in a media gap.
Related to issue https://github.com/shaka-project/shaka-player/issues/4227.
=> feat: add listenable events for playback stall detection and gap jumping

AUTHORS, CONTRIBUTORS, demo/demo.less, ui/less/containers.less, ui/less/general.less, ui/less/range_elements.less
Currently, player buttons clickable area are 24px by 32px which is not close to WCAG guidelines(44px by 44px)
Fixes # (issue)
Solution would be moving margins around buttons to paddings since padding rendered as touchable area. This makes player buttons 34*32px. (and makes focus indicators look nicer too :)
Two CSS changes in the 'containers.less' file and 'general.less' file.
- [*] Bug fix (non-breaking change which fixes an issue)
- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code
- [*] My changes generate no new warnings
=> fix(ui): Widen touchable button area

AUTHORS, CONTRIBUTORS, build/test.py
IE 11 has not been supported since v3.1, so developers following
CONTRIBUTING.md should not see tests fail due to the continued inclusion
of IE. Removed IE from the default list of browsers for Windows. Anybody
who still needs to test against IE can explicitly test via python
build/test.py --browsers IE.
=> fix: Remove IE 11 from default browsers for Windows (#4271)

demo/main.js
Closes https://github.com/shaka-project/shaka-player/issues/4209
=> fix(demo): allow switch between UITextDisplayer and SimpleTextDisplayer

lib/hls/hls_parser.js
I have been working with a server which is too aggressive at expiring
segments at the left edge of its DVR. As a result of this, when Shaka's
HLS manifest parser puts out a HEAD request on the first segment to
guess its MIME type, sometimes the segment has already been removed
(404). I have filed a bug against the server team and I hope they relax
the expiration, but truth be told if you wait long enough, any request
against the left edge of DVR will eventually fail. It seems like a
simple workaround for now to simply request the middle segment rather
than the first segment.
Closes https://github.com/shaka-project/shaka-player/issues/4269
=> fix: Use middle segment when guessing MIME type on HLS (#4269)

externs/shaka/player.js, lib/hls/hls_parser.js, lib/media/segment_index.js, lib/media/segment_reference.js, lib/media/streaming_engine.js, test/hls/hls_parser_unit.js
We now have an explicit fallback to sync on sequence numbers if
PROGRAM-DATE-TIME is explicitly ignored.  This is more robust than
relying on whatever happens to be first in the various media
playlists.
This also refactors how PROGRAM-DATE-TIME is used.  The date will now
be used to adjust segment reference start times, rather than
overriding the time used in StreamingEngine.  (This was hard to
discover when reading the HLS parser.)  Now all HLS sync logic is in
the HLS parser.
Closes #4287
=> fix(hls): Fix AV sync issues, fallback to sequence numbers if PROGRAM-DATE-TIME ignored

lib/util/platform.js
The EOS set-top box, built by Liberty Global, has WebKit embedded and should play MSE (+ EME) compatible streams. With the latest version (`4`), streams didn't play. When attaching a debugger to the box, I noticed that the srcEquals node is selected.
The EOS box identifies itself as an Apple device, which is wrong. `Platform.isApple()` returns true, therefore `shouldUseSrcEquals_` (in combination with `config_.streaming.useNativeHlsOnSafari`) returns true as-well. The native playback check is not holding it from selecting srcEquals (https://github.com/shaka-project/shaka-player/blob/main/lib/player.js#L1273) as EOS supports MPEG-DASH natively (but not in combination with DRM, as far as I know). Nonetheless, MSE is preferred.
=> feat: EOS set-top box wrongly identifies as an Apple device.

lib/polyfill/videoplaybackquality.js
It seems that webkitDroppedFrameCount is not included in the prototype but it is included in the video element itself, that's why it fails in WebOS 3.
Closes https://github.com/shaka-project/shaka-player/issues/4313
=> fix: Fix getVideoPlaybackQuality in WebOS 3

lib/polyfill/media_capabilities.js, lib/util/platform.js
This PR adds PS4 to the platform list, fixes an issue where ps4 was identified as an apple device/browser and explicitly sets the condition for installation of the mediaCapabilities polyfill for ps4, as its native implementation does not exist.
Closes #4315
=> fix: Fix MediaCapabilities polyfill on Playstation 4

README.md, docs/tutorials/welcome.md
Releases will no longer be announced on the mailing list.  Instead,
users can subscribe directly through GitHub.
=> docs: Deprecate the mailing list for releases

build/types/complete, build/types/core, build/types/fairplay, build/types/polyfill, docs/tutorials/fairplay.md, lib/hls/hls_parser.js, lib/media/drm_engine.js, lib/polyfill/patchedmediakeys_apple.js, lib/util/error.js, lib/util/fairplay_utils.js, shaka-player.uncompiled.js
Add support for Modern EME and legacy Apple Media Keys for FairPlay
Add more FairPlay documentation
=> feat: Add support for Modern EME and legacy Apple Media Keys for FairPlay

README.md, package-lock.json, package.json
[mux.js 6.2.0 ](https://github.com/videojs/mux.js/releases/tag/v6.2.0)introduce changes that are useful while parsing ID3 HLS in-band metadata.
=> chore: Update mux.js to 6.2.0

build/conformance.textproto, demo/index.html, docs/tutorials/upgrade.md, lib/util/string_utils.js, package-lock.json, package.json
Related to https://github.com/shaka-project/shaka-player/commit/a72a1e91023a33c777a6001a64f818ea2e469914
=> feat: Add fallback to TextDecoder and TextEncoder

lib/media/media_source_engine.js, lib/media/streaming_engine.js, lib/media/time_ranges_utils.js, test/media/drm_engine_integration.js, test/media/media_source_engine_integration.js, test/media/media_source_engine_unit.js, test/media/streaming_engine_unit.js, test/test/util/fake_media_source_engine.js
Issue an error with debug info, including the URL, if the placement of
a segment in buffer is very different from expectations.
b/233075535
=> fix: Debug buffer placement

lib/dash/dash_parser.js, lib/hls/hls_parser.js, lib/media/presentation_timeline.js
When DAI adds ad segments faster than real-time, the availability
windows gets messed up, and some assertions in SegmentIndex break.
This locks down the presentation start time after the initial manifest
is parsed, so that the availability window is stable throughout
playback.
b/233075535
=> fix: Fix segment index assertions with DAI

demo/index.html, docs/tutorials/ui.md
This ID points to the nightly build, and so is appropriate for the
main branch.
=> fix: Update main branch Cast receiver ID

AUTHORS, CONTRIBUTORS, lib/ads/client_side_ad_manager.js
If onAdError is called before onAdStart_ then onAdComplete_ uses
this.ad_ which is undefined.
This can happen if a VAST XML file contains no ads.
fixes #4004
=> fix: exception if on early adError

lib/media/streaming_engine.js, lib/util/buffer_utils.js, lib/util/object_utils.js
JSCompiler's strict missing properties on union types change improves the missing properties check to report properties that do not exist on all members of union types (excluding null or undefined and after boxing primitives).
=> fix: add strictMissingProperties suppressions to unblock strict missing properties on union types.

.github/workflows/build-and-test.yaml
The available package versions of Safari have changed.  This updates
to what is currently available.  This also updates to expect the
current format of the packages (pkg inside zip).
=> ci: Fix Safari 14 tests

lib/util/platform.js
The `isBrowserSupported` function in the `utils/player.js` fails if the Safari Version is < 13. However, this check doesn't work for Amazon Fire TV devices. Even tho they have a `Version/4.0` in the user agent string, the browser still supports all other requirements to support playback with Shaka Player. 
Here are a couple of examples of the different FireTV device user agents:
```
'Mozilla/5.0 (Linux; Android 7.1.2; AFTMM Build/NS6289; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 Mobile Safari/537.36'
```
```
'Mozilla/5.0 (Linux; Android 9; AFTSSS Build/PS7285.2877N; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.92 Mobile Safari/537.36'
```
The fix involves identifying the Amazon Fire TV device based on the parameters described …
=> feat: add Amazon Fire TV platform support

lib/util/stream_utils.js
Tests for VP9 codec checks were failing on Firefox on our M1 Mac.  This
addresses the issue by changing some default values that get used in a testing
environment, and another default value that is used in production.
This fixes one source of nightly test failures.
=> fix: Fix VP9 codec checks on Mac Firefox

package-lock.json, package.json
The upgraded polyfill fixes this.
See shaka-project/eme-encryption-scheme-polyfill#49
=> test: Fix Tizen test failures due to ES6 in polyfill

lib/util/player_configuration.js
This raises the default gap-detection threshold from 0.1 seconds for
some platforms and 0.5 seconds for others to 0.5 seconds universally.
This fixes test flake in gap-jumping tests on Android and may improve
gap-jumping generally for certain platforms or content.
=> feat: Improve gap-detection robustness

karma.conf.js, lib/player.js, lib/util/string_utils.js, test/util/string_utils_unit.js
In PR #4324, we lifted the requirement to have a native or polyfilled
TextDecoder implementation.  However, we forgot to remove the check
for it in isBrowserSupported().  This led to tests being skipped
entirely on Xbox, as Xbox was determined to be an unsupported platform
by Player.
To fix this, the check for TextDecoder/TextEncode in
isBrowserSupported() has been removed.
When the TextDecoder polyfill was removed, we left a reference to it
in karma.conf.js.  This didn't hurt anything per se, but this has now
been cleaned up.
Finally, TextDecoder was originally introduced to give us a way to
recover from errors instead of throwing.  The fallback that was
reintroduced in #4324 was the original code that throws on error.
This led to a test failure on Xbox, which represents a complete …
=> fix: Fix TextDecoder fallback and browser support check

demo/common/assets.js, externs/shaka/manifest.js, lib/hls/hls_parser.js, lib/media/segment_index.js, lib/media/segment_reference.js, lib/media/streaming_engine.js, lib/net/networking_engine.js, lib/util/error.js, package-lock.json, test/hls/hls_parser_unit.js, test/media/streaming_engine_unit.js, test/test/util/simple_fakes.js, test/test/util/streaming_engine_util.js
Expands on the original PR (#3880) by adding support for MP4 and key rotation.
Close #850
Co-authored-by: wjywbs <wjywbs@users.noreply.github.com>
=> feat(hls): Support AES-128 in HLS

.github/workflows/build-and-test.yaml, .github/workflows/selenium-lab-tests.yaml, karma.conf.js
This will attach a code coverage report to PRs and to nightly tests,
both specifically from Chrome on Linux.  Reports will be attached to  
workflow runs whether or not the tests pass.
=> test: Upload coverage report for PR and nightly tests

test/util/string_utils_unit.js
Since the TextDecoder fallback is only used on some devices, those
code paths were not tested on other platforms.  This makes the
StringUtil tests execute both with and without TextDecoder.
=> test: Test StringUtils both with and without TextDecoder

lib/text/simple_text_displayer.js, test/text/simple_text_displayer_unit.js
This changes the `SimpleTextDisplayer` to flatten text payloads
only starting at non-container cues. Not doing so poses an issue with
'rolled over' caption lines.
E.g., consider:
- TTML file `N` with caption line `A` from time `[1.4, 2.1]`.
- TTML file `N+1` with caption lines `A` from time `[1.4, 2.4]` and `B` from time `[2.4, 3.4]`.
If captions `A` and `B` are descendants of two different `<p>` elements, Shaka
currently flattens the text payload from `A` and `B` into a single cue that is
rendered onto the display from time `[1.4, 3.4]`. Therefore, caption `A`'s text
payload is incorrectly showing during time `[2.4, 3.4]`.
The fix updates the `SimpleTextDisplayer#append()` logic to split up individual 
non-container cues into their own `VTTCue` object. This will not be done at the …
=> fix(text): Fix TTML render timing and line break issues

lib/text/ui_text_displayer.js, test/text/ui_text_displayer_unit.js
Both TTML and VTT regions should be thought of as separate elements
from the cue structures they contain.  To this end, the UI text
displayer now creates separate region elements to represent CueRegion
objects, and the Cues attached to them nest inside those region
elements in the DOM.
Closes #4381
=> fix(text): Fix cue region rendering in UI

lib/util/player_configuration.js, test/media/drm_engine_unit.js
This fixes the config by adding a missing override in the config parser.  This also adds test coverage for the feature.
Closes #4422
=> fix: Fix drm.keySystemsMapping config

lib/player.js, test/player_unit.js
Introduced in #4189, as a side-effect of restricting tracks when a
network failure occurs.  We should not trigger such restrictions when
the browser is known to be offline.
Closes #4408
=> fix: Fix vanishing tracks while offline

lib/hls/hls_parser.js, lib/util/error.js
Now that #2337 has been implemented, the error code HLS_INTERNAL_SKIP_STREAM
is no longer used anywhere in the code.
This retires that error, and also cleans up the code that previously
was responsible for handling that error being fired.
Pre-work for #1936
=> chore(HLS): Retired unused error code

lib/player.js, test/player_src_equals_integration.js
related to https://github.com/shaka-project/shaka-player/issues/4434
=> fix: return width and height in the stats when we are using src=

lib/hls/hls_parser.js, lib/util/error.js, test/hls/hls_parser_unit.js
Now that we support AES-128, some older AES-128 code paths in the HLS
parser have become obsolete.  This cleans up those unneeded code paths
and adds a test to ensure that the correct failure handling is used
when AES-128 cannot be supported by the platform.
=> chore: Clean up unused AES-128 failure paths

lib/text/ui_text_displayer.js
Without an explicit size, some platforms render bitmap-based cues as
0x0.  This effect was seen in Chrome on Mac in particular.  This
started with PR #4412, where we factored out regions into their own
element.
The TTML spec says that background images should fill their associated
region, so this fixes the issue by making the div explicitly the size
of its parent element (100% x 100%).
=> fix: Fix bitmap-based cue size

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js, test/player_integration.js, test/test/util/manifest_generator.js, test/test/util/test_scheme.js
This feature is not entirely automatic.
The ClearKey CDM requires a key-id to key mapping.  HLS doesn't
provide a key ID anywhere.  So although we could use the 'URI'
attribute to fetch the actual 16-byte key, without a key ID, we can't
provide this automatically to the ClearKey CDM.
Instead, the application will have to use
`player.configure('drm.clearKeys', { ... })` to provide the key IDs
and keys or `player.configure('drm.servers.org\.w3\.clearkey', ...)`
to provide a ClearKey license server URI.
Closes #2146
=> feat: Add limited support for HLS "identity" key format

.github/workflows/selenium-lab-tests.yaml
This requires multiple self-hosted runners to be set up, but will
allow us to more easily read results and to re-run individual failed
jobs per browser.
This change also includes several optimizations that were motivated by
the split:
- stop installing the GitHub CLI (now installed on newer self-hosted
images, saves ~20 seconds)
- cache node_modules (saves about ~1 minute if package-lock.json
hasn't changed)
- pre-build Shaka once in a GitHub VM instead of in parallel on
multiple runner containers hosted on the same machine (saves ~45
minutes w/ 12 runners in parallel)
=> test: Split Selenium grid tests into multiple jobs

build/shaka-lab.yaml
Since we have been unable to solve #4234 (Xbox One disconnects from test runner), let's temporarily disable XboxOne from the lab to cut down on noise in our nightly tests.
=> test: Disable XboxOne

.github/workflows/deflake.yaml
This workflow will trigger after the nightly Selenium tests.  If those tests failed, this "deflake" workflow will automatically re-run the failed jobs up to 3 times (total, including the original scheduled run).
This should help cut down on noise and help highlight actual platform-specific failures.  The flakiness of our tests and infrastructure will be tracked separately and addressed at a somewhat lower priority than test greenness.
=> ci: Auto-deflake nightly selenium tests

externs/shaka/manifest_parser.js, lib/hls/hls_parser.js, lib/media/media_source_engine.js, lib/media/streaming_engine.js, lib/offline/storage.js, lib/player.js, test/dash/dash_parser_content_protection_unit.js, test/dash/dash_parser_live_unit.js, test/dash/dash_parser_manifest_unit.js, test/dash/dash_parser_segment_base_unit.js, test/dash/dash_parser_segment_list_unit.js, test/dash/dash_parser_segment_template_unit.js, test/hls/hls_live_unit.js, test/hls/hls_parser_unit.js, test/media/media_source_engine_unit.js, test/test/util/dash_parser_util.js
fix: Fix HLS dynamic to static transition
- Keep maxSegmentEndTime_ updated in PresentationTimeline by calling
notifySegments on each HLS playlist update, so that the seek range
doesn't revert to the original playlist size when it becomes
static.
- Wait to change the presentation type to VOD until after _all_
active playlists have an ENDLIST tag, to avoid missing the final
segments in one type or the other.
- Stop updating the playlists after transition to VOD.
- Update the MSE duration at exactly the same time as we transition
to VOD, to avoid a loophole where the UI knows it's VOD, but
doesn't have any way to get the correct duration.  Previously, this
state would persist until the final segments were appended.
Closes #4431
=> fix: Fix HLS dynamic to static transition

docs/jsdoc-template/publish.js, docs/jsdoc-template/tmpl/container.tmpl, docs/jsdoc.conf.json
Previously, top-level enums caused the generation of filenames like "shaka.config.html#AutoShowText" instead of
"shaka.config.AutoShowText.html".  This broke the generation of docs for top-level enums (attached to a namespace instead of a class).
This adds support for these into our jsdoc template.
Related to PR #3421
=> docs: Add support for documenting top-level enums

externs/ima.js, lib/ads/client_side_ad_manager.js
=> feat(ads): Ignore ad events with no associated ad

lib/media/streaming_engine.js
Close https://github.com/shaka-project/shaka-player/issues/3590
=> fix: allow the playback on platforms when low latency APIs are not supported

AUTHORS, CONTRIBUTORS, docs/tutorials/fairplay.md, lib/polyfill/patchedmediakeys_apple.js, test/polyfill/patchedmediakeys_apple_unit.js
Close #4469
The idea is to only enable uninstalling when it is desired, in order to not hold things in memory unnecessarily.
=> feat: enable uninstalling PatchedMediaKeysApple

test/media/streaming_engine_integration.js, test/offline/offline_integration.js
Shorten a StreamingEngine integration test to work around an issue with ChromeMac where playback doesn't always occur at 1x.  This is an issue with Selenium or Chrome itself (unknown) that is out of our control.  By making the test somewhat shorter, we can have it complete on time, even when this issue is present on a device.
Also increase timeouts on offline playback tests.
=> test: Fix playback timeouts on ChromeMac

.github/workflows/build-and-test.yaml
This should make it possible (if not easy) to download screenshots and diagnose layout test failures locally.
=> ci: Upload screenshot assets on failure

.github/workflows/build-and-test.yaml
Since Safari 16 became the default on macos-11 images in GitHub, we are updating our homedir installation of Safari 14 to Safari 15 instead.  This also renames that entry in the matrix from Safari-14 to Safari-old, in recognition of the fact that we will probably have to continue updating this.
=> ci: Test on Safari 16 and 15

.github/workflows/build-and-test.yaml, .github/workflows/selenium-lab-tests.yaml
Player integration tests use the compiled bundle by default.  This prevents us from getting coverage data in these tests, since the instrumentation was added to the uncompiled library only.
By collecting coverage data in uncompiled mode, we can fix this.
=> ci: Fix missing coverage data from integration tests

test/player_integration.js
Some timeouts in Player integration tests seem a little too short. This seems to have caused an intermittent test failure in a recent PR.
This expands those timeouts a bit, specifically before waitForEnd() calls.
=> test: Be more generous with timeouts

.github/workflows/selenium-lab-tests.yaml
The status reports were targetting main instead of the PR's HEAD.
=> ci: Fix reporting status from lab tests to PRs

AUTHORS, CONTRIBUTORS, lib/media/streaming_engine.js
The player does not operate normally when the last segment seek in the hls. (Chrome)
The fetchAndAppend_ function does not appear to be running on the last segment.
https://user-images.githubusercontent.com/25482071/193399014-6fced3ee-5bd3-4c7e-87da-f4e010d794c0.mp4
1. Click test link.
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/apple-advanced-stream-ts/master.m3u8;panel=ALL_CONTENT;panelData=HLS,MP2TS;build=compiled
2. Seek last segment.
=> fix: Fix hang when seeking to the last segment

AUTHORS, CONTRIBUTORS, lib/media/segment_index.js, test/media/segment_index_unit.js
Closes #4517
Fetching the last segment of HLS AES-128 stream fails with 3018 error
- `MediaSourceEngine` attempts to transmux encrypted TS data
- `StreamingEngine` does not decrypt TS data of the last segment
- `SegmentReference` of the last segment has `null` for `hlsAes128Key`
- `hlsAes128Key` is missing when adjusting the last SegmentReference in `SegmentIndex.fit()`
=> fix: Missing AES-128 key of last HLS segment

lib/media/media_source_engine.js, test/media/media_source_engine_integration.js, test/media/media_source_engine_unit.js
On Chromecast devices, TS-based streams tend to be more susceptible to failures related to the Cast platform's MSE implementation.
One of these failures was observed when Shaka Player updates `SourceBuffer#timestampOffset` within `MediaSourceEngine#appendBuffer()`:
1. To extract a timestamp from `MediaSource` to align text segments: https://github.com/shaka-project/shaka-player/blob/3d0f752c7d0677f750dbbd9bcd2895358358628f/lib/media/media_source_engine.js#L657
2. To re-align segments as a result of an unbuffered seek or automatic adaptation: https://github.com/shaka-project/shaka-player/blob/3d0f752c7d0677f750dbbd9bcd2895358358628f/lib/media/media_source_engine.js#L684-L686
The Cast platform throws the following error:
```
...
"stack":"Error: Failed to set the 'timestampOffset' property …
```
=> fix: Fix errors with TS segments on Chromecast

lib/media/media_source_engine.js
Clearing the buffer seems to be not enough for this case.
This avoids the choppy video start on HLS fMP4 playback.
Tested with Chrome 106 & Edge 106.
Closes #4516
=> fix: Fix choppy HLS startup

AUTHORS, CONTRIBUTORS, lib/player.js
Adds channelCount to the Select Audio Track method, this allows for selecting a audio track based on the channel count when the language, codec and role are the same.
Issue: https://github.com/shaka-project/shaka-player/issues/4550
=> feat: Adds ChannelCount as a filter to the Player Select Audio Track Method

lib/hls/hls_parser.js, lib/media/presentation_timeline.js, lib/player.js, test/hls/hls_live_unit.js, test/hls/hls_parser_unit.js
This changes the HLS parser so that the media playlists are only downloaded when the createSegmentIndex function for the associated stream is called.
Because there is some important information about HLS streams that is stored inside the media playlist, this also changes the player to call createSegmentIndex on the initial variant earlier in the load process, to make sure that information is available in time.
As of this change, we will now require HLS streams to be aligned (see #4308) for livestreams. VOD content can still
be unaligned.
Closes #1936
=> feat(HLS): Lazy-load HLS media playlists

README.md, externs/lcevc.js, externs/shaka/player.js, package.json
Changes are as follows:
1. Fixed demo breaking dependencies.
2. Fixed some typos
3. Added LCEVC support section to readme.
=> fix: Fixed LCEVC decode breaking dependencies issue and read me addition

lib/polyfill/media_capabilities.js, lib/util/platform.js
See https://github.com/shaka-project/shaka-player/issues/4569 for more context.
This affects any Chromecast model which contains the substring `Android` in their userAgent. For TS content, this causes Shaka to incorrectly filter all stream variants leaving nothing for the player to select for playback (resulting in a `4032` error): https://github.com/shaka-project/shaka-player/blob/757b34e5959f14c9a5b5aed173cc99d98a794a40/lib/util/stream_utils.js#L484-L491.
=> fix: Resolve load failures for TS-based content on Android-based Cast devices (#4569).

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
The changes to implement lazy-loading broke the previous functionality to load media playlists directly, as they are not lazy loaded. This fixes that case, so that lazy-loaded media playlists will correctly set their duration and presentation type.
Issue #1936
Issue #3536
=> fix(hls): Fix single-variant HLS streams

lib/offline/indexeddb/storage_mechanism.js, lib/util/error.js, test/offline/storage_integration.js
In some cases, indexedDB.open() can end up calling neither callback. When this does happen, according to my initial testing, it happens consistently when reloading the page, so it's not a one-off fluke but presumably some sort of implementation or browser install problem. If that does happen, the init promise of the storage muxer hangs forever, potentially blocking other operations from happening. This adds a timeout to the invocation of indexedDB.open(), after which the operation fails with a new error.
=> fix(offline): Add storage muxer init timeout

AUTHORS, CONTRIBUTORS, lib/media/playhead.js
`player.getStats()` currently fails when `stallEnabled` is set to false in Player configuration. In this PR I've added a safeguard to make sure `getStallsDetected` returns 0 when `stallDetector` is null.
=> fix(playhead): safeguard getStallsDetected as stallDetector can be null

.github/workflows/build-and-test.yaml, .github/workflows/compute-incremental-coverage.py, .github/workflows/selenium-lab-tests.yaml
GitHub is deprecating the set-output syntax and moving to writing outputs to a file.  This updates our workflows to match.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: Update workflow syntax

.github/workflows/build-and-test.yaml
Because our release PRs are created with the default GitHub token, they do not trigger test runs.  This is a feature of GitHub that prevents recursive loops of workflows.
This change makes it so that marking a PR "ready for review" will trigger the tests to run again.  This gives us an easy way to trigger test runs on a release PR, by marking it a draft, then marking it "ready" again.
=> ci: Re-run PR tests when leaving draft mode

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
We assume before a playlist is loaded that the content is MP4.  But once a single playlist is loaded with TS, we should then assume that all the other playlists of that type (video/audio) are also TS. Otherwise, as-yet-unloaded playlists are filtered out of the variants list as "incompatible".
=> fix(HLS): Fix lazy-loading of TS content

lib/player.js
With HLS lazy-loading, there were some situations where the manifest had partially loaded, enough to move onto further load stages, but no segments had been loaded, so the duration is still unknown. This could cause the UI seek bar to try to determine the seek range, fail, and cause an assertion failure.
These were not fatal errors, but they still fill up the console and make it look like something worse is happening, so they should be fixed.
With this change, the player returns a seek range of 0 to 0 until the asset is fully loaded.
=> fix(HLS): Return 0-0 seek range until fully loaded

build/conformance.textproto, lib/media/drm_engine.js, lib/text/ttml_text_parser.js, lib/util/xml_utils.js, test/util/xml_utils_unit.js
Harden the XmlUtils.parseXmlString function against XML documents that embed elements from the HTML or SVG namespaces, which could trigger script execution and cause XSS vulnerabilities.
Also migrate direct users of the DOMParser.parseFromString function to XmlUtils, and add appropriate unit tests.
=> fix: Make XML parsing secure

.github/workflows/build-and-test.yaml, .github/workflows/demo-version-index.yaml, .github/workflows/nightly-demo.yaml, .github/workflows/release-please.yaml, .github/workflows/report-incremental-coverage.yaml, .github/workflows/selenium-lab-tests.yaml
v2 uses a deprecated node version (12), and v3 uses a current version (16).
=> ci: Update actions/checkout version

build/shaka-lab.yaml
Due to shaka-project/generic-webdriver-server#57, we can not communicate with our Tizen TV in the lab.  Until this is resolved, we must disable the device in our Selenium grid config.
=> ci: Disable Tizen

lib/polyfill/media_capabilities.js
The MCap API on the EOS set-top boxes is rather buggy thus we're relying on the polyfill instead.
=> fix: Force using mcap polyfill on EOS browsers

lib/media/streaming_engine.js, lib/player.js, test/media/streaming_engine_integration.js, test/media/streaming_engine_unit.js, test/player_unit.js
In general, streaming.failureCallback is meant to give applications control over error handling at the level of streaming.  However, there was a special case for HTTP 404s built into StreamingEngine in a way that applications could not override.  This was in spite of the fact that the default failureCallback would already check for and retry on the error code BAD_HTTP_STATUS.
This removes the special case in StreamingEngine and refactors failureCallback and retryStreaming to preserve the special delay imposed in the old 404 handler.  With this, applications can override failureCallback to have complete control over 404 handling.
Closes #4548
=> fix: Allow overriding special handling of 404s

lib/cast/cast_proxy.js, lib/cast/cast_receiver.js, lib/cast/cast_sender.js, lib/cast/cast_utils.js, test/cast/cast_receiver_integration.js, test/cast/cast_receiver_unit.js, test/cast/cast_utils_unit.js
Our Cast API sends update messages from receiver to sender, and we have observed before that there is a hidden limit on the size of those messages.  A test was written long ago to catch unexpected increases in message sizes, and it has recently started failing.
Our original limit on individual messages was set to 6kB, but later raised to 7kB to silence test failures.  Our original goal was to keep messages well under 8kB.  We also had a limit on the average message size of 3kB (over 50 messages).
This change greatly reduces the sizes of individual messages by splitting out updates to certain getters into their own messages. These are the getters that produce the most data: getConfiguration(), getStats(), getVariantTracks(), and getTextTracks().  In testing, getConfiguration() alone is …
=> fix(cast): Reduce size of Cast update messages

AUTHORS, CONTRIBUTORS, externs/mux.js, lib/ads/client_side_ad_manager.js, lib/media/media_source_engine.js, lib/media/transmuxer.js, test/media/media_source_engine_integration.js
For HLS non native, Shaka gets the captions from mux.js transmuxer. This
works until you seek back before the buffered range. In mux.js there is
a condition that ignores a caption if this belongs to a DTS that is
behind the latest it already has parsed.
To handle seeks, it adds a reset method that is called by the transmuxer.resetCaptions() method in mp4\transmuxer.js in mux.js. But Shaka Player is not calling it. So I added the resetCaptions() method to the mux.js extern definition and we called it in the appendBuffer method in media_source_engine.js before sending the data to transmux and only if the seeked parameter is True.
Closes #4641
=> fix: embed cc not shown when seeking back

lib/hls/hls_parser.js, test/hls/hls_live_unit.js
If a stream switch occurs during a playlist update, that update may need to be cancelled.  This handles this edge case to prevent an exception trying to access stream.segmentIndex.
Closes #4647
=> fix: Fix HLS lazy-loading exception during update

lib/hls/hls_parser.js, test/hls/hls_live_unit.js
For HLS lazy-loading, there was a race.  If a call to switch streams occurred during a fetch-and-append operation in StreamingEngine, there would be two calls to createSegmentIndex() for the same stream.  This was being mishandled in the HLS parser, such that the second call would return immediately without waiting on the creation of the segment index.
This fixes HLS's createSegmentIndex() method to ensure that multiple calls on the same stream return the same Promise.
Closes #4621
=> fix: Fix HLS lazy-loading exception on switch

externs/shaka/manifest_parser.js, lib/hls/hls_parser.js, lib/offline/storage.js, lib/player.js, test/dash/dash_parser_content_protection_unit.js, test/dash/dash_parser_live_unit.js, test/dash/dash_parser_manifest_unit.js, test/dash/dash_parser_segment_base_unit.js, test/dash/dash_parser_segment_list_unit.js, test/dash/dash_parser_segment_template_unit.js, test/hls/hls_live_unit.js, test/hls/hls_parser_unit.js, test/test/util/dash_parser_util.js
Now that DRM info is only parsed after playback has begun, the manifest parser needs to communicate back to the other components that new DRM info is available after lazy-loading a playlist.
Closes #4622
=> fix: Fix HLS lazy-loading with DRM

ui/settings_menu.js
Going to the configuration menu using the keyboard and entering some menu, when going back the focus is lost because the first element of the HTML tree is hidden. This makes it difficult to use the player using accessibility shortcuts.
Closes [#4652](https://github.com/shaka-project/shaka-player/issues/4652)
=> fix: focus on first element when back to the settings menu

lib/hls/hls_parser.js, test/hls/hls_live_unit.js
We tested this fix internally our HLS streams but also with the stream mentioned in https://github.com/shaka-project/shaka-player/issues/741#issuecomment-1220036539
test stream: https://content.uplynk.com/playlist/ebbbf2111be144a4971dd8426b70e809.m3u8?rmt=wv&m4fenctype=cenc
license server url: https://content.uplynk.com/wv
Fixes #741
=> feat(HLS): Support for HLS key rotation

ui/controls.js
Console error in environment where fullscreen is not possible when enableFullscreenOnRotation option is turned on
```console
TypeError: i.j.requestFullscreen is not a function. (In 'i.j.requestFullscreen({navigationUI:"hide"})', 'i.j.requestFullscreen' is undefined)
```
check `isFullScreenSupported` on `onScreenRotation`
=> fix(ui): Fix exception on screen rotation if fullscreen is not supported

docs/tutorials/ui.md
In the main branch, since the code there is a pre-release, these should generally all point to the nightly demo receiver.
=> docs: Fix receiver app ID in UI tutorial

demo/index.html, docs/tutorials/ui.md
This will be reverted in the main branch after the launch/branch of v4.3, so that main continues refers to the nightly version of the receiver app.
=> chore: Set receiver app ID for v4.3

lib/util/platform.js
Xbox One was being misdetected as Chrome, causing some mistakes in which tests are skipped.
This does not appear to affect the library itself, since isChrome() and chromeVersion() are only used in tests currently.
=> test: Fix platform detection for Xbox

test/polyfill/patchedmediakeys_apple_unit.js
An internal build system spotted this issue after being synced to the v4.3.0 release.
=> chore: Add missing license header

demo/index.html, docs/tutorials/ui.md
This reverts commit ea2eaaf2106b6bcac56119e2e0559fe918664932.
Now that v4.3 is out, this sets the receiver app ID for main to refer to the nightly version of the receiver app again.
=> chore: Set receiver app ID for main (#4675)

ui/controls.js
```
[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
```
This error occurs when the first touch is initiated.
Added logic to confirm that the error can be cancelled before event.preventDefault.
=> fix(ui): Check event cancelable before event.preventDefault

test/media/drm_engine_unit.js
Since we ended up with a different default config on Xbox, the tests for DRM broke.  That went unnoticed because Xbox is offline in our lab.  The issue was discovered while working to restore that platform in the lab test runs.
=> test: Fix Xbox DRM tests

test/util/xml_utils_unit.js
Xbox seems to treat SVG and/or XML a little differently than other platforms, which led to a test failure on that platform.  That went unnoticed because Xbox is offline in our lab.  The issue was discovered while working to restore that platform in the lab test runs.
=> test: Fix XML parser security tests on Xbox

lib/polyfill/patchedmediakeys_apple.js
An internal build system failed to compile v4.3.0 due to the use of static "this".  This change fixes it.
Unfortunately, we are already running the latest public compiler release, so there is no way we could have caught this on GitHub.
=> fix: Fix compiler error on static use of "this"

build/build.py, build/conformance.textproto, build/types/polyfill, lib/polyfill/abort_controller.js, shaka-player.uncompiled.js
We started using AbortController in HlsParser in 777c27ee, but that change was made while the Tizen TV in our lab was offline.  This restores functionality to Tizen.
This polyfill uses getters, a feature of ES6 that the compiler won't transpile into ES3, so this also changes the output language to ES5. This should not be an issue, since ES5 has been well supported in all browsers since IE10.
=> fix: Polyfill missing AbortController on Tizen

build/shaka-lab.yaml
An upgrade to Tizen Studio and the Docker image for it have solved our Tizen lab infra issues.
=> ci: Re-enable Tizen in the lab

test/media/media_source_engine_integration.js, test/test/util/stream_generator.js, test/test/util/test_scheme.js
This completes the TS StreamGenerator and updates test expectations to match.  With this, we get realistic simulated TS streams, which will be important as a baseline for replacing mux.js with our own TS parser.
See also PR #4697
=> test: Finish TS StreamGenerator

lib/media/content_workarounds.js
=> fix: Fix DRM workaround for Tizen and Xbox with hvc1/hev1 boxes

test/ads/ad_manager_unit.js, test/hls/hls_parser_unit.js
This fixes test exceptions that did not fail their tests.  One was an HlsParser instance that outlived the test run and failed after server disconnection.  The other was an exception in AdManager that did not fail the test, but nonetheless caused an unexpected error to be logged.
Both of these issues were spotted while running the tests in a local browser in debug mode.  Neither caused test failures directly, but both were examples of poor hygiene in our tests.
=> test: Fix exceptions in tests

lib/polyfill/media_capabilities.js, lib/util/error.js, test/polyfill/media_capabilities_unit.js
See https://github.com/shaka-project/shaka-player/issues/4726 for more context.
This allows Cast devices to properly filter stream variants with a resolution surpassing that of the device's capabilities.
We place the fix in the `MediaCapabilities` polyfill since it's intended to be the right way to check for anything related to platform support.
--- 
HDR support checks will require `eotf=smpte2048`, as indicated in https://github.com/shaka-project/shaka-player/issues/2813#issue-684874730. Specifically, a `{hev|hvc}1.2` profile is only an *indication* of an HDR transfer function, but *may* be a non-HDR 10-bit color stream. Take for instance this publicly available hls.js HEVC stream (https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8) which …
=> fix(cast): Use cast platform APIs in MediaCapabilties polyfill

AUTHORS, CONTRIBUTORS, lib/player.js, test/player_unit.js
This enables #4189 for two more error types. As mentioned in #4728 404 status results in `BAD_HTTP_STATUS` rather than `HTTP_ERROR`. I also think `TIMEOUT` should be included, and another issue was just created for this (#4764), so I included that as well.
If we don't want this, then an alternative is to make which errors to handle here configurable, but I thought I'd start with this suggestion.
Closes https://github.com/shaka-project/shaka-player/issues/4728
Closes https://github.com/shaka-project/shaka-player/issues/4764
=> feat: Enable variant failover for BAD_HTTP_STATUS and TIMEOUT

lib/util/stream_utils.js, test/test/boot.js
=> feat: Cache mediaCapabilities.decodingInfo results

AUTHORS, CONTRIBUTORS, build/types/core, lib/media/media_source_capabilities.js, lib/media/media_source_engine.js, lib/media/transmuxer.js, lib/polyfill/media_capabilities.js, lib/util/stream_utils.js, test/polyfill/media_capabilities_unit.js
We have just derived the repository by the old shaka version and found there seems the same optimization could be implemented on the latest shaka player.
When developing on each web core livingroom platform (Tizen, WebOS, Chromecast, etc.), we found that there takes a long time to parse the manifest between downloading the manifest and downloading the first content segment. After profiling it, we found that there was a frequent function called `MediaSource.isTypeSupported` in it, up to hundreds or even thousands (the pic attached below). But this situation does not happen on the latest Chrome or Safari.
We concluded that it must be related to the old browser engine (Chromium) that does not do optimization on it.
And we just cached the function call results and let it not calls that API so …
=> perf: Caching mediaSource support for browser engine

build/install-linux-prereqs.sh, docs/tutorials/welcome.md
We require node v14+ and Java v11+ now.
Closes #4721 
Closes #4737
=> docs: Update docs about dev dependencies

lib/polyfill/media_capabilities.js
See https://github.com/shaka-project/shaka-player/issues/4790.
To be honest, I'm failing to understand how a `TypeError` can happen here (this is occurring in a Casted Apple Music, non-`AES-128` stream, so `EME`), since:
1. The problematic code lines aren't reachable unless `MediaDecodingConfig.keySystemConfiguration` is set.
2. `MediaDecodingConfig.keySystemConfiguration` is only set if `drmInfos` are provided:
https://github.com/shaka-project/shaka-player/blob/68f10a1969b3ae639cd58b76b30b223cd4a08a5c/lib/util/stream_utils.js#L659-L666
during manifest parsing (showing HLS for example):
https://github.com/shaka-project/shaka-player/blob/68f10a1969b3ae639cd58b76b30b223cd4a08a5c/lib/hls/hls_parser.js#L1003-L1016
Regardless, `requestMediaKeySystemAccess()` will never report a variant is …
=> fix(cast): Added existence checks for MediaDecodingConfig.{audio|video} in decodingInfo().

lib/hls/hls_parser.js
Closes https://github.com/shaka-project/shaka-player/issues/4771
=> feat(HLS): Poll HLS playlists using last segment duration

lib/text/ui_text_displayer.js, test/text/ui_text_displayer_unit.js
Proposed fix closes #4680
Reinstate previously removed region elements when next caption finds it is not there: Detect the absence and ensure `updateDOM` is true so its reinstated and the next caption can be shown.
=> fix: Fix subtitles not added to DOM region

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
Issue wasn't caught by the existing tests.
Closes #4759
=> fix(HLS): Fix missing roles

lib/text/ttml_text_parser.js, test/text/mp4_ttml_parser_unit.js, test/text/ttml_text_parser_unit.js
=> fix(TTML): Fix duplicate cues overlapping segment boundaries

test/test/boot.js
Unhandled global exceptions already generate test failures, but this adds specific useful information, like stack traces, to those failures.
See issue #4813
=> test: Catch and print info from unhandled global exceptions

.github/workflows/build-and-test.yaml
Since Edge 107 on Linux has an outdated CDM causing test failures, we have to force update to Edge 108 in GitHub Actions.
Closes #4825
=> ci: Force update to Edge 108

test/player_integration.js, test/test/util/test_scheme.js
For some unknown reason, using precise durations for these audio segments on Tizen creates gaps that can't be survived.  I don't know why that creates a 150ms gap, and I don't know why we can't seem to jump over it.  It feels very much like a bug in Tizen itself.
Experimentally, I found that rounding these durations to 10s even removes the gap completely.  I tried many other things, but this is the only reasonable thing I have found that works.
More details on my investigations can be found in the issue on GitHub.
This change in durations exposed some brittle tests in Player which had to be adjusted to be more robust.
Closes #4806
=> test: Fix StreamingEngine tests on Tizen

lib/hls/hls_parser.js, lib/media/media_source_engine.js, lib/media/segment_reference.js, lib/media/streaming_engine.js, test/test/util/manifest_parser_util.js
If server-side ad segments aren't aligned, AV could get out of sync by accumulating errors in the timestampOffset of the SourceBuffers.
This improves the issue by tracking discontinuity boundaries and resetting timestampOffset to theoretical segment start times when a boundary is crossed.
Issue #4589
=> fix(HLS): Fix AV sync over ad boundaries

lib/media/streaming_engine.js
There were several places where certain StreamingEngine events and timing could result in duplicate update requests for streams.  This caused some inconsistent test failures, in particular on Chromecast.
This change adds some additional checks before scheduling and cancelling updates, to ensure that the proper conditions are maintained.
Closes #4831
=> fix: Fix duplicate updates in StreamingEngine

lib/text/ui_text_displayer.js, test/text/ui_text_displayer_unit.js
Captions split over stream segment boundaries are repeated over more than one segment.
Regions in which they sit maybe described the same but allocated different ids and vice versa.
Proposal to treat internal region ids uniqely by encoding the dimensions in the id.
fixes #4839
=> fix: Treat regions uniquely

lib/util/dom_utils.js
fixes https://github.com/shaka-project/shaka-player/issues/4861
`button` element by default has `type` set to `submit` which can interfere with forms.
=> fix(ui): Avoid submitting form if player is inside form

lib/player.js
This stops the timer inside region timeline from staying in memory, even after the player is destroyed.
Closes #4850
=> fix: Release region timeline when unloading

test/media/streaming_engine_unit.js
Some of the EMSG tests were redundant, and repeated for different timestamps.  Instead, run all EMSG tests with a non-zero timestamp offset, since 0 is just a degenerate case.
This also consolidates all of the test vectors so that the tests are easier to read.
=> test: Consolidate emsg tests

lib/media/media_source_engine.js
Tested with https://pub-e06bd0d1422649108618e7121f2af8b5.r2.dev/finite.m3u8
=> fix: Fix media source duration when using sequence mode

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
fixes https://github.com/shaka-project/shaka-player/issues/4846
=> fix(HLS): Fix support for mixed AES-128/NONE decryption

lib/hls/hls_parser.js, test/hls/hls_live_unit.js
Discontinuity tracking was broken and test coverage was insufficient to catch this.  This fixes the parsing and counting of discontinuities, and replaces two outdated and useless tests with a new one that covers the counting properly.
One of the old tests was checking that a timestamp offset was set for each discontinuity, but this had become irrelevant since the test was written.  Discontinuities do not have anything to do with timestamp offsets in current versions of Shaka Player.
The other old test was checking that after a discontinuity, we didn't fetch a segment to parse out the timestamp, but we stopped doing that entirely in v4.
The new test checks that the initial discontinuity sequence number is honored, and that after a discontinuity, the number goes up.  It also checks that the …
=> fix(HLS): Fix discontinuity tracking

lib/media/segment_index.js, test/media/segment_index_unit.js
Make SegmentIndex robust against rounding errors so that we don't end up with duplicate segments on merge.  In sequence mode, this would cause a massive AV sync issue of 1 segment duration.
Issue #4589
=> fix: Fix potential duplicate segments, AV sync issues

lib/hls/hls_parser.js, lib/media/segment_index.js, lib/media/segment_reference.js
=> fix: Sync each segment against EXT-X-PROGRAM-DATE-TIME

test/player_unit.js
This test started failing on Tizen after PR #4858, which updates codecs in manifest metadata any time they are rewritten.  Since ac-3 is rewritten as ec-3 on Tizen, that caused this test case covering ac-3 to start failing (because the codec says ec-3 by the end of the test).
=> test: Fix surround sound test case on Tizen

test/text/text_displayer_layout_unit.js, test/text/ui_text_displayer_unit.js
Also fixes a compiler error that comes up for some reason when renaming the other tests.  The compiler will accept an assignment to nestedCues, but not pushing to it.  I was unable to fix the missing type information for this.
Related to work on PR #4767
=> chore: Rename layout tests

lib/text/vtt_text_parser.js, test/text/vtt_text_parser_unit.js
closes https://github.com/shaka-project/shaka-player/issues/4844
fixes https://github.com/shaka-project/shaka-player/issues/4843
fixes https://github.com/shaka-project/shaka-player/issues/4479
=> feat(WebVTT): Add support to voice tag styles

lib/text/vtt_text_parser.js, test/text/vtt_text_parser_unit.js
We do not yet support VTT region settings, but we should still not fail when a region block appears in a VTT file.
Related to work on PR #4767
=> fix: Fix WebVTT parser failure on REGION blocks

.github/workflows/selenium-lab-tests.yaml
This will upload screenshots when the Selenium lab tests fail.  This can be used to get screenshot changes either for examination or for updating the test expectations.
=> ci: Upload screenshots on test failures

externs/mathml.js, lib/util/xml_utils.js, test/util/xml_utils_unit.js
This PR fixes #4912 by adding MathML to the list of forbidden namespaces.
=> fix: Forbid MathML namespace in shaka.util.XmlUtils

test/test/assets/screenshots/review.html
Now screenshots are grouped by test for easy comparison across platforms, and have an optional line break element between each set of tests.
Related to work on PR #4767
=> test: Reorganize screenshots in review tool

lib/hls/hls_parser.js
Was this a typo? We were seeing uncaught TypeErrors when changing subtitle tracks related to this, it seems `'txt/vtt'` is not a valid mime type for webvtt subtitles.
Closes #4929
=> fix(HLS): Fix detection of WebVTT subtitles in HLS by extension

lib/text/vtt_text_parser.js
When multiple style blocks exist for the same selector, they should be combined.  For example,
::cue(b) { background: white; }
::cue(b) { color: blue; }
should set both the background and foreground of bold tags.
=> fix(VTT): Fix combining style selectors

lib/media/media_source_engine.js, lib/util/error.js, test/media/media_source_engine_unit.js
Our PROD app has been getting some 3015 errors where the exception message is as follows:
`Error: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null`
We have added some extra logging to add what is inside the error property in hopes of having a better ideia of what is causing it since we ourselves haven't quite been able to reproduce the issue.
Wanted to bring this back to the main repo in case it could help others. Because the exception Shaka gets only has that message so could be useful to know what was the exact error that the media element got that caused the `appendBuffer` call to fail.
=> feat(logs): Add extra logging for 3015 errors

lib/dash/segment_template.js, test/dash/dash_parser_manifest_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/4913
=> fix(DASH): Fix dynamic manifests from edgeware

lib/hls/hls_parser.js
Fixes #4350
The current code initially parses the subtitle track as text/vtt (mimetype) since it has no codec. Subsequently, the stpp.ttml.im1t codec is assigned but the mimetype of text/vtt is not changed to application/mp4. This PR changes this so that once the codec is assigned, the mimetype is recalculated.
=> fix(HLS): IMSC1 subtitles not working in a HLS stream

lib/media/streaming_engine.js
In Low Latency HLS, the low latency segments are integer segments instead of partial segments like in DASH, so we can avoid reading part of the segment and increase performance on low-end devices.
=> feat(HLS): Improve Low Latency performance in HLS

lib/util/stream_utils.js
Fixes https://github.com/shaka-project/shaka-player/issues/4659
=> fix(MCap): Remove robustness when robustness value is default

lib/text/vtt_text_parser.js, test/text/vtt_text_parser_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/4956
=> fix(WebVTT): Tags in the WebVTT subtitle are not parsed

lib/media/video_wrapper.js
Fixes https://github.com/shaka-project/shaka-player/issues/4888
=> fix: Failed to set 'currentTime' property on 'HTMLMediaElement' on a Hisense TV

lib/media/drm_engine.js
Closes #4902
This is not intended to be a complete fix for the issue, I do not understand the effect this new ternary on the shaka player as a whole. I have not found the root cause for `this.currentDrmInfo_` being `undefined` when accessed. It does, however, look like it has previously been acceptable for this property to be `undefined`. I opened this PR more as a point of discussion around the issue at hand.
During the work to add Fairplay support in 2022, accessing `this.currentDrmInfo_` was added on line 483. This line **does not** accept that `this.currentDrmInfo_` can be undefined. A few lines below this, `this.createOrLoad()` is called, which **does** accept that `this.currentDrmInfo_` can be `undefined`. The latter piece of code was last modified in 2019. …
=> fix: DrmEngine exception thrown when using FairPlay

lib/player.js
Fixes https://github.com/shaka-project/shaka-player/issues/4940
This occurs when the operating system defaults to enabled subtitles in src= mode. The solution is to detect that there are active subtitles and set the internal visible flag to true.
=> fix: Caption can not turn off at iOS Safari

lib/ads/client_side_ad_manager.js
Fixes https://github.com/shaka-project/shaka-player/issues/4445
After watching post roll ads, `this.video_.play()` was called on a completed content in the `onAdComplete` event. The content would then restart from the beginning.
We now flag that the content is completed before we call `this.adsLoader_.contentComplete()`. On the callback, we prevent the video element from replaying if this flag is set.
This fix is based on the Advanced Sample on the [googleads-ima-html5 repo](https://github.com/googleads/googleads-ima-html5/blob/main/advanced/ads.js#L128)
=> fix: Prevent content from being restarted after Postroll ads

lib/hls/hls_parser.js
Closes https://github.com/shaka-project/shaka-player/issues/4981
=> feat(HLS): Add support to HLS-AES128 low latency

.github/workflows/demo-version-index.yaml
The release trigger does not work yet, so compensate with a nightly schedule.
Closes #4361
=> ci: Update the version index nightly

.github/workflows/selenium-lab-tests.yaml, .github/workflows/update-screenshots.yaml
Untested.  A workflow must exist in the main branch before a version of it from any branch can be triggered.
=> ci: Experimental workflow to update screenshots in a PR

demo/close_button.js, demo/main.js, docs/tutorials/ui-customization.md, externs/pictureinpicture.js, ui/pip_button.js
This PR adds _experimental_ support for the Document Picture-in-Picture API in the Shaka Player.
I'm making some assumptions about how Shaka Player works and I'd love your review on this. Thank you!
Closes https://github.com/shaka-project/shaka-player/issues/4964
=> feat: Add support for Document Picture-in-Picture

externs/shaka/transmuxer.js
See https://github.com/shaka-project/shaka-player/issues/4998. 
Now, building Shaka debug build will correctly obfuscate `shaka.extern.Transmuxer.*` fields in the `shaka-player.compiled.debug.js` build like all the other externs provided in `externs/shaka/` directory (e.g., `aria.js`, etc.).
=> fix: Explicitly specify @externs in transmuxer externs.

docs/tutorials/errors.md
Closes #4484
Shaka error handling is getting increasingly more complex in order to "catch them all", I've tried to put together my current understanding of handling various cases in a tutorial. To read it with github md formatting: [errors.md](https://github.com/martinstark/shaka-player/blob/error-tutorial/docs/tutorials/errors.md)
=> docs: add error handling tutorial

lib/hls/hls_parser.js
The duration is the minimum of the end times of all active streams.
Non-active streams are not guaranteed to have useful maxTimestamp
values, due to the lazy-loading system, so they are ignored.
=> fix: Prevent error and incorrect duration

.github/workflows/build-and-test.yaml, .github/workflows/selenium-lab-tests.yaml, .github/workflows/update-screenshots.yaml
The initial commit was untested, but having the workflow in the main branch allowed me to iterate on the workflow and test it in a branch.
The following changes were made:
- Standardize how workflow inputs are read (using inputs, which works for all triggers, instead of github.event.inputs, which only works for some triggers)
- Improve the description of test_filter in selenium-lab-tests.
- Add missing fields in the workflow_call trigger of selenium-lab-tests.yaml.  (Unfortunately, the two triggers need to have the inputs defined separately, and with slightly different fields.)
- Log the chosen ref in selenium-lab-tests, to help debug inputs.
- Fix variable expansion in selenium-lab-tests so that test_filter can contain spaces.
- Fix ignore_test_status, which did not work at all and …
=> ci: Fix workflow to update screenshots

demo/common/asset.js, docs/tutorials/ad_monetization.md, docs/tutorials/application-level-redirects.md, docs/tutorials/fairplay.md, docs/tutorials/license-server-auth.md, docs/tutorials/license-wrapping.md, externs/shaka/net.js, lib/dash/dash_parser.js, lib/dash/segment_base.js, lib/dash/segment_template.js, lib/hls/hls_parser.js, lib/media/streaming_engine.js, lib/net/networking_engine.js, lib/util/fairplay_utils.js, test/dash/dash_parser_live_unit.js, test/dash/dash_parser_manifest_unit.js, test/dash/dash_parser_segment_base_unit.js, test/dash/dash_parser_segment_template_unit.js, test/hls/hls_live_unit.js, test/media/drm_engine_unit.js, test/media/streaming_engine_integration.js, test/media/streaming_engine_unit.js, test/test/util/fake_networking_engine.js, test/test/util/streaming_engine_util.js
This adds an optional parameter to request and response filters, of a new enum called AdvancedRequestType.
This enum describes request types that are subtypes of the basic types. For example, INIT_SEGMENT is a type of SEGMENT.
This gives users more information about the type of the request, while maintaining backwards compatibility.
Closes #4966
=> feat(net): Added advanced type to filters

docs/tutorials/fairplay.md, docs/tutorials/index.json, docs/tutorials/widevine-service-certs.md
Also fixes a related typo in the FairPlay tutorial and adds a missing entry to the tutorial index.
=> docs: Add Widevine Service Certificate tutorial

lib/hls/hls_parser.js
Fixes https://github.com/shaka-project/shaka-player/issues/5033.
=> fix(HLS): Add `.tsa` and .`tsv` file extensions as valid MPEG2-TS.

lib/polyfill/mediasource.js
Fixes https://github.com/shaka-project/shaka-player/issues/4955
=> fix: Reject TS content on Edge

lib/polyfill/mediasource.js
See: https://bugs.webkit.org/show_bug.cgi?id=165342
Tested on Safari 16 with http://storage.googleapis.com/shaka-demo-assets/_bugs/safari-10-mse-abort/index.html
=> chore: the implementation of abort() on SourceBuffer in Safari, now works

lib/ads/ad_manager.js, lib/ads/client_side_ad_manager.js
Closes https://github.com/shaka-project/shaka-player/issues/4335
The errors are now forwarded to the player
=> feat(ads): Dispatch a player event for client-side ad errors

lib/debug/log.js
This removes some workarounds that were in the logging code for the sake of Internet Explorer. We no longer support IE, so those workarounds are no longer necessary.
Closes #5032
=> fix: Simplify logging code for compatibility with webpack-terser-plugin

lib/debug/log.js
PR #5050 unboxed the console log methods, which broke logging on Tizen.  This change was never released.
This fixes the issue by using arrow functions to prevent unboxing.
=> fix(Tizen): Fix exceptions thrown from logging methods

.github/workflows/selenium-lab-tests.yaml
This allows us to run the lab tests on a subset of browsers/platforms for a given PR.
=> ci: Add browser filter to lab workflow

lib/media/media_source_engine.js
closes #5070
maybe it would make more sense to only call it when the readyState is `'open'`?
=> fix: prevent bad calls to MediaSource.endOfStream

docs/tutorials/a11y.md, docs/tutorials/ad_monetization.md, docs/tutorials/basic-usage.md, docs/tutorials/config.md, docs/tutorials/debugging.md, docs/tutorials/drm-config.md, docs/tutorials/license-server-auth.md, docs/tutorials/license-wrapping.md, docs/tutorials/network-and-buffering-config.md, docs/tutorials/ui-customization.md, docs/tutorials/ui.md, docs/tutorials/welcome.md
The links to the next tutorial were out of date, and they no longer prescribed the actual order of tutorials. This just removes those links entirely.
Fixes #5078
=> docs: Remove next links from tutorials

lib/media/segment_index.js
The `discontinuitySequence` field of the last `SegmentReference` was getting reset to `0` in this function, even if it was originally set to something other than 0. This was causing unnecessary resyncs for the final segment of the video in sequence mode.
=> fix(HLS): preserve discontinuitySequence in SegmentIndex#fit

lib/net/http_fetch_plugin.js
Fixes https://github.com/shaka-project/shaka-player/issues/5088
=> fix: Fix fetch plugin with old implementations

externs/shaka/ads.js, externs/shaka/player.js, lib/ads/ad_manager.js, lib/ads/client_side_ad_manager.js, lib/ads/server_side_ad_manager.js, lib/player.js, lib/util/player_configuration.js, test/ads/ad_manager_unit.js, test/test/util/fake_ad_manager.js
This doesn't produce any output right now, but this allow to the forks to create custom configurations for ads, and also allow future configurations to be added.
=> feat(Ads): Add ads config

lib/media/media_source_engine.js
Closes #4903
Does not fix the underlying root cause of the `init` function being called on a `closed` or `ended` MediaSource, but attempts to mitigate the throwing of an uncaught TypeError.
Thoughts on a proper fix:
Would it make sense to rework `mediaSourceOpen_` to await `sourceopen`, or reject/return false when it isn't, can't, or won't open? This would improve control flow by moving the responsibility of handling the MediaSource state to the caller.
For illustrative purposes:
```javascript
this.mediaSourceOpen_ = () => {
// there is no media source, so it cannot be open
if (!this.mediaSource_) {
return Promise.resolve(false);
}
// MediaSource was previously open, but
// MediaSource.endOfStream() has been called
if (this.mediaSource_.readyState === 'ended') {
return …
```
=> fix: mitigate uncaught type error in media_source_engine

lib/media/media_source_engine.js, test/media/media_source_engine_unit.js
The VTT cue timing fix in https://github.com/shaka-project/shaka-player/pull/4217 seems to have caused a regression for videos without VTT streams, where the first segment would sometimes not play smoothly. It also appears to fix the gap jumping seen in the "Art of Motion (HLS, TS)" demo. This was partially fixed for fMP4 in https://github.com/shaka-project/shaka-player/pull/4553 but didn't fix the issue for MPEG-2 TS.
Fixes https://github.com/shaka-project/shaka-player/issues/4975.
=> fix(HLS): don't do sequence mode workaround unless there's a text stream

test/polyfill/media_capabilities_unit.js
Even though this was not causing any problem (afaik), not clearing the supportMap between tests could potentially lead to false positives, with some tests interfering in others. 
For example, if a test checks if the video contentType is supported by checking that it is contained in the supportMap, then even if a second test executed some bad code (or no code at all), and then did the same check, this second test would pass because the contentType would already be included in the supportMap from the previous test.
=> test: clear support map between tests

lib/hls/hls_parser.js, lib/media/media_source_engine.js, lib/media/segment_reference.js, lib/media/streaming_engine.js, test/hls/hls_parser_unit.js, test/test/util/fake_media_source_engine.js
This fixes an issue where discontinuities in segments mode overwrite the existing content. This is due to the internal timestamps of segments in different discontinuity sequences overlapping (the first segment in each discontinuity sequence has an internal timestamp starting at 0). To solve this, this PR tracks the start time of each discontinuity sequence as the segment reference's `timestampOffset`, and then adds logic to resync the sourcebuffer's `timestampOffset` to match these values.
=> fix(HLS): support discontinuities in segments mode

AUTHORS, CONTRIBUTORS, lib/media/media_source_engine.js, lib/util/manifest_parser_utils.js
The SampleEntry box in the SampleDescription (stsd) box will have the codingname 'dtse' for DTS Express audio tracks.
This is defined in Table E-1 of ETSI TS 102 114 V1.6.1 (2019-08) DTS Coherent Acoustics; Core and Extensions with Additional Profiles.
The 'dtse' codingname has been added to the AUDIO_CODEC_REGEXPS_ list, which enables support for playback of DTS Express in HLS fMP4 streams.
The 'ddts' and 'udts' entries have been removed from the AUDIO_CODEC_REGEXPS_ list, as these are not audio codec identifiers, but FourCC values for the DTSSpecificBox and DTSUHDSpecificBox, which can be found within the SampleDescription box for DTS audio tracks.
The DTSSpecificBox (ddts) is defined in Section E.2.2.3.1 of ETSI TS 102 114 V1.6.1 (2019-08) DTS Coherent Acoustics; Core and Extensions …
=> fix(HLS): Adding support for DTS Express in HLS fMP4 (#5112)

test/media/content_workarounds_unit.js
Adds simple test to ensure `fakeEncryption()` adds encv/enca box correctly.
=> test: add test for ContentWorkarounds

lib/ads/client_side_ad_manager.js
Previously, we would set the starting volume of an ad to 0 if the main video is muted.
This had the problem that, because of how our custom mute/unmute functionality on ads worked, that would lead to the "unmute" button setting the ad to the "last volume" of 0.
This changes the ads manager to, instead, set the volume of the ad to the volume of the video, and then call the mute function if the ad is muted. That way, the ad will remember the previous volume of the video, and will be able to unmute properly.
Closes #5125
=> fix(ads): Fix ads starting muted behavior

externs/network_information.js, externs/shaka/abr_manager.js, lib/abr/simple_abr_manager.js, lib/player.js, test/player_unit.js, test/test/util/simple_fakes.js
SimpleAbrManager was not properly destroyed after a call to player.destroy, leading to SimpleAbrManager instances being kept in memory.
This PR aims to resolve it :)
=> fix: prevent memory leak in SimpleAbrManager while destroying

lib/media/streaming_engine.js, lib/player.js, lib/util/periods.js, lib/util/stream_utils.js, test/cast/cast_utils_unit.js, test/media/streaming_engine_integration.js, test/media/streaming_engine_unit.js, test/player_unit.js, test/test/util/streaming_engine_util.js, test/util/stream_utils_unit.js
Relates to #4189
Fixes #5054 
Fixes #5055
Fixes https://github.com/shaka-project/shaka-player/issues/5150
=> fix: Fix temporarily disable streams on network error

lib/hls/hls_parser.js, lib/media/streaming_engine.js, test/hls/hls_parser_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/5076
=> fix(HLS): Fix support of fragmented WebVTT

lib/dash/dash_parser.js, lib/util/periods.js
Fixes an issue where `createSegmentIndex()` creates a reference in cached Stream and not on a new Stream. Now cached value is reused in period flattening.
Updated assertion in Period Combiner to catch potential issues within old approach.
Without this fix I've noticed problems around seeking on multiperiod content after variant change.
=> fix(DASH): Fix seeking on multiperiod content after variant change

docs/tutorials/drm-config.md, externs/shaka/manifest.js, externs/shaka/player.js, lib/media/drm_engine.js, lib/player.js, lib/util/error.js, lib/util/player_configuration.js, test/cast/cast_utils_unit.js, test/demo/demo_unit.js, test/media/drm_engine_unit.js, test/offline/storage_integration.js
Add capability to re-use persistent license sessions across sessions.
DrmEngine will now always:
- try to start stored persistent sessions before trying to fetch a license, as-to be able to check if all needed keys are already loaded.
- ask for a new license when the persistent session doesn't have the needed keys for playback,
Given the flag `persistentSessionOnlinePlayback` is true, DrmEngine:
- won't remove the persistent session from the device at the end of the playback,
- won't throw an error when the persistent session isn't found on the device,
For now, it needs Shaka's users to persist session information by themselves (localStorage, IndexDB, ...) before giving it back for the next session. Still, it lays foundation to develop the feature to fully handling it on Shaka's side. …
=> feat: allow reuse of persistent license sessions

lib/player.js, lib/util/mime_utils.js, test/player_unit.js, test/test/util/fake_drm_engine.js, test/test/util/simple_fakes.js, test/util/mime_utils_unit.js
=> fix: `config.streaming.preferNativeHls` only applies to HLS streams

lib/net/http_fetch_plugin.js
This makes it so that we no longer try to download the body of a head response, in the http fetch plugin. This is necessary due to an upcoming change to Chromium, where the body object of such responses is null.
Fixes #5164
=> fix(net): Fix HEAD requests in new Chromium

test/media/drm_engine_integration.js, test/test/util/test_scheme.js
Axinom's DRM servers started returning 403 errors for the Axinom v6 test vectors we use in our tests, and we were forced to switch to more stable and independent DRM servers for testing.
=> test: Drop Axinom DRM servers from tests

lib/util/periods.js
Fixed handling of manifest with new codecs in later periods by adding check for empty matchedStreams array in createNewOutputStrems()
Fixes #5183
=> fix:  PERIOD_FLATTENING_FAILED error with shaka 4.3.4 that did not occur with shaka 3.1.2 #5183 

test/media/drm_engine_integration.js, test/test/util/test_scheme.js
The padding on the base64-encoded content key was missing from the URL.  This did not show up until I tested on Tizen.
=> test: Fix PlayReady server URL syntax

lib/net/networking_engine.js
We should not look for response data in a HEAD request.
Fixes #5164
=> fix: Fix HEAD request exception

maintained-branches.md
The Cast Application Framework is adopting v4.3, which allows us to drop v3.2, and v3.3 LTS support ends at the end of April.
=> chore: Update maintained branches

lib/media/drm_engine.js
Fixes https://github.com/shaka-project/shaka-player/issues/5197
When pssh is provided in the manifest we do not need to parse in-band pssh even if the drm.parseInbandPssh setting is true.
Tested on an xbox one with some additional temporary logging the reported when in-band pssh is being parsed.
Tested with setting drm.parseInbandPssh=true (the default for XboxOne)
Verified that we DO NOT parse in-band pssh when pssh is present in the manifest
Verified that we DO parse in-band pssh when pssh is NOT present in the manifest
=> fix: unnecessary parsing of in-band pssh when pssh is in the manifest

lib/mss/mss_parser.js, lib/util/mp4_generator.js
This is part of the work to have our own transmuxers
=> feat: Allow generate segments with Mp4Generator

.github/workflows/demo-version-index.yaml, app-engine/demo-version-index/generate.py, app-engine/demo-version-index/templates/index.html
Due to limits in the number of versions you can have deployed at once on App Engine, we can no longer keep every version of the Shaka Player Demo deployed.  So the version index needs to be aware of which versions are deployed, and only link to versions that are still available.
This makes the index generator aware of App Engine deployments.
=> ci: Make version index aware of deployments

lib/hls/hls_parser.js, lib/media/media_source_engine.js, lib/transmuxer/muxjs_transmuxer.js, lib/util/mime_utils.js, test/hls/hls_parser_unit.js, test/player_integration.js
With this change, the manifest codecs are not filtered when using a raw format, now it is filtered only when necessary.
=> fix: Transmux containerless to the correct mimetype

lib/dash/segment_template.js
Similar to https://github.com/shaka-project/shaka-player/issues/4717 the same problem with broken `bufferBehind` occurs with the latest addition of `TimelineSegmentIndex`.
=> fix(DASH): fix bufferBehind broken by thumbnails with TimelineSegmentIndex

lib/media/media_source_engine.js, test/media/media_source_engine_unit.js
`createMediaSource()` sets `this.url_` for later revocation when the media source opens. However, `createMediaSource()` is called before the `url_` property is declared and initialised in the constructor. As result, `this.url_` actually get declared an initialised with the object URL in `createMediaSource()` and is later overwritten with an empty string in the constructor. This compromises the revocation logic as we end up always passing an empty string to `URL.revokeObjectURL()`.
To fix this, we make sure `this.url_` is declared and assigned default value in the constructor before any other class methods are called.
=> fix: media source object URL revocation

externs/shaka/manifest.js, externs/shaka/player.js, lib/dash/dash_parser.js, lib/hls/hls_parser.js, lib/mss/mss_parser.js, lib/offline/manifest_converter.js, lib/player.js, lib/util/periods.js, lib/util/stream_utils.js, test/dash/dash_parser_manifest_unit.js, test/media/adaptation_set_unit.js, test/offline/manifest_convert_unit.js, test/offline/storage_integration.js, test/player_unit.js, test/test/util/manifest_generator.js, test/test/util/streaming_engine_util.js
=> feat(DASH): Expose accessibility purpose in track

externs/pictureinpicture.js, ui/pip_button.js
The `initialAspectRatio` option was removed from the Document Picture-in-Picture spec in favour of `width` and `height`, so we should use them. See https://github.com/WICG/document-picture-in-picture/pull/36
=> fix: Document Picture-in-Picture: Use width/height instead of initialAspectRatio

AUTHORS, CONTRIBUTORS, lib/util/language_utils.js, test/util/language_utils_unit.js
Resolves #5222.
It also opens the way for improving the compliance with [RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646) in the future.
=> feat: Enhance Audio Language Switching

lib/media/media_source_capabilities.js, lib/media/media_source_engine.js, lib/media/streaming_engine.js, test/media/media_source_engine_integration.js, test/media/media_source_engine_unit.js, test/media/streaming_engine_unit.js
Thanks to https://github.com/shaka-project/shaka-player/pull/4766
This PR adds support for codec hot-switching in MediaSourceEngine. 
There are two ways to change codec:
- Using `Sourcebuffer.changeType` on supported browsers 
- Reloading the `MediaSource` instance with the new codecs
This change does not change the current filter logic, so this code is not used yet. The change in the filtering will be done in a subsequent PR in order to simplify the changes of this PR.
=> feat: Add support for changing codecs in MediaSourceEngine

.npmignore, package-lock.json, package.json
Before packaging for NPM, remove the "engines" section of package.json to avoid unnecessary restrictions on node versions for projects that simply depend on Shaka Player, but don't need to rebuild it.  This is accomplished with the clean-package tool: https://github.com/roydukkey/clean-package
The "engines" section and its restrictions still make sense for Shaka Player development, so it will not be removed from package.json in the repo.
Closes #5243
=> fix: Ship to NPM without node version restrictions

build/types/transmuxer, lib/transmuxer/aac_transmuxer.js, lib/transmuxer/adts.js, lib/transmuxer/muxjs_transmuxer.js, lib/util/mp4_generator.js, lib/util/platform.js, lib/util/player_configuration.js, shaka-player.uncompiled.js, test/media/media_source_engine_integration.js, test/transmuxer/muxjs_transmuxer_integration.js, test/transmuxer/transmuxer_integration.js
This transmuxer is used in Firefox due the lack of support for `audio/aac`
=> feat: Add AAC transmuxer

lib/dash/segment_list.js, lib/hls/hls_parser.js
This PR improve the parsing time for DASH and HLS changing when the uris of the segments are constructed. Now the uris are constructed on demand.
=> feat: Improve parsing time in DASH and HLS

lib/media/media_source_engine.js
With this change, we are changing the minimum timestampOffsetDifference to 0.1 to prevent unnecessary timestampOffset updates
=> fix: Avoid unnecessary timestampOffset updates when using HLS segments mode

lib/hls/hls_classes.js, lib/hls/manifest_text_parser.js, lib/util/manifest_parser_utils.js, test/hls/manifest_text_parser_unit.js
Related to https://github.com/shaka-project/shaka-player/pull/5261
This PR delays the creation of the final urls of the segments so that they are not calculated in each media playlist parsing.
=> feat(HLS): Improve HLS parsing time

lib/media/playhead.js, lib/media/video_wrapper.js
With this change the latency is reduced in 50ms approx. Very important for LL streams.
=> feat: Improve live latency on load

demo/main.js
Previously all config is passed to the player but some config parameters are untouched, we need only pass the config params that are different, to allow enable LL with only one change.
=> fix(Demo): Allow enable LL only with Low Latency Mode config

externs/pictureinpicture.js, ui/pip_button.js
Document Picture-in-Picture API owners are [removing `copyStyleSheets` option](https://github.com/WICG/document-picture-in-picture/pull/79) as it can be done in JavaScript. This PR removes this option and copy all style sheets internally to the PiP window.
Please review.
=> feat(UI): Remove copyStyleSheets

lib/hls/hls_parser.js
This happens because the last segment in an LL stream may not be complete and may not have EXTINF
=> fix(HLS): Fix live playlist update when using no LL in a LL stream

README.md
Not sure how I should propose this, But want to mention that https://github.com/shaka-project/shaka-player/blob/main/README.md#framework-integrations all mention here are wrappers. Which allows us to use it with specific framework or library. Whereas, https://limeplay.me is a React Library where everything has been made from scratch specifically for React. 
Should we rename and put others under the category of **Wrappers** and this under **Library**?
=> docs: Link to Shaka Player React UI Library

externs/shaka/manifest.js, externs/shaka/player.js, lib/dash/dash_parser.js, lib/dash/mpd_utils.js, lib/dash/segment_list.js, lib/dash/segment_template.js, lib/media/manifest_parser.js, lib/media/presentation_timeline.js, test/dash/dash_parser_manifest_unit.js, test/dash/dash_parser_segment_template_unit.js, test/test/util/manifest_generator.js
- Move TimeRange from shaka.dash.MpdUtils to shaka.media.PresentationTimeline
- Move AccessibilityPurpose from shaka.dash.DashParser to shaka.media.ManifestParser
With these changes, core Shaka Player can be built without the dash module.
=> chore: Fix core build without dash

lib/hls/hls_parser.js
According to https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-6.2.5 delivery directives are allowed for all live content
=> feat(HLS): Allow delivery directives in Live streams

demo/close_button.js, ui/pip_button.js
As noted in https://groups.google.com/a/chromium.org/g/blink-dev/c/JTPl7fM64Lc, we should use "pagehide" not "unload" JS event to monitor when PiP window gets closed.
=> fix(UI): Use pagehide instead of unload for PiP

lib/hls/hls_parser.js, lib/hls/manifest_text_parser.js
Fixes https://github.com/shaka-project/shaka-player/issues/5089
=> fix(HLS): Skip EXT-X-PRELOAD-HINT without full byterange info

lib/player.js
This error can happen with `online` window event
=> fix: Fix error when network status changes on src= playbacks

AUTHORS, CONTRIBUTORS, lib/player.js
Adding `safeMargin` as a parameter of the player `selectAudioLanguage` method so it is possible to customize the buffer value when changing tracks.
=> feat: Add safeMargin as a parameter of the player selectAudioLanguage method

lib/util/periods.js
=> feat: export period combiner

lib/media/media_source_engine.js
Preload segments do not have a defined duration, so this log may be wrong.
=> fix(HLS): Avoid "Possible encoding problem detected!" when is a preload reference

lib/media/segment_reference.js, lib/media/streaming_engine.js, lib/util/mp4_box_parsers.js
Stream used for test it: https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8
=> fix: Get the correct timescale when there are two trak boxes

.github/workflows/appspot.yaml
This is a much simplified version of the appspot job from the release workflow, but with control given to the human caller instead of computed from release details.  It can be used to correct deployment issues.
=> ci: Add one-off workflow for appspot deployment

lib/hls/hls_parser.js, test/hls/hls_live_unit.js
- Mark the the full segment as preload if it has some partial preload segment
- Request _HLS_part=0 when using LL-HLS byterange optimization
=> feat(HLS): Optimize LL-HLS with byterange

lib/hls/hls_parser.js
Some servers only support blocking playlist reload for a short time (example: 3 partial segment times). If we are using byte range optimization we must change the reload time to be that of a complete segment and avoid these problems.
=> feat(HLS): Support byterange optimization on servers with support to blocking playlist reload

lib/media/drm_engine.js, lib/util/periods.js
For manifests with many streams, we saw the bulk of the manifest parse time going towards period combiner. Specifically: splitting codecs and comparing DRMs. This change cuts our manifest parse time for large manifests by nearly 30%.
There are two changes:
1. Memoize the normalized codecs inside the period combiner.
2. Short circuit the DRM compatibility check if the DRMInfos arrays are the same object. We run a custom manifest parser and are therefore able to re-use the same drm infos array for functionally equivalent drms, but short circuiting also helps since in the case that the upstream period combiner is comparing a candidate stream with itself.
=> feat: Improve performance of multi-period DASH parsing

docs/tutorials/drm-config.md
This PR updates the DRM configuration tutorial.
The configuration code example is incorrect,  and also it suggests you can change the mapping, which is not true, you are only able to overwrite parts of it.
=> fix(docs): fix player configuration code in drm config tutorial

lib/dash/dash_parser.js, test/dash/dash_parser_manifest_unit.js
Add ColourPrimaries and MatrixCoefficients schemes as specified by https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf.
In particular, `ColourPrimaries` and `MatrixCoefficients` schemes are currently considered "unrecognizedEssentialProperty", causing some streams with valid manifests to discard the video track.
=> fix: Fix DASH rejection of streams with ColourPrimaries and MatrixCoefficients

lib/media/region_observer.js, lib/player.js, test/media/region_observer_unit.js
In some cases, in a livestream situation, the region observer's poll method ends up being called before the media time is set to the live edge. This does not happen every time; it's likely based on the exact time it takes the player to start playing. When this does happen, it leads to the region observer "skipping" over every region between time=0 and the live head, as it erroneously believes that it has actually played through all of that time. This could result in confusion for applications that are relying on region data.
This change modifiers the region observer so that it does not start examining regions until the time gets past 0 seconds, except in the case of VOD.
Closes #5213
=> fix(media): Fix region checking in livestreams
