ui/resolution_selection.js
With this change, when we are in src= mode we only leave the automatic mode in the resolution selector, since we will not be able to change the resolution.
Fixes https://github.com/shaka-project/shaka-player/issues/5330
=> fix(UI): Fix resolution selection on src=

lib/text/vtt_text_parser.js
This setting is used in https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8 (Apple HLS example)
=> fix(WebVTT): Add support to middle position

lib/media/media_source_engine.js
By reducing the number of promises in the Promises.all array we gain performance on low-end devices.
=> feat: Improve performance of setStreamProperties on low-end devices

lib/media/media_source_engine.js
We see a bunch of audio segments that probe as TS, and thus trigger warnings (and unnecessary work) in appendBuffer. There should never be an MP4 mime type that probes successfully as a TS, right?
[Here's an example](https://prod.cdn-vdms.philo.com/live/EDME-VIACOM-PARAMOUNT-EAST-V2-R1/audio/128000/4946379595054.isma) fmp4 that probes as a TS (ignore the isma file extension).
=> fix: Only parse/probe TS if the reference is not an MP4 and not WebM

lib/media/gap_jumping_controller.js, lib/media/playhead.js, lib/media/video_wrapper.js
Before playback starts the video element reports as seeking == true, but because we haven't installed our seek listener yet, the gap controller does not receive the seek event.
To work around this, we explicitly tell the gap controller when playback starts so that it knows the startup position, and can synthesize a seek event.
=> fix: gap jumping when gap exists at start position

lib/media/drm_engine.js
Different streams may share `drmInfo` references, which makes problem when `keySystemsMapping` config is used. Assuming we have config:
```js
drm: {
servers: {
'a.b.c': '...',
},
keySystemsMapping: {
'a.b.c': 'd.e.f',
},
}
```
on the first access to the `drmInfo` object `DrmEngine` will set server for `a.b.c` key system and replace key system to `d.e.f`. On the 2nd access DrmEngine will not find server config for `d.e.f` and thus will remove any server set.
This issue can be easily mitigated by deduplicating `drmInfo` array.
=> fix(DRM): broken keySystemsMapping due to multiple references of drmInfo

externs/shaka/manifest.js, lib/dash/dash_parser.js, lib/hls/hls_parser.js, lib/mss/mss_parser.js, lib/offline/manifest_converter.js, lib/player.js, test/dash/dash_parser_manifest_unit.js, test/media/playhead_unit.js, test/media/streaming_engine_integration.js, test/test/util/manifest_generator.js, test/test/util/streaming_engine_util.js
- Parse ServiceDescription from Manifest
- Use ServiceDescription for live syncrhonization
- I have added support for just one ServiceDescription. [Low Latency spec](https://dashif.org/docs/CR-Low-Latency-Live-r8.pdf) seems that it supports more than one. If this support is mandatory, how can I know which ServiceDescription should I use?
- I am executing onTimeUpdate when `this.manifest_.serviceDescription` OR `this.config_.streaming.liveSync`, should it be an AND?
=> feat(DASH): Add support for service descriptions

lib/media/drm_engine.js, lib/util/stream_utils.js, test/media/drm_engine_unit.js, test/util/stream_utils_unit.js
Propagate `preferredKeySystems` config to `getDecodingInfosForVariants()` method.
By doing that, shaka can only ask for `MediaKeySystemAccess` objects that will be used during playback.
If any preferred key system is available, player will stop requesting for MKSA.
If none of preferred key systems is available, player will try to get MKSA for any existing configuration, as usual.
=> feat(DRM): use preferredKeySystems to reduce requestMediaKeySystemAccess() calls

lib/util/error.js, test/test/boot.js
=> feat: Include stack trace in errors dispatched from production builds

lib/media/gap_jumping_controller.js
This change accounts for a gap jump at the start of an asset that lands the user user inside of another gap. The video element is still `paused` at this point, but we've moved past the `startTime` because we jumped a gap. Thus the gap jumper gets stuck, and playback will never start.
This seems like it should be a wild edge case, but we have some assets that reproduce it!
=> fix: Gap jump at start when first jump lands in a new gap

lib/hls/hls_parser.js, test/hls/hls_live_unit.js
The `_HLS_msn` directive must be the next media sequence number to block playlist reload. The actual logic uses the `EXT-X-MEDIA-SEQUENCE` plus the number of segments. However, a playlist may skip segments, so it should also consider `EXT-X-SKIP:SKIPPED-SEGMENTS`.
=> fix(HLS): Consider skipped segments to calculate next media sequence

lib/media/streaming_engine.js, lib/player.js, test/media/streaming_engine_unit.js
The 'metadata' event was introduced in v4.3, and ID3 metadata from 'emsg' boxes dispatched through that event was no longer dispatched through the more general 'emsg' events.
Now we will no longer exclude ID3 emsg boxes from the more general 'emsg' event.  This restores compatibility with Shaka v4.2.
=> fix: Dispatch all emsg boxes, even if they are ID3

build/conformance.textproto, lib/cea/mp4_cea_parser.js
Tizen 3 does not support Array.flat().  This fixes a runtime exception on Tizen 3 by replacing flat() with concat() and the spread operator. This also bans the use of flat().
flat() was originally introduced in PR #5422
=> fix: Fix exception on Tizen due to unsupported Array method

lib/polyfill/orientation.js, ui/controls.js
`screen.orientation.unlock` is not defined on Safari, even though `screen.orientation` is.
This changes our orientation polyfill to add that method to `screen.orientation`.
Fixes #5437
=> fix: Fix exiting fullscreen on Safari

.github/workflows/selenium-lab-tests.yaml, build/shaka-lab.yaml, docs/tutorials/selenium-grid-config.md, karma.conf.js
- In karma.conf.js, give ourselves the ability to merge Selenium configs together without clobbering argument lists, for better deduplication in shaka-lab.yaml.  This is based on https://github.com/shaka-project/karma-local-wd-launcher/pull/50
- Refactor shaka-lab.yaml to take advantage of this new ability.  This removes a bunch of duplicate command line arguments for various versions of Chrome.
- Remove a TODO about a bug that Chrome decided they would never fix.
- Sort the list of devices and platforms, with comments to mark out the sections.
- Remove IE11, which we are well past supporting or testing.
This should be cherry-picked to all active branches.
=> ci: Refactor and update Shaka lab definitions

.github/workflows/selenium-lab-tests.yaml, build/test.py
When we first deployed certificates from letsencrypt, we did not know about the "live" folder, which contains helpful symlinks to the latest certificate.  Instead, we were copying the entire "archive" folder, which contains even old certs, then searching that folder for the latest version.  We should be using the "live" folder instead, letting certbot maintain the symlinks.  This means there is no need for --lets-encrypt-folder in test.py.
=> test: Drop --lets-encrypt-folder from test.py

build/conformance.textproto, test/test/util/util.js
The test util for fetching small files should be based on fetch() instead of XHR.
=> test: Simplify fetch test util

test/media/segment_index_unit.js
We used to have a timeout of 1s, for a test that could theoretically complete in 0.3s.  However, on heavily-loaded test devices, this was failing on occasion.
Now, we just wait for completion with no timeout.  The default timeout of 120s per test will trigger if the test truly fails.
=> test: Deflake slow SegmentIndex test

test/test/util/ui_utils.js
Some UI tests would fail with a timeout during teardown.  This may indicate some condition in which player.destroy() could hang, though I have been unable to replicate that hypothetical condition in an explicit unit test.
Since that issue has nothing to do with the UI tests, set a 10-second timeout for UI teardown, after which we move on without a failure.
This also adds a check for container.parentElement before removing child elements, since at least once I saw an exception during test teardown from an element that was already removed from its parent by that point.
=> test: Deflake UI test teardown

.github/workflows/build-and-test.yaml, build/docker/Dockerfile
This PR adds Chromium with webdriver to the Docker image, so it's now possible to run at least some subset of tests using Docker env.
Additionally, Alpine version has been bumped up, so recent version of Chromium can be used.
=> ci: run tests in Docker

lib/util/manifest_parser_utils.js, lib/util/stream_utils.js, test/hls/hls_parser_unit.js, test/util/stream_utils_unit.js
These are the correct codec strings according to the specification:
1. https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.4.2
2. https://datatracker.ietf.org/doc/html/rfc6381#section-3.3
3. https://mp4ra.org/#/codecs
The first commit just cleans up some code a bit.
The second commit provides a workaround for https://bugs.chromium.org/p/chromium/issues/detail?id=1422728
The third commit adds support for fLaC and Opus codec strings in HLS.
Fixes: #5453
=> fix: Support fLaC and Opus codec strings in HLS

externs/shaka/manifest.js, lib/dash/dash_parser.js, lib/util/periods.js, test/util/periods_unit.js
When we exported `PeriodCombiner` in https://github.com/shaka-project/shaka-player/pull/5324 we added an `@export` to `PeriodCombiner.Period`, and since then we've been testing in our dogfood builds using shaka-player.compiled.debug, because we like to get logs from dogfood. Everything was working great.
When we went to switch over to the production build, we realized that `@export` on a `typedef` doesn't really work because the type gets minified internally!!
This PR moves `Period` over to `extern` so that it does not get minified and can be used externally.
=> fix: Typing of PeriodCombiner.Period was incorrect

lib/util/stream_utils.js
Set default language to `und` for native audio/text tracks if missing.
=> fix: Default language to 'und' for native tracks

test/player_integration.js, test/test/util/waiter.js
- Migrate waitUntilBuffered() into Waiter, which has better infrastructure for delayed events and debugging
- Expand delays before expectations are measured
=> test: Deflake player integration tests

build/shaka-lab.yaml, test/media/drm_engine_integration.js, test/media/streaming_engine_integration.js, test/mss/mss_player_integration.js, test/offline/offline_integration.js, test/player_external.js, test/player_integration.js, test/player_src_equals_integration.js, test/test/util/layout_tests.js, test/transmuxer/transmuxer_integration.js
Power-saving features on Chrome and Edge were subtly interfering with playback tests.  Timers could be throttled, and both video-only media and media in occluded windows could be paused by the browser.
This was discovered only after awaiting play() Promises in all tests. These Promises were being rejected with useful error messages that led to these discoveries.
Awaiting play() requires us to disable stall detection during playback tests.  This is because on some platforms, stalls get resolved by calling pause() and then play(), which would cause the original awaited play() Promise to be rejected.
Finally, some Player tests created additional Player instances that were unnecessary.  Removing those allowed me to centralize most of the configuration to disable stall detection.
=> test: Disable power-saving features on both Chrome and Edge

demo/autoTemplate.txt, demo/customWarning.txt, demo/main.js
This updates the bug template for the bug report button in the demo, to be closer to the current bug template.
It also adds the bug label, and makes it fill out the URIs of the asset playing in a more readable way.
Fixes #5056
=> feat(demo): Improve bug report button in demo

externs/ima.js, lib/ads/client_side_ad_manager.js, test/ads/ad_manager_unit.js
More info: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.ImaSdkSettings#setDisableCustomPlaybackForIOS10Plus
=> feat(Ads): Disable custom playback on iOS 10+ browsers for CC

lib/cea/cea608_memory.js, test/cea/cea608_memory_unit.js, test/cea/cea_decoder_unit.js
Related to https://github.com/shaka-project/shaka-player/issues/2940
=> feat(CEA): Add support to vertical position in CEA-608

test/player_integration.js, test/transmuxer/transmuxer_integration.js
This reduces test failures on Tizen from 7/10 to 1/30 test runs.
=> test: Deflake tests on Tizen

.github/workflows/build-and-test.yaml
GitHub started installing "Chrome for Testing" builds on Windows and Mac.  Unfortunately, these builds don't have support for H264 and AAC codecs, which we need in our tests.
This fixes the issue by explicitly installing an official build of Chrome on Windows, to overwrite the "Chrome for Testing" build.
=> ci: Fix Chrome tests on Windows in GitHub Actions

lib/mss/mss_parser.js, lib/transmuxer/aac_transmuxer.js, lib/transmuxer/ac3_transmuxer.js, lib/transmuxer/ec3_transmuxer.js, lib/transmuxer/mp3_transmuxer.js, lib/transmuxer/ts_transmuxer.js, lib/util/mp4_generator.js
This PR prepares the Mp4Generator to generate muxed content and also add support for generate HEVC content.
=> feat: Allow generate muxed content with Mp4Generator

lib/mss/mss_parser.js, lib/transmuxer/aac_transmuxer.js, lib/transmuxer/ac3_transmuxer.js, lib/transmuxer/ec3_transmuxer.js, lib/transmuxer/mp3_transmuxer.js, lib/transmuxer/ts_transmuxer.js, lib/util/mp4_generator.js
This prevent errors when the codec specified is not the same that in the stream, and also fixes the override when there are multiples codecs (eg: muxed content)
=> fix: Prevent codecs override in the transmuxer

.github/workflows/shaka-bot-commands/command-help.sh, .github/workflows/shaka-bot-commands/command-test.sh, .github/workflows/shaka-bot-commands/lib.sh, .github/workflows/shaka-bot-commands/main.sh, .github/workflows/talk-to-shaka-bot.yaml
Now maintainers can send commands to Shaka Bot via PR comments.
Initially, Shaka Bot understands the following commands from anyone:
- `@shaka-bot help`: Show this help message
And the following commands from maintainers only:
- `@shaka-bot test`: Start lab tests on all devices
- `@shaka-bot test ce`: Start lab tests on CE devices only (no desktop browsers)
=> ci: Talk to Shaka Bot

externs/shaka/transmuxer.js, lib/media/media_source_engine.js, lib/transmuxer/ts_transmuxer.js
Fixes https://github.com/shaka-project/shaka-player/issues/5572
The main problem is that the content has audio and video muxed and then has the alternative audio tracks.
We need to detect that the main content is muxed and only extract the video.
Test stream: https://ztnr.rtve.es/ztnr/1694255.m3u8
=> fix: Fix TS transmuxer when the main content is muxed

.github/workflows/release-please.yaml
This enables workflows to be triggered automatically on release PRs, instead of requiring maintainers to edit the PR description on every release to trigger required PR workflows.
This uses a separate token from the other shaka-bot token, because it requires additional permissions to make releases.
=> ci: Use shaka-bot for releases

.github/workflows/release-please.yaml
Stop using a fork to run release actions.  Either it is missing a feature or I misunderstood what that flag is for.  See https://github.com/google-github-actions/release-please-action/issues/819
=> ci: Do not use a fork for release actions

lib/player.js, lib/util/stream_utils.js
Preferred track selection was implemented differently for MSE and native playback. In fact, native playback even had different implementations for audio and text. It leads to inconsistencies during track selection, i.e. if track language contains locale, but language preference not, on MSE we're looking for closest locale and on src= we're making direct string comparison which leads to different results.
To unify that, both MSE and native will now use `StreamUtils.filterStreamsByLanguageAndRole()` to find matching track. This method is designed to use on `shaka.extern.Stream` but luckily it uses the very same fields as defined in `shaka.extern.Track` so we can use it without major changes.
Moreover, using this more robust method also allows us to get rid of double-selection workaround …
=> fix: fix preferred track selection on Safari

.github/workflows/release-please.yaml
In #5588 we switched off one part of using a fork for release PRs, but not every part.  That caused player.js not to be updated in release PRs, which broke NPM releases.
This fixes the issue by removing other references to the shaka-bot fork.
Closes #5599
=> ci: Fix version update in release workflow

.github/workflows/release-please.yaml
This avoids the implied "latest" tag being added to each and every release by adding explicit, branch-derived tags to each release, then setting "latest" explicitly based on the highest release number so far.
See https://github.com/shaka-project/shaka-player/issues/5599#issuecomment-1707047101
=> ci: Publish NPM tags explicitly

ui/language_utils.js
Reverts shaka-project/shaka-player#5365:  "feat(UI): Use Intl.DisplayNames to show the language name"
On the Google TV Chromecast just added to the lab, Intl.DisplayNames is returning the input as output again for some languages.  For example, instead of `en` => `English`, we get `en` => `en`.  Same for `fr`.  Oddly, it works for some others, such as `zh`.
We can follow up with a change that either avoids Google TV or that falls back to the internal map when Intl.DisplayNames returns its input as output.
=> fix(UI): Fix broken language names on Google TV

build/shaka-lab.yaml, package-lock.json, package.json
Specify the explicit path to microsoft-edge on Linux if found, to work around https://github.com/MicrosoftEdge/EdgeWebDriver/issues/102#issuecomment-1710724173
This also incorporates
https://github.com/shaka-project/webdriver-installer/pull/35, https://github.com/shaka-project/karma-local-wd-launcher/pull/60, and https://github.com/shaka-project/karma-local-wd-launcher/pull/62 to revert earlier workarounds and apply new ones for local test runs.
=> ci: Work around msedgedriver 115+ bug

lib/util/error.js
We declare shaka.util.Error to extend the native Error, but only supplied a message field in uncompiled and debug modes.  This broke the Jasmine test framework when it tried to extract error message information from a compiled-mode shaka.util.Error object.
Now we always supply a message object, and merely skip the fancy enum formatting in compiled mode.
=> fix: Fix compiled-mode error formatting

.github/workflows/deflake.yaml
Before we only tried to deflake nightly lab test runs, not manual lab test runs or PR tests.  This expands the use to all lab and PR tests.
=> ci: Expand deflaking to all lab test and PR test runs

lib/text/ttml_text_parser.js, test/text/ttml_text_parser_unit.js
Related to https://github.com/shaka-project/shaka-player/issues/2853
=> feat(TTML): Add support to tts:ruby

lib/hls/hls_parser.js, lib/media/streaming_engine.js, test/hls/hls_parser_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/5584
Fixes https://github.com/shaka-project/shaka-player/issues/5013
Fixes https://github.com/shaka-project/shaka-player/issues/5397
timestampOffset calculation is no longer necessary in the HLS parser because we introduce recently some change in MediaSourceEngine to calculate the timestampOffset
=> fix(HLS): Fix audio and video out of sync

lib/util/manifest_parser_utils.js
Chained use of maps and reduce on legacy devices reduces performance. So if there is only one url to generate we can optimize performance.
=> perf: Optimization to resolve uris

lib/text/vtt_text_parser.js, test/text/vtt_text_parser_unit.js
This reverts commit 56a4cea5789f15b5e78c9a5d8d0cb97eb542bafc.
Fixes https://github.com/shaka-project/shaka-player/issues/5661
=> revert: "fix(WebVTT): Fix wrong writing-mode in nested cues (#5641)"

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/5667
=> fix(HLS): Support AES-128 in init segment according the RFC

lib/util/ts_parser.js, test/util/ts_parser_unit.js
This is necessary because some Live streams change audio or video PID when there are ads.
=> fix: Allow PID change in TsParser

lib/transmuxer/ts_transmuxer.js
Fixes https://github.com/shaka-project/shaka-player/issues/5684
This PR fixes two issues:
- Fixes the duration of a video sample when there is only one pes packet.
- When there is muxed content, in some TS segments there is not audio but the audio is declared in the PMT, so we have to add silence frames
=> fix: Fix transmuxing of muxed content

lib/player.js, lib/util/state_history.js, test/cast/cast_receiver_integration.js
Do not dispatch statechanged events unless there is an actual change. This fixes a stack overflow in the Cast proxy code triggered by statechanged events.
=> fix: Fix unreleased stack overflow on statechanged

lib/media/segment_index.js, test/dash/dash_parser_segment_template_unit.js
=> fix: seeking in segment timeline returns incorrect index

.github/workflows/release-please.yaml, build/generateExterns.js, lib/player.js
lib/player.js was being updated separately because:
1. Originally, we didn't have support for updating arbitrary files with release-please.
2. When we did get that support in release-please, it would trash the "-uncompiled" tag we have in uncompiled mode.
By separating the uncompiled version string into two parts and using the extra-files feature of release-please, we can get the updater to preserve the "-uncompiled" tag and simplify the release workflow to only update the PR once per change instead of twice.
=> ci: Simplify release version updates

build/checkversion.py
The player version format changed to split the JS string into parts in PR #5724, but the version check for release workflows did not get a corresponding update, causing the npm release workflow to fail.  This fixes that.
=> ci: Fix player version check on release

.github/ISSUE_TEMPLATE/bug_report.md, CODE_OF_CONDUCT.md
The new email (shaka-player-maintainers@googlegroups.com) will direct issue reproduction information to a google group that includes core maintainers who are not part of Google proper, as opposed to the old email (shaka-player-issues@google.com) which was Google employees only.
=> chore: Switch to new issues email

lib/hls/hls_classes.js, lib/hls/hls_parser.js, lib/hls/hls_utils.js, lib/hls/manifest_text_parser.js, test/hls/manifest_text_parser_unit.js
Fix variable substitution in: AES-128 key and EXT-X-SESSION-DATA urls.
Fix to keep previous query params when using blocking playlist reload
Simplifies and unifies URL management to allow Content Steering in the future
=> fix(HLS): Fix url management in HLS

lib/util/manifest_parser_utils.js
This removes creating an array of arrays in manifest URI resolver and uses a nested loop to update an empty array instead
=> perf(manifest): avoid unnecessary looping in uri resolver

lib/util/periods.js
This change removes chaining awaits in period combiner when combining variants and parses streams in one loop instead of 4
=> perf(DASH): reduce looping and remove chaining awaits in period

lib/util/stream_utils.js
This change:
- drops incompatible variants for XBOX before parsing codes and checking them against media capabilities API
- avoids redeclaring variables each time in the loop
=> perf(Xbox): drop incompatible variants for XBOX early

lib/player.js, test/cast/cast_utils_unit.js, test/player_integration.js, test/player_unit.js
This method returns every thumbnail for a given image track ID, simplifying the process of determining how many thumbnails a given image track contains.
Closes #5781
=> feat(thumbnails): Add Player.getAllThumbnails

AUTHORS, CONTRIBUTORS, demo/config.js, externs/shaka/player.js, lib/hls/hls_parser.js, lib/util/player_configuration.js, test/hls/hls_parser_unit.js
=> feat(HLS): Add new config to get codecs from media segment for playlists without CODECS attribute

lib/dash/dash_parser.js
This change reduces the amount of loops in dash parser, and improves code readability, as checking config and creating an array of sets is in a separate method now.
=> perf(dash): improve readability and reduce number of loops in dash parser

lib/dash/mpd_utils.js
This change creates a separate method to get context nodes, and breaks from loops early if it finds the desired result
=> chore(DASH): move repetitive code to method, avoid full iteration if possible

lib/media/drm_engine.js
This change simplifies code that parses initData in the `getCommonDrmInfos` method
=> perf: simplify and improve performance of parsing initData when deduping

AUTHORS, CONTRIBUTORS, lib/util/object_utils.js
This change removes `Set` in favour of `WeakSet` to track seen objects while cloning for performance reasons
From MDN:
`
The number of objects or their traversal order is immaterial, so a WeakSet is more suitable (and performant) than a Set for tracking object references, especially if a very large number of objects is involved.
`
=> perf(utils): use WeakSet to track object references

lib/util/xml_utils.js
Related to https://github.com/shaka-project/shaka-player/issues/5804
=> fix: Allow parseXmlString when createNodeIterator is not available

lib/util/stream_utils.js
Fixes https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd
mp4 --> 12288/512 --> 24
webm --> 1000000/42000 --> 23.80952380952381
=> fix: Fix chooseCodecsAndFilterManifest for similar frameRate

lib/media/streaming_engine.js
This change causes the prefetch to be called much earlier, which improves latency in DASH streams in around 500ms.
=> feat: Improve latency in LL DASH streams

demo/common/asset.js, demo/common/assets.js, demo/custom.js
The removed functionality is no longer necessary since the HLS parser detect the correct codecs if a media playlist is used.
=> chore(Demo): Remove HLS tab and add extra tracks tab on custom assets

lib/util/player_configuration.js
This change fixes an issue on HiSense devices, where playback is sometimes repeated because current time is updated by skip on devices which don't support precise seeking
=> fix(hisense): set stallSkip to 0 for HiSense devices

lib/player.js
This fixes a bug introduced by the removal of the state graph that caused live content to start out at time=0, instead of at the live edge.
=> fix: Fix bug with live start time

lib/util/periods.js
- reduce number of iterations during filtering out stream duplicates
- reduce number of iterations when extending output stream
- for audio or video only content, reuse existing stream array instead of copying it
=> perf(DASH): PeriodCombiner optimisations

build/conformance.textproto, lib/util/buffer_utils.js, lib/util/fairplay_utils.js, test/util/buffer_utils_unit.js
Due to typo, banned call has been executed.
Fixes typo and adds support to `Uint16Array` in `BufferUtils`.
=> fix: ban new Uint16Array(buffer)

lib/dash/segment_template.js
This was introduced in #5061.
If `.release()` is called between the time `createUrisCb()` is created and when it's called, then `this.templateInfo_` is set to null, causing #5614 and #5760. The fix in #5619 may have been enough to fix or silence #5614, but it wasn't enough to fix #5760, which is the issue I'm having (at least I'm getting the same error).
Maybe @nrcrast can confirm this is the correct `this.templateInfo_.mediaTemplate` to pass to `createUris_()`? I don't fully understand the segment template (I have git bisected my way to find the issue). The initial PR draft for #5061 didn't actually have the race condition. It was introduced when [addressing](https://github.com/shaka-project/shaka-player/pull/5061/commits/e7971c16e258fe1aa96f6d80d57e9ab2bf6f8ef8#diff-c5ae94ade4937cab5320a …
=> fix(dash): fix race condition in segment template

externs/shaka/codecs.js, lib/media/media_source_engine.js, lib/transmuxer/ts_transmuxer.js, lib/util/ts_parser.js, lib/util/uint8array_utils.js, test/util/ts_parser_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/5666
Fixes https://github.com/shaka-project/shaka-player/issues/5797
=> fix: Fix nalu parsing and improve performance in the transmuxer

demo/config.js, externs/shaka/player.js, lib/media/drm_engine.js, lib/util/player_configuration.js
Closes https://github.com/shaka-project/shaka-player/issues/4572
=> feat: Add config to ignore duplicate init data

lib/cea/cea_decoder.js, test/cea/cea_decoder_unit.js
Fixes #5891 
In production, we are seeing the occasional SEI packet [`0x5b`], which is causing the parser to error. Using Mux.JS, this packet is ignored because it's not long enough to be a valid captions packet, so for feature parity it would make sense for the built in Shaka parser to also ignore.
=> fix: CEA decoder should return early if packet is not large enough

lib/util/platform.js
In testing Shaka on Orange S.A devices, we discovered these devices require encryption info in all init segments when content includes unencrypted and encrypted periods. 
This PR adds the Orange platform to `requiresEncryptionInfoInAllInitSegments`, so the the fake encryption workaround can be applied. Resolves: https://github.com/shaka-project/shaka-player/issues/5894.
=> fix: Add Orange platform to requiresEncryptionInfoInAllInitSegments

lib/player.js
Fixes https://github.com/shaka-project/shaka-player/issues/5115
=> fix: Allow get seekRange on manifestparsed event in some cases

demo/common/assets.js, demo/search.js
Related to https://github.com/shaka-project/shaka-player/issues/5704
=> feat(Demo): Add Content Steering assets

lib/media/streaming_engine.js
Note: this happens with LL only.
=> fix: Only append to the buffer init segments when the segment is independent

lib/dash/dash_parser.js, lib/util/content_steering_manager.js, test/dash/dash_parser_live_unit.js
According to https://github.com/Dash-Industry-Forum/Dash-Industry-Forum.github.io/files/11722876/DASH-IF-CTS-001-1.0.0.pdf, Location elements can have serviceLocation, so we need support it.
=> feat(DASH): Add support for location in Content Steering

lib/media/segment_reference.js
With the introduction of Content Steering the URLs may change order, but the segment is the same
=> fix: Fix init segment comparison

lib/cea/cea708_service.js, lib/cea/cea708_window.js, test/cea/cea708_service_unit.js, test/cea/cea708_window_unit.js, test/cea/cea_decoder_unit.js, test/test/util/cea_utils.js
CEA708 captions have positioning data available in their windows. However, this isn't currently translated and exposed by shaka though it is parsed from the bitstream.
Translates the windows into WebVTT regions and uses the mappings outlined https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html#positioning-in-cea-708
This is also partially implements #2583.
=> feat: expose CEA708 window position in the cue's region

ui/presentation_time.js
Fixes https://github.com/shaka-project/shaka-player/issues/5765
=> fix(UI): Correctly display video time and duration for VOD

CONTRIBUTORS, lib/text/ui_text_displayer.js
CEA708 captions may set windows in LINE units, this needs to be converted to percentages to be properly displayed. In addition, adjust by the region anchor.
=> fix: Properly size region anchor from LINE units

lib/hls/hls_parser.js
Fixes https://github.com/shaka-project/shaka-player/issues/5959
=> fix(HLS): Provide a fallback to GET request when HEAD request fails

lib/net/networking_utils.js
Fixes https://github.com/shaka-project/shaka-player/issues/5959
=> fix: Provide a fallback to GET request when HEAD request fails

docs/tutorials/fairplay.md
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST states
> `application/x-www-form-urlencoded`: the keys and values are encoded in key-value tuples separated by '&', with a '=' between the key and the value. Non-alphanumeric characters in both keys and values are [URL encoded](https://en.wikipedia.org/wiki/URL_encoding): [...]
however, the current documentation also encodes `=`, like so:
`encodeURIComponent('spc=foobar') === 'spc%3Dfoobar'`
instead, the values (and strictly also keys, but they don't contain anything special, so no need) should be encoded separately.
this pr fixes this.
maybe there is some drm quirks why it was like that, otherwise this should be a bug.
let me know if I'm missing something!
=> docs: fix use of encodeURIComponent() in fairplay tutorial

lib/media/segment_prefetch.js
A recent change made it always log that segments were re-used, but in reality there were times when they were missed. Uses the language from the original PR
=> fix: log prefetch miss for missing segments

AUTHORS, CONTRIBUTORS, lib/text/ui_text_displayer.js, test/text/ui_text_displayer_unit.js
Currently an instance of `uiTextDisplayer` is not idempotent, crashing if `uiTextDisplayer.destroy()` is called more than once:
```javascript
const uiTextDisplayer = new shaka.text.UITextDisplayer(
videoElement,
subtitlesElement
);
uiTextDisplayer.destroy();
uiTextDisplayer.destroy();
```
This is due to `videoContainer.removeChild` being called with `null` parameter on the second interation, as `textContainer` was already deleted on the first one.
Source: https://github.com/shaka-project/shaka-player/blob/9f5e46190ca00b1df36d5210852962bb52aac0c4/lib/text/ui_text_displayer.js#L158
An early return will prevent this crash, maintaining consistency with other methods.
Already created an issue for this bug at: https://github.com/shaka-project/shaka-player/issues/6023
=> fix: avoid uiTextDisplayer.destroy crashing if called more than once

lib/util/mp4_generator.js
This change removes `concat` util function from mp4 generator iterations and runs it later, as well as stops creating new Uint8 arrays, as `concat` does this within itself.
=> perf(mp4generator): stop nesting concat in methods

lib/util/platform.js
A simillar to this PR raised last year - https://github.com/shaka-project/shaka-player/pull/4310. 
The APL devices also belong to Liberty Global and are Webkit-based. We noticed that these devices are being detected incorrectly as Apple - `Platform.isApple()`, and as such, the source equals `shouldUseSrcEquals_` is selected instead of MSE. The native playback is not working as expected, and MSE is preferred on these devices
=> fix: APL set-top box wrongly identifies as an Apple device.

demo/main.js
This occurs on a 6th generation iPod touch with iOS 12.
=> fix(Demo): Allow play MP4 and TS in legacy iOS devices

lib/util/periods.js
Fixes https://github.com/shaka-project/shaka-player/issues/6010
=> fix(DASH): Fix bad error on DASH DAI

ui/controls.js
Closes https://github.com/shaka-project/shaka-player/issues/6040
=> feat(UI): Disable forward and rewind with arrows while seekbar not active

lib/dash/dash_parser.js, lib/util/periods.js, test/util/periods_unit.js
Summary of changes:
- create dummy streams during preparing arrays of input streams
- use hash map to quickly find perfect stream matches across periods
- hash map also automatically removes duplicates, so remove previous logic for finding them
- check earlier are we trying to create output stream from dummy stream
- 2 changes from above also gives us a possibility to simplify `areCompatible()` & `isBetterMatch()` methods
- reduce creation of spare collections when concatenating streams
- reduce conditional logic when possible
I was testing `PeriodCombiner.combinePeriods()` performance of mentioned changes on Tizen 2021 on 2 streams and I've got following results:
| content | upstream | proposed changes |
| - | -: | -: |
| stream 1 | 23 ms | 17 ms |
| stream 2 | 484 ms | 191 ms |
Both …
=> perf: PeriodCombiner improvements

lib/polyfill/patchedmediakeys_apple.js
This reverts commit 5b5b2ce1746ea888e163dddb3d36125f03100102.
Due to: https://github.com/shaka-project/shaka-player/commit/b1e5063cb8f17747bad40836c3c612224e2811a5#commitcomment-136674454
=> revert: Install by default shaka.polyfill.PatchedMediaKeysApple when there is no unprefixed EME support

lib/cea/cea608_memory.js, lib/cea/cea_decoder.js, test/cea/cea_decoder_unit.js
Due to issue around channel calculation, shaka was never using CC4 track and data from there were landing in CC2 track.
=> fix: fix handling of multiple CC tracks

lib/hls/hls_utils.js
Filtering all the tags to get the first one that's required is not needed
=> perf(HLS): do not filter all tags to get the first tag

externs/shaka/manifest.js, lib/media/segment_index.js
Motivation: we (Sky/Peacock) were working on custom manifest parser and we wanted to use similar approach to `shaka.dash.TimelineSegmentIndex` but adjusted to our needs and data structure.
So similar to that, we extended base `SegmentIndex` class with our implementation, but `MetaSegmentIndex` didn't work correctly with this implementation due to 2 issues:
1. `MetaSegmentIndex` uses protected `numEvicted_` field that we cannot modify externally in any way.
2. Even adding exported `getNumEvicted()` method wasn't enough, because Closure Compiler optimization was aliasing internal call to this method in `MetaSegmentIndex` for some reason.
By moving crucial APIs to extern we can overcome this issue. Still, preferred way of using own SegmentIndex implementation is by extending base class, as …
=> feat: SegmentIndex minimal interface

demo/config.js, externs/shaka/player.js, lib/dash/dash_parser.js, lib/util/periods.js, lib/util/player_configuration.js
In our streams we have guarantee that every track will have a single match in every period. This change allows `PeriodCombiner` to take benefit of this knowledge.
I was testing `PeriodCombiner.combinePeriods()` performance of mentioned changes on Tizen 2021 on 2 streams and I've got following results:
| content | upstream | proposed changes |
| - | -: | -: |
| stream 1 | 17 ms | 12 ms |
| stream 2 | 191 ms | 98 ms |
Both streams are VOD.
Stream 1 has 18 periods with 6 video & audio tracks in each.
Stream 2 has 18 periods with 6 video tracks & 36 audio tracks in each.
=> feat(DASH): Allow PeriodCombiner for using streams once

lib/player.js
Fixes https://github.com/shaka-project/shaka-player/issues/5944
=> fix: auto cancel trickPlay on live as specified

lib/media/media_source_engine.js, test/media/media_source_engine_unit.js
When stream is paused and codec switch is done, stream resumes to play. Moving setting autoplay from `canplay` to `canplaythrough` fixes this issue.
Problem observed on Tizen 6 & 7.
=> fix: stay paused after codec switch

lib/media/streaming_engine.js
Do not retry MSE errors on startup to avoid masking errors when the stream loads
=> fix: Don't retry MSE errors on startup

AUTHORS, CONTRIBUTORS, ui/externs/ui.js, ui/play_button.js
Fixes https://github.com/shaka-project/shaka-player/issues/6125.
=> fix: add missing properties to PlayButton type

externs/shaka/player.js, externs/shaka/text.js, lib/media/media_source_engine.js, lib/text/text_engine.js, lib/util/player_configuration.js, test/demo/demo_unit.js, test/media/media_source_engine_unit.js, test/text/text_engine_unit.js
This callback gives developers a chance to modify cues after they are parsed but before they are appended.
=> feat(text): Add MediaSource.modifyCueCallback

AUTHORS, CONTRIBUTORS, lib/polyfill/media_capabilities.js, lib/util/stream_utils.js
A regression got introduced in version `4.2.7` where audio.codecs got rewrite (ref: https://github.com/shaka-project/shaka-player/pull/4858) with the corrected audio codecs.
After this change, the player tries to play the audio stream with codec EC-3 instead of AC-3 (the original value provided by the manifest representation) due to the current implementation of supporting AC-3 on Tizen.
Delegating the check from ac-3 to ec-3 in `stream_utils` to the actual media capabilities polyfill so that when a system is requesting the support of `AC-3` audio codec on Tizen, we change the capabilities to `EC-3` and let it do its check.
This completes the work on 🐛  https://github.com/shaka-project/shaka-player/issues/6160.
It was tested locally on a real Samsung TV (Tizen 5.0) in our internal project …
=> fix: AC-3 audio codec support on Tizen

demo/config.js, externs/shaka/player.js, lib/media/segment_index.js, lib/media/segment_prefetch.js, lib/media/streaming_engine.js, lib/util/player_configuration.js, test/media/segment_prefetch_unit.js, test/media/streaming_engine_unit.js, test/test/util/fake_segment_prefetch.js, test/test/util/streaming_engine_util.js
Implements the behavior outlines in #6128.
Adds `streaming.prefetchAudioLanguages` and `streaming.disableVideoPrefetch` options.
Does not currently have `disableAudioPrefetch` and `disableTextPrefetch`.
=> feat: prefetch audio languages.

demo/main.js, lib/media/drm_engine.js, lib/offline/storage.js, lib/util/player_configuration.js, test/dash/dash_parser_content_protection_unit.js
`com.adobe.primetime` is not implemented in any browser and no one has reported any problems in the 8 years of Shaka Player.
=> feat!: Remove com.adobe.primetime keysystem

lib/util/tXml.js, test/util/tXml_unit.js
It would appear that the previous `textContent` api transformed html entities. This PR provides feature parity with the DOMParser approach.
=> feat: Escape html codes when getting node contents

docs/tutorials/ui-customization.md, ui/externs/ui.js, ui/less/range_elements.less, ui/seek_bar.js, ui/ui.js
re-open: https://github.com/shaka-project/shaka-player/issues/3597
=> revert: Add chapter titles and dividers on the seek bar

README.md, demo/common/assets.js, demo/config.js, docs/tutorials/upgrade.md, externs/shaka/player.js, lib/player.js, lib/util/player_configuration.js, test/hls/hls_parser_integration.js, test/player_unit.js, test/transmuxer/transmuxer_integration.js
Our HLS implementation is stable and robust enough that we can enable it by default.
=> feat!: Prefer MSE HLS over native HLS in Apple platform when not encrypted

package-lock.json
gitpkg.now.sh dependencies started to have broken SHA for some reason which breaks CI infrastructure here & in our fork.
=> fix: Fix gitpkg.now.sh dependencies

build/shaka-lab.yaml
shaka-lab-hub reports:
```
/wd/hub/session java.io.IOException:
org.openqa.grid.common.exception.GridException:
Cannot extract a capabilities from the request:
```
Generally, there should be a request object after this, but here it is blank.  It's not clear why or how this could be. There are no errors from shaka-lab-node on Windows.
=> ci: Temporarily disable Edge on Windows in the lab

build/shaka-lab.yaml
By specifying the binary path and also merging https://github.com/shaka-project/shaka-lab/pull/47, we are able to restore Edge on Windows in the lab.
=> ci: Restore Edge on Windows in the lab

package-lock.json, package.json
This updated version of karma-local-wd-launcher incorporates https://github.com/shaka-project/karma-local-wd-launcher/pull/65 to supply a path to the Edge binary on all platforms.  This fixes local testing and GitHub CI testing of Edge.
Though the tests run once more, there are still some test failures that need to be dealt with.
=> ci: Fix Edge launcher for local testing and GitHub CI

demo/config.js, externs/shaka/player.js, lib/media/streaming_engine.js, lib/util/player_configuration.js
Increases the default required removal duration from `0.01` => `1.0`.
Closes #6240.
=> feat: add an option specifying when source buffer removals happen

lib/player.js, test/player_unit.js
This method should be called after the load is successful, not if the load fails.
This also adds a new test that ensures that onKeyStatus_ messages work correctly, as a regression test.
This was exposed by the test failures, but was not the cause of them.
Issue #6225
=> fix(preload): Fix timing of call to stopQueuingLatePhaseQueuedOperations

lib/hls/hls_parser.js
The `constructSegmentUris` util already returns an array, so the call to `makeRequest` was being made with an array of arrays. This wasn't causing errors for requests that use the `fetch` plugin, since `fetch` will stringify the first argument if it's an array. But the data URI plugin expects to receive a string and calls `.split()` on it, so keys using data URIs throw an error if the URI is wrapped in an array.
Thanks to https://github.com/shaka-project/shaka-player/pull/6243 and @andrew0
=> fix: don't double wrap URIs for HLS key requests

externs/shaka/player.js, lib/util/cmcd_manager.js, lib/util/player_configuration.js, test/util/cmcd_manager_unit.js
This PR adds the ability to filter/limit the amount of data transmitted when CMCD is enabled. It matches the functionality provided in [`dash.js`](https://github.com/Dash-Industry-Forum/dash.js/blob/9e3da3cb35da71d339444158db359bfec63035a0/src/core/Settings.js#L712-L713) and [`hls.js`](https://github.com/video-dev/hls.js/blob/dfb384dc765f400ea3d401b790cfc4d53a44410f/src/config.ts#L70-L75) and addresses concernes raised by video providers:
https://github.com/cta-wave/common-media-client-data/issues/122
=> feat: add includeKeys to CMCD config to allow filtering of CMCD data

AUTHORS, CONTRIBUTORS, lib/util/stream_utils.js
When constructing the MediaDecodingConfigurations to query media capabilities in `stream_utils.js`, the spelling of "fLaC" should not change to "flac" on Safari. This is because on Safari the query will return `supported: false` for "flac" but `supported: true` for "fLaC".
This change allows manifests with "fLaC" codecs to work properly on Safari when using MSE / Managed Media Source.
Fixes #6249
=> fix: Fix detection of flac support on Safari

lib/util/periods.js, test/util/periods_unit.js
If available streams differ only by label, PeriodCombiner does not take it into account when looking for the best candidate. Due to that streams from newly arrived periods will create new audio tracks, as existing streams match always with firstly found stream from new period.
Issue has been mitigated by recent PeriodCombiner improvements, as label has been used for hash generation. But if hash don't match i.e. due to bandwidth change, issue would still appear.
I haven't added similar check for video streams because I'm not sure what should be the precedence of it. If any suggestions, I'm happy to add it as well!
=> fix(DASH): Use labels to stitch streams across periods

lib/dash/segment_template.js, test/dash/dash_parser_segment_template_unit.js
When recalculations of period end are made, it is possible that we will not be able to find last segment from period on low precision platforms. To mitigate it, try to use cached value of `periodEnd_` whenever possible.
Issue observed on Xbox One & Xbox Series.
=> fix(DASH): Fix precision issue on some platforms

lib/polyfill/mediasource.js
Although Chromecast natively supports TS content, it does not work in all cases.  In particular, we have some sample live streams where some TS segments can be parsed by external tools as valid TS, but cause the Chromecast to throw a parsing error.
We should reject TS content on Chromecast, and allow the builtin transmuxer to take over parsing.
This also removes the use of `cast.__platform__.canDisplayType` to patch MediaSource.isTypeSupported on Chromecast.  Current versions of Shaka Player are doing very rough filtering with isTypeSupported before calling MediaCapabilities.decodingInfo.  And our MediaCapabilities polyfill calls `cast.__platform__.canDisplayType` directly, bypassing any polyfill we might install on isTypeSupported.  So there is no longer any purpose to canDisplayType in …
=> fix(Cast): Force TS content to be transmuxed on Chromecast

lib/player.js, test/player_load_graph_integration.js
Interrupting load() was causing two concurrent sets of load() operations to happen at once, which led the asset URI for the second operation to be overwritten by the first.
This was exposed by a test failure on Safari.  There is nothing special about Safari, but the timing happened to work out such that the concurrent load() calls would intefere with each other.
This fixes the issue by acquiring the mutex in load() for the preloadManager.start() operation.
This issue did not affect any releases.
Closes #6225
=> fix(preload): Fix load interruption

.github/workflows/shaka-bot-commands/lib.sh, .github/workflows/shaka-bot-commands/main.sh, .github/workflows/talk-to-shaka-bot.yaml
- Fix wrong index variable in loop ("i" vs "INDEX") that prevented detection of commands at arbitrary places in a comment.
- Fix parsing of comments with newlines.
- Normalize commands to lowercase before checking them.
- Enhance debugging of command parsing.
- Allow the user to say "please" because it just feels nicer to me, even when I'm talking to a robot.
=> ci: Tweak command parsing

test/transmuxer/transmuxer_integration.js
My previous fix only affected one H265 test, not both.
I also found some maximum versions in exclusions around AC3/EC3, and removed those, as the issue is still not fixed in Chrome and there is no way to predict when it will get fixed.  I would rather not increment that number after every new Chrome release.
=> test: Exclude all H265 tests for Chrome+Windows

test/hls/hls_parser_integration.js, test/transmuxer/transmuxer_integration.js
Whatever was wrong seems to be fixed in `main`, so we can restore these tests.
Closes #5834
=> test: Restore disabled tests on Edge

lib/media/manifest_parser.js, lib/util/error.js, test/player_unit.js
A test suite that overwrites the HLS parser needs to restore it afterward.  To aid in debugging future parser issues, this adds the detected or specified MIME type to the error object for UNABLE_TO_GUESS_MANIFEST_TYPE.
Closes #5834
=> test: Fix missing HLS parser in tests

test/media/streaming_engine_unit.js
When overwriting any part of the library or platform in a test, we must restore it afterward.
This fixes two test suites that overwrote SegmentPrefetch with a test fake, but never restored the original.
This fixes failures in unrelated preload tests running in uncompiled mode.
Closes #6275
=> test: Fix prefetch test fake pollution

docs/tutorials/upgrade.md, lib/dash/content_protection.js, lib/dash/segment_base.js, lib/dash/segment_list.js, lib/dash/segment_template.js
To provide feature parity with the `DOMParser.getAttribute` API which would unescape html entities for free this PR unescapes url strings which come from node attributes.
In a similar vain to https://github.com/shaka-project/shaka-player/pull/6198 which unescapes child strings.
=> fix(tXml): html unescape node attributes with urls

lib/ads/ad_manager.js, lib/deprecate/deprecate.js, lib/media/manifest_parser.js, lib/player.js, lib/util/ts_parser.js
Some deprecation messages were misleading, and claimed that entire classes like AbrManager were deprected, when in fact, it was a particular form of AbrManager (without a method) that is deprecated.
This adds method and other details to the deprecation calls where needed.
We also had a malformed messsage where join('') was called on the pieces instead of join(' ').  This fixes the formatting.
=> chore: Fix deprecation messages

lib/media/drm_engine.js, lib/util/manifest_parser_utils.js
This is a preliminary step to be able to support HLS identity without the user configuring clearkeys.
=> chore: Add createDrmInfoFromClearKeys and simplify DrmEngine

.github/workflows/appspot.yaml, .github/workflows/build-and-test.yaml, .github/workflows/demo-version-index.yaml, .github/workflows/nightly-demo.yaml, .github/workflows/release-please.yaml, .github/workflows/report-incremental-coverage.yaml, .github/workflows/selenium-lab-tests.yaml, .github/workflows/sync-labels.yaml, .github/workflows/talk-to-shaka-bot.yaml, .github/workflows/update-issues.yaml, .github/workflows/update-screenshots.yaml
This eliminates warnings about outdated node runtimes in GitHub Actions.
actions/download-artifact and actions/upload-artifact are the only ones with any potential breaking changes, and adjustments have been made and tested.
See https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
=> ci: Update all actions

.github/workflows/custom-actions/set-commit-status/action.yaml, .github/workflows/selenium-lab-tests.yaml, .github/workflows/update-screenshots.yaml
- Link CI status to specific jobs, not just the run
- Split selenium job status flag away from ignore_test_status (which is for getting screenshots)
- Remove redundant status setting step in update-screenshots
- Fix final status computation in update-screenshots to account for edge cases and old typo
=> ci: Improve CI status setting

.github/workflows/appspot.yaml, .github/workflows/demo-version-index.yaml, .github/workflows/nightly-demo.yaml, .github/workflows/release-please.yaml
I missed some before.  I only updated actions from GitHub "actions/..."
This updates all other actions except google-github-actions/release-please, which has some breaking changes we would need to absorb and test.
=> ci: Update more actions

demo/demo.less
Each tab in the demo config had a max height of 1000px. That was not a problem previously, but the "streaming" config now has so many config values that it no longer fits into that limit. This PR removes that limit, by instead setting a max-height value of "fit-content".
Unfortunately, doing that seems to break the open/close animation of the tabs, and makes it look kind of bad, so this also removes the animation entirely; it's better to have no animation than an ugly one.
=> fix(demo): Remove max height of demo config tabs

lib/cea/cea608_memory.js, test/cea/cea608_memory_unit.js, test/media/media_source_engine_integration.js
Ensure whitespace rendered in CEA-608 test streams instead of `⠀` (braille pattern blank).
Updated UT too, but avoiding this char at ends of the string hence vulnerable to trim() 🤦 
Fixes #6328
=> fix: Fix cea608 whitespace rendering

lib/text/vtt_text_parser.js, test/text/vtt_text_parser_unit.js
This moves VTT sequence mode offset calculations into a method.
It also makes all X-TIMESTAMP-MAP usage dependent on HLS specifically, rather than sequence mode, simplifying the conditions.  Sequence mode is typically only used with HLS, and X-TIMESTAMP-MAP is explicitly only for HLS.  So excluding X-TIMESTAMP-MAP for DASH makes sense, instead of conflating HLS and sequence mode.
This required updating some tests to explicitly set both the manifest type and sequence mode flag.
This does *not* change the offset calculations themselves.  Changes will be made in follow-up PRs.
Issue #6320
=> refactor: Move sequence mode VTT offset calculations

lib/media/segment_reference.js, lib/media/streaming_engine.js
This is useful when creating custom manifests, which are actually a single segment. For example, a custom AAC manifest or any other audio format.
=> feat: Add segmentData info to SegmentReference

lib/cast/cast_proxy.js, lib/cast/cast_sender.js, test/cast/cast_proxy_unit.js, test/cast/cast_sender_unit.js
CastProxy's getInitState_() pauses the local video as part of a transfer of state to the receiver.  Calling getInitState_() (via  CastSender's onInitStateRequired_()) should be deferred until we establish a connection.  This keeps the local video from pausing during a connection attempt.
Closes https://github.com/shaka-project/shaka-player/issues/6293
=> fix(Cast): Don't pause local video until the cast connection is established

externs/shaka/player.js, lib/hls/hls_parser.js, lib/util/player_configuration.js, test/demo/demo_unit.js
This new configuration value allows the HLS parser to selectively ignore EXT-X-PROGRAM-DATE-TIME tags on some streams while honoring him for other streams.
=> feat(HLS): Add ignoreManifestProgramDateTimeForTypes

lib/hls/hls_parser.js, lib/media/presentation_timeline.js, lib/player.js, test/player_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/5939
=> fix(HLS): getPlayheadTimeAsDate() differs from X-EXT-PROGRAM-DATE-TIME

lib/media/segment_utils.js, lib/util/ts_parser.js
This detection is necessary to be able to correctly detect whether a media playlist of HLS that has TS segments is compatible or not.
Example: https://raw.githubusercontent.com/obecny/hls-opus-testing/main/stream.m3u8 (media playlist with Opus)
=> fix: Add Opus and AV1 detection in TS

lib/media/media_source_engine.js, lib/polyfill/mediasource.js
Related to https://github.com/shaka-project/shaka-player/issues/6334
Related to https://github.com/shaka-project/shaka-player/issues/6320#issuecomment-1979835203
Also reverts https://github.com/shaka-project/shaka-player/pull/6045 since now it is not necessary
=> fix: Reject TS content on all platforms and transmux always

AUTHORS, CONTRIBUTORS, ui/controls.js, ui/externs/ui.js, ui/ui.js
Closes https://github.com/shaka-project/shaka-player/issues/6376
=> feat(UI): Add config for refreshTickInSeconds

lib/player.js
=> fix: Looser tolerance for ending trick play at edge of seek range.

lib/media/streaming_engine.js
This reverts #4886, which was found to cause issues with fetching segments after seeking.
Closes #5785
Re-open #4589
=> revert: Fix potential AV sync issues after seek or adaptation

lib/media/playhead.js, test/media/playhead_unit.js
Use recurring timer to correct playhead when time is beyond seekRange.
Fixes https://github.com/shaka-project/shaka-player/issues/5202
=> fix: Correct playhead when seek beyond seekRange

lib/ads/client_side_ad_manager.js
When using customPlayheadTracker the content of video could have been replaced by the advertisement (case of SmartTVs where only one video element is supported at a time), so we want to prevent actions from being taken on the advertisement.
=> fix(Ads): Fix ad pausing when using customPlayheadTracker

demo/config.js, externs/shaka/player.js, lib/ads/client_side_ad_manager.js, lib/util/player_configuration.js
This configuration solves problems with some devices not being able to play a pre-roll.
=> feat(Ads): Skip play detection in some devices

test/codec_switching/codec_switching_integration.js
The tests were not testing what they were supposed to because their configs were invalid and being ignored.
Related to #6458
=> test: Fix codec-switching test config

test/media/media_source_engine_unit.js
The tests for MediaSourceEngine codec switching were written to ignore types and suppress access controls.  The were unreadable, too, with very little whitespace, confusing one-letter variable names, and difficult-to-follow event mocking.  This made it more difficult to debug test failures in PR #6460.
This rewrites the tests in a more readable manner with compiler enforcement of types in the tests.  Two helper functions are used to isolate the necessary access-control suppressions.
This exposed a bug in the tests, in which one test case (preserve SourceBuffer attributes) only passed because the original version failed to await on an async process.  I am not sure that the functionality in that test exists at that level.  For now, the test is disabled.  I'll follow up with removal after …
=> test: Rewrite MediaSourceEngine codec switching tests

lib/util/platform.js, test/util/platform_unit.js
webOS platforms don't contain OS version explicitly in user agent, instead they signal it via chrome version. This PR fixes webOS 4 & 5 methods and unifies all webOS check methods.
=> fix: Fix webOS 4 & 5 utility methods

test/media/media_source_engine_unit.js
MediaSourceEngine does not, in fact, preserve SourceBuffer properties when we reset it to switch codecs.  This is handled by StreamingEngine instead, through a follow-up call to setStreamProperties.
The test only ever passed as originally written because there was a missing `await` on an async reset process.
This removes the bogus test.
Related to #6458, #6462
=> test: Remove bogus MediaSourceEngine test case

lib/media/streaming_engine.js
When reloading MediaSourceEngine via StreamingEngine, some logic executed before the reload cancels operations and aligns StreamingEngine state with MediaSourceEngine.
However, additional logic was executed after setStreamProperties, which caused a race condition that broke StreamingEngine state by manipulating it out of the usual sequence and outside the usual methods, leading to exceptions and failed assertions.  This removes that unnecessary logic and leaves subtle state management to the functions that are meant to do it.
Closes #6458
=> fix: Fix exceptions in StreamingEngine when reloading

lib/media/manifest_filterer.js, lib/offline/storage.js, lib/util/stream_utils.js, test/util/stream_utils_unit.js
Follow up to #5391
Always use `preferredKeySystems` during manifest filtering, not only via DRM Engine.
=> perf(DRM): pass `preferredKeySystems` to `filterManifest()`

externs/shaka/player.js, lib/util/tXml.js, test/util/tXml_unit.js
Required by #5247 
Simple XPath parser for tXml utils. Not used for now, but needed for MPD Patch support.
=> feat: Parse XPath

lib/util/tXml.js
`replaceAll` is not supported on Tizen 3.
=> fix: Do not use `replaceAll` in XPath parsing

lib/text/ui_text_displayer.js
This avoids wasting processing resources when it is not necessary
=> fix: Don't update captions when video is paused

externs/shaka/manifest.js, lib/dash/content_protection.js, lib/hls/hls_parser.js, lib/media/drm_engine.js, lib/mss/content_protection.js, lib/util/manifest_parser_utils.js, test/dash/dash_parser_content_protection_unit.js, test/hls/hls_parser_unit.js, test/media/drm_engine_unit.js, test/offline/manifest_convert_unit.js, test/offline/storage_integration.js, test/test/util/manifest_generator.js
Related to https://github.com/shaka-project/shaka-player/issues/1419
=> feat: Add encryptionScheme to shaka.extern.DrmInfo

lib/player.js
Fixes https://github.com/shaka-project/shaka-player/issues/6447
=> fix: call to load in MediaElement using src= in HLS Safari

lib/dash/dash_parser.js, lib/mss/mss_parser.js, lib/util/player_configuration.js
Fixes https://github.com/shaka-project/shaka-player/issues/6488
=> fix: Fix deprecation warning for manifestPreprocessor that is always logged

AUTHORS, CONTRIBUTORS, lib/dash/segment_template.js, lib/media/segment_reference.js
=> fix(DASH): decrease memory preasure on manifest with SegmentReference by updating old initSegmentReference

lib/media/segment_index.js, lib/media/streaming_engine.js, lib/player.js, lib/util/cmcd_manager.js, test/media/segment_index_unit.js, test/media/streaming_engine_integration.js, test/media/streaming_engine_unit.js, test/test/util/simple_fakes.js
Fixes https://github.com/shaka-project/shaka-player/issues/1958
=> fix: Fix inefficient buffering behavior with negative trick play rate

.github/workflows/release-please.yaml
Since upgrading the deployment action from v0 to v2, and stumbling into google-github-actions/deploy-appengine#361, new versions were not properly promoted.  However, our promotion setting in the workflow was actually ignored the whole time due to a missing "echo".
Closes #6502
=> ci: Fix appspot promotion during deployment

.github/workflows/release-please.yaml
The condition for tagging the main branch was inverted after v4.7.11.
The main-branch tags for v4.6.16, v4.6.17, v4.7.12, v4.7.13, and v4.8.1 all had to be created and pushed by hand to correct this.
=> ci: Fix main tags

test/media/playhead_unit.js
The playhead test, "does not change once the initial position is set", is not really as important as it was when it was first added. The playhead class has been refactored significantly since then, and drift tolerance has been improved (see #999).
However, the behavior of the getTime method not changing until the video starts... it's not something we would write a test for today, perhaps, but it's still worthwhile enough to at least keep. Perhaps if it was a slow integration test it'd be worth trimming, but as a simple synchronous unit test it won't have any major effects on the durations of test runs.
Closes #1754
=> chore: Remove old comment

lib/dash/mpd_utils.js
We previously supported float duration attributes in DASH SegmentTemplate, due to an ambiguity in the DASH samples.
The code linked to a DASH IOP issue asking if duration could be a float or it had to be an int.
That issue has since been closed, with the clarification that duration attributes must be an unsigned int and the sample was in violation of the spec.
=> chore(DASH): Remove support for float durations.

lib/util/platform.js
This fix will make it possible to use v4.8 in Cobalt browser. The problem is that navigator.platform doesn't exist in Cobalt browser.
Fixes https://github.com/shaka-project/shaka-player/issues/6517
=> fix: Handle non existing navigator.platform string (#6517)

.github/workflows/build-and-test.yaml
- Install Edge & Firefox explicitly
- Switch to macos-13 for now to resolve Edge & Chrome timeouts
Issue #6508
=> ci: Fix macOS CI failures

lib/media/play_rate_controller.js, lib/media/stall_detector.js, lib/player.js, test/media/play_rate_controller_unit.js, test/player_integration.js, test/player_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/6355
it's still in draft until having proper unit tests to control this
This PR is doing the following
At startup time and at buffering it will set the playback rate to 0. like it was before and reset it to the default value we no buffer.
I'm still passing all the unit test but i'm still thinging if we have an impact with the live catchup feature that is changing the playback rate.
Maybe we should just re introduce the isBuffering_ value in playbackrate class.
Happy to do it if you think so
here the link the PR that introduce the regression
https://github.com/shaka-project/shaka-player/pull/5696/files#diff-274a4cc3948f85eed18f86e04c6260b93faa97b995d38f0e3b1af618fd01fab7L34
=> fix: reBufferingGoal is not respected 

lib/text/ui_text_displayer.js, test/text/ui_text_displayer_unit.js
Keep constructor backward compatible with earlier that had two arguments, i.e. make the new third optional for existing applications.
Fixes https://github.com/shaka-project/shaka-player/issues/6531
=> fix: Make UITextDisplayer constructor backward compatible

lib/media/playhead.js, test/media/playhead_unit.js
PR #6304 caused seeking timeouts in Cast Application Framework, in v4.7.13, v4.8.0, and v4.8.1.
Reverts "fix: Correct playhead when seek beyond seekRange (#6304)"
This reverts commit f91188eaecb91583385f49fdf1e39add3f77d7c2.
Reopens #5202
=> fix: Fix seeking timeouts

externs/shaka/player.js
This adds more information to the docs for defaultBandwidthEstimate and useNetworkInformation, to make it clearer that they are mutually exclusive.
Closes #4691
=> docs: Clarify bandwidth estimation docs.

ui/resolution_selection.js
We recently added the ability for the UI to display multiple variants of the same resolution, if they had different video bandwidths.
This changes the UI to also list the video bandwidth in the menu itself, in that case.
Closes #6494
=> feat(UI): List bandwidth for duplicate resolutions

lib/media/play_rate_controller.js, lib/media/stall_detector.js, lib/player.js, test/media/play_rate_controller_unit.js, test/player_src_equals_integration.js
Fixes https://github.com/shaka-project/shaka-player/issues/6527
Fixes https://github.com/shaka-project/shaka-player/issues/6355
This reverts commit https://github.com/shaka-project/shaka-player/commit/6156dced6bddc5e2cd0cc52071295cff63cadfcd.
=> fix: Re-add setting playbackRate to 0 to control buffering state

test/test/util/waiter.js
This change reduces the duration of the tests by approximately 3 minutes.
=> test: Improve tests speed

.github/workflows/selenium-lab-tests.yaml
You should be able to request a browser explicitly even if it is disabled by default.  This fixed the workflow logic that limited this.
=> ci: Fix workflow request for disabled browsers

test/offline/offline_integration.js
The offline DRM tests have begun failing on Android at a rate of 80% or more.  This was eventually determined to be related to https://crbug.com/1108158 and the timeout workaround in DrmEngine.
When close() hangs and we time out and move on, we leave sessions open that consume hardware resources at the OEMCrypto level in Android.  This eventually leads to failures like `Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': MediaDrmBridge creation failed`.  Logs from `adb logcat` show that 17 sessions are open when this fails, which likely means our lab device has a limit of 16 open sessions.
Initially, delays between these offline DRM test cases were found to be an effective workaround, but full test runs showed this to be ineffective after all.
The only recourse, until Chrome …
=> test: Skip offline DRM tests on Android

lib/player.js
A PreloadManager can only be used on the Player instance that created it. That means that once that Player instance is destroyed any PreloadManagers it made are basically useless, so they should be automatically destroyed too.
=> fix: Destroy preload managers on player destroy

karma.conf.js
Splitting code from test/test/boot.js into proxy-cast-platform.js caused issues with non-ES6 devices because the new file did not match the list of files run through Babel before being served by Karma.
=> test: Fix test infra failure on non-ES6 devices

lib/util/platform.js, test/offline/storage_integration.js, test/test/util/ui_utils.js, test/ui/ui_unit.js
In some cases, Fuchsia Chromecast tests will fail with the error: "The play() request was interrupted because video-only background media was paused to save power."
This resolves the issue by ensuring tests run un-muted on that platform, based on this Chrome code, which indicates the "paused to save power" logic does not activate when sound is playing: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/media/web_media_player_impl.cc;l=3535;drc=d23075f3
This also fixes two places in our tests where the `createVideoElement()` was bypassed.  This should always be used, because it is a central place to apply workarounds such as this.
=> test: Fix Fuchsia background-video errors

test/test/util/waiter.js
In some rare cases, particularly on Fuchsia-based Chromecasts at the moment, I am seeing test failures where the test is waiting for a time that has already passed. It appears that the `timeupdate` events may be missed in some cases. The `currentTime` appears to be less than the target at the last `timeupdate` event, then the time progresses internally, then a buffering state is hit and no new `timeupdate` events fire. So the Waiter class should use a timer for this as it does for many other types of waits.
=> test: Fix test failure waiting for passed time

lib/player.js
This could be relevant if destroy() is called multiple times in a row.
Based on a comment on #6576
=> fix: Clear preload array before awaiting destroy

.github/workflows/build-and-test.yaml, .github/workflows/selenium-lab-tests.yaml
When tests occasionally timeout (as is currently happening with IndexedDB hangs on Mac), we should stop the test run after 30 minutes and allow the "deflake" workflow to rerun them.  Without this timeout, the test run can takes hours.
A successful test run takes 15-20 minutes currently.
=> ci: Add overall test timeout of 30 minutes

karma.conf.js
When running tests locally on many browsers, it can be difficult to tell which browsers are done.  You need to look at the number of executed and skipped tests, sum them, and compare that to the total number of tests.  With each browser skipping different numbers of tests and running at different speeds, this is painful.
This modifies the test reporters to show the number of tests left.  This gives you, at a glance, which browsers are done and how close each is to completion.
=> test: Show number of tests left to be executed

lib/media/media_source_engine.js
Our addTextTrackAsync function supports conversion of text types registered in TextEngine to WebVTT.
=> chore: Check TextEngine support on all platforms

test/media/media_source_engine_integration.js
All browsers support transmusing to audio/mp4 with AAC, so this condition is wrong.
=> test: Remove bad condition on extracts ID3 metadata from AAC when transmuxing

demo/config.js, externs/shaka/player.js, lib/util/player_configuration.js, lib/util/stream_utils.js, test/player_unit.js
Close https://github.com/shaka-project/shaka-player/issues/6491
=> feat: Add a new setting to allow remove based on channels count

lib/cea/cea_decoder.js, lib/media/closed_caption_parser.js
Fixes #6605
Resets cache (including last used presentation timestamp) of CEA Decoder on every init segment append.
Adds few debug logs to easify investigations in the future.
=> fix(CEA): reset PTS on new init segment

test/test/util/util.js, test/util/stream_utils_unit.js
This prevents any tests from being skipped in Safari.
=> test: Use MCap on StreamUtils tests

lib/media/media_source_engine.js, lib/transmuxer/ts_transmuxer.js, lib/util/stream_utils.js, test/test/util/util.js
In Safari:
```
> MediaSource.isTypeSupported('audio/mp4;codecs=Opus')
< true
> MediaSource.isTypeSupported('audio/mp4;codecs=opus')
< false
> MediaSource.isTypeSupported('audio/webm; codecs="Opus"')
< false
> MediaSource.isTypeSupported('audio/webm; codecs="opus"')
< true
```
=> fix: Fix Opus support in Safari

test/util/periods_unit.js
A partner bug we are investigating involves content not being played at 4K when it could be.  This test (which passes) helped us eliminate a theory that our period-flattener was the cause.
=> test: Add multiperiod test case mirroring partner bug

build/shaka-lab.yaml
Still disabled by default until test failures are resolved.
=> ci: Make ChromeOS device available in the lab again

lib/hls/hls_parser.js
Fixes https://github.com/shaka-project/shaka-player/issues/6627
=> fix(HLS): Support request byterange on media playlist detection

test/test/boot.js
Karma creates a dump() function on the context window that we can use to log something to the console without respect for the normal captureConsole setting.  Use this for the output of probeSupport(), so we always have it in CI logs.
=> test: Bypass log settings for support dump

build/test.py, karma.conf.js, package-lock.json, test/test/closure-boot.js, test/test/util/layout_tests.js
Chromecast WebDriver Server and Karma both used iframes, which caused complications when testing on Chromecast.  The test environment couldn't directly access `cast.__platform__` APIs, and more recently stopped being able to access EME due to presumed mistakes in the platform's implementation of iframe permission policies.
This resolves the issue by removing iframes at both levels.
- Flatten Karma's environment using "useIframe: false" and "runInParent: true"
- Remove test flag --single-run; not supported in combination with Karma's "useIframe: false" option
- Add a test boot file to force closure to use dynamic script tags instead of document.write; required with Karma's "useIframe: false" option
- Adjust screenshot tests not to assume an iframe host
- Fix compatibilty between Tizen and …
=> test: Flatten test environment for Chromecast

demo/config.js, externs/shaka/player.js, lib/net/networking_engine.js, lib/player.js, lib/util/player_configuration.js, test/test/util/fake_networking_engine.js
This may be necessary on older devices where not all certificates are present.
=> feat: Optionally force HTTP content URIs

demo/config.js, externs/shaka/player.js, lib/media/drm_engine.js, lib/player.js, lib/polyfill/media_capabilities.js, lib/util/player_configuration.js, lib/util/stream_utils.js, test/polyfill/media_capabilities_unit.js, test/test/boot.js
On PlayStation, cached `MediaKeySystemAccess` objects may corrupt after several playbacks, and they are not able anymore to properly create `MediaKeys` objects. To prevent it, clear the cache after each playback.
Make it configurable via `streaming.clearDecodingCache`.
=> feat: add config to clear decodingInfo cache on unload

externs/shaka/player.js, lib/util/player_configuration.js
The previous default value served no purpose and was a mistake in the PR that added the functionality.
=> fix: Fix default value of liveSyncMinPlaybackRate

lib/util/platform.js, test/util/platform_unit.js
My recent tests on using smooth codec switch on Tizen 6.0 unfortunately failed. Ban this platform together with Tizen 5.
=> fix: Ban smooth codec switching on Tizen 5 & 6

demo/config.js, externs/shaka/manifest.js, externs/shaka/player.js, lib/dash/dash_parser.js, lib/player.js, lib/util/player_configuration.js, test/dash/dash_parser_manifest_unit.js
Related to https://github.com/shaka-project/shaka-player/pull/6193
Thanks to @gkatsev
=> feat(DASH): Parse and use target latency

build/types/polyfill, lib/polyfill/patchedmediakeys_cert.js, lib/util/platform.js, test/util/platform_unit.js
We've tried to enable setting server certificates to optimize playback start, but turned out that with our widevine certificate shaka was throwing 6004 error. The issue is not reproducible starting from Tizen 5.5. The same certificate was working properly also on Chrome.
=> fix: patch `setServerCertificate()` on older Tizens & webOS

lib/media/gap_jumping_controller.js
It looks like Xbox incorrectly rounds values to seek and it's not able to jump over gaps sometimes.
=> fix: Xbox - round gap jumping values

CONTRIBUTORS, lib/util/stream_utils.js
I believe a bug was introduced as part of the refactor in this PR #6348 that affects Firefox.
This line here https://github.com/shaka-project/shaka-player/blob/main/lib/util/stream_utils.js#L561 , would clone mediacapabilitiesInfo only if this was a plain `Object`. This seems to be the case in Chrome, however, it looks like the Firefox implementation of `MediaCapabilities.decodingInfo()` returns a "non-simple" `MediaCapabilitiesInfo` object instead - that results in [cloneObject retuning null](https://github.com/shaka-project/shaka-player/blob/main/lib/util/object_utils.js#L56), see screens:
FF:
Chrome:
Switching to use shallow clone instead fixes the problem.
Fixes #6690
=> fix(DASH): Firefox multi-period/multi-codec bug

lib/cea/cea_decoder.js
=> fix(CEA): Fix stream detection when the stream has not control codes

lib/media/manifest_filterer.js, lib/media/preload_manager.js
Regression of Preload API
In HLS the definition of variants is only done once and it is the master playlist.
In DASH, the definition of variants is done in each manifest update.
If we make the codec choice only at the beginning, in HLS it works, but in DASH in the updates we lose this choice.
=> fix: Fix multi-codec filtering on DASH live

docs/tutorials/preload.md, lib/net/networking_engine.js, lib/player.js, test/test/util/fake_networking_engine.js
Some assets might rely on networking engine filters (request and response filters) to properly download their assets. However, the preload manager's need to use a fresh networking engine also caused it to not use any filters set on the player already. This changes the process of setting up a preload manager, to make it copy over any filters defined on the player's networking engine.
Fixes #6698
=> fix(preload): Copy net filters to preload manager

lib/util/object_utils.js
For some reason on PS4, the check `val.buffer.constructor == ArrayBuffer` returns `false` when it should be `true` which causes the object cloning to return `null` instead of the array buffer.
Modifying this to `val.buffer instanceof ArrayBuffer` now returns true which fixes the issue. This should work across devices.
Original author: @nick-michael
=> fix(PS4): Fix serverCertificate defaulted to null

lib/player.js
We aren't sure if this is the best solution, because we don't entirely understand the original reason for using `startTimeOfLoad`, the wall clock time that the load started, instead of `startTime`, the playhead time offset passed to `player.load()`. We are looking for some clarity and this is our initial fix. This issue results in DAI impressions being missed, especially on lower powered and network constrained devices.
Resolves #6711
=> fix: ensure all timelineregionenter events are fired

test/ads/ad_manager_unit.js
MockAdManager did not define setVolume() in this one test, causing the test to throw an exception.  This exception got swallowed and did not fail the test, but was noticed in the JS console during a Karma debug run.
=> test: Fix exception calling setVolume() in ads test

externs/shaka/manifest_parser.js, externs/shaka/player.js, lib/hls/hls_parser.js, lib/hls/manifest_text_parser.js, lib/offline/storage.js, lib/player.js, test/dash/dash_parser_content_protection_unit.js, test/dash/dash_parser_live_unit.js, test/dash/dash_parser_manifest_unit.js, test/dash/dash_parser_patch_unit.js, test/dash/dash_parser_segment_base_unit.js, test/dash/dash_parser_segment_list_unit.js, test/dash/dash_parser_segment_template_unit.js, test/hls/hls_live_unit.js, test/hls/hls_parser_unit.js, test/mss/mss_parser_unit.js, test/test/util/dash_parser_util.js, test/test/util/mss_parser_util.js, test/util/content_steering_manager_unit.js
Closes https://github.com/shaka-project/shaka-player/issues/3523
=> feat(HLS): Add support for EXT-X-DATERANGE

lib/media/preload_manager.js
Regression of https://github.com/shaka-project/shaka-player/commit/90710023466dcad4d1d14a2869ae50e8da4e93ee
Fixes https://github.com/shaka-project/shaka-player/issues/6710
=> fix: Avoid filter manifest when the DRM is not initialized

test/test/closure-boot.js, test/test/externs/karma.js
To debug Karma tests, you can load debug.html in a browser.  However, this context has no back-channel to Karma and tries to load scripts by direct insertion into the document.  For compatibility, we need to have Closure inject scripts with the same methodology, to avoid having scripts load in the wrong order.  We also have to define the dump() method that Karma would normally inject into the testing context.
=> test: Fix Karma debug.html support

lib/player.js, lib/polyfill/mediasource.js, lib/util/platform.js, test/player_unit.js
Few bugfixes to support DT Zenterio platform:
- Zenterio seems to have a problem with the EME onKeyStatus event payload (the key statuses map), where the map key ID comes in as empty. This is not correct based on the EME spec:
https://w3c.github.io/encrypted-media/#dom-mediakeysession-keystatuses
- Add polyfills that are used to fix issues with older webkits, same as for older safari browsers
=> fix: Support for Zenterio

lib/ads/ad_manager.js, lib/ads/client_side_ad_manager.js, lib/player.js
This change simplifies the integration of HLS interstitials on platforms that do not support multiple video elements.
=> feat(Ads): Add content resume/pause requested events

ui/presentation_time.js
This bug has been detected when implementing HLS interstitials
=> fix(UI): Don't show presentation time in ads

lib/media/drm_engine.js, lib/media/preload_manager.js, lib/player.js, test/player_load_graph_integration.js
After a previous bugfix to the preload system, we ended up with a situation where the
overall progress in the preload was tracked by two promises:
`successPromise_`, which is resolved when the preload finishes successfully.
`destroyPromise_`, which is rejected with an error when the preload process trips an error condition.
These two promises were confusingly named; it sounds like destroyPromise is related to the destroy process,
but really it has more to do with errors.
They were also completely redundant, as a single promise can be used to carry both a resolved and
rejected state.
This PR simply combines the two promises into one.
=> fix(preload): Fix error handling

lib/hls/hls_parser.js
With this change avoids errors like: 
`DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.`
=> fix(HLS): Ignore query params in the uri of EXT-X-SESSION-KEY tags

lib/player.js
Since the latest versions we always make TS transmux.
=> chore: Remove old LCEVC code

externs/polyfill.js, lib/media/drm_engine.js, lib/player.js, lib/polyfill/patchedmediakeys_apple.js, lib/polyfill/patchedmediakeys_nop.js, lib/polyfill/patchedmediakeys_webkit.js, lib/util/platform.js, test/player_unit.js, test/polyfill/patchedmediakeys_apple_unit.js, test/util/platform_unit.js
On WebOS 3.0 we've noticed an issue in production, where TVs are slowly starting to throw the following error after a user has watched at least 30+ episodes: `Code: 6006 Category: 6 Severity: 2 ["EME v0.1b key error",{"errorCode":{"code":1,"systemCode":65535}},"0xffff"]` and can only be resolved by clearing the app cache, or unplugging the TV.
Further investigation revealed that current workflow, where MSE is destroyed before DRM Engine causes that old EME implementation is not able to close session properly.
=> fix(DRM): close properly webkit media key sessions

lib/media/presentation_timeline.js
For our Seek To Date feature, we need the presentation start date directly from the manifest since all of the client’s key play times are based directly on the `availabilityStartTime` from the manifest directly.
=> fix: `getPresentationStartTimeAsDate()` should return time unaffected by clock drift

lib/dash/dash_parser.js, lib/net/networking_engine.js, test/dash/dash_parser_patch_unit.js
Add `shaka.net.NetworkingEngine.AdvancedRequestType.MPD_PATCH` to distinguish regular MPD requests from MPD Patch requests.
=> feat(DASH): add  `MPD_PATCH` advanced request type

lib/hls/hls_parser.js
https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-6.2.4
```
If any Playlist contains Date Ranges, then at least one Playlist
in any playable combination of Renditions of any Variant Stream
MUST contain Date Ranges.  Any Playlist with Date Ranges MUST
contain the same set of Date Ranges as the others that do.  The
EXT-X-DATERANGE tags of corresponding Date Ranges MUST have the
same ID attribute value and contain the same set of attribute/
value pairs.
```
So it would not be allowed. We can omit Date Ranges from img and subtitle Playlists in a Rendition that has Date Ranges in the Variant Playlists (main video STREAM-INF Playlists).
=> feat(HLS): Only process DATE-RANGE in AUDIO and VIDEO playlists

lib/player.js, test/player_unit.js
When restrictions are set, `selectAudioLanguage()` ignores them and may suggest variant that is marked as unplayable.
=> fix: `selectAudioLanguage()` should ignore unplayable variants

lib/media/time_ranges_utils.js
On Firefox, in some cases after a period ends, seeking shortly after will cause playback to fail or stall.
This occurs when the next period has small gaps and we're seeking to after the gap. Seeking to before the gap succeeds. Even though the seek requests the soure buffers to be fully cleared, Firefox actually keeps around less than 1e-4s of content and won't let us forcibly remove this content. Trying to call flush causes in infinite loop.
This leftover content makes shaka think that the buffer end in where we used to be even though the presentation time reflects where we seeked to. This means that playback doesn't continue. The buffer contitues getting filled and playback will either fail when the SourcBuffer is filled and triggers a QuotaExceededError or contiue when the buffer will …
=> fix: ignore buffered content less than 1e-4s

.github/workflows/selenium-lab-tests.yaml, .github/workflows/update-screenshots.yaml
Always compute sha1 in lab and screenshot workflows in advance.  A symbolic ref can change mid-workflow if the repo changes.
=> ci: Compute sha1 from ref in advance in lab and screenshot workflows

lib/util/manifest_parser_utils.js
See: https://ott.dolby.com/OnDelKits/AC-4/Dolby_AC-4_Online_Delivery_Kit_1.5/Documentation/Specs/AC4_HLS/help_files/topics/hls_playlist_c_codec_indication.html
=> fix(HLS): Fix AC-4 codec selection in HLS

lib/text/mp4_ttml_parser.js
No need to reject the subtitles when the parser can already handle them.
> Quote from specs:
> Valid examples include:
> • "stpp.ttml.etd1" - TTML content suitable for presentation by an EBU-TT-D renderer
> • "stpp.ttml.etd1|im1t" or "stpp.ttml.im1t|etd1" - TTML content suitable for presentation by an EBU-TT-D or
IMSC1 renderer 
Fixes #6831
=> fix(TTML): Extended subtitle codec support

lib/net/http_fetch_plugin.js
This fix excludes the use of https://www.npmjs.com/package/fetch-polyfill because it does not support a signal to cancel requests in progress.
=> fix: Exclude fetch polyfill from fetch plugin

.github/workflows/shaka-bot-commands/command-test.sh
ChromecastHub is currently disabled, so we don't want to trigger it explicitly on `test ce` commands.
=> ci: Remove ChromecastHub from shaka bot commands

build/README.md
I found this out when I got this error message
test.py: error: argument --enable-logging: invalid choice: '3' (choose from 'none', 'error', 'warning', 'info', 'debug', 'v1', 'v2')
=> docs: fix test.py enable-logging section of README

.github/workflows/build-and-test.yaml
Using arm (macos-latest) wherever possible reduces build times by 3 minutes.
We have a limited number of macos runners, so if we save time even on Firefox alone (all we can do pending #6508), we can speed up the queue of pending jobs across PRs.
=> ci: Migrate Firefox from macos-13 to macos-latest

lib/media/preload_manager.js, lib/player.js
Previously, when preloading, we would measure startTimeOfLoad based on when the PreloadManager was created.
This meant that if a PreloadManager was created and then not used for a while, it would lead to the load latency stats reporting an extreme load latency.
This changes the startTimeOfLoad to instead record when the PreloadManager is consumed by the player.
Fixes #6871
=> fix(preload): Fix preload load latency logic.

lib/media/streaming_engine.js
There was a memory leak where the segments that the PreloadManager prefetched did not get cleaned up, after the player unloads. This fixes that memory leak.
Fixes #6883
=> fix(preload): Fix memory leak with preload feature

lib/hls/hls_parser.js
Allows you to obtain the correct segment to detect the basic information of the stream (middle segment for Live, and the first segment for VoD).
Avoid obtaining information from segments that are gaps.
=> fix(HLS): Fix get basic info from segments

demo/input.js
If an input in the demo can't be zero and a value <1 was given, the check pattern would fail for it, and it'll show the warning that the input isn't valid even though it is valid.
This slightly simplifies the regex creation as canBeZero adds `0+|` to the pattern and the main pattern `([0-9]*[1-9][0-9]*)` is always used. Then, if it can be a decimal, it uses the existing pattern but adds `?(0(?=\.))?'` which makes the main pattern optional and instead adds the optionally a `0` but only if it is followed by a `.`.
The main pattern `([0-9]*[1-9][0-9]*)` potentially could be simplified into `[1-9]\d*` but it would make leading zeros invalid.
=> chore(demo): fix pattern to allow <1 decimals if can't be zero

demo/config.js, externs/shaka/player.js, lib/player.js, lib/util/player_configuration.js, test/cast/cast_receiver_integration.js
This adds a new feature for adjusting the target latency closer to the live edge when playback is stable and back off away from the live edge when playback rebuffers. It is off by default and will only run a default of 5 times before it will stop trying to adjust the target latency.
Closes https://github.com/shaka-project/shaka-player/issues/6131.
=> feat: Dynamic target latency

lib/media/preload_manager.js, lib/media/segment_index.js, lib/media/segment_prefetch.js, lib/media/streaming_engine.js, test/media/segment_prefetch_unit.js, test/test/util/fake_segment_prefetch.js
Starts caching `SegmentIterator` in `SegmentPrefetch` to avoid creating new one on every update. Previous behavior was more time-consuming & could cause issues on platforms with precision problems, like Xbox.
=> fix(Prefetch): cache iterator to avoid precision issues

externs/shaka/player.js, lib/dash/dash_parser.js, lib/dash/segment_base.js, lib/media/quality_observer.js, lib/player.js, lib/util/fake_event.js, test/media/quality_observer_unit.js, test/media/segment_reference_unit.js, test/test/util/test_scheme.js
This piggybacks on the media quality observer to also check whether the audio track changed and the change was in label, language, or role.
Currently, this new event is triggered is `observeQualityChanges` is set. This could be moved to a separate config.
I do play to add a test or two to the integration tests.
For verifying the role/label, I was testing against this public test stream https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel-desc-aud.ism/.mpd (though, it does seem to error out every so often). There might be other test streams. Angel One is a great one for language.
Also, something that we noticed, but won't be part of this PR. The timing of this event is likely incorrect if the track was switched and safeMargin was set. We have some …
=> feat: add an audiotrackchanged event for when label, language, or roles of an audio track change

demo/visualizer.js
Previously, updates in the visualizer would fade away after a set period of time.
This changes the visualizer to continue to show updates as long as they remain in the buffered content.
=> chore(demo): Change visualizer update duration

lib/abr/simple_abr_manager.js
This rare case can occur when a stream is disabled and this stream disables the entire variant.
=> fix(ABR): Add a guard when variant is null

lib/media/streaming_engine.js, test/media/streaming_engine_unit.js
According to https://w3c.github.io/media-source/#dom-sourcebuffer-remove
Deleting a range from the source buffer does not delete the initialization segment, so this change will prevent the initialization segment from being requested when it is not needed.
=> fix: Only request initialization segment when it's necessary

lib/hls/hls_parser.js, lib/player.js
This change allows us to detect when the initial variant fails (for example due to a 404, 503 in the m3u8 request) and we can change to another variant.
=> fix(HLS): Allow disable initial variant if necessary

lib/util/ts_parser.js
PES arrays can get pretty big so it would be prudent to avoid looping over them more than needed
=> perf(HLS): do not loop twice when processing nalus

lib/hls/hls_parser.js, lib/media/drm_engine.js, lib/player.js, lib/polyfill/media_capabilities.js, lib/polyfill/patchedmediakeys_apple.js, lib/polyfill/patchedmediakeys_webkit.js, lib/util/drm_utils.js, lib/util/periods.js, test/media/drm_engine_unit.js, test/polyfill/media_capabilities_unit.js, test/util/drm_utils_unit.js
As we already have `DrmUtils`, try to cut few lines from `DrmEngine`.
=> chore(DRM): Move util methods from DrmEngine to DrmUtils

lib/text/ttml_text_parser.js
Exclude default fontFamily (not supported in Chromium browsers)
Allow fontSize with 3 and 4 digits, for example 300% or 1000%
=> fix(TTML): Fix font styles parsing

lib/player.js, test/offline/storage_integration.js, test/player_unit.js
Related to https://github.com/shaka-project/shaka-player/issues/6672#issuecomment-2130166183
=> feat: Allow set the videoContainer in the Player constructor

lib/media/streaming_engine.js
Using different time bases can result in duplicate or unnecessary segments being downloaded in HLS LL
=> fix(Prefetch): Use the same references time for evict and prefetchSegmentsByTime

lib/media/streaming_engine.js
When using HLS LL and making seek small this produces overlaps
=> fix: Avoid reset iterator when seek into the buffer

lib/media/playhead.js, lib/util/platform.js, test/media/playhead_unit.js
Previously, we added a 1 second "cooldown" period between attempts to perform a corrective seek.
This was for the benefit of old v1 Chromecasts, which found the process of seeking so slow that they would sometimes get stuck in an infinite loop trying to start a presentation.
However, that cooldown period was causing issues in some situations during seeking, so this PR removes the restriction on everything but pre-Android Chromecast devices.
Fixes #4393
Fixes #5202
=> fix: Disable seek retry cooldown on most platforms

lib/dash/dash_parser.js
Fixes https://github.com/shaka-project/shaka-player/issues/2581
=> fix(DASH): Fix transitions from 'dynamic' to 'static'

lib/dash/segment_template.js
Related to https://github.com/shaka-project/shaka-player/issues/6610
=> fix(DASH): Improve memory usage with live streams

lib/polyfill/mediasource.js
Fixes https://github.com/shaka-project/shaka-player/issues/7048
=> fix: Fix MSE polyfill for iOS

lib/util/periods.js, test/util/periods_unit.js
When roles exist and are equal between tracks and periods, period combiner matches based on that instead of looking for other similarities. This PR addresses it & adds regression test.
=> fix(DASH): Fix period combining when roles are equal

externs/shaka/player.js, lib/player.js, test/cast/cast_utils_unit.js
Related to https://github.com/shaka-project/shaka-player/pull/6825
=> feat: Add getFetchedPlaybackInfo method

lib/dash/dash_parser.js, lib/dash/segment_base.js, lib/dash/segment_list.js, lib/dash/segment_template.js, lib/util/manifest_parser_utils.js, test/dash/dash_parser_manifest_unit.js
Resolves https://github.com/shaka-project/shaka-player/issues/6472
=> feat(DASH): Support Annex I: Flexible Insertion of URL Parameters

lib/player.js
Related to https://github.com/shaka-project/shaka-player/issues/7097
=> fix: Allow dispatch metadata event with cueTime equal to 0

lib/text/ui_text_displayer.js
This is a follow-up for https://github.com/shaka-project/shaka-player/pull/6986/files#r1667140796
=> fix: properly map region height/width when applying anchors

package-lock.json, package.json
This was forked in 2022 to fix a vulnerability, and the fix was only just merged.
=> chore: Upgrade/unfork less-plugin-clean-css

lib/hls/hls_parser.js, lib/media/preload_manager.js, lib/util/stream_utils.js
If any segment gets evicted in live scenario, `segmentIndex.get(0)` will return `null`. Due to that, image tracks have `tilesLayout` set to `null` if we call `player.getImageTracks()` after segments have been evicted.
Additionally to main fix, I've replaced all other appearances of `segmentIndex.get(0)` with `segmentIndex.earliestReference()` to prevent similar bugs.
=> fix(HLS): Expose tilesLayout properly for live

lib/media/streaming_engine.js
Currently passing adaptation value via media state has 2 flaws:
- it's not passed on init segment append (thus we don't use this value at all in CaptionParser)
- it often marks already pending update as an adaptation, instead of the actual segment we care about
=> fix: Pass correct adaptation value to MediaSourceEngine

CONTRIBUTORS, docs/tutorials/screen-resolution-detection.md, externs/xbox.js, lib/util/platform.js
=> fix(Xbox): Support screen resolution detection on Xbox when using WebView2

externs/shaka/drm_info.js, externs/shaka/manifest.js, externs/shaka/player.js, externs/shaka/resolution.js
In order for some internal tools at Google to reference subsets of Shaka Player's code, we need to break out some low-level externs so that they are not entangled with other parts of Shaka's code.  For example, references to Shaka classes are made inside some externs.
This extracts DRM-related and resolution-related externs into their own files, where they can be more easily referenced without needing to import various other Shaka classes.
=> chore: Split externs

lib/hls/hls_classes.js, lib/hls/hls_parser.js
Fixes https://github.com/shaka-project/shaka-player/issues/7122
=> fix(HLS): Fix use of EXT-X-MEDIA when not using Content Steering

lib/util/tXml.js
Related to #7148 
Does not create parent elements anymore to reduce memory consumption.
Starts to use `createElementNS()` so created elements will keep proper cases for tag names and they won't be anymore of type `HTMLElement`, but `Element`, which should be more lightweight and suitable for our needs.
=> fix(DASH): Fix EventStream Elements creation

lib/config/codec_switching_strategy.js
Enum keys has been minified in release build.
As comments were using wrong syntax, they weren't displayed in documentation.
=> fix: Do not minify CodecSwitchingStrategy enum keys

lib/media/streaming_engine.js, test/media/streaming_engine_unit.js, test/test/util/manifest_generator.js
Reverts shaka-project/shaka-player#7157 ("fix: Defer `closeSegmentIndex()` for old streams during ABR switches when segment fetches are ongoing")
A regression was reported in video-dev.org Slack, and they narrowed it down to this PR.  Playing https://d24rwxnt7vw9qb.cloudfront.net/v1/dash/e6d234965645b411ad572802b6c9d5a10799c9c1/All_Reference_Streams/4577dca5f8a44756875ab5cc913cd1f1/index.mpd with this PR, reportedly:
> playback stops rendering with a warning "cannot find segment endTime" just a few seconds prior to the rendering alt.
This was initially observed on Samsung TVs, but then later on LG and even in Chrome.
=> fix: Revert change that caused stalls with "cannot find endTime"

lib/player.js, lib/util/cmcd_manager.js
This aligns Shaka's implementation with what Apple's native player will return when CMCD is enabled, see: https://developer.apple.com/streaming/Whats-new-HLS.pdf
=> feat(CMCD): Implement new streaming format from CMCDv2

lib/media/streaming_engine.js
Reverts https://github.com/shaka-project/shaka-player/pull/7184 ("fix: Add null check for current reference")
See https://github.com/shaka-project/shaka-player/pull/7184#issuecomment-2317424817
=> fix: Revert change that caused a lot of warning with "cannot find endTime" and hls playback errors

demo/demo.less, ui/less/containers.less, ui/less/tooltip.less
font-family settings always started with "Roboto-Regular" before "Roboto", but we don't load "Roboto-Regular". It may exist already on some systems, but we don't explicitly load it. We do explicitly load "Roboto", so that should be the only Roboto-family font in the list.  This issue has been present since the very first introduction of our UI.
=> fix(UI): Remove not loaded font

lib/media/media_source_engine.js, lib/media/streaming_engine.js
Fixes #7232
On some Comcast devices (Flex series) calling `isTypeSupported()` with base codec string results in video playback failure and an immediate application crash.
=> fix: Fix type passed to isTypeSupported in some cases

demo/common/assets.js, externs/shaka/player.js, lib/util/player_configuration.js, test/dash/dash_parser_manifest_unit.js, test/test/util/dash_parser_util.js
Since xlink processing is slow and very few streams use it, it is best to disable this functionality by default to improve performance especially on STB or SmartTV devices.
=> feat(DASH): Disable xlink processing by default

lib/text/simple_text_displayer.js, lib/text/text_utils.js
This change prevents cues from being created without payload, as is the case with subtitles in image format.
=> fix: Fix rendering of image subs when using SimpleTextDisplayer

lib/text/text_utils.js
Chromium browsers do not currently support the `lineAlign` or `positionAlign` properties on the VTTCue class, just like the region property. So this pull request adds an if before reading those properties so that the position and line values are handled correctly in UITextDisplayer (without this change the subtitles are always at the bottom edge of the player and right aligned subtitles are displayed off-screen).
https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/lineAlign#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/positionAlign#browser_compatibility
Before fix
After fix
Steps to reproduce:
- Get local demo running (`python build/all.py --debug`?)
- Visit custom content, add https://d2zihajmogu5jn.cloudfront.net/elephantsdream/ed_hd.mp4 (with …
=> fix(WebVTT): Fix mapNativeCueToShakaCue in Chromium browsers

lib/util/periods.js, test/util/periods_unit.js
Issue https://github.com/shaka-project/shaka-player/issues/6239
=> fix(DASH): Avoid adding originalId when it is not necessary

lib/dash/dash_parser.js, test/dash/dash_parser_live_unit.js
=> fix(DASH): Use presentationTimeOffset in EventStream

lib/util/periods.js
Old references to segment index are already stored in meta segment index, so there's no reason to recreate them.
=> perf(DASH): Create segment indexes only on new periods

lib/util/periods.js
It should always be MetaSegmentIndex, so handle it via assertion instead of an `if()`. This way we will satisfy compiler, avoid unnecessary `if()` check and potentially find errors quicker thanks to assertion.
=> perf(DASH): Do not check is index instance of MetaSegmentIndex

.github/workflows/selenium-lab-tests.yaml
In #6811, I introduced a bug into the lab workflow.  This came to my attention through the GitHub Actions warning: "Unexpected input(s) 'sha', valid inputs are ...".  This came from the "actions/checkout" step of the "matrix config" job.  The correct input is "ref", not "sha".
This bug meant that any changes to the matrix config were not being properly tested.  It's likely we haven't had any PRs that touched the matrix config since the bug was introduced in June.
=> ci: Fix SHA1 selection in lab run

.github/workflows/selenium-lab-tests.yaml
Using the branch this PR is based on, I was able to start two concurrent lab runs on different sets of browsers:
https://github.com/shaka-project/shaka-player/actions/runs/10836501320
- FirefoxLinux
- FirefoxWindows
- FirefoxMac
https://github.com/shaka-project/shaka-player/actions/runs/10836507170
- ChromeLinux
- ChromeWindows
- ChromeMac
- ChromeAndroid
The early jobs (Compute SHA, Matrix config, Pre-build Player) were all able to run simultaneously since they only use Actions VMs.  The later jobs under the matrix "lab-tests" were also able to run at the same time across workflow runs because they used disjoint sets of browsers.
I started a third run 5 minutes later with some overlap in browsers with the first two runs:
https://github.com/shaka-project/shaka-player/actions/runs/108365719 …
=> ci: Allow concurrent lab runs that use different devices

lib/util/periods.js
This reverts commit a32043864a3f8c642f44c333fe9350a6f84e70de.
MetaSegmentIndex may be closed during an async operation and we must take this into account.
BEGIN_COMMIT_OVERRIDE
chore: Ignore this in the changelog; it was reverted
END_COMMIT_OVERRIDE
=> revert: Revert "perf(DASH): Do not check is index instance of MetaSegmentIndex (#7295)"

lib/player.js
The bug was introduced in #6340, and affects v4.6.16-18, v4.7.12-15, v4.8.0-20, v4.9.0-26, v4.10.0-16, and v4.11.0.
Closes #7310
=> fix: Do not seek to first subtitle

lib/player.js
The max line length of 80 characters was exceeded by a release PR in the newly-created v4.9.2-caf branch, for release tagged as v4.9.2-caf1.
This disables the line length check for this robot-maintained line.
=> chore: Disable line-length checking on player version line

lib/media/streaming_engine.js
This case can occur with a live HLS in which the playlist timeout errors and that playlist is deactivated and changed to another one and this other one takes a long time to be received.
=> fix(HLS): Fix uncaught error in slow network scenario

demo/common/assets.js, demo/main.js, externs/shaka/manifest.js, externs/shaka/offline.js, lib/media/segment_reference.js, lib/offline/download_info.js, lib/offline/indexeddb/v1_storage_cell.js, lib/offline/indexeddb/v2_storage_cell.js, lib/offline/manifest_converter.js, lib/offline/storage.js, test/offline/manifest_convert_unit.js
Related to https://github.com/shaka-project/shaka-player/issues/2016
=> feat(Offline): Allow store external thumbnails

demo/config.js, externs/shaka/player.js, lib/media/gap_jumping_controller.js, lib/util/player_configuration.js, test/media/playhead_unit.js
Default value for Tizen set to 2 and can be configurable  Solving issue associated to gapManager not able to pass the GAP on Tizen
Fixes https://github.com/shaka-project/shaka-player/issues/7124
=> fix(Tizen): Adding gapPadding to gap manager to solve Tizen issue

externs/shaka/player.js, lib/offline/storage.js
Support for using the old parallel download mechanism is also added.
Fixes: https://github.com/shaka-project/shaka-player/issues/4878
=> fix(offline): Text segments are downloaded before audio&video

test/polyfill/media_capabilities_unit.js
On some real Cast devices, you can't delete window.cast.  This is fine, and shouldn't cause the test to fail.  If this happens, skip the test instead.  The test, which mocks everything including the platform detection and the Cast API, is still valid on platforms where we can get away with those mocks.
=> test: Don't fail tests when cast property can't be deleted

test/test/boot.js
We get strange uncaught errors sometimes on Cast devices.  These are unreadable "script error" events that have nothing to do with our tests (see https://sentry.io/answers/script-error/), and we intend to ignore them.
However, our existing logic to ignore those is not sufficient, because in addition to our own error handler (via window.addEventListener("error")), Jasmine has its own unconditional error handler (via window.onerror).
To take complete control over how these are handled, we need to remove Jasmine's handler.
Jasmine's handler is installed at the top of its execute() function, so our top-level beforeAll() is the best place to remove it.
=> test: Fix uncaught errors while testing on Cast

test/test/boot.js, test/test/cast-boot.js
If we fail certain actions during test setup, we should log those unconditionally through Karma's dump() function, and not just when browser console logs are enabled with --enable-logging.
=> chore: Improve logging around test setup failures

externs/shaka/manifest.js, externs/shaka/offline.js, lib/dash/dash_parser.js, lib/hls/hls_parser.js, lib/media/media_source_engine.js, lib/media/streaming_engine.js, lib/mss/mss_parser.js, lib/offline/indexeddb/v1_storage_cell.js, lib/offline/indexeddb/v2_storage_cell.js, lib/offline/manifest_converter.js, lib/offline/storage.js, lib/player.js, lib/util/periods.js, roadmap.md, test/hls/hls_parser_unit.js, test/media/adaptation_set_unit.js, test/media/media_source_engine_integration.js, test/offline/manifest_convert_unit.js, test/test/util/manifest_generator.js, test/test/util/offline_utils.js, test/test/util/streaming_engine_util.js
Close https://github.com/shaka-project/shaka-player/issues/5836
=> feat(HLS): Make dummy streams for tags representing muxed audio

lib/polyfill/encryption_scheme.js, lib/util/platform.js
Fixes https://github.com/shaka-project/shaka-player/issues/7354
These platforms don't support `encryptionScheme`, so there is no need to install this polyfil.
=> fix: Disable Encryption Scheme Polyfil On Some Devices

lib/media/preload_manager.js, lib/player.js, test/player_load_graph_integration.js
Previously, there were situations where, when handling `trackschanged` events, the manifest would not yet have been
copied from the preload manager to the player. This would prevent developers from properly handling those events.
This PR changes the order of operations slightly, such that the manifest is copied over earlier.
=> fix(preload): Set manifest before initializing DRM

lib/media/preload_manager.js, lib/player.js
Resolve manifest promise a bit sooner to ensure `player.getManifest()` returns correct value on `manifestparsed` event.
=> fix(preload): Resolve manifest promise sooner

test/test/boot.js
In #7345, we disabled Jasmine's global error handler.  However, jasmine still tries to call this.  So instead of replacing it with null, replace it with a stub.
Also add comments about why we are able to do this and still handle global errors in our own way.
=> test: Fix secondary error thrown from unhandled errors

lib/media/streaming_engine.js
In #7368, we get stuck in a loop loading forever.  This regression was introduced in v4.4.0 and affects all v4.4, v4.5, v4.6, v4.7, and v4.8 releases, as well as v4.9.0-28, v4.9.2-caf1, v4.10.0-20, and v4.11.0-6.
The loop is composed of these elements:
1. an error that triggers disabling a stream
2. an error that doesn't resolve itself over time
3. an error that is slow enough to trigger that the first streams get re-enabled
4. VOD content that doesn't change while we sit in the loop
5. enough streams to avoid exhausting them during the cycle
Only `TIMEOUT` errors can trigger this bug AFAICT, so we should exclude those from the logic to disable streams.  Note also that live streaming already retries indefinitely by default, and that normal ABR logic will change streams for us if we …
=> fix: Exclude TIMEOUT errors when disabling streams

lib/polyfill/media_capabilities.js
=> fix: Reduce calls to EME by ignoring MIME type in MediaKeySystemAccess cache

test/codec_switching/codec_switching_integration.js
Previously we were disabling tests only by using `supportsSmoothCodecSwitching()` method, but it checks only user agent and not API existence.
=> test: Disable codec switch smooth test if changeType() is unavailable

lib/util/platform.js
Recent tests have shown that although `SourceBuffer.changeType()` exists on PS5, calling it when switching between AAC and EC3 always throws an exception. Disable smooth codec switch on that platform together with PS4.
=> fix(PS4/5): Disable smooth codec switch on PS4/5

lib/media/drm_engine.js, lib/media/media_source_engine.js, lib/player.js, lib/util/dom_utils.js, test/media/media_source_engine_integration.js, test/media/media_source_engine_unit.js, test/player_load_graph_integration.js, test/player_src_equals_integration.js, test/test/util/simple_fakes.js, ui/ui.js
Needed for #5022 
This PR does not enable AirPlay on MSE yet, but moves shaka from using `src` attribute to `source` tags. With this change we will be able to enable it more easily, as `src` and `source` should not be used together.
=> feat: Use source tags instead of src attribute

lib/dash/segment_template.js
fix(DASH): Live DASH allows segment overlap in the updated manifest for first new segments to avoid creating GAP with ms inaccurate manifest vs Segment duration and start time
Fixes https://github.com/shaka-project/shaka-player/issues/7397
=> fix(DASH): Live DASH allows segment overlap in the updated manifest for first new segments

test/ui/ui_unit.js, ui/ui.js
In 4425dca2, we broke auto-loading content with `<source>` tags or `src=` in the UI, such that we tried to load content before we had attached a video element.  That was almost a year ago.  Oops!
This also adds an appropriate unit test.
=> fix(UI): Fix auto-load with source tags

ui/ui.js
This change is necessary because the remote playback button is not in the initial list, and this causes it to be positioned in last place when we do not want this to happen.
=> fix(UI): Fix the position of save video frame in the overflow menu

test/ui/ui_unit.js
The promise for DOM auto setup tests doesn't guarantee that load() is complete, only that we started it.  So checking video duration causes flake, in particular on slow devices like Tizen.  Instead, check for the player to have an asset URI.
=> test: Fix DOM autosetup test flake

lib/dash/dash_parser.js, test/dash/dash_parser_manifest_unit.js
Fix tag:dolby.com,2014:dash:audio_channel_configuration:2011 scheme to correctly handle bits that represent channel pairs according to document at [dolby.com](https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.5/Documentation/Content_Creation/SDM/help_files/topics/ddp_mpeg_dash_c_mpd_auchlconfig.html)
Add tag:dolby.com,2015:dash:audio_channel_configuration:2015 scheme according to ETSI TS 103 190-2 v1.2.1, Annex G.3
Test stream is available here: [manifest.mpd](https://content.media24.link/ac4_512/manifest.mpd)
=> fix: calculations of channel count for DASH AudioChannelConfiguration elements.

.github/workflows/selenium-lab-tests.yaml
When we have two jobs queued for FirefoxWindows, for example, we want one of them to wait, not cancel each other.  The only time you would cancel one is if the other is from the same branch/PR after an update.  Right now, only the browser name is used in the key, so we should never cancel another job with the same key.
This fix lets us start tests for multiple release PRs at once.
=> ci: Do not cancel other Selenium jobs

lib/media/media_source_engine.js
Fixes https://github.com/shaka-project/shaka-player/issues/7473
=> fix: Fix metadata timing when using TS

externs/shaka/ads.js, lib/ads/ad_utils.js, lib/ads/interstitial_ad.js, lib/ads/interstitial_ad_manager.js, ui/skip_ad_button.js
Close: https://github.com/shaka-project/shaka-player/issues/7466
=> feat(Ads): New HLS interstitial DATERANGE attributes for Skip Button

lib/dash/content_protection.js, lib/util/error.js, lib/util/player_configuration.js, test/dash/dash_parser_content_protection_unit.js
Support Fairplay DRM for DASH, specifying the license server in the manifest using dashif:Laurl.
For example, multi-drm manifest is here: https://content.media24.link/drm/manifest.mpd
=> feat: Support Fairplay DRM in DASH manifest.

lib/ads/interstitial_ad_manager.js
Currently, if the interstitial lasts 30 and we have a stream that lasts 31 seconds, we would go back to live after the interstitial, but with 1 extra second of latency. This PR solves this by limiting the play range to 30.
Related to https://github.com/shaka-project/shaka-player/pull/7480
=> fix(Ads): Limit interstitial duration to actual duration if available when using src=

lib/util/mp4_generator.js
With this change, no default flags are used. It seems that when a sample has to use the default flags, in Safari, it can cause problems with MSS. With HLS this does not happen.
Fixes https://github.com/shaka-project/shaka-player/issues/7509
=> fix(MSS): Fix playback of some MSS streams

lib/ads/interstitial_ad_manager.js
Previously we relied on an event triggered by the video itself which was launched 4 to 60 times per second, which meant that we had an update (in the worst case) of 250ms. Now we use a timer that is triggered every 25ms, which considerably reduces the delay.
This is important so as not to show anything from the original ad's live.
=> perf(Ads): Reduce latency for interstitial to start playing

demo/config.js, externs/shaka/player.js, lib/media/playhead.js, lib/util/player_configuration.js
Close https://github.com/shaka-project/shaka-player/issues/7531
=> feat: Add safeSeekEndOffset feature for live reposition

externs/shaka/ads.js, lib/ads/client_side_ad.js, lib/ads/interstitial_ad.js, lib/ads/interstitial_ad_manager.js, lib/ads/media_tailor_ad.js, lib/ads/server_side_ad.js, test/test/util/fake_ad.js, ui/controls.js, ui/fullscreen_button.js
Only disable fullscreen button when the devices doesn't support the standard Fullscreen API and playing an ad that use another media element
Fixes https://github.com/shaka-project/shaka-player/issues/6133
=> fix(UI): Disable fullscreen button conditionally when playing ads

lib/media/streaming_engine.js
Instead of checking for both lastSegmentReference and lastInitSegmentReference, we shoould only check lastSegmentReference.
As of shaka-project/shaka-player#6929, init segment references aren't cleared on clearBuffer, this onInitSegmentAppended not account for the safe margin properly.
=> fix: only use lastSegmentReference for knowing if variant changed

lib/media/preload_manager.js, lib/media/segment_prefetch.js, test/test/util/fake_segment_prefetch.js
Previously, the PreloadManager would consider a preload "finished" after a few major files like the manifest had been preloaded. It would start prefetching some segments, but wouldn't wait on it to notify the developer.
This PR changes the PreloadManager so that
PreloadManager.waitForFinish won't return until the prefetched segments have finished loading.
Because of that, this also better surfaces errors thrown during segment prefetching, when preloading.
Issue #7520
=> feat(preload): Wait for prefetches when preloading

.github/workflows/deflake.yaml
Deflaking tests depends on an exact workflow name, but #7535 renamed the test workflow.  This syncs the name in the deflake workflow.
=> ci: Fix test deflake

.github/workflows/build-and-test.yaml, .github/workflows/demo-version-index.yaml, .github/workflows/nightly-demo.yaml, .github/workflows/release-please.yaml, .github/workflows/selenium-lab-tests.yaml, .github/workflows/update-screenshots.yaml
This was found by auditing workflows based on research published here:
https://github.com/joeyparrish/workflow-cheat-sheet
The research was prompted by a workflow bug in Shaka Streamer
=> ci: Fix workflow events

lib/util/platform.js, ui/controls.js, ui/externs/ui.js, ui/ui.js
With this config we will use the fullscreen API of the video element itself if it is available in Vision OS. This is useful to be able to access 3D experiences that are only allowed with the fullscreen of the video element itself.
=> feat(UI): Allow configure the fullscreen mode in VisionOS

demo/common/assets.js
The Shaka Player History live stream is available again, now with AV1!
The stream loops over the history of Shaka Player commits, and the loop gets longer every time a PR is merged.
Brought to you by:
- https://github.com/shaka-project/shaka-streamer
- https://github.com/shaka-project/shaka-packager
- https://github.com/FFmpeg/FFmpeg
- https://github.com/acaudwell/Gource
- https://github.com/shaka-project/shaka-player-history
=> chore: Re-enable Shaka Player History live stream

lib/media/media_source_engine.js
Fixes https://github.com/shaka-project/shaka-player/issues/7399
This PR resolves issue https://github.com/shaka-project/shaka-player/issues/7399 which has the same pid for audio and video, but they are different segments.
=> fix: Do not reuse the same tsParser for different contentType

demo/config.js, externs/shaka/player.js, lib/media/media_source_engine.js, lib/media/streaming_engine.js, lib/player.js, lib/util/player_configuration.js, test/cast/cast_utils_unit.js, test/media/drm_engine_integration.js, test/media/media_source_engine_integration.js, test/media/media_source_engine_unit.js, test/media/streaming_engine_integration.js, test/media/streaming_engine_unit.js
With the change, we reuse MediaSource's MP4 parsing code to avoid parsing everything twice.
It will also help with the implementation of https://github.com/shaka-project/shaka-player/issues/7556 in the future.
=> perf: Improve performance when parsing EMSG

externs/shaka/player.js, lib/player.js, lib/util/player_configuration.js, test/demo/demo_unit.js
For some niche cases where content is only available at resolutions beyond the device's native resolution, and you are confident it can be decoded and downscaled, this flag can allow playback when it would otherwise fail.
=> feat: Add config to ignore hardware resolution

.github/workflows/selenium-lab-tests.yaml, .github/workflows/update-screenshots.yaml
To report commit status on a PR, the head commit must be used, not the merge of that head back into the target (e.g. into main).
I would prefer to make status reporting special, so that we can run tests and other operations against the merge (for more realistic results and to avoid test failures that only show up after a merge).  But this is the quickest way for me to fix this critical feedback.
=> ci: Fix status reporting on PRs

.github/workflows/release-please.yaml
This uses very explicit ref names for both source and destination, to fix this error during branch creation:
>   TAG=v4.12.0
>   BRANCH=$(echo "$TAG" | sed -e 's/\.0$/.x/')
>   git push origin HEAD:"$BRANCH"
>
> error: The destination you provided is not a full refname (i.e.,
> starting with "refs/"). We tried to guess what you meant by:
>
> - Looking for a ref that matches 'v4.12.x' on the remote side.
> - Checking if the <src> being pushed ('HEAD')
>   is a ref in "refs/{heads,tags}/". If so we add a corresponding
>   refs/{heads,tags}/ prefix on the remote side.
>
> Neither worked, so we gave up. You must fully qualify the ref.
> hint: The <src> part of the refspec is a commit object.
> hint: Did you mean to create a new branch by pushing to
> hint: 'HEAD:refs/heads/v4.12.x'?
> error: …
=> ci: Fix auto-branch job

demo/main.js, lib/player.js, lib/text/ui_text_displayer.js
Fixes https://github.com/shaka-project/shaka-player/issues/7568
=> fix: Prefer SimpleTextDisplayer on iOS

demo/main.js
When testing from different parts of the world, the Akamai server always has a better response time, so it is changed to this one by default.
=> chore(Demo): Change manifest.dash.clockSyncUri in the Demo

lib/ads/interstitial_ad_manager.js
This is necessary because in our UI when reusing the same video element the unloading event is launched and we clear the cuepoints with that event.
=> fix(Ads): Always fire CUEPOINTS_CHANGED when not using multi video elements

test/util/periods_unit.js
Add test related to https://github.com/shaka-project/shaka-player/commit/5eff0384d04e22a971336c90aae0a83db2a451d5
Fixes https://github.com/shaka-project/shaka-player/issues/7516
=> test: Add unit tests for DASH period eviction

lib/net/networking_engine.js
=> fix: Calculate timeToFirstByte before fire the event 'downloadheadersreceived'

lib/util/platform.js
It seems all Tizen versions do not support smooth codec switch for now.
Additionally I removed webOS versions listed here, as they don't have `SourceBuffer.changeType()` API anyway. They're available since Chrome 70, but webOS 5 uses Chrome 68.
And rephrased docs a bit.
=> fix: Disable smooth codec switch on Tizen 8

docs/tutorials/faq.md, docs/tutorials/manifest-parser.md, docs/tutorials/network-and-buffering-config.md, externs/shaka/manifest.js, externs/shaka/player.js, lib/dash/dash_parser.js, lib/hls/hls_parser.js, lib/media/playhead.js, lib/media/streaming_engine.js, lib/mss/mss_parser.js, lib/offline/manifest_converter.js, lib/player.js, test/dash/dash_parser_manifest_unit.js, test/media/playhead_unit.js, test/media/streaming_engine_integration.js, test/media/streaming_engine_unit.js, test/offline/storage_compatibility_unit.js, test/test/util/manifest_generator.js, test/test/util/streaming_engine_util.js
Related to https://github.com/shaka-project/shaka-player/issues/7602#issuecomment-2479518970
From 23009-1:
The value of the minimum buffer time does not provide any instructions to the client on how long
to buffer the media. The value however describes how much buffer a client should have under
ideal network conditions. As such, MBT is not describing the burstiness or jitter in the network,
it is describing the burstiness or jitter in the content encoding. Together with the BW value, it is
a property of the content. Using the "leaky bucket" model, it is the size of the bucket that makes
BW true, given the way the content is encoded
=> feat: Update usage of minBufferTime according to the DASH spec

ui/chapter_selection.js
If the remote player does not have getChapters(), the proxied call returns undefined.  This led to exceptions when .length was accessed.
Reported as part of issue #7546
=> fix(UI): Fix exception while casting to mismatched player version

.eslintrc.js, lib/polyfill/media_capabilities.js, package-lock.json, package.json
Also document what is recognized, how, and why those strings are used.
=> fix: Fix cast support for HLG HDR

lib/util/platform.js, test/util/platform_unit.js
In our preliminary tests webOS 6 does not support smooth codec switch, but webOS 22 (so the next one) does, so hopefully this will be the last adjustment in this method.
=> fix: Disable smooth codec switch on webOS 6

lib/util/abortable_operation.js
On PS5 we are seeing following uncaught exceptions when requests are aborted:
```
[Error] Fetch is aborted – PromiseRejectionEvent {isTrusted: false, promise: Promise, reason: AbortError: Fetch is aborted, …}
PromiseRejectionEvent {isTrusted: false, promise: Promise, reason: AbortError: Fetch is aborted, type: "unhandledrejection", target: Window, …}PromiseRejectionEvent
(anonymous function) (Anonymous Script 1 (line 429))
[Error] Unhandled Promise Rejection: AbortError: Fetch is aborted
promiseEmptyOnRejected
promiseReactionJob
```
=> fix(PS5): Prevent uncaught promise rejections when requests are aborted

build/eslint-plugin-shaka-rules/array-no-instanceof.js, build/eslint-plugin-shaka-rules/index.js, test/test/util/manifest_parser_util.js, test/test/util/ttml_utils.js
Roughly related to #6279.
Whenever possible, we should limit usage of `instanceof` operator for the sake of `documentPip` mode.
=> chore: Forbid using instanceof on arrays

build/types/core, lib/player.js, lib/util/number_utils.js, test/util/number_utils_unit.js
Due do rounding errors the progress events were fired way too early (especially the complete event on longer videos). This changes use float comparison to mitigate the issue.
Further improvements (video with start time, seek handling) will be added in follow up PRs.
=> fix: Fix video progress events accuracy

build/eslint-plugin-shaka-rules/arraybuffer-no-instanceof.js, build/eslint-plugin-shaka-rules/buffersource-no-instanceof.js, build/eslint-plugin-shaka-rules/index.js, lib/cast/cast_utils.js, lib/net/http_xhr_plugin.js, lib/util/buffer_utils.js, lib/util/object_utils.js, lib/util/uint8array_utils.js, test/test/util/canned_idb.js
=> fix: Forbid usage of instanceof ArrayBuffer

lib/ads/interstitial_ad_manager.js
Fixes https://github.com/shaka-project/shaka-player/issues/7665
=> fix(Ads): Fix behavior when user JUMPS across more than one interstitial

test/ads_integration.js
VAST and VMAP parsing are now covered by unit tests, and ad playing is already covered by the other HLS and DASH tests since the same code is used internally. There is no change in coverage.
=> test: Remove some flaky integration test covered with unit tests

lib/media/media_source_engine.js, lib/text/vtt_text_parser.js
Fixes https://github.com/shaka-project/shaka-player/issues/7673
=> fix(HLS): Fix subtitle timing when no discontinuity but there is X-TIMESTAMP-MAP

lib/media/drm_engine.js, lib/media/preload_manager.js, test/test/util/fake_drm_engine.js
=> fix(preload): Wait for drm keys when preloading

lib/util/object_utils.js, lib/util/stream_utils.js
Add special case for arrays, for compatibility with frameworks or polyfills that add properties to Array or Array instances.
Add special case for functions, which always contain circular references and are unexpected in this context.  These seem to appear because of the frameworks/polyfills mentioned above.
Move everything to ObjectUtils, since this is extremely generic.
Closes #7435
=> fix: Avoid stack overflow when stringifying objects

lib/dash/dash_parser.js, lib/hls/hls_parser.js, test/dash/dash_parser_manifest_unit.js, test/hls/hls_parser_unit.js
Based on the work of @gmcgarry Thank you very much!
Currently the codec adds supplemental codecs to the list of allCodecs and has an implicit priority order to select a codec. Support for the codec is tested with MediaSource.isTypeSupported().
There are multiple issues with this approach:
- the priority is implicit
- MediaSource.isTypeSupported() decision is effectively overriding platform-specific MediaCapabilities logic
- MediaSource.isTypeSupported() is frequently wrong depending on whether the content is encrypted
This patch duplicates the variant with each supplemental codec and defers codec priority and codec selection until after MediaCapabilities.decodingInfo().
This fixes support for DolbyVision Profile 8, which is otherwise broken because the chromium browsers always return …
=> fix: Fix support for supplemental codecs (Dolby Vision)

lib/util/stream_utils.js, test/player_unit.js
There should not be any call to isTypeSupported if we have already used Mcap with the same codecs/mimeType
=> perf: Reduce calls to isTypeSupported

.github/workflows/deflake.yaml, .github/workflows/selenium-lab-tests.yaml, .github/workflows/update-issues.yaml
Now that default permissions are read-only, we must enable specific permissions for certain workflow jobs.
This fixes every job except "update screenshots", which has unresolved permissions issues.
=> ci: Update workflow permissions

demo/config.js, externs/shaka/player.js, lib/player.js, lib/util/mime_utils.js, lib/util/player_configuration.js, test/player_unit.js
This is useful for WebOS, because in MSE there is no support for VVC but there is support for src=
=> feat: Add streaming.preferNativeDash config

docs/design/gap-jumping.md
`smallGapsLimit` and `largeGaps` have been removed.
=> fix(Docs): Remove info about small/large gaps from manual

.github/workflows/build-and-test.yaml, .github/workflows/demo-version-index.yaml, .github/workflows/release-please.yaml, .github/workflows/report-incremental-coverage.yaml, .github/workflows/selenium-lab-tests.yaml, .github/workflows/talk-to-shaka-bot.yaml, .github/workflows/update-screenshots.yaml
See https://github.com/actions/checkout/issues/485 and https://johnstawinski.com/2024/01/11/playing-with-fire-how-we-executed-a-critical-supply-chain-attack-on-pytorch/
In short, it is a terrible idea to persist even our default credentials after checkout.  There's no call for that, so we will now set `persist-credentials: false` on all checkout actions.
The only exceptions are for the release job, which wants to push a tag and create a branch, each of which explicitly persist credentials now and explain why in a comment.
=> ci: Do not persist credentials after checkout

lib/media/media_source_engine.js, test/media/media_source_engine_unit.js
Builds on top of @tykus160's observation in https://github.com/shaka-project/shaka-player/issues/4903 where `MediaSource.readyState` was either in a `closed` or `ended` state when the `MediaSourceEngine.init()` logic is executed. 
This fix will simply re-open the `MediaSource` if non-open, resulting in fewer scenarios where the `MEDIA_SOURCE_OPERATION_THREW` error: https://github.com/shaka-project/shaka-player/blob/de0f33c2623b057e80b7cafd53e19fac2f984961/lib/media/media_source_engine.js#L648-L651
is thrown because of an [`InvalidStateError`](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/addSourceBuffer#exceptions).
=> fix: re-open the `MediaSource` if `readyState` is not open when the `init()` method is called.

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/7766
=> fix(HLS): Correctly identify webvtt subtitles with cmft extension

demo/config.js, demo/main.js, docs/tutorials/upgrade.md, externs/shaka/player.js, lib/drm/drm_engine.js, lib/player.js, lib/util/player_configuration.js, lib/util/stream_utils.js, test/drm/drm_engine_unit.js
This changes the `drm.advanced.videoRobustness` and `audioRobustness` config options from a string to an array of strings. Internally, in the drm engine, this gets expanded into an array of `DrmInfos` which have those values as strings.
Best way to review this change is with whitespace turned off in the diff options.
=> feat: add support for multiple robustness levels in drm

lib/drm/drm_engine.js, test/drm/drm_engine_unit.js
Related to https://github.com/shaka-project/shaka-player/pull/7453
Thanks @gmcgarry !
=> fix: Don't ignore the license server in manifest when another key-system has license server in configuration

demo/config.js, externs/shaka/player.js, lib/drm/drm_engine.js, lib/drm/drm_utils.js, lib/util/player_configuration.js, test/drm/drm_utils_unit.js
The following bug is avoided in Chromium: `It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.Understand this warningAI`
It also prevents errors when initializing EME on Android.
Fixes https://github.com/shaka-project/shaka-player/issues/7760
=> fix(Widevine): Add default audio/video robustness for Widevine

lib/media/media_source_engine.js, lib/util/stream_utils.js, test/transmuxer/transmuxer_integration.js
It also enables a test that has been disabled due to this bug.
=> fix: Remove useless calls to isTypeSupported

lib/cast/cast_utils.js, lib/player.js, ui/controls.js, ui/play_button.js
When 'playRangeStart' and/or 'playRangeEnd' is specified in the config, limit the actual play range to this range.
In particular, this means stop the video after playRangeEnd. This implies that 'video.ended' is no longer a good marker of the end of the video.
=> fix: Follow the configured playRange for src=

lib/cea/cea708_service.js, lib/cea/dtvcc_packet_builder.js, test/cea/cea708_service_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/7829
=> fix(CEA): Fix multi byte language support in CEA-708

lib/hls/hls_parser.js
Per the HLS spec, we require a START-DATE for SCTE35-IN 
However, unlike for SCTE35-OUT and SCTE35-CMD, it’s not clear what that value should be – and the HLS spec example does not include it.
=> fix(HLS): Omit daterange without START-DATE in order to avoid errors

lib/offline/download_manager.js, lib/offline/storage.js
Fixes https://github.com/shaka-project/shaka-player/issues/6311
=> fix(Offline): Fix some aborted downloads continue to download

demo/custom.js
Related to https://github.com/shaka-project/shaka-player/issues/7546
=> chore(Demo): Fix "Custom DRM System" field when set to known drm system

lib/dash/dash_parser.js, test/dash/dash_parser_manifest_unit.js
The correct way is to use JOC, but some packagers do not use it.
=> fix(DASH): Fix Dolby Atmos detection when there is not SupplementalProperty

lib/dash/mpd_utils.js, lib/dash/segment_template.js, test/dash/dash_parser_segment_template_unit.js, test/test/util/manifest_parser_util.js
`$Time$` in SegmentTemplate should not be adjusted for presentationTimeOffset or Period start.  It should always match the segment's own media timestamp as it appears in the manifest.
=> fix(dash): Fix $Time$ usage with SegmentTemplate

lib/net/http_fetch_plugin.js, lib/net/http_plugin_utils.js
The Cast SDK currently assumes that SEGMENT response objects always have data, however this stopped being true for HEAD requests in v4.3.6.
This PR fixes the behavior of the Fetch plugin so that HEAD requests will at least have an empty ArrayBuffer for data, as they did in v4.3.5 and earlier.
The Cast SDK will also receive a fix to stop assuming this, fixing compatibility with v4.3.6+ - v4.12.6.
This incompatibility between the current Cast SDK and these versions of Shaka Player is only triggered by HLS content whose segment URLs have no recognizable extension.
Affected Shaka Player versions:
- v4.3.6 - v4.3.16
- v4.4.x - v4.8.x
- v4.9.0 - v4.9.34
- v4.9.2-caf - v4.9.2-caf4
- v4.10.x
- v4.11.0 - v4.11.18
- v4.12.0 - v4.12.6
Affected Cast Web Receiver SDK versions:
- <= 3.0.0137
Fixes will …
=> fix: Fix SEGMENT HEAD requests, compatibility with Cast SDK

README.md, lib/drm/drm_engine.js, lib/hls/hls_parser.js, lib/offline/storage.js, lib/util/player_configuration.js, package-lock.json, package.json, project-words.txt, test/dash/dash_parser_content_protection_unit.js, test/hls/hls_parser_unit.js
Some info:
https://drmnow.pro/wiseplay/
https://developer.huawei.com/consumer/en/doc/Media-Guides/client-dev-0000001050040000
=> feat: Add support for WisePlay DRM

.github/workflows/release-please.yaml
google-github-actions/release-please-action has been deprecated and replaced with googleapis/release-please-action.
=> ci: Update release-please-action

.github/workflows/build-and-test.yaml
This is meant to fix errors like "Failed request: (409) Conflict: an artifact with this name already exists on the workflow run" which occur when more than one instance of a browser fails tests in the same run.
The change in behavior that led to the error likely began after updating actions/upload-artifact.
=> ci: Fix screenshot upload

lib/drm/drm_engine.js
Fixes https://github.com/shaka-project/shaka-player/issues/4199
=> fix: Silence uncaught rejection errors when closing EME sessions

externs/shaka/player.js, lib/media/adaptation_set.js, lib/media/adaptation_set_criteria.js, lib/media/example_based_criteria.js, lib/media/preference_based_criteria.js, lib/media/preload_manager.js, lib/player.js, lib/util/player_configuration.js, test/media/adaptation_set_criteria_unit.js, test/player_unit.js
This exports AdaptationSet, and AdaptationSetCriteria to enable an `adaptationSetCriteriaFactory` method to allow for shaka users to provide their own implementation of a class that implements AdaptationSetCriteria.
Fixes #7768
=> feat: Add adaptation set criteria factory configuration

.github/workflows/nightly-demo.yaml
There is no need to do this anymore because we always use that ID in any release
=> chore: Remove "Override Cast Receiver App ID" in the nightly workflow

.github/workflows/demo-version-index.yaml, .github/workflows/release-please.yaml
Fixes https://github.com/shaka-project/shaka-player/issues/7379
=> ci: Fix demo index workflow runs too early when a release is made

.github/workflows/demo-version-index.yaml
The `workflow_call` trigger is required to allow calling a workflow from another with "uses:".  The `schedule` trigger was always a workaround, and should now be removed.
See also PR #7892.
=> ci: Fix trigger for version index workflow

externs/shaka/player.js, lib/util/player_configuration.js
Fixes https://github.com/shaka-project/shaka-player/issues/7899
=> fix: Use infiniteLiveStreamDuration equal to true in Safari 17 or above

lib/dash/segment_template.js
Now we always are fitting the timeline
=> fix(DASH): Ignore early segments in a period

lib/media/streaming_engine.js
Some older devices require the range to be greater than 1 or exceptions are thrown, due to an old and buggy implementation.
=> fix: Fix setLiveSeekableRange when the seekable range is too short

lib/offline/stream_bandwidth_estimator.js
=> chore: Stop using "Object" in StreamBandwidthEstimator annotations

lib/mss/mss_parser.js
=> chore: Stop using "Object" in MSS annotations

lib/util/stream_utils.js
=> chore: Stop using "Object" in DV codecs mapping

lib/cea/mp4_cea_parser.js
=> chore: Stop using "Object" in MP4-CEA annotations

lib/cast/cast_proxy.js, lib/cast/cast_receiver.js, lib/cast/cast_sender.js, lib/cast/cast_utils.js, test/cast/cast_receiver_unit.js, test/cast/cast_utils_unit.js
=> chore: Stop using "Object" in Cast functions

third_party/closure-uri/uri.js
=> chore: Stop using "Object" in goog.Uri annotations

externs/shaka/player.js, lib/util/player_configuration.js, test/media/streaming_engine_unit.js, test/ui/ui_unit.js
Closes #1352
Segment prefetch keeps the segments until the position of the segment to be requested changes, which is exactly what happens when the QuotaExceededError error occurs. So enabling this by default with a value of 1 solves this problem.
=> feat: Retain segment in memory on QuotaExceededError

lib/dash/dash_parser.js, test/dash/dash_parser_manifest_unit.js
dolby digital plus tracks can have a bandwidth of exactly 384000
Fixes https://github.com/shaka-project/shaka-player/issues/7965
=> fix(DASH): Fix Dolby Atmos detection

lib/media/content_workarounds.js, lib/media/media_source_engine.js, lib/util/platform.js, lib/util/stream_utils.js, test/media/media_source_engine_unit.js
Fixes https://github.com/shaka-project/shaka-player/issues/7955
=> fix: Fix AC-3 playback on Tizen 3.0 devices

lib/media/example_based_criteria.js, lib/player.js
Fixes https://github.com/shaka-project/shaka-player/issues/7968
=> fix: Use audio label on ExampleBasedCriteria

build/conformance.textproto, eslint.config.mjs
For some reason closure config does not work correctly, so enable equivalent ESLint rule.
=> chore: Disable console logs in ESLint

lib/media/preload_manager.js, lib/media/region_observer.js, lib/media/region_timeline.js, lib/player.js, test/media/region_observer_unit.js, test/media/region_timeline_unit.js
This will allow experimentation on storing other things inside it.  We still store shaka.extern.TimelineRegionInfo in all current usage.
=> chore: Templatize RegionTimeline

lib/player.js
This can happen with HLS, when there is Widevine with keyId and PlayReady without keyId and the system only supports Playready.
=> fix: Avoid launch RESTRICTIONS_CANNOT_BE_MET when it's not necessary

lib/text/cue.js
=> fix(Subtitles): Prevent rounding errors when filtering duplicated cues

lib/util/cmcd_manager.js
b2673fd (#7412) introduced a call to video.play() in a function that says "Set start time of load if autoplay is enabled", but the function did not actually check the autoplay attribute.  This fixes the oversight.
Fixes #8022
=> fix: Do not autoplay if autoplay is not set

lib/media/media_source_engine.js, lib/media/streaming_engine.js, test/media/streaming_engine_unit.js
This avoid keep in the buffer content that is not necessary.
=> fix: Evict the buffer against seekRangeStart

lib/media/streaming_engine.js
Related to https://github.com/shaka-project/shaka-player/pull/7994
=> feat: Change the way to handle the STREAMING_NOT_ALLOWED error

lib/polyfill/media_capabilities.js, lib/util/platform.js, test/util/platform_unit.js
Our Apple device detection misdetects any Webkit-based STB as Apple, due to looking only at vendor property. To mitigate it, we were excluding another user agents, but maintenance of this is problematic.
This PR tries to change direction - an Apple device right now is a device with Apple vendor AND with characteristics of MacOS or iOS.
=> chore: Simplify Apple detection

lib/player.js
This was introduced with version 4.13.0
This is a simple oversight on arguments of the function `this.currentAdaptationSetCriteria_.configure(...)` and made sure this was following the doc here https://shaka-player-demo.appspot.com/docs/api/shaka.media.AdaptationSetCriteria.html#.Configuration
Fixes https://github.com/shaka-project/shaka-player/issues/8037
=> fix: audio label when selecting variants by label

lib/player.js, lib/util/error.js
Related to https://github.com/shaka-project/shaka-player/issues/8042
=> fix: Throw preload destroyed error when re-using same preloadManager

lib/media/playhead.js, test/media/playhead_unit.js
MediaSource's setLiveSeekableRange overrides seeks outside the seekable range automatically without any additional corrective seeking.  When this API is active, we should not make additional corrective seeks in Playhead.
=> feat: Do not make corrective seeks when setLiveSeekableRange is used

lib/util/periods.js, test/util/periods_unit.js
Fixes #8052
Key ids were not used when looking for stream duplicates, so it was possible to filter out streams without accompanying configuration. Now we will use key ids as well for duplicates detection.
=> fix(DASH): Fix playback of ClearKey when only part of keys are defined

build/generateExterns.js
Add `@suppress {constantProperty}` to generated shaka externs to fix build errors in external projects.
=> chore: Add @suppress {constantProperty} to shaka externs.

build/generateExterns.js
Add `@suppress {constantProperty}` to shaka externs.
Cherry-picked from v4.13.x, where the original PR was sent by mistake.
=> chore: Add @suppress {constantProperty} to shaka externs. (#8062)

lib/util/tXml.js, test/util/tXml_unit.js
This is not in the spec, but it is used to make some malformed content work. Dash.js already does this by default.
=> fix(tXml): Allow case insensitive in parseDuration

lib/ads/interstitial_ad_manager.js
This is necessary because you can have two interstitials in a row where the first one uses playRangeEnd but the second one doesn't. Without this fix the second one would have the same playRangeEnd as the first one, but this is wrong.
=> fix(Ads): Reset playRangeEnd value between interstitials

ui/less/thumbnails.less
The thumbnail sometimes stuck (would not disappear) when mouse cursor hovers over it (not over seek bar)
Steps to reproduce:
- Get local demo running (python build/all.py --debug?)
- Find a video with thumbnail to play
Bug reproduction
https://github.com/user-attachments/assets/d0212307-7d12-41e0-af22-c111f019cae8
Reported in https://github.com/FreeTubeApp/FreeTube/issues/5965
Fix from https://github.com/FreeTubeApp/FreeTube/pull/6812
=> fix(UI): Fix thumbnail sometimes not disappearing due to mouse hover

lib/drm/drm_engine.js
Our automated test lab runs Windows browsers under a headless service.  In this environment, Firefox's ClearKey CDM seems to crash when we create the CDM in probeSupport().
To avoid this, we check for a debug or uncompiled build running in Firefox on Windows, and if this combination is found, we skip createMediaKeys() in probeSupport().
Because the check uses the compile-time constant goog.DEBUG, we avoid any penalty in a production build.
=> test: Fix crash of Firefox on Windows

lib/util/platform.js, lib/util/stream_utils.js, ui/remote_button.js
This replacement is safe to do and also reduces the number of internal operations to obtain the result.
=> fix: Remove isSafari and always use isApple

.github/workflows/update-screenshots.yaml
This keeps the job from failing if a one-off PR for screenshots already exists.
=> ci: Check if screenshot PR exists before creating new one

lib/player.js
`getAllThumbnails` creates an array of promises when grabbing each thumbnail. This is because `getThumbnails` might have to create a segment index, but `getAllThumbnails` already does this. This separates `getThumbnails` into two functions so `getAllThumbnails` can get the thumbnails synchronously.
=> perf: Remove promises from getAllThumbnails loop

.github/workflows/selenium-lab-tests.yaml, build/test.py, karma.conf.js, test/test/util/layout_tests.js
Native text layout in Safari renders differently on different devices, OS versions, and with different OS a11y settings.  Because this is so inconsistent across devices, we now have a flag to explicity enable native text layout tests on Safari.  This flag will be used in our lab only.  Our lab tests on Safari will be the source of canonical results for Safari layout tests.
=> ci: Only run Safari native layout tests in lab

lib/dash/dash_parser.js, test/dash/dash_parser_manifest_unit.js
Reverts https://github.com/shaka-project/shaka-player/commit/cf581cd039db62b658f6851590b6c623bd7bf924 Reverts https://github.com/shaka-project/shaka-player/commit/56c5f52c9a69d87f005163f7d0def1a49d8d599d
=> fix(DASH): Revert Dolby Atmos detection when there is not SupplementalProperty

lib/util/stream_utils.js, test/util/stream_utils_unit.js
=> fix: Check bandwidth when filtering streams

lib/drm/drm_engine.js
My previous change, #8109, didn't go far enough.  In a full test run, some ClearKey tests still crash Firefox in the lab.  By removing it from the support dictionary used to gate DRM tests, we ensure all ClearKey tests are skipped.
=> test: Reject all FF+Windows ClearKey testing

.github/workflows/update-screenshots.yaml
If a maintainer requests screenshot updates in a new PR, but there are no changes, simply don't create a PR.
Also adds logs to make it clear which path was taken.
=> ci: Handle screenshot updates with no changes

.github/workflows/custom-actions/prep-for-appspot/action.yaml, .github/workflows/demo-version-index.yaml, app-engine/gcloudignore
Naive use of google-github-actions/auth and google-github-actions/deploy-appengine can lead to leaked credentials.
In particular, uploading static content from the workspace root leads to servable copies of the credentials file written by google-github-actions/auth.  This is exactly what the Shaka Player Demo did.  Making matters worse, google-github-actions/auth logs credential filenames for all to see.
All uploaded credentials were expired before I uploaded this PR.
This fixes the leak by installing a gcloudignore file which prevents the credentials from being uploaded.
=> ci: Prevent leaked credentials

test/player_dolby_vision_integration.js
This is because Apple has introduced a regression in their latest versions and now they do not work correctly. I hope we can revert this in a few months.
=> test: Disable DV-P8 tests on Safari

test/hls/hls_parser_integration.js
Our logic never waits for subtitles, so we need to increase the playback time to ensure we process the subtitles correctly. This error is only seen on slow devices, for example Tizen.
=> test: Increase playback time on HLS integration test

lib/dash/segment_template.js
`TimelineSegmentIndex` `fitTimeline` doesn't check if `templateInfo` is null. This means it errors in this case when it tries to access the `timeline` property. It now exits early if it's null
=> fix: Fit template check template info

ui/ad_statistics_button.js, ui/context_menu.js, ui/settings_menu.js, ui/statistics_button.js
Close https://github.com/shaka-project/shaka-player/issues/8192
=> feat(UI): Close submenu or context menu on option click

lib/util/stream_utils.js, test/util/stream_utils_unit.js
Fixes ccbbb01e55aa04c657caea2b253a329e077af9c3 that broken codec selection on https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
=> fix: Fix codec selection

docs/tutorials/text-displayer.md, lib/text/ui_text_displayer.js, test/text/ui_text_displayer_unit.js, ui/less/containers.less
With reference to #8025, this is a partial proposal to see if this style of extensible customisation could be favourable to the shaka-player community:
Proposal for some accessibility options whereby an App builder can customise subtitle/caption size, with the potential of an App offering accessibility options for text size.
This style could be used for other text styling attributes in a similar way, but this is just the first step.
=> feat: Text font scaling customisation ability

ui/hidden_seek_button.js
Related to https://github.com/shaka-project/shaka-player/issues/8199
=> fix(UI): Improve seekOnTaps behavior on tap and scroll

lib/media/streaming_engine.js
Text track handling is not managed by MSE but by ourselves, thus we do not need to discard text references.
As we do not reset the text engine alongside MSE, text tracks would simply disappear when crossing a boundary and MSE was reset.
=> fix: Text tracks disappear when crossing a boundary in RESET mode.

lib/player.js
Follow up on https://github.com/shaka-project/shaka-player/pull/8254, which I tested in the demo app (debug build). The debug build contains the call to `modifyCueCallback` both with and without a reference check. The production build however does not:
Production build, without reference check (previous PR):
```js
for (var e = d.next(); !e.done; e = d.next()) {
e = e.value;
// ... lots of code ...
// The call to mediaSource.modifyCueCallback is missing below.
e && c.push(e)
}
a.B.append(c)
```
Production build, with reference check (in PR):
```js
for (var f = e.next(); !f.done; f = e.next()) {
f = f.value;
// ... lots of code ...
f && ((g = a.g.mediaSource.modifyCueCallback) && g(f, null, c), d.push(f))
}
a.B.append(d)
```
It'd like to understand why Closure Compiler decides to drop the …
=> fix: Closure compiler removes call to modifyCueCallback in src= mode

lib/util/lazy.js, test/util/lazy_unit.js
Due to usage of `==` instead of `===` Lazy utility does not work correctly with null generators, despite of what is stated in documentation.
=> fix: Make shaka.util.Lazy work with null

build/types/core, karma.conf.js, lib/debug/running_in_lab.js, lib/drm/drm_engine.js, test/test/boot.js
Firefox 136 running on Windows in our lab seems to crash when accessing the CDM.  This happens in our background Windows service, but not in the foreground when run as a regular user.  We don't really understand the nature of it, so we have to disable this in lab tests.
This reverts commit eda85d66078f1756baa3b48c8f99b9588904f089 (#8173), but then goes a bit further:
- Add a flag to we know if we're running in the lab
- Narrow the workaround to lab test runs, not local runs or GitHub Actions VM workflows
=> test: Reject all FF+Windows DRM testing in the lab

lib/media/region_observer.js, test/media/region_observer_unit.js
This is necessary because some EMSG and ID3 events might not fire because the endTime is equal to or very close to the startTime. 
Related to https://github.com/shaka-project/shaka-player/pull/8012
=> fix: Update region observer with new rules for small regions

lib/media/preference_based_criteria.js, test/media/adaptation_set_criteria_unit.js
One of unit tests indicated that when we have channel count preference, but don't have direct match, we should select variants with largest channel count less than config. Test was falsy positive, as we don't have logic to satisfy that scenario.
=> fix: Fix audio selection by channel count

lib/media/preference_based_criteria.js
1. Don't do selection by language if it's empty.
2. Only filter by primary if we don't have match by language.
=> perf: AdaptationSetCriteria improvements

lib/media/streaming_engine.js
When fetch of segments is aborted or cannot succeed due to fetch promise rejection, we may end up with unhandled promise rejections.
=> fix: Prevent unhandled rejections on segment fetch failures

test/util/platform_unit.js
Added platform-detection unit tests for three flavors of Chromecast:
- Android-based
- Fuchsia-based
- Older Chromecasts (including Vizio builtins)
Closes https://github.com/shaka-project/shaka-player/issues/8308
=> test: Added platform unit tests for Chromecast devices

externs/shaka/abr_manager.js, externs/shaka/net.js, lib/abr/simple_abr_manager.js, lib/net/networking_engine.js, lib/player.js, test/net/networking_engine_unit.js
Provides the Segment Reference to the ABR Manager via the request context. This allows the ABR manager to get information about the specific segment being downloaded such as the start and end time (used to calculate segment duration).
=> feat: Provide Segment Reference to ABR Manager (via the request context)

lib/hls/hls_parser.js, lib/media/segment_prefetch.js, lib/media/segment_reference.js, lib/offline/download_info.js, lib/offline/storage.js, test/hls/hls_parser_unit.js, test/test/util/manifest_parser_util.js, test/test/util/util.js
This allows temporary caching of init segment and data segment used to obtain the data (eg: codec) needed for playback.
=> perf(HLS): Reduce load time when loading in the player a media playlist

lib/media/media_source_engine.js, lib/media/streaming_engine.js, lib/player.js, test/media/media_source_engine_unit.js
With resetting MSE on boundary crossing, we might seek into a gap. This would cause MSE not to reset properly, and playback will stall. The following changes are made:
- We rely on `seeking` to check if we need to start the boundary timer. The timer assumes we will cross a boundary in a short period of time, and is built to handle edge cases like misalignment & subtle gaps. We first relied on `seeked` but that event might never come when MSE does not reset. Thus seeking into a gap near a boundary end would have never spawned the timer in the first place, leaving the player endlessly stalling.
- When crossing a boundary, the MSE resets but never completes (as explained earlier). In this case, the timer will advance the playhead. However, due to the incomplete MSE reset, the video element …
=> fix: Improve boundary gap mitigation at DASH period transitions

lib/media/content_workarounds.js
This is already done in MP4 sinf generator.
=> perf(ContentWorkarounds): Do not override codec twice

ui/resolution_selection.js
Fixes https://github.com/shaka-project/shaka-player/issues/8357
=> fix(UI): Make UI display 4096x2160 (DCI 4k) video as also being "4k"

lib/dash/dash_parser.js, lib/media/manifest_parser.js
Today we solely map visually impaired and hard hearing. I've added `Spoken Subtitles` as a new accessibility purpose.
For reference:
```
<?xml version="1.0" encoding="UTF-8"?>
<ClassificationScheme uri="urn:tva:metadata:cs:AudioPurposeCS:2007">
<Term termID="1">
<Name xml:lang="en">Audio description for visually impaired people</Name>
</Term>
<Term termID="2">
<Name xml:lang="en">Audio description for hard of hearing people</Name>
</Term>
<Term termID="3">
<Name xml:lang="en">Supplemental commentary</Name>
</Term>
<Term termID="4">
<Name xml:lang="en">Director's commentary</Name>
</Term>
<Term termID="5">
<Name xml:lang="en">Educational notes</Name>
</Term>
<Term termID="6">
<Name xml:lang="en">Main programme audio</Name>
</Term>
<Term termID="7">
<Name xml:lang="en">Clean feed - no …
```
=> feat(DASH): Add support for "Spoken Subtitles" in tva:metadata:cs:AudioPurpose

lib/drm/fairplay.js, lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
Related to #8335 
This will allow us to put key id into fake encryption boxes.
=> fix(HLS): Add key ids to Fairplay DRM parser

lib/util/string_utils.js, test/util/string_utils_unit.js
Previously, shaka.util.StringUtils.fromBytesAutoDetect assumed any character between ' ' and '~' was ASCII.
This worked for many cases, but it meant that the method would be unable to determine the encoding of a buffer if there was a newline character near the start.
This could be a problem for parsing, for example, JSON.
Closes #8336
=> fix: Count line break characters as ASCII

lib/util/mp4_box_parsers.js
From ISO/IEC 14496-12
```
aligned(8) class TrackRunBox
extends FullBox('trun', version, tr_flags) {
unsigned int(32) sample_count;
// the following are optional fields
signed int(32) data_offset;
unsigned int(32) first_sample_flags;
// all fields in the following array are optional
{
unsigned int(32) sample_duration;
unsigned int(32) sample_size;
unsigned int(32) sample_flags
if (version == 0)
{ unsigned int(32) sample_composition_time_offset; }
else
{ signed int(32) sample_composition_time_offset; }
}[ sample_count ]
}
```
=> fix: Read TRUN data_offset as signed int

lib/util/manifest_parser_utils.js, lib/util/mime_utils.js, test/util/mime_utils_unit.js
Player errors out for Dolby contents in adaptive streaming because correct mimetype is not identified.
This change adds ac3, ac-3, eac3, ec-3, and ac-4 mimetype support.
=> fix: Support more Dolby codec notations

lib/net/http_fetch_plugin.js
fetch API returning a ReadableStream response body is not supported by all browsers.
Browser compatibility:
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API If it is not supported, download the whole segment in one shot
=> fix: Handle null response body for fetch responses

lib/media/playhead.js, lib/media/preload_manager.js, lib/player.js, test/media/playhead_unit.js, test/test/util/simple_fakes.js
Closes #8402 
This PR introduces ability to pass Date object instead of number to `shaka.Player#load()` call. Date, together with PDT is used to calculate relative start time.
If stream does not have PDT, nothing will happen.
Additionally, for src= playback, we set current time on `canplay` event now instead of `loadeddata`. It seems that Safari goes to live edge on it's own if we set time too soon.
=> feat: Use Date for playback start time

lib/media/gap_jumping_controller.js, project-words.txt, test/media/stall_detector_unit.js
In some platforms custom audio focus events are emitted. This needs to  be handled to avoid the stall detection.
=> feat: Handle audio focus events

lib/util/player_configuration.js
Some platforms may not support window.matchMedia API.
=> fix(Offline): Handle missing window.matchMedia API

lib/drm/drm_engine.js
Without this change, `expandRobustness` ended up running 480 times for the stream `Angel One (multicodec, multilingual, Widevine)` with `SW_SECURE_CRYPTO,SW_SECURE_CRYPTO,SW_SECURE_CRYPTO` set up as the multiple robustness. With it, it only runs 44 times, which is expected because there are 22 unique streams, and it expands `videoRobustness` and `audioRobustness` on each.
Fixes #8408
=> fix: Only expand robustness on each stream once

lib/player.js
=> fix: Fix getAudioTracks when audioId is null but exists originalAudioId

lib/media/streaming_engine.js
This will prevent duplicate segments from being downloaded when we are close to the live edge.
=> fix: Add a small fudge to prefetch eviction

demo/common/assets.js, demo/main.js, test/player_external.js
This change allows checking multiple keysystems because some browsers support one and others the other.
=> chore(Demo): Fix check DRM support

lib/polyfill/media_capabilities.js
This is no longer necessary since we dynamically detect the resolution and this allows us to cache isTypeSupported calls with less dispersion.
=> perf: Remove extendedType when checking isTypeSupported on Tizen

lib/player.js
When calling configure() with a partial configuration (which is the usual practice), not every field is present.  When we update that configuration to move deprecated fields to their new location, we can't assume that the hierarchy before the new location is present.  We took care of this already in several cases, but not all.
Discovered while casting and transferring the configuration to the remote device.  This bug prevented the existing content state from being transferred correctly, forcing me to reload the content after casting.
=> fix: Fix exception updating partial config with deprecated fields

lib/cast/cast_proxy.js, lib/cast/cast_utils.js, test/cast/cast_utils_unit.js
These maps of proxied methods have not been properly maintained, so some methods were not working while casting.
In the case of getThumbnails, it was incorrectly categorized as a synchronous getter, and so the return value while casting was a deserialized Promise, which is an empty object.
Several async methods were called void methods, as were several synchronous getters.  This should be up-to-date now.
=> fix(cast): Fix proxying of Player methods in CastProxy

lib/player.js
Use segment references from `forEachTopLevelReference()` callback to avoid unnecessary linear search on every possible thumbnail.
=> perf: Optimize getAllThumbnails()

lib/player.js, lib/util/dom_utils.js
All changes were part of #8520
- Object URLs created in `addSrcTrackElement_()` are now released correctly
- Use `HTMLTrackElement.track` to access its associated `TextTrack`. Searching in `HTMLMediaElement.textTracks` is not reliable
- Remove only `<source>` elements during initialization. User added `<track>` elements are not harmful and they may want to keep them for dual subtitles for example.
=> fix: External text tracks in src mode related issues

lib/drm/drm_engine.js, lib/util/platform.js, project-words.txt
Fixes https://github.com/shaka-project/shaka-player/issues/8576
Browser on this Sony TV returns little-endian, which results in false-positive unsupported key system. Looks like this is a known issue impacting couple of other platforms as well. I need to add this TV as well.
=> fix: Sony Bravia TV Playready DRM Failure

lib/media/region_timeline.js, lib/player.js
What this change does is remove from the timeline using  the buffered instead of the seekRange for Metadata and EMSG.
Fixes #8535
=> fix: Fix memory leak on Metadata and EMSG timelines

lib/util/config_utils.js
When the user passes an array-based config, we should never copy the reference.  Instead, we should clone the array.  This way, changes to that outside array don't immediately affect the running config.
Closes #8478
=> fix: Fix config failures with multiple references to an input array

lib/player.js, lib/util/fake_event.js, project-words.txt
Close https://github.com/shaka-project/shaka-player/issues/8506
Example of use:
```
this.player_.addEventListener('canupdatestarttime', () => {
this.player_.updateStartTime(this.player_.seekRange().start + 300);
});
```
=> feat: Add canupdatestarttime to allow update the startTime safely

build/types/polyfill, lib/polyfill/typed_array.js, shaka-player.uncompiled.js
`TypedArray.prototype.indexOf` is available since Chrome 45, which means it's not implemented on WebOS 3 (using Chromium 38). As we extensively use this method in `Id3Utils` it leads to fatal errors on this platform whenever we encounter ID3 tags.
For completeness and to prevent errors in the future, I also added implementations of connected methods: `lastIndexOf` & `includes`.
=> fix(WebOS): Do not throw error during parsing ID3

lib/text/ui_text_displayer.js
Eg: fullscreen is not supported on Tizen, but we want use UITextDisplayer
=> chore: Useless warning on UITextDisplayer

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
According to HLS spec, there might be few date ranges with the same ID, which complement each other (i.e. SCTE35-IN / SCTE35-OUT).
If date ranges are true duplicates (i.e. due to live update) it will be filter out anyway by `RegionTimeline` logic.
=> fix(HLS): Do not skip DateRanges based on ID

ui/resolution_selection.js
Note: This only applies to audio-only streams.
=> fix(UI): Filter audio qualities when bandwidth is missing

lib/net/http_xhr_plugin.js
=> perf(net): Do not parse headers twice in XHR plugin

lib/drm/drm_engine.js
- map `servers` and `advanced` config fields to maps once
- use `WeakSet` instead of `Set` to mark which objects have been processed
=> chore(DRM): DRM Engine init improvements

docs/tutorials/text-displayer.md, externs/shaka/player.js, lib/player.js
We prefer NativeTextDisplayer when using PiP and Fullscreen API of the video element itself. Otherwise we prefer UITextDisplayer
=> feat: Allow switch between UITextDisplayer and NativeTextDisplayer on runtime

lib/device/tizen.js
Earlier this year https://github.com/shaka-project/shaka-player/pull/8365 provided a solution to the maxResolution detection on Tizen devices. This was then refactored into the device api under https://github.com/shaka-project/shaka-player/pull/8210 but the earlier fix was not propagated. This PR reinstates it.
=> fix: Fix 4k stream support within browser env on Tizen

ui/range_element.js, ui/seek_bar.js
Fixes https://github.com/shaka-project/shaka-player/issues/7129
=> fix(UI): The playback time displayed in the seek bar is different from currentTime when click

ui/less/range_elements.less
Fixes https://github.com/shaka-project/shaka-player/issues/8802
=> fix(UI): Prevent override box-sizing style on range elements

lib/player.js
PR #8603 refactored the conditions for being "buffered to the end". Two of these conditions from Player didn't fit in the new location (Playhead).  One (this.isEnded()) was moved, and the other (this.mediaSourceEngine_.ended()) was dropped by accident.  This restores the dropped condition next to isEnded().
Verified in the Cast Application Framework.
=> fix: Fix end-of-stream detection for VOD

lib/device/abstract_device.js, lib/device/default_browser.js, lib/device/i_device.js, lib/drm/drm_engine.js
This info should be abstract to DRM Engine.
=> chore: Move wait for encrypted event check to device API

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
We currently have many integrated transmuxers, so we should avoid assigning the same mimetype to all unloaded variants. 
We can dynamically transmux all content; we just need a compatible codec. 
Partial reverts https://github.com/shaka-project/shaka-player/pull/4601
=> fix(HLS): Fix playback of content with mixed containers (mp4 and ts)

lib/util/periods.js, test/util/periods_unit.js
Fixes #8839
Changes how do we consider best AV match. Exact codec equality is now better than codec compatibility.
=> fix(DASH): Consider codec profile when matching multi-period renditions

lib/dash/segment_base.js, lib/dash/segment_template.js, lib/media/streaming_engine.js
Due to not setting the `boundaryEnd` for the last period, we ensure we do not discard the wrong segments in a live to VOD situation (where a boundaryEnd becomes available mid stream).
The same applies in live, when a period ends and a new period starts. The previous one will now have a boundaryEnd, the new one does not.
Co-authored-by: @avelad
=> fix: Live to VOD discards the wrong segments when crossBoundaryStrategy is not KEEP

build/generateExterns.js, externs/domstringlist.js, externs/texttrackcuelist.js, lib/dash/segment_template.js, lib/media/segment_index.js
Closure Compiler will soon start typechecking well-known symbol properties, such as Symbol.iterator - see
https://github.com/google/closure-compiler/issues/1737.
This will cause some type errors in existing code that implements `Iterable` (for context, I ran into these errors  in google's internal repo) that is missing a Symbol.iterator override or `@override` annotation
=> refactor: fix upcoming Closure Compiler type errors on Symbol.iterator

lib/transmuxer/h265.js
`default_display_window_flag` is not somehow used to compute video dimensions from SPS.
Only offsets of display window.
=> fix(Transmuxer): Fix width calculation when using HEVC-TS

lib/dash/segment_template.js
Fixes https://github.com/shaka-project/shaka-player/issues/8351.
When we detect a change in `unscaledPresentationTimeOffset`, we'll update the timeline along with both the scaled and unscaled presentationTimeOffset.
For reference, updating `templateInfo_` introduced a memory leak a while back (https://github.com/shaka-project/shaka-player/issues/6610), I ran this change for 2 hours straight and memory was kept in check.
=> fix(DASH): Update timeline on PTO change

lib/media/preload_manager.js
Regression introduced in https://github.com/shaka-project/shaka-player/pull/8835 by changing the order of operations in the preload manager.
=> fix(HLS): Fix preload initial variant on Tizen

externs/shaka/abr_manager.js, lib/abr/simple_abr_manager.js, lib/media/preload_manager.js, lib/media/segment_prefetch.js, lib/media/streaming_engine.js, lib/player.js, test/media/segment_prefetch_unit.js, test/media/streaming_engine_integration.js, test/media/streaming_engine_unit.js
fastSwitching can be used in case there is a need to start linear playback at very low delay (e.g. shortly after the time the client acquired MPD, initialization segments, and DRM license) or to switch from ad content to main content at an arbitrary point in the stream.
As an example, two representations, join6_540p and join6_1080p, have 6-frame GOPs and are used to start playback at a 6-frame boundary. This enables start-up and fine-grain random access at any 6-frame boundary.
fastSwitching are aligned with the “normal” adaptation set. Asa result, it it is possible to switch between “normal” and fastSwitching variant at any segment sequence boundary.
=> feat(DASH): Change from L3D to non-L3D after the successful playback

lib/dash/dash_parser.js
Keeping `this` references in DASH uri callbacks leads to keeping DashParser instances in memory after unloading.
Luckily this is only the issue in uncompiled mode, Closure Compiler handles it somehow. It is though better to fix it in case we change tooling some day.
=> fix(DASH): Prevent memory leak in uncompiled mode

lib/dash/dash_parser.js
Follow up to #8884 based on comment https://github.com/shaka-project/shaka-player/pull/8884#discussion_r2213944738
=> chore(DASH): Add comments to latest DashParser changes

demo/main.js
Related to https://github.com/shaka-project/shaka-player/issues/8529#issuecomment-3096506228
=> fix(Demo): Interact with queueManager before do any adManager operation

third_party/closure-uri/uri.js
There's no requirement that "+" characters not be used in URLs.  In fact, if you start up `python3 -m http.server` and point your browser at `http://localhost:8000/foo+bar?bar+baz=baz+bar`, you'll see every one of those "+" symbols sent directly to the server without encoding at all.
There is an old convention in CGI parameters to turn " " into "+", but proper URL encoding turns " " into "%20".
The URI parser we use was assuming that "+" is always an escaped " ".  So it would decode "+" into " " and then later re-encode it into "%20".
By removing the special treatment of "+" in the URI parser, we make requests to the correct URLs when they involve "+".
Fixes #8713
=> fix: Fix URI encoding with plus characters

lib/ads/interstitial_ad_manager.js, lib/player.js
Apple Vision Pro supports `webkitSupportsFullscreen` and `webkitDisplayingFullscreen`, but it doesn't suppport `webkitPresentationMode`.
=> fix: Fix Apple Vision Pro integration with some features

lib/player.js
Use `buffered` property directly, as there is no need for us to create ranges from SourceBuffers. Also, just take start and end from frist and last range, respectively, looping is unnecessary.
=> perf: Simplify region timeline buffer management

package-lock.json, package.json
Two patches:
- Fix warning in base.js triggered by the latest compiler update
- Revert default setting of ENABLE_DEBUG_LOADER to previous value to fix uncompiled mode
=> chore: Update Closure Library to latest + patches

lib/device/webkit_stb.js
Classifies Orange STB as a Webkit STB device and returns true for `requiresEncryptionInfoInAllInitSegments`
Fixes #8965
=> fix: Add Orange STB Back To `requiresEncryptionInfoInAllInitSegments`

lib/media/media_source_engine.js
Since `RegionTimeline` is used for storing EMSG events, used memory significantly grew when content extensively uses EMSG.
When creating EMSG region, we’re creating `message_data` by using method `readBytes()` from `DataViewReader`. Internally, it calls `BufferUtils.toUint8(buffer)` which creates new `Uint8Array` on shared `ArrayBuffer`. We need to make a copy with data needed only to not store whole segments in memory.
=> fix(EMSG): Fix memory leak in EMSG handling

lib/dash/content_protection.js, lib/dash/dash_parser.js
Use PSSH string to cache init data in order to avoid creating duplicated init data buffers. On streams with many periods due to ad insertion it can make a difference - i.e. on stream with 50 periods this change reduces used memory by init data buffers from 40 KB to 1 KB.
In DASH, PSSH can often be a duplicated data between protected periods and/or adaptation sets.
=> perf(DASH): Do not store duplicated pssh data buffers

build/types/core, lib/media/buffering_observer.js, lib/player.js, lib/util/media_element_event.js, test/media/buffering_observer_unit.js
After #7617, we stopped using the polling mechanism and playback rate to control the buffering state, but the old behavior of checking the buffer was still in place. Moreover, since buffer thresholds were set based on the rebuffering goal value, when that value was 0, the underlying logic tended to underreport buffering.
Now, when the goal is 0, Shaka will rely solely on media element events for buffering reporting.
=> fix: Fix buffering states when rebuffering goal is 0

build/conformance.textproto, lib/cea/mp4_cea_parser.js, lib/media/media_source_engine.js, lib/text/mp4_ttml_parser.js, lib/text/mp4_vtt_parser.js, lib/util/data_view_reader.js, lib/util/mp4_box_parsers.js, lib/util/mp4_parser.js, lib/util/pssh.js, test/util/data_view_reader_unit.js, test/util/mp4_parser_unit.js, ui/seek_bar.js
Make cloning buffers (or not) explicit in readBytes.
When we use a range of bytes temporarily for further parsing, we pass clone=false and get a view on the existing memory buffer.  When we want to store the range of bytes, we pass clone=true and avoid holding a reference to an entire segment in memory.
The call for the EMSG parser in MediaSourceEngine had an explicit clone, but now uses the new clone parameter.  This is not a functional change, though.
The only readBytes call that changed in this audit was in the UI seek bar.
The rest all appear to be values for temporary usage, and so are not being cloned.
The new `clone` parameter will require future callers of `readBytes()` to think about their purpose and make a choice.
=> fix: Audit all usage of readBytes for memory leaks

lib/player.js
Removed code predates MediaCapabilities. Right now ABR variants are already set during initial variant selection, so this one is just a duplication.
=> perf: Remove unnecessary ABR update during load

lib/media/streaming_engine.js
We often do not know stream bandwidth in HLS, but Streaming Engine relies on this knowledge to calculate new segment size to fetch. It helps in decision shall we abort currently ongoing request when switching rendition due to ABR change.
This PR adjusts this logic and looks into variant bandwidth if we don't know stream bandwidth.
Additionally, if we cannot determine size at all, by default we will abort currently ongoing request to not accidentally block fetching entirely.
=> fix(HLS): Improve abort decision logic

lib/media/segment_prefetch.js, test/media/segment_prefetch_unit.js
We evict SegmentPrefetched on each streaming engine update, in the case of Live, it may happen that we are on the Live edge and do not have segments, but we want to avoid the initialization segment being downloaded again in the future when it is not necessary.
=> fix: Avoid download init segments again when not necessary

ui/less/general.less, ui/less/thumbnails.less, ui/less/tooltip.less
This is currently only supported in Chromium browsers (it is behind a feature flag in Firefix and WebKit doesn't have it), if you don't want to enable the setting at the operating system level to test this, you can simulate it in the "Rendering" tab in the Chromium developer tools.
=> fix(UI): Respect prefers-reduced-transparency for tooltips and seekbar times

lib/util/cmcd_manager.js, test/util/cmcd_manager_unit.js
This PR fixes a few issues:
- The infinite loop described in #9050 
- ~~The fact that CMCD functions were executed when the feature was disabled~~
- Query params being stripped in the `nor` field. https://github.com/streaming-video-technology-alliance/common-media-library/issues/239
=> fix: prevent infinite loop when constructing CMCD relative urls

lib/drm/drm_engine.js
Fixes https://github.com/shaka-project/shaka-player/issues/9032
Regression introduced in https://github.com/shaka-project/shaka-player/pull/8497
=> fix: Attach mediaKeys when the device does not force us to wait for the encrypted event

lib/hls/hls_parser.js, test/hls/hls_parser_unit.js
This PR is a follow-up optimisation to the recent performance improvements for the HLS parser, as discussed in **Issue #9067**.
Following a review of the previous changes, this PR addresses a similar, remaining bottleneck: redundant mimetype calculation. The parser was determining the mimetype from the URI for every segment, which, while less expensive than the init segment lookup, still adds unnecessary overhead in performance-critical loops when parsing large manifests.
This PR applies the same optimisation pattern used for the init segment fix:
-  The `createSegments_` function now tracks the file extension of the last-processed segment in a local variable.
-  The mimetype is recalculated only when a segment's file extension changes. This is more efficient and correctly handles …
=> perf(HLS): Optimize mimetype resolution during parsing

lib/media/segment_reference.js
When calculating the size of a segment when using startByte and endByte, both are inclusive. So the sum should add 1.
=> fix: Bad init segment size calculation when using byte ranges

lib/drm/drm_engine.js
Speed up execution of `shaka.Player.probeSupport()` which tends to be super slow on Windows with HW DRM. Changes include several tweaks in DRM probing:
- test only using `navigator.requestMediaKeySystemAccess()`, using MediaCapabilities as well was redundant
- test HDCP only once
- drop HDCP tests once we know some version is unsupported
On Windows it speeds up execution from 20s to 0.7-1s.
=> perf: Speed up `shaka.Player.probeSupport()`

ui/icon.js, ui/less/material_svg_icon.less
Previously, `currentcolor` was applied to the background even for unconfigured icons, causing a black square to appear in place of the icon.
Now, the background color is applied only when the icon is configured.
=> fix(UI): apply background color only for configured icons

lib/hls/hls_utils.js, lib/hls/manifest_text_parser.js
These changes were made in an attempt to address issues with Shaka on Chromecast getting stuck with buffer underruns while parsing large manifests (~7k segments). Instead of parsing once, it gets stuck parsing a manifest over and over on encrypted streams, each manifest parse taking over ~1.2s.
The changes here did not solve the issue, but [I was asked to make a PR](https://github.com/martinstark/shaka-player/commit/786d1370e566e0bdecf3ec8a847b62c6ebc1f7af). While the manifest parsing is slow, it's appears not to be the root cause of the issue we've been seeing.
In synthetic testing, with HLS manifests ranging from 100 to 100,000,000 segments on an AMD processor, Node22, arch linux, the updated  manifest parser uses somewhere between 12-40% less processor time. Assuming my tests were …
=> perf(HLS): Optimise manifest text parser
