CONTRIBUTORS
lib/util/ajax_request.js

Handling timeouts on Ajax Request

Handle Ajax Request timeouts issue #78

---

tutorials/intro.html

https://github.com/google/shaka-player/issues/217

Fixes #217 broken link

---

AUTHORS
CONTRIBUTORS
lib/player/i_video_source.js
lib/player/player.js
lib/player/stream_video_source.js

In my use case i want to keep the live stream playing while switching audio tracks,
i've added this option to allow switching audio at specific time and not pause the stream for that.
Thanks,

add opt_clearBufferOffset for audio

---

lib/media/stream.js

Nudge no longer needed on seek because http://crbug.com/478151
has been closed

Remove stream nudge

---

lib/media/presentation_timeline.js
test/media/presentation_timeline_unit.js

change getSeekRangeEnd to allow scrubbing to end of in-progress VOD

---

demo/asset_section.js
demo/common/assets.js
demo/index.html
demo/main.js

Add certificate field in the custom asset section of the demo.

---

lib/media/media_source_engine.js

Very simple change: remove a duplicated entry in testMimeTypes.

Remove duplicated mime types

---

lib/media/segment_reference.js
test/media/segment_reference_unit.js

Add getters to SegmentReference and InitSegmentReference

---

CHANGELOG.md

Correct dates in changelog

---

lib/net/data_uri_plugin.js
lib/net/http_fetch_plugin.js
lib/net/http_plugin_utils.js
lib/net/http_xhr_plugin.js
lib/offline/offline_scheme.js
lib/util/error.js
test/net/http_plugin_unit.js
test/test/util/jasmine_fetch.js
test/test/util/test_scheme.js

Provide RequestType in error data from HttpPlugin.

---

lib/media/drm_engine.js
test/media/drm_engine_unit.js

Remove misleading logging in DrmEngine#fillInDrmInfoDefaults_

---

lib/util/error.js

Update docs for 6014 EXPIRED

---

test/net/http_plugin_unit.js

Use capital letter at start of constructor function name

---

lib/text/ttml_text_parser.js

Add missing require for shaka.util.XmlUtils

---

AUTHORS
CONTRIBUTORS
docs/tutorials/config.md
externs/shaka/player.js
lib/media/playhead.js
lib/util/player_configuration.js
test/media/playhead_observer_unit.js
test/media/playhead_unit.js
test/media/streaming_engine_integration.js
test/media/streaming_engine_unit.js

Please see the #1723 for more details.
Thank you

Add safeSeekOffset to StreamingConfiguration (#1723)

---

docs/tutorials/ui-customization.md

" member" instead of "memeber".

Fix typo in code section

---

ui/less/other_elements.less

1. Open the test page
1. Load the Angel asset
1. Enter full screen mode
The current time element is left-aligned and other controls are right-aligned.
The current time element isn't left-aligned but has an indentation. For example:

Make spacer growable in order to align control elements

---

demo/common/demo_utils.js

"corresponding" intead of  "corresonding".

Typo fix in code comment

---

demo/common/assets.js
externs/shaka/text.js
lib/text/cue.js
lib/text/ttml_text_parser.js
ui/less/buttons.less
ui/less/containers.less
ui/text_displayer.js

Related to: https://github.com/google/shaka-player/issues/840 & https://www.smpte.org/sites/default/files/st2052-1-2010.pdf
Tasks:
- Add sample stream
- Modify ttml_text_parser.js to parse metadata elements and support smpte:backgroundImage
- Modify text_displayer. to support images

Support to SMPTE-TT subtitles (only smpte:backgroundImage)

---

lib/player.js

Return the mediaElement when using src on player getMediaElement

Fix getMediaElement function when using src.

---

lib/player.js

Allow play mp3, aac and flac files with src=

Add mp3, aac and flac mapping to mime type

---

AUTHORS
CONTRIBUTORS
docs/tutorials/manifest-parser.md

Fix a typo in the docs

---

lib/offline/download_manager.js
lib/offline/storage.js
lib/polyfill/patchedmediakeys_ms.js
lib/util/pssh.js
test/offline/storage_integration.js

This is a PR for the same thing as #1600 for solving issue #1531 . I took the comments from #1600 and created a solution based on that. 
However i'm not entirely sure how to update the drmEngine in the best way, i would love some pointers and comments about how to solve that in the best way!

feature: Offline PSSH support for manifest that are missing inline init data

---

lib/dash/content_protection.js
lib/util/pssh.js
test/dash/dash_parser_content_protection_unit.js

Fix for https://github.com/google/shaka-player/issues/2058

Get PlayReady PSSH from <mspr:pro> in DASH

---

lib/polyfill/patchedmediakeys_ms.js
lib/util/pssh.js

Extracted from https://github.com/google/shaka-player/commit/6e5a0797de42a4b7ade45667552cf1b20cb0f143
It also simplifies the logic of https://github.com/google/shaka-player/pull/2042 to continue working on the functionality.

Move PatchedMediaKeysMs.normaliseInitData_ to shaka.util.Pssh.normaliseInitData

---

CONTRIBUTORS
lib/media/region_timeline.js
test/dash/dash_parser_live_unit.js
test/media/region_observer_unit.js
test/media/region_timeline_unit.js

Include event ID in findSimilarRegion_() check so that events with same presentationTime and duration but different ID are treated as separate events.
Closes #2077

Include event ID in findSimilarRegion_() check

---

lib/dash/dash_parser.js

Resolves https://github.com/google/shaka-player/issues/2178

Use label from DASH manifest AdaptationSet

---

demo/config.js
externs/shaka/player.js
lib/dash/dash_parser.js
lib/hls/hls_parser.js
lib/util/player_configuration.js
test/dash/dash_parser_manifest_unit.js
test/hls/hls_parser_unit.js

Resolves https://github.com/google/shaka-player/issues/2195

Allow disable the audio parsing/decoding/.. in DASH/HLS with a config

---

lib/media/drm_engine.js

Resolve https://github.com/google/shaka-player/issues/2177

AirPlay support HLS with FairPlay

---

lib/media/playhead.js
lib/player.js
test/player_src_equals_integration.js

Resolves https://github.com/google/shaka-player/issues/2267

Add startTime support in src mode

---

lib/ads/ad_manager.js
lib/util/error.js

Resolves the comment: https://github.com/google/shaka-player/issues/2222#issuecomment-581538019

IMA: disambig between CS and DAI

---

lib/ads/ad_manager.js

Change AdsManager by AdsLoader (https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/ima.AdsLoader)

Fix IMA CS detection

---

externs/shaka/text.js
lib/text/cue.js
lib/text/ttml_text_parser.js
ui/text_displayer.js

tts:border --> https://www.w3.org/TR/2018/REC-ttml2-20181108/#style-attribute-border
tts:letterSpacing --> https://www.w3.org/TR/2018/REC-ttml2-20181108/#style-attribute-letterSpacing
tts:opacity --> https://www.w3.org/TR/2018/REC-ttml2-20181108/#style-attribute-opacity

Add support to tts:border, tts:letterSpacing and tts:opacity in TTML

---

docs/tutorials/drm-config.md

Improving documentation for DRM-Configuration for ClearKey
#2434

Improved ClearKey Example

---

externs/shaka/text.js
lib/text/cue.js
lib/text/ttml_text_parser.js
test/text/ttml_text_parser_unit.js
test/ui/text_displayer_unit.js
ui/text_displayer.js

Resolves https://github.com/google/shaka-player/issues/2407
WORK IN PROGRESS, not merge yet.
I need https://github.com/google/shaka-player/pull/2442, so when it is closed, I will rebase the changes to this PR and then it will be ready

Add ebutts:linePadding to ttml parser

---

lib/hls/hls_parser.js

Resolves https://github.com/google/shaka-player/issues/2470

Recognize new CMAF file extensions cmfv, cmfa, cmft in HLS

---

externs/shaka/ads.js
lib/ads/ad_manager.js
lib/ads/ads_stats.js
lib/ads/client_side_ad_manager.js
lib/ads/server_side_ad_manager.js

The implementation covers CS and SS

Add loadTimeSeconds to ads stats

---

externs/mux.js
lib/media/transmuxer.js

This work is necessary to expose metadata info to ads (SS)

Parse metadata in transmuxer (mux.js)

---

externs/shaka/player.js
lib/player.js
lib/util/stats.js
test/player_integration.js

Resolves https://github.com/google/shaka-player/issues/1872

Add liveLatency to stats (only MSE)

---

lib/player.js

Resolves https://github.com/google/shaka-player/issues/2531

Setup preferredVariantRole and preferredTextRole in src mode

---

lib/util/stream_utils.js

Kind audioTrack --> https://developer.mozilla.org/en-US/docs/Web/API/AudioTrack
Kind textTrack --> https://developer.mozilla.org/en-US/docs/Web/API/TextTrack
Note: This change has been discussed by email.

Add roles in text and audio tracks (src mode) using the kind parameter

---

lib/media/drm_engine.js
lib/util/platform.js

Tivo Box with Opera browser and Opera Devices SDK inbuilt (Virgin Media STB in UK)

fix(drm): use correct endian for TiVo with playready DRM

---

AUTHORS
CONTRIBUTORS
lib/text/ttml_text_parser.js
test/text/ttml_text_parser_unit.js

Adds support for nested TTML captions with an offset raised in #2601.

Add support for nested TTML captions with an offset

---

externs/shaka/player.js
lib/player.js
lib/util/stats.js
test/player_integration.js

Resolves https://github.com/google/shaka-player/issues/2610

Add maxSegmentDuration to stats

---

lib/text/ui_text_displayer.js

Resolves https://github.com/google/shaka-player/issues/2623

Background color only should apply to nested cues in UITextDisplayer

---

docs/tutorials/a11y.md
docs/tutorials/ad_monetization.md
docs/tutorials/basic-usage.md
docs/tutorials/debugging.md
docs/tutorials/license-server-auth.md
docs/tutorials/license-wrapping.md
docs/tutorials/manifest-parser.md
docs/tutorials/offline.md
docs/tutorials/service-worker.md
docs/tutorials/ui-customization.md
docs/tutorials/ui.md

related with #2544
@joeyparrish
I understood this issue wanna change from old syntax to modern syntax in docs.
So first, I replace `var` declaration to `let` or `const`.
If these changes are right with your intent, I'll replace `then` to `await` in the other PR :)

docs: change variable declaration to modern syntax

---

docs/tutorials/basic-usage.md
docs/tutorials/license-server-auth.md
docs/tutorials/license-wrapping.md
docs/tutorials/service-worker.md

docs: change promise then to await

---

build/types/core
externs/mux.js
lib/dependencies/all.js
lib/media/closed_caption_parser.js
lib/media/media_source_engine.js
lib/media/transmuxer.js
lib/text/text_engine.js
test/media/media_source_engine_integration.js
test/media/media_source_engine_unit.js
test/text/text_engine_unit.js
ui/ui.js

This is an example (not finished yet) how you could handle dependencies from third-party libs, the initial issue is https://github.com/google/shaka-player/issues/2562. If the suggested solution is acceptable, I will proceed

Change the way of loading muxjs

---

lib/player.js

Related to: https://github.com/google/shaka-player/commit/4ba162797b9c43759b61106e57a6c6317668e1c6

Fix src= playback on WebOS

---

README.md

Closes: https://github.com/google/shaka-player/issues/2783

Add note about CEA-708

---

README.md
build/types/text
lib/player.js
lib/text/srt_text_parser.js
lib/util/error.js
shaka-player.uncompiled.js
test/text/srt_text_parser_unit.js

Add SRT support
Support is done by converting SRT to WEBVTT
The main use is to side-load subtitles

Add SubRip (SRT) subtitle support

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js

Resolves https://github.com/google/shaka-player/issues/2903

HLS - Allow mapping characteristics into multiples roles

---

lib/media/adaptation_set.js
test/media/adaptation_set_unit.js

Resolves https://github.com/google/shaka-player/issues/2908

Mono and stereo tracks considered incompatible

---

lib/player.js
lib/util/error.js

Related to https://github.com/google/shaka-player/pull/2891

Add Shaka errors to addTextTrack

---

lib/cast/cast_utils.js
lib/player.js
lib/text/srt_text_parser.js
lib/util/error.js
test/player_integration.js
test/player_src_equals_integration.js

Add addTextTrackAsync

---

lib/text/vtt_text_parser.js
test/text/vtt_text_parser_unit.js

Resolves https://github.com/google/shaka-player/issues/2720

Be more permissive in vtt files

---

lib/media/segment_reference.js
lib/media/streaming_engine.js
test/media/streaming_engine_unit.js

Resolves https://github.com/google/shaka-player/issues/2856

Fix initSegment requests on manifest updates

---

lib/dash/dash_parser.js
test/dash/dash_parser_manifest_unit.js

Resolves https://github.com/google/shaka-player/issues/2978

Trick-mode attribute should be whitespace-separated list

---

lib/player.js

Closes: https://github.com/google/shaka-player/issues/3037

Add parameter to probeSupport to skip DRM tests

---

lib/dash/dash_parser.js
test/dash/dash_parser_manifest_unit.js

Closes: https://github.com/google/shaka-player/issues/2873

Add support for schemeIdUri="urn:mpeg:mpegB:cicp:ChannelConfiguration

---

lib/text/ttml_text_parser.js
test/text/ttml_text_parser_unit.js

Adapt to a list of supported namespaces and iterate through them.

3061 extend support to 2013

---

lib/hls/hls_parser.js

Closes: https://github.com/google/shaka-player/issues/3099

Add support for "m4f" in HLS

---

lib/player.js

Closes: https://github.com/google/shaka-player/issues/2915

Move drmEngine_.attach() from onLoad_ to onInitializeDrm_

---

README.md

Adding examples for:
- Vue.js - https://github.com/davidjamesherzog/shaka-player-vuejs
- Nuxt.js - https://github.com/davidjamesherzog/shaka-player-nuxtjs
- video.js - https://github.com/davidjamesherzog/videojs-shaka

Add vue.js, nuxt.js and video.js examples

---

demo/common/assets.js

Closes: https://github.com/google/shaka-player/issues/3154

Add DAI live DASH example to DEMO app

---

.github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md

#3201
Add a pull request template.
Comes in handy to guide contributors to fill PR descriptions to the point.

[chore] : added PULL_REQUEST_TEMPLATE 

---

CONTRIBUTING.md
docs/tutorials/ad_monetization.md
docs/tutorials/plugins.md
docs/tutorials/ui-customization.md
docs/tutorials/upgrade-v2-4.md
docs/tutorials/upgrade-v2-5.md

Corrected some typos & corrected some spellings

fix: Fixed typos found in documentations

---

lib/util/stream_utils.js

Check spatialRendering against Media Capabilities

---

docs/tutorials/basic-usage.md
docs/tutorials/config.md
docs/tutorials/ui-customization.md

Minor changes in order to improve the documentation.
cc @michellezhuogg

doc: add minor changes

---

docs/tutorials/ad_monetization.md
docs/tutorials/debugging.md
docs/tutorials/offline.md
docs/tutorials/ui-customization.md
lib/ads/ad_manager.js

Update in links having event and formatting

Update in links having event and formatting

---

demo/common/assets.js
lib/offline/storage.js
lib/offline/stream_bandwidth_estimator.js
lib/util/player_configuration.js

Related to: https://github.com/google/shaka-player/pull/3145

Allow download thumbnails (for offline usage)

---

lib/text/web_vtt_generator.js
test/text/web_vtt_generator_unit.js

Creates style tags for cues with underline/italics/bold in WebVttGenerator. Also add support for nestedCues in WebVttGenerator.

Creates style tags for cues with underline/italics/bold in WebVttGenerator

---

lib/text/ttml_text_parser.js
test/text/ttml_text_parser_unit.js

Closes: https://github.com/google/shaka-player/issues/3097

Fix image subtitles parsing in TTML

---

lib/media/drm_engine.js

Related to: https://github.com/google/shaka-player/issues/1495

Test 'com.microsoft.playready.recommendation' in DrmEngine

---

ui/mute_button.js

Closes: https://github.com/google/shaka-player/issues/3305

Update icon doesn't work for 'muted' attribute.

---

lib/player.js

Close: https://github.com/google/shaka-player/issues/3312

Add crossorigin attribute to the video element when adding external text track in src=

---

docs/tutorials/network-and-buffering-config.md

- [Yes] I have signed the Google CLA <https://cla.developers.google.com>

Fixed minor punctuation and grammatical errors

---

CONTRIBUTORS
README.md

Correction of typo in project README.
- [ x] This change requires a documentation update
This change is a documentation update
- [x ] I have signed the Google CLA <https://cla.developers.google.com>
- [ x] My code follows the style guidelines of this project
- [ x] I have made corresponding changes to the documentation

fix(docs): corrects typo in project README

---

lib/abr/simple_abr_manager.js

Close: https://github.com/google/shaka-player/issues/3385

fix: Ignore network changes if ABR is disabled

---

README.md

Added a reference to README to an Github repo that shows how to integrate Shaka Player with Angular
- [ X] Slight change to the README.md of the project 
- [ X] I have signed the Google CLA <https://cla.developers.google.com>
- [ X] My code follows the style guidelines of this project
- [ X] I have made corresponding changes to the documentation
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] I have verified my change on multiple browsers on different platforms
- [ X] I have run `./build/all.py` and the build passes
- [ X] I have run `./build/test.py` and all tests pass

added a reference to an Angular integration example on README

---

lib/player.js

This PR is only to improve the code health

Improve code health for text extensions to mime types

---

lib/util/stream_utils.js

Close: https://github.com/google/shaka-player/issues/3380

Filter unsupported H.264 streams in Xbox

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js

Related to: https://github.com/google/shaka-player/issues/3422#issuecomment-847291183

HLS: Prioritize AVERAGE-BANDWIDTH to BANDWIDTH

---

lib/media/streaming_engine.js

Close: https://github.com/google/shaka-player/issues/3463

Fix: rapid seek causes CCs to disappear when ignoreTextStreamFailures is true

---

lib/player.js

Related to https://github.com/google/shaka-player/issues/3530

Fix URI in onInitializeSrcEqualsDrm_

---

lib/text/vtt_text_parser.js
test/text/vtt_text_parser_unit.js

fix: fix breaking captions

---

lib/net/http_fetch_plugin.js
lib/net/http_xhr_plugin.js

Related to https://github.com/google/shaka-player/pull/3401

Add blob-url support

---

docs/tutorials/blob-url.md
docs/tutorials/index.json

Close: https://github.com/google/shaka-player/issues/1481

Add blob-url tutorial

---

lib/media/playhead.js

Close: https://github.com/google/shaka-player/issues/3518

Avoid seeking on src when start time is 0

---

lib/text/mp4_ttml_parser.js

Our VOD delivery provider is upgrading their workflow and will output a different codec for stpp text streams, which they think Shaka should be able to handle.
> The change we've implemented is to default to the IMSC1 text or image profile when packaging TTML input into an ISO BMFF (MP4) track, if no profile is signaled in the TTML document (which is the case for your content). Text will be selected if text is present, images if images are present. The end result of this is that for TTML packaged into ISO BMFF (.ismt or .cmft) using our latest beta, Origin will output 'stpp.ttml.im1t' if the TTML contains text.
> However, this change will not change the output for TTML documents you have already packaged into ISO BMFF. I have discussed this problem internally and we've come to the …

fix: support stpp.ttml codec in Mp4TtmlParser

---

demo/common/assets.js

Fix 'Tears of Steel (live, DASH, Server Side ads)'
See: https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai/streams

Fix 'Tears of Steel (live, DASH, Server Side ads)'

---

lib/text/ttml_text_parser.js
test/text/ttml_text_parser_unit.js

Fixes https://github.com/google/shaka-player/issues/3766

Allow comments in the TTML parser

---

ui/less/buttons.less

Fixes https://github.com/google/shaka-player/issues/3739

Fix current time's height on safari

---

lib/dash/dash_parser.js
test/dash/dash_parser_manifest_unit.js

Close: https://github.com/google/shaka-player/issues/3767

Fix wrong role for forced subtitle in DASH

---

.github/workflows/build_and_test.yaml

Add mac/Safari, mac/Edge to GitHub Actions workflow

test: Add mac/Safari, mac/Edge to GitHub Actions workflow

---

ui/text_selection.js

Fixes https://github.com/google/shaka-player/issues/3728

Fix Shaka Player UI shows wrong caption selection

---

test/test/assets/screenshots/review.html

The screenshot review page now has options to organize screenshots either by test or by platform.  Previously, it was only by test.  This is useful if you want to review many anomalous screenshots for a particular device.
Change to a test tool only.

test: Review screenshots by test or by platform

---

test/player_integration.js
test/test/util/test_scheme.js

Issue #2337
Adds an integration test for sequence mode content, which we did not have before.

test: Added integration test for sequence mode

---

demo/common/assets.js

Issue https://github.com/google/shaka-player/issues/2337

Add new asset: Apple Advanced HLS Stream (TS) with raw AAC

---

package-lock.json
package.json

https://github.com/joeyparrish/webdriver-installer/pull/8

test: Fix failing WebDriver installations

---

.github/workflows/release-please.yaml

The fix we needed has now been released there.

ci: Revert to upstream release-please-action

---

lib/text/ttml_text_parser.js

Closes: https://github.com/shaka-project/shaka-player/issues/4015

fix(ttml): Subtitles are not centered by default

---

externs/shaka/net.js
lib/media/drm_engine.js
lib/net/networking_engine.js
test/util/cmcd_manager_unit.js

Adds drmInfo field to all LICENSE-type requests.
Based on comments here: https://github.com/shaka-project/shaka-player/issues/4001#issuecomment-1050655197

feat(DRM): add drmInfo to license requests

---

.github/workflows/release-please.yaml

When an automated feature release is created, we should also create
the corresponding release branch.

ci: Auto-create release branch for feature release

---

.github/workflows/demo-version-index.yaml

ci: Fix typo in demo index workflow

---

build/shaka-lab.yaml

Our Tizen device is finally back online in the lab!

ci: Re-enable tests on Tizen

---

package-lock.json
package.json

Fixed upstream in shaka-project/karma-local-wd-launcher#38
Closes #3967

test: Fix Safari tests hanging in GitHub Actions environment

---

ui/less/ad_controls.less
ui/less/buttons.less
ui/less/containers.less
ui/less/range_elements.less
ui/less/tooltip.less

fix(css): Fix missing calc() statements

---

docs/tutorials/gsoc-ideas-list.md

This is very outdated and should not appear in our docs

chore: Drop GSOC ideas list

---

externs/shaka/player.js
lib/player.js

Related to https://github.com/shaka-project/shaka-player/issues/3895

feat: Add Id to chapters

---

.github/config.yml

More info in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

chore: Always use a template for issues

---

lib/text/vtt_text_parser.js
test/text/vtt_text_parser_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/4264
Closes https://github.com/shaka-project/shaka-player/issues/3893

feat(webvtt):  add support for karaoke style text in WebVTT

---

CONTRIBUTORS
lib/util/string_utils.js

Addresses [issue/4321](https://github.com/shaka-project/shaka-player/issues/4321)

fix: VTT Cue Parsing On PlayStation 4

---

package-lock.json
package.json

Upgrade eme-encryption-scheme-polyfill to support chromecast version of PlayReady.

feat: Upgrade eme-encryption-scheme-polyfill

---

lib/polyfill/media_capabilities.js

Close https://github.com/shaka-project/shaka-player/issues/4383
Close https://github.com/shaka-project/shaka-player/issues/4357

fix: Fix MediaCapabilities polyfill on Tizen and WebOS

---

.github/workflows/build-and-test.yaml
ui/text_selection.js

fix: Fixed minor bug #4358 
Part of #4358  fixed the code 
Type of change
Checklist:
Reviewed-by: @anshgo01yal 
Refs: #4358

fix: Fix UI captions icon state

---

.github/workflows/build-and-test.yaml
.github/workflows/compute-incremental-coverage.py
.github/workflows/report-incremental-coverage.yaml
karma.conf.js

This generates a more detailed JSON coverage file containing maps of
exactly what statements were executed by tests.  This also extracts
the data from this file and updates the PR with a comment showing how
much of the changed code is covered by tests.

test: Generate incremental code coverage data

---

.github/workflows/compute-incremental-coverage.py

The initial implementation had a bug where a class declaration
"statement" would be seen as covering all the lines of all the methods
in that class.  This change fixes that case, so that the lines of
methods and inner statements are not "part" of their outer containers.

test: Fix incremental coverage stats

---

ui/less/ad_controls.less

Close https://github.com/shaka-project/shaka-player/issues/4339

fix(UI): Ad position and ad counter are too close to each other

---

lib/util/stream_utils.js

Related to https://github.com/shaka-project/shaka-player/pull/3411

fix: Filter unsupported H.264 streams in Xbox

---

build/types/core
build/types/text

Closes https://github.com/shaka-project/shaka-player/issues/3863

fix: allow build without text

---

test/ads/ad_manager_unit.js

test: Add additional test for ads

---

lib/cea/cea608_memory.js
test/cea/cea608_memory_unit.js

fix: check for negative rows before moving

---

lib/text/ttml_text_parser.js
test/test/util/ttml_utils.js
test/text/ttml_text_parser_unit.js

fix(ttml): Default TTML background color to transparent if unspecified

---

.github/workflows/selenium-lab-tests.yaml

Reverts shaka-project/shaka-player#4539
This doesn't actually fix the problem.  I was too hasty in putting it up for review.

ci: Revert "Fix reporting status from lab tests to PRs"

---

AUTHORS
CONTRIBUTORS
lib/cast/cast_sender.js

fix: Respect existing app usage of Cast SDK

---

.github/workflows/compute-incremental-coverage.py

Broken in 062aa07e71c01325a03bb27c2c3e9abe99c20443 (#4588)

ci: Fix incremental coverage reports

---

lib/media/drm_engine.js

Closes https://github.com/shaka-project/shaka-player/issues/4512

fix: fix support clear and encrypted periods

---

lib/player.js

Close https://github.com/shaka-project/shaka-player/issues/4547

fix: Fix metadata assert when the ID3 is future (coming in a previous segment)

---

lib/hls/hls_parser.js

Closes https://github.com/shaka-project/shaka-player/issues/3917

fix(HLS): Infer missing codecs from config

---

lib/hls/hls_parser.js

See PR #4568, which was merged without feedback addressed.

chore: Cleanup after HLS key rotation PR

---

build/types/cea
lib/cea/dummy_cea_parser.js
lib/cea/i_cea_parser.js
lib/cea/mp4_cea_parser.js
lib/media/closed_caption_parser.js
lib/media/media_source_engine.js
lib/player.js
lib/util/mp4_box_parsers.js
test/cast/cast_utils_unit.js
test/cea/mp4_cea_parser_unit.js
test/media/closed_caption_parser_unit.js
test/media/drm_engine_integration.js
test/media/media_source_engine_integration.js
test/media/media_source_engine_unit.js
test/media/streaming_engine_integration.js

Fixes https://github.com/shaka-project/shaka-player/issues/4605
Fixes https://github.com/shaka-project/shaka-player/issues/3659
Also added a change to support a TS CEA parser in the future.

fix(cea): Fix not rendering CEA-608 Closed Captions

---

lib/dash/segment_template.js
test/dash/dash_parser_manifest_unit.js

fix: Fix bufferBehind setting broken by image segments

---

test/media/media_source_engine_integration.js
test/test/util/util.js

Related to PR #4697
This will help us ensure we're not changing parsing outputs by accident.

test: Expand CEA test expectations

---

lib/cea/cea708_window.js

Fixes https://github.com/shaka-project/shaka-player/issues/3634

fix(cea): Fix MAX_ROWS in CEA-708 window

---

externs/shaka/player.js

docs: Clarify description of drmTimeSeconds.

---

lib/hls/hls_parser.js

Closes https://github.com/shaka-project/shaka-player/issues/4780

fix(HLS): Single alternative video renditions not working

---

lib/text/ttml_text_parser.js

Closes https://github.com/shaka-project/shaka-player/issues/4749

fix(TTML): Add font-family mapping

---

AUTHORS
CONTRIBUTORS
lib/player.js

fixes https://github.com/shaka-project/shaka-player/issues/4750
Solved by creating a `Set` for filtering out deplicate elements.
Need confirmation, Shouldn't we add an `assert` for `language` argument passed to https://github.com/shaka-project/shaka-player/blob/76f96b9fee2dc43b03f6803dd80c51fdc5b73a9e/lib/player.js#L4340-L4342

fix(chapters): removed duplicate chapters by id

---

ui/controls.js

fix(UI): Suppress error log from fullscreen button on desktop

---

lib/text/web_vtt_generator.js

Fixes https://github.com/shaka-project/shaka-player/issues/4856

fix: Fix flattenedCues in WebVttGenerator

---

lib/util/timer.js
test/player_integration.js

test: Added test to detect lingering timers

---

lib/media/media_source_engine.js

Broken by PR #4824
Fixes #4889

fix: Fix exception enabling captions on HLS

---

test/test/assets/screenshots/review.html

This rewritten screenshot review tool is more dynamic and better organized.
It is now easier to add additional test suites, and filtering can be done dynamically by any attribute (platform, suite, or test).
Related to work on PR #4767

test: Rewrite screenshot review tool

---

test/test/assets/screenshots/review.html

test: Preserve filters when reloading the review page

---

lib/polyfill/media_capabilities.js
lib/util/platform.js

fixes https://github.com/shaka-project/shaka-player/issues/4925

fix: Fix MediaCapabilities polyfill on Hisense

---

ui/controls.js
ui/externs/ui.js
ui/ui.js

Closes https://github.com/shaka-project/shaka-player/issues/4859

feat(UI): Allow customizate FullScreen element

---

lib/offline/indexeddb/storage_mechanism.js

Related to https://github.com/shaka-project/shaka-player/issues/4625

fix: Increase IndexedDB timeout

---

lib/ads/client_side_ad_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/4992

fix(ads): Fix VMAP ads stay muted on muted autoplay

---

build/misspellings.txt
lib/media/streaming_engine.js

chore: Fix typos in comments

---

AUTHORS
CONTRIBUTORS
lib/util/stream_utils.js

Closes https://github.com/shaka-project/shaka-player/issues/5098

feat(utils): Export shaka.util.StreamUtils.meetsRestrictions

---

lib/abr/simple_abr_manager.js

fix: check for existance of addEventListener and removeEventListener in navigator.connection before using them

---

lib/hls/hls_parser.js

Fix a regression caused by https://github.com/shaka-project/shaka-player/commit/fdc5cb165d1cf02e48de8c814efaae6eb54a3dbe

chore: Fix unreleased HLS playback regression

---

docs/tutorials/welcome.md

docs: Update Java download link

---

build/types/transmuxer
docs/tutorials/upgrade.md
externs/shaka/transmuxer.js
lib/media/media_source_engine.js
lib/transmuxer/mp3_transmuxer.js
lib/transmuxer/mpeg_audio.js
lib/util/id3_utils.js
lib/util/mp4_generator.js
shaka-player.uncompiled.js
test/transmuxer/transmuxer_integration.js

This transmuxer is used in Firefox due the lack of support for `audio/mpeg`

feat: Add MP3 transmuxer

---

lib/hls/hls_parser.js

With this change, we improve performance on very large playlists.

fix(HLS): Avoid variable substitution if no variables

---

lib/media/segment_prefetch.js
lib/media/streaming_engine.js

This change improve the latency in LL-DASH streams when using prefetch

feat: Add support to streamDataCallback when using prefetch

---

externs/ima.js

Adds StreamRequest.omidAccessModeRules, OmidVerificationVendor, and OmidAccessMode.
Copied from a contribution to the Shaka Player mirror in Google's internal repository.

chore: Update IMA externs

---

demo/common/assets.js
demo/common/message_ids.js
demo/locales/en.json
demo/locales/source.json
demo/search.js

* Allow filtering by low latency streams in demo page.

feat(Demo): Add Low Latency filter in demo page

---

package-lock.json
package.json

Fixed via shaka-project/webdriver-installer#24 in webdriver-installer@1.1.6 and shaka-project/karma-local-wd-launcher#53 in karma-local-wd-launcher@1.6.2

fix: Fix failure when drivers lag behind browser

---

karma.conf.js

While working on some lab infrastructure changes, I ended up with screenshot commands timing out.  This ended up triggering a surprising error condition that we didn't handle correctly.  This adds a check for this condition, and some helpful debug logs for it.  The underlying issue is solved now, but should it ever return, this will help.

ci: Debug unexpected screenshot failures

---

lib/text/vtt_text_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/5020

fix(WebVTT): Fix text-shadow in WebVTT not working

---

ui/range_element.js

Fixes https://github.com/shaka-project/shaka-player/issues/5450

fix(UI): Disable right click on range elements

---

README.md

Related to https://github.com/shaka-project/shaka-player/issues/5438

chore: Add thumbnails support to README

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/5471

fix: Fix playRangeEnd does not work with HLS streams

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/5480

fix: Remove duplicate adaptation event before init

---

lib/cea/mp4_cea_parser.js
lib/text/mp4_vtt_parser.js

Related to https://github.com/shaka-project/shaka-player/issues/3784

feat: Parses a TFDT Box, with a loss of precision beyond 53 bits

---

lib/text/srt_text_parser.js
lib/text/vtt_text_parser.js
test/text/srt_text_parser_unit.js

Info about the format in https://docs.fileformat.com/video/srt/

feat(SRT): Support stylized payload in SRT format

---

externs/shaka/manifest.js
externs/shaka/offline.js
lib/dash/dash_parser.js
lib/hls/hls_parser.js
lib/media/media_source_engine.js
lib/media/streaming_engine.js
lib/mss/mss_parser.js
lib/offline/indexeddb/v1_storage_cell.js
lib/offline/indexeddb/v2_storage_cell.js
lib/offline/manifest_converter.js
lib/offline/storage.js
lib/player.js
lib/util/periods.js
test/media/adaptation_set_unit.js
test/media/media_source_engine_unit.js
test/offline/manifest_convert_unit.js
test/test/util/manifest_generator.js
test/test/util/offline_utils.js
test/test/util/streaming_engine_util.js

Fixes https://github.com/shaka-project/shaka-player/issues/5458
Fixes https://github.com/shaka-project/shaka-player/issues/5443

fix(HLS): Fix external subtitles out of sync in HLS

---

ui/externs/ui.js

Closes https://github.com/shaka-project/shaka-player/issues/5019

docs: Update Label documentation

---

externs/ima.js
externs/shaka/ads.js
lib/ads/client_side_ad.js
lib/ads/server_side_ad.js
lib/text/simple_text_displayer.js
test/test/util/fake_ad.js

Closes https://github.com/shaka-project/shaka-player/issues/5431

feat(ads): Add getPodIndex to CS and SS ads

---

ui/seek_bar.js

Fixes https://github.com/shaka-project/shaka-player/issues/5080

fix(UI): Fix playback restarts in safari when click on seekbar end

---

demo/main.js
docs/tutorials/ad_monetization.md
externs/ima.js
externs/shaka/ads.js
lib/ads/ad_manager.js
lib/ads/client_side_ad_manager.js
test/ads/ad_manager_unit.js
test/test/util/fake_ad_manager.js

Closes https://github.com/shaka-project/shaka-player/issues/5011

feat(Ads): Add control AdsRenderingSettings

---

demo/common/assets.js

Closes https://github.com/shaka-project/shaka-player/issues/5534

chore(Demo): Move livesim URLs to livesim2

---

lib/ads/client_side_ad_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/4800

fix(Ads): Initialize correctly the IMA ads manager

---

test/test/util/ui_utils.js
test/transmuxer/transmuxer_integration.js

Closes https://github.com/shaka-project/shaka-player/issues/5546

test: Improve transmuxer tests

---

lib/util/mp4_generator.js

Fixes the mvex generation
Removes width and height from tkhd box for audio tracks

fix: Fix Mp4Generator

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/5577

fix(HLS): Allow audio groups on audio-only content

---

externs/shaka/namespace.js

This gets around some compilation issues I had with a large codebase.

chore: Added constantProperty to the @suppress statement namespace.js

---

lib/text/simple_text_displayer.js

Fixes https://github.com/shaka-project/shaka-player/issues/5581

fix: Remove debugging code on Simple Text

---

lib/dash/segment_template.js

Fixes https://github.com/shaka-project/shaka-player/issues/5614

fix(DASH): Fix race condition error while switching audio tracks

---

CONTRIBUTORS
docs/tutorials/faq.md

docs: Fix registerScheme snippet

---

lib/text/vtt_text_parser.js
test/text/vtt_text_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/4765

fix(WebVTT): Fix wrong writing-mode in nested cues

---

externs/css_style_declaration.js
lib/text/cue.js
lib/text/ui_text_displayer.js
lib/text/vtt_text_parser.js
test/text/vtt_text_parser_unit.js

Related to https://github.com/shaka-project/shaka-player/issues/2853

feat(WebVTT): Add support to text-combine-upright

---

lib/abr/simple_abr_manager.js

Closes: https://github.com/shaka-project/shaka-player/issues/5335
Closes: https://github.com/shaka-project/shaka-player/issues/5101

feat(ABR): Allow some downscale when use restrictToElementSize or restrictToScreenSize

---

lib/text/cue.js
lib/text/ui_text_displayer.js
lib/text/vtt_text_parser.js
test/text/vtt_text_parser_unit.js

Related to https://github.com/shaka-project/shaka-player/issues/2853

feat(WebVTT): Add support to ruby, rt, rp html tags

---

lib/dash/mpd_utils.js
lib/dash/segment_template.js

Closes https://github.com/shaka-project/shaka-player/issues/4337
Only supported on browsers with support to BigInt

feat(DASH): Allow the playback of DASH with $time$ and large timescale value

---

lib/text/ttml_text_parser.js
test/text/ttml_text_parser_unit.js

Related to https://github.com/shaka-project/shaka-player/issues/2853

feat(TTML): Add support to tts:textCombine

---

lib/dash/dash_parser.js

This change is required in preparation for https://github.com/shaka-project/shaka-player/issues/5622

chore(DASH): Create makeNetworkRequest_ method

---

externs/shaka/manifest.js
lib/hls/hls_parser.js
lib/media/segment_index.js
lib/media/segment_reference.js
lib/media/streaming_engine.js
test/hls/hls_parser_unit.js
test/media/segment_index_unit.js
test/media/segment_prefetch_unit.js
test/media/streaming_engine_unit.js
test/test/util/streaming_engine_util.js

This change is required in preparation for https://github.com/shaka-project/shaka-player/issues/5622

chore: Rename hlsAes128Key to aes128Key

---

lib/hls/hls_parser.js
lib/util/error.js

This change is required in preparation for https://github.com/shaka-project/shaka-player/issues/5622

chore: Rename HLS_AES_128_* to AES_128_*

---

build/types/ui
docs/tutorials/ui-customization.md
externs/media_remote.js
shaka-player.uncompiled.js
ui/remote_button.js
ui/ui.js

API: https://developer.mozilla.org/en-US/docs/Web/API/RemotePlayback
Chrome Status: https://chromestatus.com/feature/5778318691401728
Examples: https://avayvod.github.io/remote-playback/test.html and https://beaufortfrancois.github.io/sandbox/media/remote-playback.html
Tested in Safari (iOS and macOS) and Chrome in Android
About desktop support: https://bugs.chromium.org/p/chromium/issues/detail?id=728609

feat(UI): Add remote button with RemotePlayback API

---

lib/dash/dash_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/5672

fix: Fix creation of new Stream object for each manifest request in DASH Live when using CEA

---

lib/text/cue.js

Fixes https://github.com/shaka-project/shaka-player/issues/5669

fix: Fix some properties on the shaka.text.Cue that are mangled

---

ui/controls.js
ui/externs/ui.js
ui/ui.js

Closes https://github.com/shaka-project/shaka-player/issues/5689

feat(UI): Add config to preferDocumentPictureInPicture

---

lib/hls/hls_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/5627

fix(HLS): Fix display CEA-708 in HLS

---

docs/tutorials/offline.md

Fixes https://github.com/shaka-project/shaka-player/issues/5703

docs: Fix offline tutorial

---

lib/player.js
lib/util/fake_event.js

Closes https://github.com/shaka-project/shaka-player/issues/1365

feat: Add KeyStatusChanged and UpdateState events

---

lib/media/play_rate_controller.js
lib/media/stall_detector.js
lib/player.js
test/media/play_rate_controller_unit.js
test/player_src_equals_integration.js

Closes https://github.com/shaka-project/shaka-player/issues/2093

feat: Stop setting playbackRate to 0 to control buffering state

---

lib/media/media_source_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/5730

fix: For text content is not necessary codec switching

---

docs/tutorials/plugins.md

Closes https://github.com/shaka-project/shaka-player/issues/5741

docs: Add missing text and manifest parsers

---

ui/language_utils.js

Fixes https://github.com/shaka-project/shaka-player/issues/5747

fix(UI): Fix text selector when the trackLabelFormat is set to LABEL

---

ui/resolution_selection.js

Closes https://github.com/shaka-project/shaka-player/issues/5749

feat(UI): Display frame rates in the quality selector

---

lib/media/segment_prefetch.js

Regression introduced at https://github.com/shaka-project/shaka-player/pull/5310

fix: Dispatch streamDataCallback correctly in SegmentPrefetchOperation

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js
third_party/closure-uri/uri.js

Closes https://github.com/shaka-project/shaka-player/issues/5333

feat(HLS): Add support for QUERYPARAM variable type in #EXT-X-DEFINE

---

demo/common/assets.js
lib/player.js
lib/util/error.js
test/player_src_equals_integration.js

Closes https://github.com/shaka-project/shaka-player/issues/5778

feat: Add thumbnails support in src=

---

build/types/core
lib/player.js
lib/text/stub_text_displayer.js

Closes https://github.com/shaka-project/shaka-player/issues/5804

feat: Add a stub text display class (#5804)

---

build/types/core
externs/shaka/cea.js
externs/shaka/manifest.js
externs/shaka/offline.js
lib/cea/cea_decoder.js
lib/cea/dummy_caption_decoder.js
lib/hls/hls_parser.js
lib/media/closed_caption_parser.js
lib/media/segment_utils.js

Related to https://github.com/shaka-project/shaka-player/issues/1826

feat(HLS): Build closed captions metadata for media playlist on-the-fly.

---

lib/hls/hls_parser.js

Related to https://github.com/shaka-project/shaka-player/issues/5810

fix(HLS): Fix kind detection for 'captions' text tracks

---

demo/common/asset.js
demo/common/assets.js
demo/main.js

Related to https://github.com/shaka-project/shaka-player/issues/3597

chore(Demo): Add extra chapter functionality

---

test/ui/ui_integration.js
ui/resolution_selection.js

Closes https://github.com/shaka-project/shaka-player/issues/2090

feat(UI): Bucketize resolution names in the UI

---

ui/remote_button.js

Fixes: https://github.com/shaka-project/shaka-player/issues/5766

fix(UI): Console error on remote.cancelwatchavailability() method in remote playback feature

---

lib/media/streaming_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/5824

fix: Fix crash while playing HLS AES 128 streams

---

lib/offline/storage.js
lib/player.js
lib/util/stream_utils.js
test/util/stream_utils_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/4242

fix: Fix incompatible codec is selected in Windows Edge for Widevine

---

docs/tutorials/basic-usage.md

Looks like this was just introduced in #5752

docs: fix await keyword for attach method

---

lib/hls/hls_parser.js

Closes https://github.com/shaka-project/shaka-player/issues/5810

fix(HLS): Fix accessibilityPurpose detection

---

demo/config.js
externs/shaka/manifest.js
externs/shaka/player.js
lib/dash/dash_parser.js
lib/player.js
lib/util/player_configuration.js
test/dash/dash_parser_manifest_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/5780

feat(DASH): Add support for minimum values in service descriptions

---

lib/offline/storage.js

Fixes https://github.com/shaka-project/shaka-player/issues/5132

fix(offline): Fix server certificate error when trying to store content

---

lib/ads/media_tailor_ad_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/5854

fix: AD_STARTED fires before ad started with AWS Media Tailor

---

README.md
lib/player.js
lib/polyfill/mediasource.js

Closes https://github.com/shaka-project/shaka-player/issues/5134

feat: Add support for WPE based browsers in RDK set-top boxes

---

lib/offline/storage.js
lib/player.js
lib/util/stream_utils.js
test/util/stream_utils_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/5858

fix: Fix variant filtering by preferredAudioChannelCount

---

demo/common/assets.js

Closes https://github.com/shaka-project/shaka-player/issues/2457

feat(Demo): Add CBCS content to demo

---

README.md
demo/common/assets.js
externs/shaka/player.js
lib/hls/hls_parser.js
lib/player.js
lib/util/stream_utils.js
test/hls/hls_parser_unit.js
ui/seek_bar.js

It also adds support for rendering downloaded thumbnails.

feat(HLS): Add support for mjpg I-Frames playlist

---

demo/common/assets.js
demo/main.js
demo/search.js
lib/media/media_source_engine.js

It also creates a filter for UHD and corrects the filtering in some assets.

feat(Demo): Add new 3D movie stream from Apple

---

lib/media/streaming_engine.js

Related to https://github.com/shaka-project/shaka-player/issues/5785#issuecomment-1801944841

fix(HLS): Fix decryption of AES-128

---

lib/util/stream_utils.js
test/util/stream_utils_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/5858

fix: Fix missing audio streams

---

lib/abr/simple_abr_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/5873

fix(ABR): Fix HLS playback after internet connection is restored

---

lib/hls/hls_classes.js
lib/hls/hls_parser.js
lib/hls/hls_utils.js
lib/hls/manifest_text_parser.js
test/hls/hls_live_unit.js
test/hls/hls_parser_unit.js
test/hls/manifest_text_parser_unit.js
test/test/util/manifest_parser_util.js

This will allow adding support for Content Steering in HLS
It also improves the detection of duplicate playlists, and improves redirect management, leaving the original URL available in case it is needed.

refactor(HLS): Refactor URLs management in HLS

---

lib/dash/dash_parser.js
lib/dash/segment_template.js
test/dash/dash_parser_manifest_unit.js

Related to https://github.com/shaka-project/shaka-player/issues/5704

feat(DASH): Add support for Content Steering in AdaptationSet BaseURL

---

lib/hls/hls_parser.js
lib/util/content_steering_manager.js
test/hls/hls_parser_unit.js
test/test/util/fake_networking_engine.js

Closes https://github.com/shaka-project/shaka-player/issues/5704

feat(HLS): Add support for Content Steering

---

lib/util/content_steering_manager.js

Related to https://github.com/shaka-project/shaka-player/issues/5704

fix: Fix mangled property in compiled mode in Content Steering

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/5447

feat(HLS): Improve the stream info when EXT-X-MEDIA has not uri

---

lib/dash/segment_template.js

Fixes https://github.com/shaka-project/shaka-player/issues/5898

fix(DASH): SegmentTemplate@media not updated after change in manifest

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/5901

fix: Fix language comparison in addTextTrackAsync

---

build/types/core
demo/common/assets.js
demo/config.js
externs/shaka/abr_manager.js
externs/shaka/player.js
lib/abr/simple_abr_manager.js
lib/player.js
lib/util/cmsd_manager.js
lib/util/player_configuration.js
test/util/cmsd_manager_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/5890

feat: Add support for Common Media Server Data (CMSD)

---

lib/dash/dash_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/2216

fix(DASH): Fix false redirect detection

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/5915

fix(HLS): Recognize CEA subtitles when CLOSED-CAPTIONS attribute is missing

---

docs/tutorials/lcevc.md
package-lock.json
package.json

This update adds support for Managed Media Source in LCEVC

chore(LCEVC): Update lcevc_dec.js dependency

---

demo/main.js
externs/mediasession.js

Closes https://github.com/shaka-project/shaka-player/issues/2812

feat(Demo): Use MediaSession action handler in the demo

---

ui/audio_language_selection.js
ui/resolution_selection.js

Closes https://github.com/shaka-project/shaka-player/issues/4720

feat(UI): Hide language and resolution overflow menu button if there's only one choice

---

lib/cea/cea608_memory.js
test/cea/cea608_memory_unit.js
test/cea/cea_decoder_unit.js

See: https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html#positioning-in-cea-608
Related to https://github.com/shaka-project/shaka-player/issues/2940

fix(CEA): Fix positioning in CEA-608

---

lib/transmuxer/ts_transmuxer.js
lib/util/error.js

Fixes https://github.com/shaka-project/shaka-player/issues/5931

fix: Fix transmuxer when sample has no video data

---

demo/common/asset.js
demo/custom.js
demo/main.js

Closes https://github.com/shaka-project/shaka-player/issues/5932

feat(Demo): Add field for chapters URL when adding custom content

---

demo/custom.js

Fixes https://github.com/shaka-project/shaka-player/issues/2200

fix(Demo): Pressing "Edit" button unstores custom asset, but does not update "stored" button

---

lib/media/streaming_engine.js

Closes https://github.com/shaka-project/shaka-player/issues/1384

feat: Avoid streams which cannot fit into the browser's MediaSource quota

---

ui/controls.js

Closes https://github.com/shaka-project/shaka-player/issues/3223

feat(UI): Add more keyboard shortcuts

---

lib/media/media_source_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/5946

fix: Fix reset Media Source when using mixed codecs in different containers

---

demo/config.js
docs/tutorials/config.md
externs/shaka/player.js
lib/media/adaptation_set_criteria.js
lib/player.js
lib/util/player_configuration.js
test/media/adaptation_set_criteria_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/5947

feat: add preferred video label

---

.npmignore

Closes https://github.com/shaka-project/shaka-player/issues/2172

feat: Improve npm package size

---

test/transmuxer/transmuxer_integration.js

Related to https://github.com/shaka-project/shaka-player/issues/5834

test: Fix Edge versions to skip

---

test/player_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/2533

test: Add test for frameRate restriction

---

lib/util/ts_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/5913

fix: Fix transmuxer when some PES has the same pts and dts value

---

lib/media/media_source_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/5849

fix(HLS): Fix variant synchronization in HLS after selectVariantTrack

---

ui/volume_bar.js

Fixes https://github.com/shaka-project/shaka-player/issues/3987

fix(UI): Fix keyboard navigation of volume bar on Firefox

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/4474

fix: Fix liveLatency in stats

---

ui/controls.js

Fixes https://github.com/shaka-project/shaka-player/issues/5991

fix(UI): Fix disable PiP when using documentPictureInPicture

---

externs/shaka/manifest.js
lib/dash/dash_parser.js
lib/dash/segment_base.js
lib/dash/segment_list.js
lib/dash/segment_template.js
lib/hls/hls_parser.js
lib/media/segment_index.js
lib/media/segment_reference.js
lib/media/streaming_engine.js
test/hls/hls_parser_unit.js
test/media/segment_index_unit.js
test/media/segment_prefetch_unit.js
test/media/streaming_engine_unit.js
test/test/util/streaming_engine_util.js

See: https://mailarchive.ietf.org/arch/msg/hls-interest/RZBgatOvI4W0M0J5cShuXWzdigg/

feat: Rename aes128Key to aesKey to allow aes256 in the future

---

ui/resolution_selection.js

Fixes https://github.com/shaka-project/shaka-player/commit/628bb63c4c082b44f749876cf1cb8b3f06887d0b

feat(UI): Hide resolution overflow menu button if there's only one choice

---

lib/util/periods.js
test/util/periods_unit.js

fix: text roles being combined incorrectly in some multiperiod cases

---

ui/externs/ui.js
ui/text_selection.js
ui/ui.js

Closes https://github.com/shaka-project/shaka-player/issues/6008

feat(UI): Separate trackLabelFormat settings for text tracks and audio tracks

---

ui/hidden_seek_button.js

Fixes https://github.com/shaka-project/shaka-player/issues/6027

fix(UI): Fix the scrolling when scrolling from the laterals when seekOnTaps is enabled

---

lib/hls/hls_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/6019

fix(HLS): Live recovery after disconnects

---

lib/ads/client_side_ad.js
lib/ads/client_side_ad_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/6020
Fixes https://github.com/shaka-project/shaka-player/issues/6037

fix(Ads): Fix VMAP won't play in muted autoplay

---

lib/hls/hls_parser.js
lib/media/media_source_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/6032

fix(HLS): Fix playback of muxed TS content in Safari

---

lib/hls/hls_parser.js
lib/media/presentation_timeline.js

Fixes https://github.com/shaka-project/shaka-player/issues/5939

fix(HLS): getPlayheadTimeAsDate() differs from X-EXT-PROGRAM-DATE-TIME

---

ui/resolution_selection.js

Related to https://github.com/shaka-project/shaka-player/issues/6039

feat(UI): Use the same logic to group variants into audio and quality selectors

---

lib/text/vtt_text_parser.js

Related to https://github.com/shaka-project/shaka-player/issues/6065

perf(WebVTT): Improve parsing time for unstyled payloads

---

lib/ads/client_side_ad.js
lib/ads/client_side_ad_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/6071

fix(Ads): Fix muting/unmuting ads won't affect video and vice versa

---

lib/offline/session_deleter.js

Fixes https://github.com/shaka-project/shaka-player/issues/6079

fix(offline): Fix server certificate error when trying to delete stored content

---

lib/cast/cast_utils.js
lib/media/presentation_timeline.js
lib/player.js
test/player_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/2711

feat: Expose PresentationTimeline segment availability duration through Player

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/6065

perf: Improve performance of addThumbnailsTrack

---

lib/util/periods.js

fix: do not append blank codec strings

---

docs/tutorials/index.json
docs/tutorials/text-displayer.md

Closes https://github.com/shaka-project/shaka-player/issues/4862

docs: Add tutorial for text displayer

---

build/test.py

closes https://github.com/shaka-project/shaka-player/issues/2078

test: Make it easier to run just the offline tests

---

build/test.py

Related to https://github.com/shaka-project/shaka-player/pull/6102

test: Make it easier to run just the offline tests (documentation)

---

lib/cast/cast_proxy.js

Fixes https://github.com/shaka-project/shaka-player/issues/4036

fix: When disconnecting from chromecast, subtitles are turned off

---

ui/controls.js

Closes https://github.com/shaka-project/shaka-player/issues/6116

feat(UI): Allow show/hide ui programmatically

---

lib/util/platform.js
lib/util/stream_utils.js

Fixes https://github.com/shaka-project/shaka-player/issues/6111

fix: Reject Opus encrypted on Firefox Android

---

lib/util/ts_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/6136

fix: Fix nalu parsing in TS

---

lib/text/vtt_text_parser.js
test/text/vtt_text_parser_unit.js

The tXml parser gracefully handles this now, so it is no longer needed.

feat(WebVTT): Remove un-needed VTT payload normalisation

---

lib/media/drm_engine.js
lib/player.js
test/test/util/fake_drm_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/5176

fix: Allow by default variants without pssh in the manifest

---

lib/offline/storage.js

Fixes https://github.com/shaka-project/shaka-player/issues/6141

fix(offline): Fix store persistent licenses with drm info in the pssh

---

lib/polyfill/media_capabilities.js
test/polyfill/media_capabilities_unit.js

See https://developers.google.com/cast/docs/media#audio_passthrough

fix: Fix detection of spatial rendering support in Cast

---

lib/util/stream_utils.js
test/util/stream_utils_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/6162

fix: player Dropping Variant (better codec available) when it should not

---

lib/mss/mss_parser.js
lib/transmuxer/aac_transmuxer.js
lib/transmuxer/ac3_transmuxer.js
lib/transmuxer/ec3_transmuxer.js
lib/transmuxer/h264.js
lib/transmuxer/h265.js
lib/transmuxer/mp3_transmuxer.js
lib/transmuxer/ts_transmuxer.js
lib/util/mp4_generator.js

Fixes https://github.com/shaka-project/shaka-player/issues/6168

fix: Fix wrong aspect ratio in transmuxed videos

---

lib/dash/dash_parser.js
test/dash/dash_parser_live_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/6185

fix(DASH): Update dash manifest when minimumUpdatePeriod = 0

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/3429

fix: Prevent license requests for unplayable variants

---

docs/tutorials/ui-customization.md

Closes https://github.com/shaka-project/shaka-player/issues/3464

docs: Add specific doc on UI localization strategies

---

demo/config.js
externs/shaka/player.js
lib/player.js
lib/util/player_configuration.js

Dynamically update playback rate to keep the buffer full.
Related to https://github.com/shaka-project/shaka-player/issues/6131

feat: vod dynamic playback rate buffer control

---

demo/asset_card.js
lib/player.js

Also fixes how demo cards handle src= preloads.

fix(preload): Only start preload if manager exists

---

test/test/util/waiter.js

test: Fix seek range test flake on Safari

---

demo/config.js
externs/shaka/player.js
lib/media/streaming_engine.js
lib/util/player_configuration.js

Fixes: https://github.com/shaka-project/shaka-player/issues/6205

feat: Add config to set live stream duration to Infinity

---

test/test/util/fake_segment_prefetch.js

test: Add missing method in fake SegmentPrefetch

---

lib/util/mp4_box_parsers.js

Related to https://github.com/shaka-project/shaka-player/issues/2532

fix: Fix compiler issue in Mp4BoxParsers

---

lib/hls/hls_parser.js
lib/media/presentation_timeline.js

This reverts 776b69dcb99e1f5dbd22181e40c22898f0b8e47a
Closes #6317
Closes #6299
Reopening issue #5939

revert: getPlayheadTimeAsDate() differs from X-EXT-PROGRAM-DATE-TIME

---

externs/shaka/abr_manager.js
externs/shaka/net.js
lib/abr/simple_abr_manager.js
lib/media/streaming_engine.js
lib/net/networking_engine.js
lib/player.js
test/net/networking_engine_unit.js

This PR makes the following request information available for ABR consideration. Allowing the ABR manager to know about the request latency from the time to first byte and knowing the order order of a packet, as well as the contentType of the request.

feat(ABR): Additional request information for ABR Managers

---

externs/shaka/player.js

https://i.imgur.com/gcvICl9.png

chore: Update getStats() docs WRT NaN

---

test/util/cmcd_manager_unit.js

test: update CMCD tests to allow them to be run individually 

---

docs/tutorials/faq.md

Closes https://github.com/shaka-project/shaka-player/issues/6231

docs: Add FAQ documentation for minimum recommended chunks

---

demo/config.js
docs/tutorials/upgrade.md
externs/shaka/player.js
lib/media/media_source_engine.js
lib/util/player_configuration.js
test/media/media_source_engine_unit.js

feat: add `mediaSource.addExtraFeaturesToSourceBuffer`

---

lib/polyfill/media_capabilities.js

Related to https://github.com/shaka-project/shaka-player/issues/5776#issuecomment-1934955286

perf(Cast): memoize/cache canDisplayType results to reduce startup latency

---

externs/shaka/ads.js
lib/ads/ad_manager.js
lib/ads/media_tailor_ad_manager.js
test/test/util/fake_ad_manager.js

Closes https://github.com/shaka-project/shaka-player/issues/6234

feat(Ads): Add ability to set tracking URL for Media Tailor

---

lib/util/platform.js

Fixes https://github.com/shaka-project/shaka-player/issues/6353

fix: Disable smooth codec switching in Edge Windows

---

lib/util/manifest_parser_utils.js

IAMF spec: https://aomediacodec.github.io/iamf/
IAMF codec string: https://aomediacodec.github.io/iamf/#codecsparameter

fix(HLS): Fix IAMF codec selection in HLS

---

lib/text/vtt_text_parser.js
test/text/vtt_text_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/6320

fix(WebVTT): Remove rollover logic because we always transmux TS

---

lib/text/ttml_text_parser.js
test/text/ttml_text_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/4974

fix(TTML): Fix trim surrounding spaces with xml:space="default"

---

lib/util/tXml.js
test/text/vtt_text_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/6374

fix(WebVTT): Fix multiline colored VTT subtitles

---

lib/dash/dash_parser.js
lib/dash/segment_template.js
test/dash/dash_parser_manifest_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/2430
Test stream: http://dash.akamaized.net/dash264/TestCasesIOP41/LastSegmentNumber/1/manifest_last_segment_num.mpd

feat(DASH): Add signalling the last segment number in Period

---

demo/config.js
externs/shaka/player.js
lib/dash/dash_parser.js
lib/util/player_configuration.js

Closes https://github.com/shaka-project/shaka-player/issues/6418

feat(DASH): update period as part of configuration

---

docs/tutorials/faq.md

docs: Add FAQ entry about new versions.

---

lib/util/stream_utils.js

Fixes https://github.com/shaka-project/shaka-player/issues/6233

fix(HLS): Fix labelling of captions in Safari

---

lib/hls/hls_parser.js
lib/player.js
test/player_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/2959

feat: Make getPlayheadTimeAsDate and getPresentationStartTimeAsDate available for VOD

---

docs/tutorials/offline.md

Closes https://github.com/shaka-project/shaka-player/issues/6338

docs: Add note about the result of calling storage.store twice

---

demo/common/assets.js
demo/config.js
externs/shaka/player.js
lib/player.js
lib/util/player_configuration.js
test/hls/hls_parser_integration.js
test/player_unit.js
test/transmuxer/transmuxer_integration.js

Backwards compatibility for https://github.com/shaka-project/shaka-player/pull/6188

chore: Add backwards compatibility for useNativeHlsOnSafari

---

build/conformance.textproto
build/types/core
docs/tutorials/upgrade.md
externs/shaka/player.js
lib/ads/ad_manager.js
lib/dash/dash_parser.js
lib/mss/mss_parser.js
lib/player.js
lib/util/player_configuration.js
lib/util/tXml.js
lib/util/xml_utils.js
test/dash/dash_parser_live_unit.js
test/dash/dash_parser_manifest_unit.js
test/media/region_observer_unit.js
test/media/region_timeline_unit.js
test/mss/mss_parser_unit.js

Backwards compatibility for https://github.com/shaka-project/shaka-player/pull/6063

chore: Add backwards compatibility for "Remove DOM Parser"

---

lib/media/media_source_engine.js

fix: Fix uncaught global OBJECT_DESTROYED errors

---

lib/media/segment_index.js

Fixes https://github.com/shaka-project/shaka-player/issues/6461
Tested by @tykus160

fix: Fix support of getAllThumbnails when using DASH multi-period

---

externs/shaka/player.js
lib/net/networking_engine.js
lib/player.js
lib/util/stats.js
test/player_integration.js
ui/statistics_button.js
ui/ui.js

Closes https://github.com/shaka-project/shaka-player/issues/6413

feat: Add bytesDownloaded to stats

---

lib/text/ui_text_displayer.js

Fixes https://github.com/shaka-project/shaka-player/issues/6341

fix: Fix reusing region elements in UITextDisplayer

---

lib/player.js
test/player_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/5420

fix: Fix duplicate init segment download when using startAtSegmentBoundary

---

lib/polyfill/media_capabilities.js

Related to https://github.com/shaka-project/shaka-player/issues/1419

feat: Add encryptionScheme support on MCap polyfill

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js

Test stream: https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel-aes.ism/.m3u8

feat: Preload AES key when the key is available in EXT-X-SESSION-KEY

---

docs/tutorials/ui.md

A set of small changes to improve the documentation on the UI chapter.

docs: add missing closing text and capitalize UI

---

ui/resolution_selection.js

Fixes https://github.com/shaka-project/shaka-player/issues/6494

fix(UI): Allow show same resolution with different video bandwidth

---

lib/util/tXml.js

Fixes https://github.com/shaka-project/shaka-player/issues/6524

fix: Fix tXml conversion to DOMElement

---

lib/util/platform.js

Fixes https://github.com/shaka-project/shaka-player/issues/6533
The original author is: @stuartflanagan 
The original PR is: https://github.com/shaka-project/shaka-player/pull/6554

fix: Issue with compiler minifying webOS device properties

---

lib/net/http_plugin_utils.js
lib/util/error.js
test/net/http_plugin_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/2969

feat: Add response URI to BAD_HTTP_STATUS error

---

package-lock.json
package.json

This uses a preview of https://github.com/faisalman/ua-parser-js/pull/724 to differentiate between Chromecast models in Karma.

test: Upgrade UA parser to differentiate Chromecasts

---

lib/dash/dash_parser.js
lib/media/segment_utils.js

Close https://github.com/shaka-project/shaka-player/issues/6589

feat(DASH): Support Dolby Vision profile 8.x (HEVC) and 10.x (AV1)

---

AUTHORS
CONTRIBUTORS
lib/media/segment_utils.js

fix(HLS): Fix mimetype checking when using SUPPLEMENTAL-CODECS

---

karma.conf.js

Using --filter naturally causes a bunch of tests to be skipped.  Only print skipped tests when we are not explicitly filtering tests on the command-line.

test: Do not print skipped tests when filtering

---

package-lock.json
package.json

Karma is no longer being bug-fixed or maintained.  This upgrades to the latest version as a prelude to moving to a fork with additional bugfixes.

test: Upgrade Karma to latest

---

docs/tutorials/errors.md

Correctly pass the event.detail to the error handler instead of the event

docs: update error documentation

---

demo/common/assets.js

- Delete assets that no longer work
- Fix features that are incorrect in some DASH-IF streams
- Fix some wrong urls when assets were migrated from livesim to livesim2

chore(Demo): Update demo assets

---

demo/config.js
externs/shaka/player.js
lib/abr/simple_abr_manager.js
lib/util/player_configuration.js

Close https://github.com/shaka-project/shaka-player/issues/6623

feat(ABR): Add cacheLoadThreshold config

---

ui/range_element.js

Fixes https://github.com/shaka-project/shaka-player/issues/6625

fix(UI): Fix dragging the seek bar seeks and pans the view in VR mode

---

lib/polyfill/media_capabilities.js
test/polyfill/media_capabilities_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/5776

fix(Cast): Incorrect detection of MediaCapabilities on Chromecast

---

demo/config.js
externs/shaka/player.js
lib/player.js
lib/util/player_configuration.js

Fixes https://github.com/shaka-project/shaka-player/issues/6664

fix: Add timeout to fullyLoaded in src=

---

lib/cea/cea608_data_channel.js
lib/cea/cea_decoder.js

fix(CEA): Ignore XDS control codes

---

demo/config.js
externs/shaka/player.js
lib/hls/hls_parser.js
lib/util/player_configuration.js
test/cast/cast_receiver_integration.js
test/hls/hls_live_unit.js
test/hls/hls_parser_unit.js

Closes https://github.com/shaka-project/shaka-player/issues/1826
Also fixes variable substitution when using `getMediaPlaylistBasicInfo_`

feat(HLS): Build closed captions metadata on-the-fly

---

lib/media/content_workarounds.js
lib/media/media_source_engine.js
lib/transmuxer/aac_transmuxer.js
lib/transmuxer/ac3_transmuxer.js
lib/transmuxer/ec3_transmuxer.js
lib/transmuxer/mp3_transmuxer.js
lib/transmuxer/mpeg_ts_transmuxer.js
lib/transmuxer/mss_transmuxer.js
lib/transmuxer/ts_transmuxer.js
lib/util/error.js
test/media/content_workarounds_unit.js
test/media/media_source_engine_unit.js

This makes it more feasible to debug and fix transmuxer bugs or other segment append failures.
Closes #6712

feat: Add segment URIs to segment-related errors

---

ui/audio_language_selection.js
ui/resolution_selection.js
ui/text_selection.js

Fixes https://github.com/shaka-project/shaka-player/issues/6720

fix(UI): UI does not update after loading a new stream

---

demo/common/assets.js

Related to https://github.com/shaka-project/shaka-player/issues/6710

chore(Demo): Add new assets with clearkeys

---

lib/hls/hls_parser.js
test/hls/hls_live_unit.js

Only happens when we use `useSafariBehaviorForLive = false`.

fix(HLS): Fix seekRange when using delta playlist

---

externs/shaka/player.js
lib/player.js
lib/util/stats.js
test/player_integration.js
ui/statistics_button.js

Add `nonFatalErrorCount` to shaka stats.

feat(Stats): count non fatal errors

---

externs/shaka/manifest.js
externs/shaka/player.js
lib/dash/dash_parser.js
lib/hls/hls_parser.js
lib/mss/mss_parser.js
lib/offline/manifest_converter.js
lib/player.js
lib/util/stats.js
test/dash/dash_parser_live_unit.js
test/dash/dash_parser_patch_unit.js
test/media/playhead_unit.js
test/media/streaming_engine_integration.js
test/player_integration.js
test/test/util/manifest_generator.js
test/test/util/streaming_engine_util.js
ui/statistics_button.js

feat(Stats): Add `manifestPeriodCount` to stats

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/6801

fix: Fix initial track selection in src= when using HLS

---

externs/shaka/manifest.js
externs/shaka/player.js
lib/dash/dash_parser.js
lib/hls/hls_parser.js
lib/mss/mss_parser.js
lib/offline/manifest_converter.js
lib/player.js
lib/util/stats.js
test/dash/dash_parser_manifest_unit.js
test/hls/hls_parser_unit.js
test/media/playhead_unit.js
test/media/streaming_engine_integration.js
test/player_integration.js
test/test/util/manifest_generator.js
test/test/util/streaming_engine_util.js
ui/statistics_button.js

feat(Stats): Add `manifestGapCount` to stats

---

lib/player.js
lib/util/cmcd_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/6819

fix(CMCD): Fix reset CMCD on unload

---

lib/text/ttml_text_parser.js
test/text/ttml_text_parser_unit.js

Fixes: https://github.com/shaka-project/shaka-player/issues/6829

fix(TTML): Fix timing parsing when using 1dp

---

lib/media/playhead.js

Fixes https://github.com/shaka-project/shaka-player/issues/6841

fix: Allow use startTime equal to 0 in HLS live streams using src=

---

lib/media/drm_engine.js

https://github.com/shaka-project/shaka-player/pull/6651#discussion_r1643959553

fix(DRM): Probe robustness only for modern PlayReady keysystem

---

lib/media/streaming_engine.js
lib/player.js
test/test/util/simple_fakes.js

Fixes https://github.com/shaka-project/shaka-player/issues/6766

fix: Fix continues to play a few seconds after reaching playRangeEnd

---

build/types/ads
docs/tutorials/ad_monetization.md
lib/ads/ad_manager.js
lib/ads/ad_utils.js
lib/ads/client_side_ad_manager.js
lib/ads/interstitial_ad_manager.js
lib/ads/media_tailor_ad_manager.js
lib/ads/server_side_ad_manager.js
lib/player.js
test/ads/ad_manager_unit.js
test/ads_integration.js
test/test/util/fake_ad_manager.js
test/ui/ad_ui_unit.js
ui/ad_counter.js
ui/ad_position.js
ui/ad_statistics_button.js
ui/controls.js
ui/element.js
ui/mute_button.js
ui/overflow_menu.js
ui/play_button.js
ui/presentation_time.js
ui/seek_bar.js
ui/skip_ad_button.js
ui/volume_bar.js

To eliminate `* @suppress {missingRequire}` it was necessary to create a new class with the constants and deprecate the old ones. That's why this change is feat.

feat(Ads): Remove circular dependency

---

ui/less/thumbnails.less
ui/seek_bar.js

Close https://github.com/shaka-project/shaka-player/issues/3236

feat(UI): Highlight current time when hovered on seek bar

---

lib/cea/mp4_cea_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/5919

fix(CEA): CEA-608 is not rendered in some cases (multiples TRAF boxes)

---

lib/dash/mpd_utils.js
test/dash/mpd_utils_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/6889

fix(DASH): Allow play when SegmentTimeline has a duration 0 "S" element

---

lib/media/segment_prefetch.js
test/media/segment_prefetch_unit.js

fix(Prefetch): Ensure prefetched segments are continuous

---

externs/mediatailor.js
lib/ads/media_tailor_ad.js

Fixes https://github.com/shaka-project/shaka-player/issues/6909

fix(Ads): Fix skip functionality in MediaTailor

---

lib/hls/hls_parser.js

fix(HLS): Fix getAvailableSegment_ function

---

demo/config.js
externs/shaka/manifest_parser.js
externs/shaka/player.js
lib/dash/dash_parser.js
lib/hls/hls_parser.js
lib/media/preload_manager.js
lib/mss/mss_parser.js
lib/offline/offline_manifest_parser.js
lib/player.js
lib/util/player_configuration.js
test/offline/storage_integration.js
test/test/util/test_scheme.js

Close https://github.com/shaka-project/shaka-player/issues/3781

feat: Add option to disable continue loading live stream manifest when paused

---

build/types/ui
docs/tutorials/ui-customization.md
shaka-player.uncompiled.js
ui/enums.js
ui/locales/en.json
ui/locales/es.json
ui/locales/fr.json
ui/locales/pl.json
ui/locales/pt-BR.json
ui/locales/pt-PT.json
ui/locales/source.json
ui/save_video_frame_button.js
ui/ui.js

Thank you @tykus160 for your Polish translation!

feat(UI): Add save video frame button

---

demo/common/assets.js
demo/config.js
externs/shaka/player.js
lib/player.js
lib/util/player_configuration.js
test/ads_integration.js
test/hls/hls_parser_integration.js
test/player_dolby_vision_integration.js
test/player_unit.js
test/transmuxer/transmuxer_integration.js

This change is feat because it changes Safari's default from native to MSE.

feat: Fix useNativeHlsOnSafari deprecation

---

build/build.py

build: don't include externs in generated .d.ts files

---

lib/text/ssa_text_parser.js
test/text/ssa_text_parser_unit.js

Related to https://github.com/shaka-project/shaka-player/issues/6943

fix(SSA): Support files with line breaks that are not necessary

---

lib/media/presentation_timeline.js
test/media/presentation_timeline_unit.js

Resolves https://github.com/shaka-project/shaka-player/issues/6963

fix: Exclude future segments in notifyTimeRange calculations

---

lib/hls/hls_parser.js

Regression of https://github.com/shaka-project/shaka-player/pull/6378 (only in debug builds)

chore(HLS): Change bad warning

---

lib/player.js

Resolves https://github.com/shaka-project/shaka-player/issues/6943

feat: Export addFont method

---

lib/util/platform.js

See: https://video-dev.slack.com/archives/C01QRAFHLQK/p1720126664717089

fix(Xbox): Fix screen resolution detection

---

lib/text/ui_text_displayer.js
test/text/text_displayer_layout_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/3732 (we resolve it using offset operation instead of clipping)

fix: Offset text regions that are out of viewport

---

lib/media/media_source_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/5528
This PR handles audio compensation when the audio and video are decompensating.

fix(HLS): A/V sync regression for HLS live

---

docs/tutorials/index.json
docs/tutorials/screen-resolution-detection.md

Related to https://github.com/shaka-project/shaka-player/pull/6988#issuecomment-2211344636

docs: Add documentation about screen resolution detection

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/6665

fix: Fix bad warning when use selectAudioLanguage

---

lib/util/stream_utils.js
test/hls/hls_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7007

fix(HLS): Fix filtering video/audio streams without bandwidth

---

lib/media/media_source_engine.js

Regression of https://github.com/shaka-project/shaka-player/pull/6987
See: https://github.com/shaka-project/shaka-player/pull/6987#issuecomment-2220013890

fix(HLS): A/V sync regression for HLS with different segment sizes

---

build/types/ui
docs/tutorials/ui-customization.md
shaka-player.uncompiled.js
ui/chapter_selection.js
ui/enums.js
ui/less/overflow_menu.less
ui/locales/en.json
ui/locales/es.json
ui/locales/fr.json
ui/locales/source.json
ui/ui.js

Closes https://github.com/shaka-project/shaka-player/issues/3597

feat(UI): Add chapter button

---

lib/text/simple_text_displayer.js
lib/text/text_utils.js

chore: Move convertToTextTrackCue_ to shaka.text.Utils

---

lib/cea/cea608_data_channel.js
lib/cea/cea608_memory.js

Closes https://github.com/shaka-project/shaka-player/issues/2940

feat(CEA): Support alignment in CEA-608

---

ui/seek_bar.js

Related to https://github.com/shaka-project/shaka-player/pull/7029

fix(UI): Fix seek preview time in VoD

---

externs/shaka/player.js

Closes https://github.com/shaka-project/shaka-player/issues/1544

docs: Extract the current defaults config values into the config documentation

---

lib/text/text_utils.js
test/text/text_utils_unit.js

chore: Add native cue to shaka cue mapping

---

lib/util/periods.js
test/util/periods_unit.js

Resolves https://github.com/shaka-project/shaka-player/issues/7026
Resolves https://github.com/shaka-project/shaka-player/issues/3816

fix(DASH): Prioritize highest bandwidth in PeriodCombiner

---

lib/util/string_utils.js
test/util/string_utils_unit.js

fix(ttml): Handle escaped special characters.

---

externs/shaka/ads.js
lib/ads/ad_manager.js
lib/ads/ad_utils.js
lib/ads/interstitial_ad.js
lib/ads/interstitial_ad_manager.js
lib/ads/media_tailor_ad.js
lib/text/cue.js
lib/text/sbv_text_parser.js
lib/text/vtt_text_parser.js
lib/util/error.js
lib/util/tXml.js
lib/util/text_parser.js
test/test/util/fake_ad_manager.js

This only includes playback, no tracking is sent.

feat(Ads): Add basic VAST support without IMA

---

lib/media/adaptation_set.js
test/media/adaptation_set_unit.js

Do not adapt between spatial & non spatial audio to avoid annoying users.

fix(ABR): Do not adapt between spatial & non spatial audio

---

demo/config.js
externs/shaka/net.js

Related to https://github.com/shaka-project/shaka-player/issues/7069

docs: Update maxAttempts documentation

---

lib/util/stream_utils.js
test/media/drm_engine_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7057

fix: Only check encryptionScheme when is not null and not empty string

---

externs/shaka/ads.js
lib/ads/client_side_ad.js
lib/ads/interstitial_ad.js
lib/ads/media_tailor_ad.js
lib/ads/server_side_ad.js
test/test/util/fake_ad.js
ui/skip_ad_button.js

SKIP UI in IMA CS can not be disabled, see: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/faq#13

fix(Ads): Don't show duplicate SKIP UI in IMA CS

---

lib/media/streaming_engine.js

Related to https://github.com/shaka-project/shaka-player/issues/7097

fix: Fix ID3 timing when included in EMSG

---

lib/text/vtt_text_parser.js
test/text/vtt_text_parser_unit.js

Fixes: https://github.com/shaka-project/shaka-player/issues/6448
Revert https://github.com/shaka-project/shaka-player/commit/9ab54d1485564065e02136b538b080186a0161e9

fix(WebVTT): Re-add rollover logic

---

externs/shaka/player.js
lib/player.js

feat: Add width/height to getFetchedPlaybackInfo

---

lib/media/media_source_engine.js

fix: Compare normalized codecs in codec switching checks

---

AUTHORS
CONTRIBUTORS
lib/media/video_wrapper.js

Fixes https://github.com/shaka-project/shaka-player/issues/7146
https://sample-videos-zyrkp2nj.s3.eu-west-1.amazonaws.com/20240809_shaka_start_issue/index.html
https://github.com/user-attachments/assets/881cd16f-9717-42bc-8afc-791b722fb5a6

fix: Repeated initial segment load & cancellations

---

AUTHORS
CONTRIBUTORS
lib/abr/simple_abr_manager.js

Resolves https://github.com/shaka-project/shaka-player/issues/7151

fix(ABR): Fix restrictToElementSize running while abr disabled

---

externs/shaka/manifest_parser.js
externs/shaka/net.js
lib/dash/dash_parser.js
lib/hls/hls_parser.js
lib/media/drm_engine.js
lib/media/preload_manager.js
lib/media/streaming_engine.js
lib/mss/mss_parser.js
lib/player.js
test/dash/dash_parser_live_unit.js
test/media/drm_engine_unit.js
test/test/util/fake_networking_engine.js

feat(preload): Add isPreload to net filter context

---

demo/common/asset.js
demo/main.js

Closes https://github.com/shaka-project/shaka-player/issues/7113

chore(Demo): Save all asset info in the URL

---

lib/media/media_source_engine.js

Related to https://github.com/shaka-project/shaka-player/issues/7139

chore: Detect segmentDuration mismatch

---

lib/player.js
test/player_src_equals_integration.js

Fixes https://github.com/shaka-project/shaka-player/issues/7135

fix: Apply playRange config to src=

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/7127

fix: Fire the correct error code in src= mode in some situations

---

lib/player.js

Closes https://github.com/shaka-project/shaka-player/issues/6918

fix: Fix ended state in stateHistory

---

ui/resolution_selection.js

Fixes https://github.com/shaka-project/shaka-player/issues/7187

fix(UI): Only show frame rate if there are several frame rates

---

demo/common/assets.js

Closes https://github.com/shaka-project/shaka-player/issues/2035

chore(Demo): Add more demo assets

---

test/media/streaming_engine_unit.js
test/test/util/simple_fakes.js
test/test/util/streaming_engine_util.js

Related to https://github.com/shaka-project/shaka-player/pull/7184

test: Fix FakeSegmentIndex implementation

---

lib/player.js
lib/util/fake_event.js

It allows to inform clients media source recovery happened.

feat: Dispatch MediaSourceRecovered event

---

lib/media/streaming_engine.js

Resolves https://github.com/shaka-project/shaka-player/issues/7174.

fix: Add null check for current reference

---

lib/media/streaming_engine.js

Related to https://github.com/shaka-project/shaka-player/issues/7206

fix: Dont use inaccurateManifestTolerance for sequenceMode

---

lib/hls/hls_parser.js
test/hls/hls_live_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7206

fix(HLS): Calculate the delay based on the sum of the segment lengths

---

lib/cea/mp4_cea_parser.js
lib/media/content_workarounds.js
lib/media/segment_utils.js
lib/media/streaming_engine.js
lib/util/mime_utils.js
lib/util/stream_utils.js
test/util/mime_utils_unit.js

Info from https://dolby.my.salesforce.com/sfc/p/#700000009YuG/a/4u000000l6G4/4R18riPaaW3gxpVx7XwyQLdEITLFjB.w.Si0LoQR5j8

fix: Fix support for Dolby Vision based in VVC

---

lib/player.js

Related to https://github.com/shaka-project/shaka-player/issues/7222

fix(Stats): Fix bytesDownloaded when using src=

---

lib/dash/dash_parser.js
lib/util/tXml.js
test/dash/dash_parser_patch_unit.js
test/util/tXml_unit.js

fix(DASH): Fix MPD Patch when SegmentTemplate is shared between Representations

---

lib/text/ttml_text_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/7269

fix(TTML): Fix subtitles not rendered due to complaint about xml:id

---

externs/shaka/text.js
lib/player.js
lib/text/simple_text_displayer.js
lib/text/stub_text_displayer.js
lib/text/ui_text_displayer.js
test/test/util/fake_text_displayer.js
ui/controls.js

Close https://github.com/shaka-project/shaka-player/issues/1860

feat(UI): Use the lang= attribute to help screen-readers recognize localized labels

---

lib/text/ttml_text_parser.js
test/text/ttml_text_parser_unit.js

fix(TTML): Fix absence of conversion of alpha (transparency) from 0-255 -> 0-1

---

lib/dash/dash_parser.js

fix(DASH): Clone EventStream nodes to reduce memory consumption

---

lib/dash/segment_template.js
lib/media/presentation_timeline.js
test/dash/dash_parser_manifest_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7192

fix(DASH): Allow mixing SegmentTemplate-SegmentTimeline with SegmentTemplate-numbering

---

lib/media/segment_index.js
lib/media/streaming_engine.js

Issue https://github.com/shaka-project/shaka-player/issues/6239

fix(DASH): Evict (by time) indexes in MetaSegmentIndex

---

lib/offline/indexeddb/storage_mechanism.js

Related to https://github.com/shaka-project/shaka-player/issues/7253

feat(Cast): Enable storage in Android Cast devices

---

lib/dash/dash_parser.js
lib/util/periods.js
test/util/periods_unit.js

Issue: https://github.com/shaka-project/shaka-player/issues/6239

perf(DASH): Delete old matchedStreams

---

lib/dash/mpd_utils.js
lib/text/ttml_text_parser.js
lib/util/tXml.js

Issue https://github.com/shaka-project/shaka-player/issues/6239

perf: Only use tXml parent when necessary

---

lib/dash/dash_parser.js
lib/util/periods.js
test/util/periods_unit.js

Issue https://github.com/shaka-project/shaka-player/issues/6239

fix(DASH): Clear usedPeriodIds when period is removed from the manifest

---

lib/util/periods.js

fix(DASH): Clone closedCaptions map in PeriodCombiner output stream

---

ui/controls.js

Fixes https://github.com/shaka-project/shaka-player/issues/7311
Original author: @absidue

fix(UI): Remove spinner and client side ad container elements when calling destroy

---

demo/common/asset.js
demo/common/assets.js
demo/main.js
externs/shaka/player.js
lib/offline/storage.js

Close https://github.com/shaka-project/shaka-player/issues/2016

feat(Offline): Allow store external text

---

lib/dash/dash_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/7323

fix(DASH): Fix HTTP redirect during manifest update

---

lib/media/presentation_timeline.js
test/player_integration.js
test/test/assets/3675/dash_0.mpd
test/test/assets/3675/dash_1.mpd
test/test/assets/3675/dash_2.mpd
test/test/assets/3675/dash_3.mpd
test/test/assets/3675/dash_4.mpd

Fixes https://github.com/shaka-project/shaka-player/issues/7346

fix(dash): live to vod transition seek start

---

lib/hls/hls_parser.js

Related to https://github.com/shaka-project/shaka-player/pull/7343

fix(HLS): Avoid disabling muxed audio streams

---

lib/ads/interstitial_ad_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/7372

fix(Ads): Release interstitials timer correctly

---

test/media/streaming_engine_unit.js
test/test/externs/jasmine.js

test: Add test case for exclude TIMEOUT errors when disabling streams

---

lib/media/media_source_engine.js

Always raise prft events so consumers can have access to the wall clock time.

fix: Fire PRFT event every time

---

lib/player.js

fix: Export getFetchedPlaybackInfo

---

docs/tutorials/ui-customization.md
ui/mute_button.js

Close https://github.com/shaka-project/shaka-player/issues/7407

feat(UI): Added Mute button to context menu and overflow menu

---

lib/media/drm_engine.js
test/media/drm_engine_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7429

fix(DRM): Fix persistent licenses not working for online playback

---

lib/media/adaptation_set_criteria.js

Fixes https://github.com/shaka-project/shaka-player/issues/7468

fix: Fix select HLG tracks when using AUTO hdr level

---

docs/tutorials/ui.md

This fixes minor formatting and adds a section with links to a real example of Shaka UI usage with some unique features.

docs: Add a section to the UI tutorial

---

ui/controls.js
ui/less/containers.less

Fixes https://github.com/shaka-project/shaka-player/issues/7394

fix(UI): Hidden cursor correctly

---

lib/media/content_workarounds.js
lib/util/platform.js

Fix Windows detection on platforms which do not implement `userAgentData` & disable explicitly one workaround on Xbox (as Xbox is also Windows).

fix: Fix Windows detection

---

lib/mss/mss_parser.js
test/mss/mss_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7483

fix(MSS): Fix timeline repetitions

---

demo/asset_card.js
demo/common/assets.js
demo/demo.less
demo/icons/custom_fairplay.svg
demo/main.js
lib/media/media_source_engine.js
test/player_external.js

Related to https://github.com/shaka-project/shaka-player/pull/7454
Thanks to @gmcgarry

feat(Demo): Add new asset with DASH-FairPlay

---

lib/player.js

Related to https://github.com/shaka-project/shaka-player/issues/5022

chore: Simplify listener management to be able to use the same basic listeners in MSE and src=

---

lib/player.js

Related to https://github.com/shaka-project/shaka-player/issues/5022

fix: Don't use info from MSE mode when using Remote Playback

---

lib/media/media_source_engine.js

Related to https://github.com/shaka-project/shaka-player/issues/5022

fix: Do not allow MSE operations when using Remote Playback

---

demo/config.js
externs/shaka/player.js
lib/hls/hls_parser.js
lib/util/player_configuration.js

Create the update period for hls parse
still need to check it
Close https://github.com/shaka-project/shaka-player/issues/7505

feat(HLS): Add the update period for HLS manifest

---

lib/player.js

This only happens when using src= mode

fix(AirPlay): Don't show subtitles on the player when using AirPlay

---

demo/config.js
demo/main.js
externs/shaka/player.js
lib/media/manifest_filterer.js
lib/offline/storage.js
lib/util/player_configuration.js
lib/util/stream_utils.js
test/demo/demo_unit.js
test/util/stream_utils_unit.js

Close https://github.com/shaka-project/shaka-player/issues/4650

feat: Add preferredTextFormats config

---

lib/ads/interstitial_ad_manager.js

Use requestVideoFrameCallback the achieve better performance

perf(Ads): Reduce latency for interstitial to start playing

---

docs/tutorials/faq.md

Close https://github.com/shaka-project/shaka-player/issues/7551

chore(docs): Update FAQ to mention a HLS out of sync on some cases

---

lib/text/cue.js

Fixes https://github.com/shaka-project/shaka-player/issues/7553

fix(WebVTT): Fix display italic subtitles with end align

---

lib/text/ui_text_displayer.js

Fixes https://github.com/shaka-project/shaka-player/issues/7576

fix: Allow the user to disable subtitles while paused

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/7577

fix: Disable live sync when the stream is paused

---

.github/workflows/build-and-test.yaml

Closes https://github.com/shaka-project/shaka-player/issues/6508

ci: Switch to use macos-latest

---

externs/shaka/manifest_parser.js
lib/dash/dash_parser.js
lib/media/streaming_engine.js
lib/offline/storage.js
lib/player.js
lib/util/periods.js
test/dash/dash_parser_content_protection_unit.js
test/dash/dash_parser_live_unit.js
test/dash/dash_parser_manifest_unit.js
test/dash/dash_parser_patch_unit.js
test/dash/dash_parser_segment_base_unit.js
test/dash/dash_parser_segment_list_unit.js
test/dash/dash_parser_segment_template_unit.js
test/hls/hls_live_unit.js
test/hls/hls_parser_unit.js
test/media/streaming_engine_integration.js
test/media/streaming_engine_unit.js
test/mss/mss_parser_unit.js
test/test/util/dash_parser_util.js
test/test/util/mss_parser_util.js
test/util/content_steering_manager_unit.js
test/util/periods_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7516 in a simpler way
Reverts https://github.com/shaka-project/shaka-player/commit/5eff0384d04e22a971336c90aae0a83db2a451d5
Reverts https://github.com/shaka-project/shaka-player/commit/037193c2d601e02c8611a4527dcb04d32adbbd27

fix(DASH): Fix playback after DASH period eviction

---

lib/net/networking_engine.js
lib/player.js
lib/util/fake_event.js
test/util/cmcd_manager_unit.js

feat: Add 'downloadcompleted' event

---

lib/media/preload_manager.js

fix: Silence aborted errors from PreloadManager.

---

AUTHORS
CONTRIBUTORS
lib/media/media_source_engine.js

Caches source buffer parameters on codec switch with the RELOAD configuration
Fixes https://github.com/shaka-project/shaka-player/issues/7555

fix: cache source buffer params on codec switch reload

---

lib/polyfill/media_capabilities.js
test/polyfill/media_capabilities_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/5776

fix(Cast): Incorrect detection of MediaCapabilities on Linux Chromecast

---

lib/media/media_source_engine.js

Test stream: https://playertest.longtailvideo.com/adaptive/elephants_dream_v4/index.m3u8

fix(HLS): Fix playback of raw AAC

---

package-lock.json
package.json

Fixes https://github.com/shaka-project/shaka-player/issues/7477

fix: Fix CBCS support in recent WebOS

---

lib/net/networking_engine.js
lib/player.js
test/test/util/fake_networking_engine.js

Close https://github.com/shaka-project/shaka-player/issues/7649

feat: Add basic support for the Common Access Token

---

lib/ads/interstitial_ad_manager.js

See: https://mailarchive.ietf.org/arch/msg/hls-interest/TfPMm5VcabtNnauJUf7qIVcFXrE/

fix(Ads): Fix usage of ENABLE-SKIP-FOR in Interstitals

---

.csslintrc
demo/demo.less
ui/less/ad_controls.less
ui/less/buttons.less
ui/less/containers.less
ui/less/overflow_menu.less
ui/less/thumbnails.less
ui/less/tooltip.less

Related to https://github.com/shaka-project/shaka-player/issues/7419
See: Space-separated rgb() parameters --> https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb#browser_compatibility

fix(UI): Change to use legacy css format to support old TVs

---

lib/ads/interstitial_ad_manager.js

Regression of https://github.com/shaka-project/shaka-player/commit/70257ffefe609dfa0bb8888f91c2ce1d52c78f9f

fix(Ads): Fix ad position by default

---

lib/ads/interstitial_ad_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/7661

fix(Ads): Fix id of X-ASSET-LIST

---

lib/media/media_source_engine.js

fix: Fix playback on Apple devices without ManagedMediaSource

---

lib/ads/ad_manager.js
lib/ads/interstitial_ad_manager.js
test/ads/interstitial_ad_manager_unit.js

The spec is not finalized, but the info can be found at https://demuxed2024.qualabs.com/home/alex-giladi

feat(Ads): Add basic support to DASH OverlayEvent

---

demo/config.js
externs/shaka/player.js
lib/dash/dash_parser.js
lib/hls/hls_parser.js
lib/util/player_configuration.js
test/dash/dash_parser_manifest_unit.js
test/hls/hls_parser_unit.js

Based on the work of @gmcgarry Thank you very much!

feat: Add configuration to ignore SCTE214 supplemental codecs

---

lib/dash/dash_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/7722

fix(DASH): Error due to deleted stream

---

ui/controls.js

Fixes https://github.com/shaka-project/shaka-player/issues/7724

fix(UI): Fix playback rate resets when pausing or playing the video

---

lib/media/drm_engine.js
lib/media/manifest_filterer.js
lib/offline/storage.js
lib/util/stream_utils.js

Related to https://github.com/shaka-project/shaka-player/issues/7613

fix: Fix usage of keySystemsMapping

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

chore: update feature request and bug report templates

---

lib/player.js
ui/fast_forward_button.js
ui/rewind_button.js

Fixes https://github.com/shaka-project/shaka-player/issues/7756

fix(UI): Video starts playing automatically when selecting a playback rate

---

ui/playback_rate_selection.js

Fixes https://github.com/shaka-project/shaka-player/issues/7757

fix(UI): Allow 1x playback rate when default playback rate is not x1

---

externs/shaka/ads.js
lib/ads/ad_manager.js
lib/ads/interstitial_ad_manager.js
test/test/util/fake_ad_manager.js

Close https://github.com/shaka-project/shaka-player/issues/7763

feat(Ads): Expose the interstitial player

---

lib/player.js
lib/text/simple_text_displayer.js
lib/text/ui_text_displayer.js
test/test/util/layout_tests.js
test/text/ui_text_displayer_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7803

fix: Remove useless deprecation in UITextDisplayer and add some guards in SimpleTextDisplayer

---

lib/hls/hls_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/7774

fix(HLS): Do not use EXT-X-PROGRAM-DATE-TIME on vod when there is only video or audio

---

docs/tutorials/ad_monetization.md
externs/shaka/ads.js
lib/ads/ad_utils.js
lib/ads/interstitial_ad_manager.js
test/ads/interstitial_ad_manager_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7782

fix(Ads): Apply X-PLAYOUT-LIMIT to entire interstitial

---

demo/common/assets.js
demo/main.js

Source of audio only assets: https://testweb.playready.microsoft.com/Content/ContentAudioOnly
Source of AV1 assets: https://testweb.playready.microsoft.com/Content/ContentAV1
Source of Tear of Steel assets: https://testweb.playready.microsoft.com/Content/Content2X
Source of DASH-PR asset: https://testweb.playready.microsoft.com/Content/Content4X

chore(Demo): Add more assets from Microsoft

---

lib/transmuxer/aac_transmuxer.js
lib/transmuxer/ac3_transmuxer.js
lib/transmuxer/ec3_transmuxer.js
lib/transmuxer/mp3_transmuxer.js
lib/transmuxer/ts_transmuxer.js
test/transmuxer/transmuxer_integration.js

Fixes https://github.com/shaka-project/shaka-player/issues/7462
Fixes https://github.com/shaka-project/shaka-player/issues/7780

fix: Fix gaps produced by the transmuxer

---

externs/shaka/manifest.js
lib/hls/hls_parser.js
lib/offline/download_info.js
lib/offline/storage.js
test/offline/storage_playback_integration.js

Also adds integration tests for DASH AES-128, HLS AES-256 and HLS SAMPLE-AES download and playback

fix(Offline): Allow downloading AES content

---

lib/hls/manifest_text_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/7861

fix(HLS): Assign EXT-X-TILES to segment tags

---

lib/util/player_configuration.js

Related to https://github.com/shaka-project/shaka-player/pull/7470

fix(Offline): Fix download HLG tracks when using AUTO hdr level

---

lib/hls/hls_parser.js
lib/media/preload_manager.js
lib/player.js
test/hls/hls_parser_unit.js

Related to https://github.com/shaka-project/shaka-player/pull/6383

feat: Create segmentIndex when there is only one variant

---

ui/controls.js

Fixes https://github.com/shaka-project/shaka-player/issues/7875

fix(UI): Fix handle of seek on MediaSession

---

lib/abr/simple_abr_manager.js

Close https://github.com/shaka-project/shaka-player/issues/7872

feat(ABR): Use PiP window size when using documentPictureInPicture

---

externs/pictureinpicture.js
lib/abr/simple_abr_manager.js

Close https://github.com/shaka-project/shaka-player/issues/7872

feat(ABR): Use PiP window size when using requestPictureInPicture

---

lib/drm/drm_engine.js
lib/drm/drm_utils.js
test/drm/drm_utils_unit.js

Fixes to https://github.com/shaka-project/shaka-player/issues/7449

perf: Improve times of probeSupport

---

.github/workflows/demo-version-index.yaml
.github/workflows/release-please.yaml

ci: Fix secrets for version index workflow

---

demo/config.js
externs/shaka/player.js
lib/media/media_source_capabilities.js
lib/media/media_source_engine.js
lib/media/streaming_engine.js
lib/util/player_configuration.js
test/test/util/fake_media_source_engine.js

Close https://github.com/shaka-project/shaka-player/issues/3153
Fixes https://github.com/shaka-project/shaka-player/issues/7903

feat: Use MSE clearLiveSeekableRange and setLiveSeekableRange when available

---

externs/shaka/text.js
lib/player.js
lib/text/simple_text_displayer.js
lib/text/stub_text_displayer.js
lib/text/ui_text_displayer.js
test/test/util/fake_text_displayer.js
test/text/simple_text_displayer_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7912

fix: Only create TextTrack of SimpleTextDisplayer when necessary

---

lib/ads/interstitial_ad.js
lib/ads/interstitial_ad_manager.js
lib/ads/interstitial_static_ad.js

Close https://github.com/shaka-project/shaka-player/issues/7920

feat(Ads): Populate getAdId and getMediaUrl for interstitials

---

lib/hls/hls_parser.js

chore: Stop using "Object" in HLS parser annotations

---

lib/util/multi_map.js

chore: Stop using "Object" in MultiMap annotations

---

demo/config.js
demo/input.js
demo/main.js
demo/search.js

chore: Stop using "Object" in Demo annotations

---

lib/media/closed_caption_parser.js
lib/media/manifest_parser.js
lib/net/networking_engine.js
lib/text/text_engine.js
lib/transmuxer/transmuxer_engine.js

chore: Stop using "Object" in plugins annotations

---

lib/net/networking_utils.js

chore: Stop using "Object" in networking annotations

---

ui/ad_statistics_button.js
ui/statistics_button.js

chore: Stop using "Object" in UI annotations

---

lib/polyfill/media_capabilities.js
lib/util/stream_utils.js

chore: Stop using "Object" in cache annotations

---

test/offline/storage_integration.js

chore: Stop using "Object" in Storage integration annotations

---

lib/player.js

chore: Stop using "Object" in Player annotations

---

lib/dash/dash_parser.js
lib/dash/mpd_utils.js
lib/dash/segment_list.js
lib/dash/segment_template.js

chore: Stop using "Object" in DASH

---

lib/text/ttml_text_parser.js

chore: Stop using "Object" in TTML annotations

---

demo/main.js

Regression introduced in https://github.com/shaka-project/shaka-player/commit/8276b59cd9ced8482e08b8b480a0f1bf13f66f6d

chore: Fix Demo reload

---

lib/hls/hls_parser.js

Related to https://github.com/shaka-project/shaka-player/issues/7915

fix(HLS): Fix redirect management at media playlist level

---

lib/net/http_plugin_utils.js

Fixes https://github.com/shaka-project/shaka-player/issues/7925

fix(net): Add 304 as successful request

---

demo/config.js
externs/shaka/player.js
lib/hls/hls_parser.js
lib/util/player_configuration.js

Close https://github.com/shaka-project/shaka-player/issues/7973

feat(HLS): Add allowRangeRequestsToGuessMimeType config

---

lib/media/content_workarounds.js
test/media/content_workarounds_unit.js

test: Add unit test for ContentWorkarounds.fakeEC3

---

demo/config.js
externs/shaka/player.js
lib/dash/dash_parser.js
lib/hls/hls_parser.js
lib/player.js
lib/util/player_configuration.js
test/dash/dash_parser_content_protection_unit.js
test/hls/hls_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/7985.

feat(HLS): Add an option to ignore DRM info

---

lib/media/media_source_engine.js
lib/media/streaming_engine.js
lib/util/error.js

Maybe related to https://github.com/shaka-project/shaka-player/issues/7960

feat: Add new error code when the streaming is not allowed

---

lib/media/media_source_engine.js

chore: Stop using "Object" in MediaSourceEngine annotations

---

CONTRIBUTORS
lib/player.js
test/player_unit.js

fix(CMCD): Only report ltc if playing; round to int

---

lib/media/region_timeline.js

Fixes https://github.com/shaka-project/shaka-player/issues/8009

fix: Duplicate timelineregion* events fired for the same event id

---

lib/media/gap_jumping_controller.js
lib/media/playhead.js
lib/media/stall_detector.js

Related to https://github.com/shaka-project/shaka-player/issues/3673

chore: Simplify StallDetector creation to a single place

---

demo/config.js
externs/shaka/player.js
lib/media/streaming_engine.js
lib/util/player_configuration.js

Related to https://github.com/shaka-project/shaka-player/issues/7349

feat: Add avoidEvictionOnQuotaExceededError config

---

.github/workflows/build-and-test.yaml
README.md
build/all.py
build/types/complete
build/types/optionalText
build/types/text

Related to https://github.com/shaka-project/shaka-player/issues/8034
Compared to the current version without UI:
DASH -24,5% of size
HLS -19,5% of size

build: Add new builds with only HLS or DASH

---

README.md
docs/tutorials/architecture.md
docs/tutorials/lcevc.md

Regression introduced in #7891

docs: Fix design links

---

lib/net/networking_engine.js
test/net/networking_engine_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/8041

fix(net): Allow preventDefault() on retry event

---

docs/tutorials/errors.md

Related to https://github.com/shaka-project/shaka-player/commit/a30f1da2a2edaa7093676c7d525d6a09f9e75372

docs: Update retry documentation

---

ui/controls.js

Fixes https://github.com/shaka-project/shaka-player/issues/8098

fix(UI): Improve performance and compatibility with MediaSession

---

lib/util/platform.js
test/polyfill/media_capabilities_unit.js

More info: https://wicg.github.io/ua-client-hints/#sec-ch-ua-platform

perf: Use navigator.userAgentData.platform to detect Android and Fuchsia

---

ui/ui.js

This is a performance improvement because each call to configure recreates the UI DOM.

perf(UI): Reduce configure calls to use shakaPlayerCastReceiverId

---

lib/dash/dash_parser.js

Fixes: https://github.com/shaka-project/shaka-player/issues/8123

fix(DASH): ContentSteering promise is resolved too late for fetching of init segment

---

lib/media/gap_jumping_controller.js
lib/media/stall_detector.js
test/media/stall_detector_unit.js

Related to https://github.com/shaka-project/shaka-player/issues/3673

chore: Simplify StallDetector

---

lib/media/media_source_engine.js

This simplifies the integration of LCEVC Dual Track.

chore: Create a new method appendDependency in MediaSourceEngine

---

ui/controls.js

Fixes https://github.com/shaka-project/shaka-player/issues/8164

fix(UI): Use touchend to show the controls

---

lib/media/gap_jumping_controller.js

Fixes https://github.com/shaka-project/shaka-player/issues/8175

fix: Fix seek to initial live position on slow devices

---

ui/mute_button.js
ui/volume_bar.js

Fixes https://github.com/shaka-project/shaka-player/issues/8184

fix(UI): Fix weird behaviour when volume was 0, and we unmute

---

lib/polyfill/patchedmediakeys_apple.js

Related to https://github.com/shaka-project/shaka-player/issues/8190

fix: Clear some caches when install/uninstall PatchedMediaKeysApple

---

AUTHORS
CONTRIBUTORS
docs/tutorials/fairplay.md
lib/util/fairplay_utils.js

This adds support for FairPlay DRM license requests for Mux.io
Close https://github.com/shaka-project/shaka-player/issues/8202

feat(FairPlay): Add support for Mux

---

lib/media/region_timeline.js

- Only run filter timer if we have any region cached
- use map for faster lookup

perf: Region timeline improvements

---

ui/controls.js
ui/hidden_seek_button.js
ui/play_button.js

Fixes https://github.com/shaka-project/shaka-player/issues/8199

fix(UI): Allow play/pause when seekOnTaps is enabled

---

lib/media/media_source_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/8200

fix(HLS): Only apply compensation if the difference is greater than 150ms

---

lib/media/preload_manager.js

Fixes https://github.com/shaka-project/shaka-player/issues/8214

fix: When standard load, do not wait for pending license requests to finish.

---

ui/playback_rate_selection.js

Fixes https://github.com/shaka-project/shaka-player/issues/8227

fix(UI): Don't sort playback rates

---

ui/vr_manager.js
ui/vr_webgl.js

The requestVideoFrameCallback API is used if available.

perf(UI): Improve VR performance

---

ui/controls.js

Related to https://github.com/shaka-project/shaka-player/issues/8224#issuecomment-2707172649

fix(UI): Allow use hideUI on mobile devices

---

ui/context_menu.js
ui/controls.js

Related to https://github.com/shaka-project/shaka-player/issues/8224

fix(UI): Close context menu when hide the UI

---

lib/hls/hls_parser.js
lib/media/media_source_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/8232
This is addressing a wrong download of the reference due to rounding issue in HLS Parser.

fix(hls): Removing Possible encoding problem detected

---

package-lock.json
package.json

To fix this, update to a newer version of karma-local-wd-launcher which fixes it.

ci: Fix Firefox macOS hang

---

ui/less/thumbnails.less
ui/seek_bar.js

Fixes https://github.com/shaka-project/shaka-player/issues/8272

fix(UI): Optimize portrait thumbnail display

---

demo/common/asset.js
demo/custom.js
demo/main.js

Allow preload adTagUri to improve the behavior with pre-roll 
Include the AD feature when using a custom asset

chore(Demo): Improve ad behavior

---

lib/cast/cast_proxy.js

Fixes https://github.com/shaka-project/shaka-player/issues/8293

fix: Fix destroy CastProxy on browser without Cast support

---

externs/audiotrack.js
externs/videotrack.js
lib/player.js
lib/util/stream_utils.js

More info https://github.com/WebKit/explainers/tree/main/TrackConfiguration

feat: Add more info on src= tracks when the browser support it

---

ui/controls.js

Fixes https://github.com/shaka-project/shaka-player/issues/8301

fix(UI): Avoid hide controls when seeking

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/8280
It also simplifies buffering management.

fix: Fix buffering event on native playback

---

ui/seek_bar.js

Fixes https://github.com/shaka-project/shaka-player/issues/8317

fix(UI): Fix thumbnail exception when the thumbnails doesn't exist

---

ui/less/thumbnails.less
ui/seek_bar.js

Fixes https://github.com/shaka-project/shaka-player/issues/8321

fix(UI): Don't cover useless space with the position in the thumbnail image

---

lib/util/platform.js

fix(HLS): Fix HLS live playback on older Webkit STBs

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/8320

fix(HLS): Handle redirect URLs correctly

---

lib/hls/hls_parser.js
lib/media/streaming_engine.js

Related to https://github.com/shaka-project/shaka-player/issues/8335

fix: Add support to crossBoundaryStrategy when using HLS

---

demo/config.js
lib/config/cross_boundary_strategy.js
lib/media/streaming_engine.js
lib/util/player_configuration.js

Related to https://github.com/shaka-project/shaka-player/issues/8335

fix: Add new crossBoundaryStrategy for Apple browsers

---

lib/hls/hls_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/8332

fix(HLS): Fix queryData to prevent url params percent encoding

---

lib/hls/hls_utils.js
test/hls/hls_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/8349

fix(HLS): Fix variable substitution when using relative paths

---

build/types/core
build/types/transmuxer
lib/media/content_workarounds.js
lib/media/media_source_engine.js
lib/mss/mss_parser.js
lib/transmuxer/aac_transmuxer.js
lib/transmuxer/ac3_transmuxer.js
lib/transmuxer/ec3_transmuxer.js
lib/transmuxer/mp3_transmuxer.js
lib/transmuxer/ts_transmuxer.js
lib/util/mp4_generator.js
test/media/content_workarounds_unit.js
test/media/media_source_engine_unit.js

Also added cbcs handling in SCHM box

chore: Re-use Mp4Generator in ContentWorkarounds

---

lib/util/platform.js

Fixes https://github.com/shaka-project/shaka-player/issues/8356

fix: Improve maxResolution detection on Tizen

---

demo/common/assets.js
test/mss/mss_player_external.js
test/mss/mss_player_integration.js

Change MSS URL to the new one.

test: Change MSS URL for tests

---

docs/tutorials/offline.md
lib/offline/indexeddb/storage_mechanism.js

Close https://github.com/shaka-project/shaka-player/issues/8355

feat(Offline): Make timeout for opening IndexedDB configurable

---

lib/media/preference_based_criteria.js

Some platforms may not support window.matchMedia API.

fix: Handle missing window.matchMedia API

---

lib/player.js

In some platforms prototype based check fails.

fix: Check addTextTrack in video

---

ui/less/thumbnails.less

fix(UI): Improve layout of current time container above hovered seek bar

---

ui/ad_info.js

Related to https://github.com/shaka-project/shaka-player/issues/8406#issuecomment-2786583244

fix(UI): Fix a11y issue with shaka.ui.AdInfo

---

ui/less/overflow_menu.less

Related to https://github.com/shaka-project/shaka-player/issues/8406#issuecomment-2786583244

feat(UI): Customize scrollbar style

---

ui/controls.js

Fixes https://github.com/shaka-project/shaka-player/issues/5930

fix(UI): Don't hide the UI when using the wheel over the UI

---

ui/less/range_elements.less

Close https://github.com/shaka-project/shaka-player/issues/8422

feat(UI): Hide volume slider when not hovering over the mute button

---

ui/less/range_elements.less

Related to https://github.com/shaka-project/shaka-player/pull/8426

fix(UI): Only show the volume bar on hover

---

ui/less/ad_controls.less
ui/less/range_elements.less

Related to https://github.com/shaka-project/shaka-player/issues/8422#issuecomment-2789964942

feat(UI): Optimize default UI for small screens

---

ui/less/overflow_menu.less
ui/playback_rate_selection.js
ui/resolution_selection.js

Close https://github.com/shaka-project/shaka-player/issues/7444

feat(UI): Show current playback rate and quality without hover

---

demo/common/assets.js

Using und allows it to be viewed in any language.

chore(Demo): Set chapter demo asset language to und

---

lib/media/streaming_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/8492

fix(HLS): Fix text tracks disappear after seek

---

ui/resolution_selection.js

Close https://github.com/shaka-project/shaka-player/issues/8501

feat(UI): Resolution selector should display width for vertical videos

---

lib/ads/interstitial_ad_manager.js
test/ads/interstitial_ad_manager_unit.js

This matches with the latest draft of SCTE 214-1

feat(Ads): Update DASH overlay implementation

---

lib/media/streaming_engine.js

This update introduces buffering logic to the LCEVC dual track implementation, allowing the system to prefetch dependency segments when current buffered segments are behind the buffering goal. This helps improve playback stability and ensures smoother streaming performance.

feat(LCEVC): Add buffering support to dual track implementation

---

lib/drm/drm_engine.js
lib/util/player_configuration.js
test/cast/cast_receiver_integration.js

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1806566 and https://bugzilla.mozilla.org/show_bug.cgi?id=1960673
This also adds mapping for other browsers on Windows, since Chromium is working on the same functionality (https://issues.chromium.org/issues/378869813).

fix: Fix Firefox PlayReady support

---

lib/cast/cast_proxy.js
lib/cast/cast_utils.js
test/cast/cast_utils_unit.js

Reverts shaka-project/shaka-player#8513
I haven't figured out yet what my mistake was, but this change introduced many regressions in the Cast API.

fix(cast): Revert proxy changes

---

test/ui/ui_integration.js
third_party/language-mapping-list/language-mapping-list.js
ui/language_utils.js

This PR helps reducing bundle size. All changes were part of https://github.com/shaka-project/shaka-player/pull/8520

feat: Shrink the size of language-mapping-list.js

---

lib/media/media_source_engine.js

Related to https://github.com/shaka-project/shaka-player/issues/8491

fix: Make sure we are calling setLiveSeekableRange and clearLiveSeekableRange at the correct time

---

lib/media/streaming_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/8491

fix: Fix race condition stoping timers

---

lib/polyfill/media_capabilities.js

Fixes: https://github.com/shaka-project/shaka-player/issues/8537

fix: Fix MediaCapabilities polyfill on Vizio

---

package-lock.json
package.json

Fixes https://github.com/shaka-project/shaka-player/issues/8538

fix: Update eme-encryption-scheme-polyfill

---

project-words.txt
ui/controls.js
ui/range_element.js

Fixes https://github.com/shaka-project/shaka-player/issues/8539

fix(UI): Fix seekbar allows seeking even when hidden

---

ui/seek_bar.js

Fixes https://github.com/shaka-project/shaka-player/issues/8557

fix(UI): Fix erroneous current time when dragging

---

demo/common/assets.js

Close https://github.com/shaka-project/shaka-player/issues/8563

chore(Demo): Fix FairPlay Axinom assets

---

lib/offline/storage.js

docs: Clarify storage.removeEmeSessions

---

ui/seek_bar.js

fix(UI): Keep the current position gradient when seeked

---

package-lock.json
package.json

fix: Fixes eme-encryption-scheme-polyfill, null encryptionScheme is valid

---

lib/cast/cast_utils.js
lib/player.js

Close https://github.com/shaka-project/shaka-player/issues/8582

feat: Add useTrickPlayTrackIfAvailable method

---

lib/media/media_source_engine.js

Related to https://github.com/shaka-project/shaka-player/issues/8491

fix: Fix onUpdateEnd when the MSE engine has been destroyed

---

lib/drm/drm_utils.js

fix(DASH): Inconsistent DRM across periods when using clearkeys

---

lib/polyfill/media_capabilities.js

Fixes https://github.com/shaka-project/shaka-player/issues/8607
Fixes https://github.com/shaka-project/shaka-player/issues/8590

fix: Fix garbage-collection issue in safari on mediaCapabilities polyfill

---

lib/media/adaptation_set_criteria.js
lib/media/preference_based_criteria.js
lib/media/preload_manager.js
lib/player.js
test/media/adaptation_set_criteria_unit.js

Close https://github.com/shaka-project/shaka-player/issues/8587

feat: Add additional codec & channel count configs to Adaptation Set Criteria

---

lib/drm/drm_utils.js

Do not create new DRM Info objects just for compatibility checks.

perf: Optimize DRM compatibility check across streams

---

demo/main.js

The Close button is a special button with a different position than the rest of the control panel elements.
Fixes #8655

fix(Demo): Fix bad tooltip position of last control panel element

---

ui/controls.js
ui/seek_bar.js

Fixes https://github.com/shaka-project/shaka-player/issues/8689

fix(UI): Hide player labels when More Settings menu is open

---

lib/media/streaming_engine.js

Increase the fudge append window end to fix a playback bug.

fix: Fix chopped playback in some DASH multiperiod streams

---

demo/common/asset.js
demo/main.js

Fixes https://github.com/shaka-project/shaka-player/issues/8711

chore(Demo): Simplify certificate setup

---

lib/media/media_source_engine.js
lib/media/segment_utils.js
lib/util/manifest_parser_utils.js
project-words.txt

More info in https://developer.apple.com/av-foundation/Apple-Positional-Audio-Codec.pdf

fix(HLS): Fix APAC detection

---

lib/media/streaming_engine.js

See https://developer.apple.com/streaming/Whats-new-HLS.pdf

feat(HLS): Get info about projection from REQ-VIDEO-LAYOUT  instead of parsing the init segment

---

lib/media/streaming_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/8737

fix(HLS): Fix reset media source when using muxed content

---

lib/hls/hls_parser.js
lib/media/streaming_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/8737

fix(HLS): Fix switching between muxed and alternate audios

---

demo/main.js

Fixes https://github.com/shaka-project/shaka-player/issues/8746

chore(Demo): Fix demo extraconfig configuration

---

lib/cea/mp4_cea_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/8729

fix(CEA): INVALID_MP4_CEA error being thrown when shouldn't be

---

ui/externs/ui.js
ui/ui.js

Fixes https://github.com/shaka-project/shaka-player/issues/8314

fix(UI): Fix fullscreen doesn’t work on iPad (Edge/Chrome)

---

ui/ui.js

Regression of https://github.com/shaka-project/shaka-player/pull/8751

fix(UI): Fix default value of enableKeyboardPlaybackControlsInWindow

---

demo/main.js
lib/util/object_utils.js

The previous fix doesn't work with streaming.lowLatencyMode config.

fix(Demo): Fix keep custom config on page reload

---

lib/hls/hls_parser.js

Fixes https://github.com/shaka-project/shaka-player/issues/8780

fix(HLS): mediaSequenceToStartTime isn't maintained correctly for AUDIO manifest

---

lib/drm/drm_engine.js
lib/util/error.js
test/drm/drm_engine_unit.js

Related to https://github.com/shaka-project/shaka-player/issues/1772#issuecomment-2979980293

feat: Add shaka.extern.DrmSessionMetadata to LICENSE_REQUEST_FAILED error

---

demo/config.js
docs/tutorials/upgrade.md
externs/shaka/player.js
lib/dash/dash_parser.js
lib/hls/hls_parser.js
lib/player.js
lib/util/player_configuration.js

Close https://github.com/shaka-project/shaka-player/issues/8684

feat: Add enableAudioGroups config

---

ui/less/range_elements.less

Fixes https://github.com/shaka-project/shaka-player/issues/8798

fix(UI): Fix volume slider control is not accessible by keyboard

---

lib/dash/segment_template.js

fix(DASH): Always fit segments to period boundaries on VOD

---

package-lock.json
package.json

Update msedgedriver CDN URL, which recently changed

test: Fix msedgedriver install

---

lib/ads/interstitial_ad_manager.js

This change makes the detach operation after firing the AD_STARTED event

fix(Ads): Fix AD_STARTED delayed when using the base video

---

externs/shaka/player.js
lib/device/default_browser.js

Fixes https://github.com/shaka-project/shaka-player/issues/8801

fix: Fix default value of defaultAudioRobustnessForWidevine and defaultVideoRobustnessForWidevine on Android

---

lib/ads/interstitial_ad_manager.js

A VMAP is composed of a list of VASTs. Previously, processing was done sequentially; now, it is done in parallel, achieving significant performance improvements.

perf(Ads): Reduce VMAP processing time

---

lib/util/cmcd_manager.js

Add missing JSDoc
Rename setupMSDEventListeners_ to setupEventListeners_

chore(CMCD): Improvements to the CMCD manager code

---

lib/player.js

Fixes https://github.com/shaka-project/shaka-player/issues/8934

fix(DASH): Fix Playback Fails on Widevine L1/L3 Streams

---

.github/workflows/release-please.yaml

Missed in previous PRs and not discovered until release day.  :-(

ci: Fix Java setup for deployment to npm

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js

Fixes https://github.com/shaka-project/shaka-player/issues/8957

fix(HLS): Fix HLS audio only stream does not play when URI field is omitted from #EXT-X-MEDIA

---

package-lock.json
package.json

Changelog: https://github.com/v-novaltd/LCEVCdecJS/commit/50e4f35c7d82b1b1a9cca434ccca544622f38e11

chore: Update lcevc_dec.js to 1.3.0

---

externs/shaka/player.js
lib/player.js
test/player_unit.js

Related to https://github.com/shaka-project/shaka-player/issues/8943

feat: Allow update some prefer* config on the fly

---

lib/hls/hls_parser.js

Only for Widevine and WisePlay
Related to #9006

perf(HLS): Do not store duplicated pssh data buffers

---

demo/common/assets.js

Description:
Update LCEVC Dual-Track contents to be compatible with LCEVCdecJS 1.3.0

chore(LCEVC): Update LCEVC Dual-Track contents

---

externs/shaka/player.js

As discussed in the monthly meet, we need to make users aware of the fact that CMCD v2 is a draft, work in progress, spec.

chore: Comment about CMCD v2 draft spec note

---

build/compiler.py

Using the Closure Compiler with newer builds of Java results in a warning about "terminally deprecated methods".  These are used by the compiler itself, and outside of our control, so we pass --sun-misc-unsafe-memory-access=allow to Java to avoid the noisy warning.

build: Fix warning from newer Java

---

lib/hls/hls_parser.js
lib/media/segment_reference.js

Related to https://github.com/shaka-project/shaka-player/pull/9041

fix(HLS): Allow get better segment size estimations

---

ui/audio_language_selection.js
ui/text_selection.js

Submitting as a pull request instead of opening an issue for it, as I am hoping that this comment still applies: https://github.com/shaka-project/shaka-player/issues/8656#issuecomment-2916487256. If that doesn't apply anymore, feel free to take these changes, no need to credit me :).

perf(UI): Combine consecutive configure calls

---

lib/media/media_source_engine.js

Fixes https://github.com/shaka-project/shaka-player/issues/7761

fix: Fix some EMSG events missing

---

lib/player.js

docs: Update MediaQualityChangedEvent description

---

lib/hls/hls_parser.js
test/hls/hls_parser_unit.js

fix(HLS): Keep syncTime continuous by using previous value, if available

---

lib/util/error.js

Fixes https://github.com/shaka-project/shaka-player/issues/9137

fix: Fix CANNOT_ADD_EXTERNAL_CHAPTERS_TO_LIVE_STREAM error code

---

lib/hls/hls_parser.js

Related to https://github.com/shaka-project/shaka-player/issues/9149

fix(HLS): Determine the duration of an HLS content when it ends live
